### ISSUE TITLE
How to deploy on the cloud sentence transformer from the UKPLab from 

### ISSUE THREAD

**Issue by mattvan83** [pytorch/serve#1001]
Hi community,

How could I practically deploy on the cloud pre-trained sentence transformer from the UKPLab ?

I saw the issue #681 and customisation proposed but didn't know whether it was intended for cloud.

Secondly, once deployed on cloud how to configure at scale?

Thanks !

**Comment by HamidShojanazeri** [comment]
@mattvan83  can please provide more context on what cloud service you need to deploy your model and also steps to produce the .mar file(handler, etc.). [Here](https://aws.amazon.com/blogs/machine-learning/serving-pytorch-models-in-production-with-the-amazon-sagemaker-native-torchserve-integration/) is a tutorial for deploying Bert model form Huggingface on sagemaker, also you can read more on using Torchserve on kubernetes with different cloud provider [here](https://github.com/pytorch/serve/tree/master/kubernetes).

**Comment by mattvan83** [comment]
@HamidShojanazeri ideally I would like to deploy on OVH Cloud and I am interesting not in BERT model from HuggingFace but in `SentenceTransformer('stsb-xlm-r-multilingual')` model from the UKPLab repository.

I admit, I am pretty newbie regarding deployment so I can't describe the needed steps regarding deployment to the cloud service. Could you kindly address me to the correct sequence of steps to follow ?

I am principally interested in deploying at scale for industrial inference an already pre-trained model without specific need for fine-tuning.

Thanks!
