### ISSUE TITLE
macOS dependencies fails to install with HomeBrew>=2.7

### ISSUE THREAD

**Issue by covix** [pytorch/serve#1005]
## Context

* Operating System and version: macOS (Big Sur) with HomeBrew 3.0.5

## Your Environment

* Installed using source? no
* Are you planning to deploy it using docker container? no

## Expected Behavior

Installing dependencies with `python ./ts_scripts/install_dependencies.py` works as intended

## Current Behavior

When installing on macOS, installing java with brew fails without interrupting the installation process. The only reported message is `Error: Unknown command: cask`, before moving on installing python packages.

This is because the executed commands uses the [brew cask install](https://github.com/pytorch/serve/blob/master/ts_scripts/install_dependencies.py#L91) command that [was deprecated since HomeBrew version 2.6 and removed from 2.7](https://github.com/Homebrew/discussions/discussions/340#discussioncomment-232364)

## Possible Solution

The installation script should check the HomeBrew version and decide whether to use `brew cask install adoptopenjdk11` or `brew install --cask adoptopenjdk11`

## Steps to Reproduce

1. Run `python ./ts_scripts/install_dependencies.py` on a Darwin platform with HomeBrew>=2.7

**Comment by msaroufim** [comment]
Hi @covix would you like to go ahead and make a PR for this since you found the appropriate fix? 

After making your changes make sure to run  `python ./torchserve_sanity.py` from
 https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md and we should be good to go

**Comment by covix** [comment]
Hi @msaroufim, thanks for asking, but I think a solution has already been developed (https://github.com/pytorch/serve/blob/master/ts_scripts/install_dependencies.py#L89)
