### ISSUE TITLE
start multiple instances on one machine

### ISSUE THREAD

**Issue by JohnHerry** [pytorch/serve#1009]
## Is your feature request related to a problem? Please describe.

one machine, want to start multiple torchserver instances, so that different user of the machine can dev and test their models independently. 

## Describe the solution
The idea of a HARD CODE .model_server.pid is VERY BAD!!! shoud be a start command option, or , config file option

**Comment by dhanainme** [comment]
I think you are referring to this. 
https://github.com/pytorch/serve/blob/a166ad2d2b3cec9a8381434c445e91d379d78f73/ts/model_server.py#L24

The limiting factor for having multiple instances of TS running is the manner in which we assign ports for IPC between JVM frontend & python workers.  Although there is a config for it - https://github.com/pytorch/serve/blob/a166ad2d2b3cec9a8381434c445e91d379d78f73/frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java#L722

Adding this as a bug for future release

**Comment by JohnHerry** [comment]
> I think you are referring to this.
> https://github.com/pytorch/serve/blob/a166ad2d2b3cec9a8381434c445e91d379d78f73/ts/model_server.py#L24
> 
> The limiting factor for having multiple instances of TS running is the manner in which we assign ports for IPC between JVM frontend & python workers. Although there is a config for it -
> 
> https://github.com/pytorch/serve/blob/a166ad2d2b3cec9a8381434c445e91d379d78f73/frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java#L722
> 
> Adding this as a bug for future release

Thanks for the help. The JVM IPC Python designment is good, But what I said in this page is practically meaningfull. You known many small compaies do not have enough money to buy independent machines for every one. When you and your partners debug different torch models on the same machine, the same torchserver instance, It is horrible to bear frequently stop and restart.

**Comment by maaquib** [comment]
@JohnHerry As a workaround, you can start multiple docker containers with different host port mapping

**Comment by JohnHerry** [comment]
> @JohnHerry As a workaround, you can start multiple docker containers with different host port mapping

Yes,  docker can isolate different developers. But what we need is a more DIRECT and SIMPLE and NATURAL  solution.  Running containers are always costly  without carefully designed images, and we do not want to pay so much time on its design when we were just on the stage of Developing and Debuging.

**Comment by lxning** [comment]
@JohnHerry We recommend docker container to run multiple TS on one host. [Here](https://github.com/pytorch/serve/tree/master/docker#create-torchserve-docker-image) is the command link. 

Otherwise, you have to config [ports](https://github.com/pytorch/serve/blob/master/docs/configuration.md#configure-torchserve-listening-address-and-port) to start multiple TS on one host. It's painful.
