### ISSUE TITLE
Model Archiver creates lingering temporary files

### ISSUE THREAD

**Issue by MFreidank** [pytorch/serve#1012]
## Context

* torchserve version: 0.3.0
* torch-model-archiver version: 0.3.0
* torch version: 1.7.0
* torchvision version [if any]: -
* torchtext version [if any]: -
* torchaudio version [if any]: -
* java version: openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
* Operating System and version: RHEL Linux 7.9

## Your Environment

* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: no
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom handler
* What kind of model is it e.g. vision, text, audio?: text
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: no
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: not relevant
* Link to your project [if any]: -

## Expected Behavior
Temporary files created in the process of packaging models in MAR files should get cleaned up after successful MAR creation.

## Current Behavior
Temporary directory with model files inside (large footprint on disk) lingers on after MAR has been successfully created.

## Possible Solution
Use python's `tempfile.TemporaryDirectory` or remove the directory created in https://github.com/pytorch/serve/blob/fcc336d410c1c7ef992776177a0ea69b94375297/model-archiver/model_archiver/model_packaging_utils.py#L128 after successful packaging.

## Steps to Reproduce

Running the following script does not raise an error, but creates a directory `/tmp/bert` that lingers on long after successful execution and is never cleaned up. 

```python
from argparse import Namespace
from glob import glob
from os import makedirs, path

from model_archiver import manifest_components, model_packaging, model_packaging_utils
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased")
model_directory = "./bert_model"
model.save_pretrained(model_directory)
model_name, model_version, model_archive_directory = "bert", "1.0", "./mar_files"
makedirs(model_archive_directory, exist_ok=True)

extra_files = [
    filename for filename in glob(f"{model_directory}/*")
    if filename != "pytorch_model.bin"
]

model_archive_args = Namespace(
    model_name=model_name,
    version=model_version,
    serialized_file=path.join(model_directory, "pytorch_model.bin"),
    extra_files=",".join(extra_files),
    handler="text_classifier",
    export_path=path.abspath(model_archive_directory),
    runtime=manifest_components.manifest.RuntimeType.PYTHON.value,
    archive_format="default",
    force=True,
    model_file=None,
    requirements_file=None,
)
manifest = (
    model_packaging_utils.ModelExportUtils.generate_manifest_json(
        model_archive_args
    )
)

# Package model checkpoint to a MAR file for TorchServe
model_packaging.package_model(model_archive_args, manifest=manifest)
```

**Comment by chauhang** [comment]
@MFreidank This has been fixed in TorchServe 0.4.2 release
