### ISSUE TITLE
Specify port which failed to bind during java.io.IOException: Failed to bind. Exception

### ISSUE THREAD

**Issue by lezwon** [pytorch/serve#1015]
## Is your feature request related to a problem? Please describe.
Hi, I was recently trying to run torch serve locally and couldn't get it running. It used to fail with the following error: [Torchserve issue](https://discuss.pytorch.org/t/torchserve-stopped-failed-to-bind-address-already-in-use/115232). I used to get the error `java.io.IOException: Failed to bind. Address already in use` . As a newbie I couldn't figure out which port was this and had to spend some time debugging. It would be really helpful if the message instead said `java.io.IOException: Failed to bind port 7070`.

## Describe the solution
Print the port which failed to bind during torch serve initialization.

**Comment by xiumingliu** [comment]
Hi 

In this [document](https://pytorch.org/serve/configuration.html#configure-torchserve-listening-address-and-port), you can find that, by default, the TorchServe uses the following three ports: 

inference_address: Inference API binding address. Default: http://127.0.0.1:8080
management_address: management API binding address. Default: http://127.0.0.1:8081
metrics_address: metrics API binding address. Default: http://127.0.0.1:8082

So probably one of the ports is in used. Please check which processes are using those ports. And you can either kill that process, or tell TorchServe to use another port, by creating the config.properties file as it is suggested in the [document](https://pytorch.org/serve/configuration.html#config-properties-file).

**Comment by prajwaljpj** [comment]
In my case the same issue is occurring even for unused ports. I have tried random port numbers such as 5552, 5553, 5554, etc.

A more detailed view of the error:
```python
2021-04-15 10:24:34,624 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
java.io.IOException: Failed to bind
	at io.grpc.netty.shaded.io.grpc.netty.NettyServer.start(NettyServer.java:264)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:183)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:90)
	at org.pytorch.serve.ModelServer.startGRPCServer(ModelServer.java:396)
	at org.pytorch.serve.ModelServer.startGRPCServers(ModelServer.java:377)
	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:116)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:95)
Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
Exception in thread "Thread-0" java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818)
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:989)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:472)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:232)
	at org.pytorch.serve.ModelServer.stop(ModelServer.java:473)
	at org.pytorch.serve.ModelServer$1.run(ModelServer.java:91)

```

**Comment by prajwaljpj** [comment]
> In my case the same issue is occurring even for unused ports. I have tried random port numbers such as 5552, 5553, 5554, etc.
> 
> A more detailed view of the error:
> 
> ```shell
> 2021-04-15 10:24:34,624 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
> java.io.IOException: Failed to bind
> 	at io.grpc.netty.shaded.io.grpc.netty.NettyServer.start(NettyServer.java:264)
> 	at io.grpc.internal.ServerImpl.start(ServerImpl.java:183)
> 	at io.grpc.internal.ServerImpl.start(ServerImpl.java:90)
> 	at org.pytorch.serve.ModelServer.startGRPCServer(ModelServer.java:396)
> 	at org.pytorch.serve.ModelServer.startGRPCServers(ModelServer.java:377)
> 	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:116)
> 	at org.pytorch.serve.ModelServer.main(ModelServer.java:95)
> Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
> Exception in thread "Thread-0" java.util.concurrent.RejectedExecutionException: event executor terminated
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818)
> 	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:989)
> 	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608)
> 	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:472)
> 	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957)
> 	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:232)
> 	at org.pytorch.serve.ModelServer.stop(ModelServer.java:473)
> 	at org.pytorch.serve.ModelServer$1.run(ModelServer.java:91)
> ```
> 
> This is my config.properties
> 
> ```shell
> inference_address=http://0.0.0.0:4321 # Ive also tried with http://localhost:xxxx and http://127.0.0.1:xxxx
> management_address=http://0.0.0.0:4322
> metrics_address=http://0.0.0.0:4324
> max_workers=1
> min_workers=1
> # number_of_gpu=1
> install_py_dep_per_model=true
> #enable_metrics_api=false
> ```
> 
> Some version information
> 
> ```shell
> $ java --version
> openjdk 11.0.10 2021-01-19
> OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
> OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
> 
> $ pip freeze | grep torchserve
> torchserve==0.3.1
> ```
> 
> Any comments?

Solved! The gRPC port by default uses 7070 and 7071 as per [documentation](https://github.com/pytorch/serve/blob/master/docs/configuration.md). It can be changed by adding this to your config.properties
```shell
grpc_inference_port=<<your_preferred_port>>
grpc_management_port=<<yout_preferred_port>>

```

**Comment by ducvulqd** [comment]
> > In my case the same issue is occurring even for unused ports. I have tried random port numbers such as 5552, 5553, 5554, etc.
> > A more detailed view of the error:
> > ```shell
> > 2021-04-15 10:24:34,624 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
> > java.io.IOException: Failed to bind
> > 	at io.grpc.netty.shaded.io.grpc.netty.NettyServer.start(NettyServer.java:264)
> > 	at io.grpc.internal.ServerImpl.start(ServerImpl.java:183)
> > 	at io.grpc.internal.ServerImpl.start(ServerImpl.java:90)
> > 	at org.pytorch.serve.ModelServer.startGRPCServer(ModelServer.java:396)
> > 	at org.pytorch.serve.ModelServer.startGRPCServers(ModelServer.java:377)
> > 	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:116)
> > 	at org.pytorch.serve.ModelServer.main(ModelServer.java:95)
> > Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
> > Exception in thread "Thread-0" java.util.concurrent.RejectedExecutionException: event executor terminated
> > 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
> > 	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
> > 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
> > 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
> > 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818)
> > 	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:989)
> > 	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608)
> > 	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:472)
> > 	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957)
> > 	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:232)
> > 	at org.pytorch.serve.ModelServer.stop(ModelServer.java:473)
> > 	at org.pytorch.serve.ModelServer$1.run(ModelServer.java:91)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is my config.properties
> > ```shell
> > inference_address=http://0.0.0.0:4321 # Ive also tried with http://localhost:xxxx and http://127.0.0.1:xxxx
> > management_address=http://0.0.0.0:4322
> > metrics_address=http://0.0.0.0:4324
> > max_workers=1
> > min_workers=1
> > # number_of_gpu=1
> > install_py_dep_per_model=true
> > #enable_metrics_api=false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Some version information
> > ```shell
> > $ java --version
> > openjdk 11.0.10 2021-01-19
> > OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
> > OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
> > 
> > $ pip freeze | grep torchserve
> > torchserve==0.3.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any comments?
> 
> Solved! The gRPC port by default uses 7070 and 7071 as per [documentation](https://github.com/pytorch/serve/blob/master/docs/configuration.md). It can be changed by adding this to your config.properties
> 
> ```shell
> grpc_inference_port=<<your_preferred_port>>
> grpc_management_port=<<yout_preferred_port>>
> ```

Thank you, it works for me!
![image](https://user-images.githubusercontent.com/52074395/155282177-8a924bca-4975-4334-9416-f27920b1c075.png)
