### ISSUE TITLE
Question about efficiency of batch inference, and throughput

### ISSUE THREAD

**Issue by zyxstudycs** [pytorch/serve#1017]
Hi, I'm trying to use torchserve to increase my model throughput when deploy it.
However, I got two problems in the process.

1. After model is deployed, when I test its throughput with requests thread number 100, it works fine. But when I increase it into 200 or more, some of the response will show error like this: {
  "code": 503,
  "type": "ServiceUnavailableException",
  "message": "Model \"deeplabv3_resnet_101\" Version null\" has no worker to serve inference request. Please use scale workers API to add workers."
}.
 I tried to adjust max_request_size and max_response_size in config.properities, but it not helps. I tried to increase initial_workers, it also useless.

2. Batch size increase seem not helping overall throughput. After model is deployed, I fixed number of initia_worker=1 and set requests thread number as 100. I only adjust batch_size and max_batch_delay, to search the best batch config. However, increasing batch_size seems not helping the overall throughput at all. When batch_size increases, the overall throughput always not increase or even decrease, no matter how I adjust max_batch_delay. 

I tested them with three examples:
(1) https://github.com/pytorch/serve/tree/master/examples/image_classifier/resnet_152_batch
(2) https://github.com/pytorch/serve/tree/master/examples/image_segmenter/deeplabv3
(3) my own model and handler.
All the three examples have the two problems I meationed before.

I am very appreciated if anyone meets the same issue and help out there.
Thanks.

**Comment by HamidShojanazeri** [comment]
cc @dhanainme

**Comment by dhanainme** [comment]
> "message": "Model "deeplabv3_resnet_101" Version null" has no worker to serve inference request. Please use scale workers API to add workers."

Did you try to scale up worker - https://github.com/pytorch/serve/blob/master/docs/management_api.md#scale-workers

Every worker is an additional python process that is expected to  increase throughput 

Also is this a GPU model ?

**Comment by msaroufim** [comment]
Hi @zyxstudycs - if you increase the batch size substantially then the inference server will wait some time before processing the entire batch so that may explain why you saw a performance degradation. This will be more pronounced for smaller models.

Try to scale the number of workers using something like `curl -v -X PUT "http://localhost:8081/models/noop?min_worker=3"
`

Also would be helpful to understand how many workers you're setting up and what kind of hardware. If CPU how many cores do you have? If GPU then which one?
