### ISSUE TITLE
Possible bug in ts.utils.util.map_class_to_label

### ISSUE THREAD

**Issue by chrisbaume** [pytorch/serve#1020]
This doesn't seem quite right:
https://github.com/pytorch/serve/blob/f0da8d2714628cb5de0c6eaa3ac0448a6b226640/ts/utils/util.py#L63-L64

It's checking the same thing twice and talking about the classes being wrong. Looks like it should be checking `lbl_classes` and `prob` are both lists (or None in the case of `lbl_classes`).

**Comment by HamidShojanazeri** [comment]
@chrisbaume Thanks for pointing out.

**Comment by msaroufim** [comment]
Hi @chrisbaume would you like to make the PR for this? We can follow a similar convention to this https://github.com/pytorch/serve/blob/f0da8d2714628cb5de0c6eaa3ac0448a6b226640/ts/utils/util.py#L65
