### ISSUE TITLE
"Model name not defined" response while registering models

### ISSUE THREAD

**Issue by PushpakBhoge** [pytorch/serve#1022]
I am getting the below response while trying registering model on torch serve
{
    "code": 400,
    "type": "InvalidModelException",
    "message": "Model name is not defined."
}

context:- contain 2 files model.py and util.py model.py contain only one class inheriting from torch.nn.module nad util.py contains code for blocks which are imported into model.py my model is unet and it take [N, C, W, H] input and output  [N, 1, W,H] model is saved using following code.
```
torch.save(unet, "unet.pt")
```
and to create .mar file I am using following commafn
```
torch-model-archiver --model-name MaskUnet --version 1.0 --model-file model.py --serialized-file unet.pt --handler image_segmenter --extra-files utils.py 
```
what is it that I am doing wrong ?

**Comment by HamidShojanazeri** [comment]
@PushpakBhoge  would you please share the full server side log/ minimal code to reproduce, in the meantime you can check [issue#689](https://github.com/pytorch/serve/issues/689) to make sure you there is no issue with imports of the util file.
