### ISSUE TITLE
Question about benchmark report

### ISSUE THREAD

**Issue by gyin-ai** [pytorch/serve#1026]
The example in benchmark shows TS latency is 500ms while model latency is 200ms. Does it mean torch serve itself would take extra 300ms latency overhead to serve a single request? That seems a lot. Please correct me if I am wrong. Thanks

**Comment by dhanainme** [comment]
The numbers you seem to share are way off from what we had observed. Usually if there is no queuing involved TSOverhead <<< Model Latency. 

Also, there are many factors which determine the final latency of TS model.  If you have Dynamic batching enabled you might want to look in to your batch_size & max_batch_delay

Also is this latency observed in normal load / when stress testing ?

**Comment by gyin-ai** [comment]
@dhanainme the number is from this official benchmark. https://github.com/pytorch/serve/blob/master/benchmarks/README.md
![Uploading image.png…]()

**Comment by gyin-ai** [comment]
Do you mind sharing any example or benchmarking result about TSOverhead itself? How many milli seconds would it take?
