### ISSUE TITLE
Have system metrics available for prometheus

### ISSUE THREAD

**Issue by t-henri** [pytorch/serve#1032]
## Is your feature request related to a problem? Please describe.
It would be nice to have system metrics available in prometheus to be able to setup grafana boards and alerting on these metrics. Also, we can add custom metrics to be logged by the system, but these will not be served by the metric API. 
For example, we would like to be alerted when the server returns too many 500, and this metric is already available in the system metrics.

## Describe the solution
Expose the system metrics through the metrics API. 
I noticed this PR https://github.com/pytorch/serve/pull/722 that achieves exactly that, and that also add interesting metrics (InferenceRequest, HandlerTime and QueueTime that are really useful to monitor the server).

## Describe alternatives solution
The /metrics endpoint of the metrics API could read the metric_log file to expose these metrics.

**Comment by t-henri** [comment]
Hello, I am willing to contribute on this if it interests the open source community. 
But I am wondering if there is a reason that you didn't merge the following pull requests: https://github.com/pytorch/serve/pull/722 ?

If you think this feature doesn't belong in this repository, I can create a separate repository to do a prometheus plugin, what do you think ?

**Comment by msaroufim** [comment]
Hi @t-henri, team is busy with the 0.4 release https://github.com/pytorch/serve/projects/9 so we should get back to this soon

That said we could move faster if you try it out and see if it works well for you

`gh checkout 722`

Feel free to add your feedback and tag me directly and we can see it merged more quickly

**Comment by t-henri** [comment]
Hello @msaroufim , thanks for your answer.

I checkout-ed and tried the PR, and it works well for me. I managed to build the frontend and the plugin code, and I could see the new metrics in the /metrics endpoint. With this, I would be able to extend the plugin to have all the metrics I want available.

I can help on this PR if you want, I can fix the conflicts and try to fix the failing CI (or if you prefer I can wait for you to do it once you have time, after the 0.4 release).

**Comment by t-henri** [comment]
Hello, sorry for the long delay before my answer.

For why I like grafana and prometheus, that is what we use for all our other applications, and we have integrations to send prometheus/grafana alerts directly in our slack channels and everything, so I would like to not use another technology to monitor my Torchserve instances.

For what kind of data I'd like to track, I can think of a few:
- The count of requests by path and status (to be able to send alerts if I have many 5XX or 4XX requests, and the path is to know which model is failing).
- The time spent in the handler by path, and the time spent in the queue
- The average time it takes to build a full batch (to be able to fine tune the batch timeout value)
These would already be nice to have information on the server state.

**Comment by agunapal** [comment]
@t-henri This is available in 0.8.2. Please try it and let us know. Closing the issue
