### ISSUE TITLE
Handwritten text classifier in model zoo

### ISSUE THREAD

**Issue by KeithCu** [pytorch/serve#1033]
I'd like to do some recognition of handwriting text in images. For example, the open source Tesseract does a good job with printed text, but fails terribly on handwritten: "eX ng Ko hy 536 0 gwmailicom" (That's using their tessdata (https://github.com/tesseract-ocr/tessdata) dataset, LSTM engine, and telling Tesseract that it's English!)

There is an IAM dataset:
https://fki.tic.heia-fr.ch/databases/iam-handwriting-database

Please consider including a prebuilt model for handwritten text. Lots of people use MNIST with PyTorch, but handling letters also would be very helpful.

**Comment by msaroufim** [comment]
Hi @KeithCu would you be interested in contributing this change? I'd be happy to review it

**Comment by KeithCu** [comment]
I don't have much experience with PyTorch, but I could probably figure something simple out based on the MNIST examples. I'll try and work on it some weekend soon.

**Comment by KeithCu** [comment]
I've been doing some research. The dataset is broken into pages (forms), lines and sentences. In many cases the lines and sentences are the same since most sentences are longer than one line. The only difference between the lines and sentences is that if a sentence ends in the middle of a line, the next words of that line are put in a new image.

I could feed it a line at a time, but it also has the bounding boxes of the words, so I could parse that format and break it up by words as well. However, in the case of either a word or a line, I realize a pure classifier is not enough, I would need some RNN layers as well.

**Comment by msaroufim** [comment]
A baseline is always good to start with, you don't need a fancy model to get started - looking forward to your PR

**Comment by KeithCu** [comment]
I have been busy with a new job but I'll keep working on it during the weekends.
