### ISSUE TITLE
Restart model after an error input

### ISSUE THREAD

**Issue by vuongdanghuy** [pytorch/serve#1036]
Hi. 

I'm using Torchserve to deploy a PyTorch model and it works well. When i send an error input sample for inference, it cause an error within the model. After that, even if I send valid input sample the model keep getting error and I must re-run torchserve for it to run again.

Is there any way to reload model or restart model loading in torchserve when the model is failed from previous inference request?

**Comment by HamidShojanazeri** [comment]
@vuongdanghuy If I understood correctly, for example you send an image instead of a text to a NLP model, then it fails and continue to fail on the next inference requests which is correct (text), if this is the case, it is not expected. Also, with re-run torchserve, do you mean stop and run the instance again? Would you please share more details, your env info and minimum steps to reproduce.

**Comment by vuongdanghuy** [comment]
Hi @HamidShojanazeri 

I'm using [LayoutLM](https://github.com/microsoft/unilm/tree/master/layoutlm/layoutlm/modeling) for document images understanding. 

The model expects a bounding box for each text in the image in format [xmin, ymin, xmax, ymax]. Those bounding boxes will be sent to torch.nn.embedding layer as in the following [code](https://github.com/microsoft/unilm/blob/715bbdea0c3cbc96647100e7d6e61145654e9ff1/layoutlm/layoutlm/modeling/layoutlm.py#L74)

If I set a coordinate to a negative number, for example ymin = -1, embedding layer will fail as it has been shown [here](https://discuss.pytorch.org/t/embeddings-shows-index-out-of-range-if-padding-id-is-1/49457). Following is the log in ts_log.log: 
`/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = c10::Half, IndexType = unsigned int, DstDim = -1, SrcDim = -1, IdxDim = -1, IndexIsMajor = true]: block: [10,0,0], thread: [13,0,0] Assertion srcIndex < srcSelectDimSize failed.`

After that, if I correct ymin value and send it again, the model will fail with `RuntimeError: CUDA error: device-side assert triggered` error.

My env info:
- python: 3.6
- GPU: RTX 2080 Ti
- torch: 1.4.0
- torchserve: 0.3.0
- transformers: 3.1.0

**Comment by msaroufim** [comment]
Hi @vuongdanghuy I tried to repro this with the hello world example we have in our main repo and couldn't find such an issue where I took an image classifier fed it an image it worked fine, then some text and it crashed and then an image again and it worked fine

So I need a bit more information to help so I can reproduce everything exactly
1. All the files you used to generate the mar file
2. How you're deploying the model
3. How you're making an inference

It's possible the LayoutLM codebase crashes CUDA after a failure so would also be helpful to make sure this issue doesn't occur when you don't use torchserve

```
(batch) ubuntu@ip-172-31-73-244:~$ curl http://127.0.0.1:8080/predictions/densenet161 -T kitten_small.jpg
{
  "tabby": 0.5078848004341125,
  "lynx": 0.18985238671302795,
  "tiger_cat": 0.16152901947498322,
  "tiger": 0.054622188210487366,
  "Egyptian_cat": 0.04894307628273964
}(batch) ubuntu@ip-172-31-73-244:~$ curl http://127.0.0.1:8080/predictions/densenet161 -T "hello"
curl: Can't open 'hello'!
curl: try 'curl --help' or 'curl --manual' for more information
(batch) ubuntu@ip-172-31-73-244:~$ curl http://127.0.0.1:8080/predictions/densenet161 -T config.properties 
{
  "code": 503,
  "type": "InternalServerException",
  "message": "Prediction failed"
}
(batch) ubuntu@ip-172-31-73-244:~$ curl http://127.0.0.1:8080/predictions/densenet161 -T kitten_small.jpg
{
  "tabby": 0.5078848004341125,
  "lynx": 0.18985238671302795,
  "tiger_cat": 0.16152901947498322,
  "tiger": 0.054622188210487366,
  "Egyptian_cat": 0.04894307628273964
```

**Comment by vuongdanghuy** [comment]
Hi @msaroufim. Here is the [link](https://github.com/vuongdanghuy/ts_layoutlm) to my repo. All the files and instructions are included. In the `inference` folder there are 2 json files: `abc.json` file is a correct example and `error_layoutlm.json` file is the wrong one. Inference request using `error_layoutlm.json` file will crash the server.

## My Environment
* Installed using source? [yes/no]: yes
* Is it a CPU or GPU environment?: GPU

**Comment by msaroufim** [comment]
>And yes, even if I don't use torchserve, the model still crash if the input sample is not correct.

Interesting so this is probably your best bet - I'd open a Github issue on LayoutLM repo and see if they can assist. Feel free to reopen this if you run into any issues with torchserve
