### ISSUE TITLE
Add community blog posts and videos to README

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#1039]
Add blog posts and videos by companies and individuals experimenting with Pytorch Serve. Examples to README

Blog posts
* https://towardsdatascience.com/serving-pytorch-models-with-torchserve-6b8e8cbdb632
* https://towardsdatascience.com/how-to-deploy-your-pytorch-models-with-torchserve-2452163871d3
* https://aws.amazon.com/blogs/machine-learning/deploying-pytorch-models-for-inference-at-scale-using-torchserve/
* https://cloud.google.com/ai-platform/prediction/docs/getting-started-pytorch-container
* https://medium.com/pytorch/torchserve-and-torchelastic-for-kubernetes-new-pytorch-libraries-for-serving-and-training-models-2efd12e09adc
* https://cceyda.github.io/blog/torchserve/streamlit/dashboard/2020/10/15/torchserve.html

Videos
* https://www.youtube.com/watch?v=9lMMCwVhPpo
* https://www.youtube.com/watch?v=jdE4hPf9juk&t=300s
* https://www.youtube.com/watch?v=AIrrI8WOIuk
* https://www.youtube.com/watch?v=mYV8nk29m8o
* https://www.youtube.com/watch?v=EkELQw9tdWE

**Comment by cceyda** [comment]
Self promotion 😄 : https://cceyda.github.io/blog/torchserve/streamlit/dashboard/2020/10/15/torchserve.html

**Comment by msaroufim** [comment]
Excellent thank you @cceyda! Added it and let me know if you have any feedback to the team since Oct 2020.

This is really cool, I will try out the dashboard for my own projects!
