### ISSUE TITLE
Automatic API documentation generation

### ISSUE THREAD

**Issue by cceyda** [pytorch/serve#1043]
## Auto docs
It would be nice to have something similar to FastAPI's https://fastapi.tiangolo.com/#interactive-api-docs
Also supporting adding docstrings from custom handlers to the generated docs
Why:
+ Make it easier to test models API
+ Nice to have some basic documentation

**Comment by brianjo** [comment]
@msaroufim Maybe also consider adding hooks for Swagger.- https://swagger.io/

**Comment by cceyda** [comment]
I have an idea/question since the [request envelope](https://github.com/pytorch/serve/blob/master/ts/torch_handler/request_envelope/base.py) reformats the inputs/outputs of a call to a handler.
I was wondering if it would be possible to use pydantic BaseModel instead for this purpose (similar to FastApi)
then we could just auto generate a [schema](https://pydantic-docs.helpmanual.io/usage/schema/) which can be returned on querying model details.

**Comment by msaroufim** [comment]
I know this is late but I recently discovered that postman actually does API discovery for you for free https://www.postman.com/

Install postman locally and connect it to a directory or github repo to get free API discovery
