### ISSUE TITLE
Torch serve failing saying .mar file is not UTF Encoded

### ISSUE THREAD

**Issue by maheshcheetirala** [pytorch/serve#1060]
https://torchserve-on-aws.workshop.aws/en/300/330-main-lab.html 
I am trying to reproduce this workshop by AWS trying pytorch native server on Sagemaker, but my serve is failing when i have inspected the logs I have found that .mar file is not UFT-8 encoded saving disabled.
and when in run the ping command to endpoint it says unhealthy,\.
![torchserveerror](https://user-images.githubusercontent.com/44243235/117770116-315a5c80-b252-11eb-96e5-45fd2fccc7df.PNG)
[ts_log.log](https://github.com/pytorch/serve/files/6457019/ts_log.log)
Please let me know how to fix this error.  And what changes needs to be done.

**Comment by vuongdanghuy** [comment]
In the ts_log.log file i see that image_classifier module and py3 can not be imported. When you create .mar file, are you sure that those module are included in extra-files or requirements-file option?

**Comment by maheshcheetirala** [comment]
I am just following the jupyter notebook created on Sagemaker . in the
workshop link given.
And am running standard model archive commands  from the torch serve
densenet image classification, how do i add those  imports which are
missing.

Thanks
Mahesh

**Comment by maheshcheetirala** [comment]
This is the notebook I am running and  serve is failing with the attached
logs. Could you please help me move forward.
I tried all the instructions but still serve is failing.

Thanks
Mahesh

**Comment by msaroufim** [comment]
Hi @maheshambule if you can share repro instructions according to the issue template I can assist you further. I don't see the notebook you attached here
