### ISSUE TITLE
Wrong link in readme file

### ISSUE THREAD

**Issue by KYKong1997** [pytorch/serve#1061]
### Get predictions from a model

To test the model server, send a request to the server's `predictions` API. TorchServe supports all [inference](docs/inference_api.md) and [management](docs/management_api.md) api's through both [gRPC](docs/grpc_api.md) and [HTTP/REST](docs/grpc_api.md).

the rest api and grpc api are linked to same page

**Comment by msaroufim** [comment]
Thank you just fixed this!
