### ISSUE TITLE
Enhance benchmarking automation

### ISSUE THREAD

**Issue by nskool** [pytorch/serve#1067]
## Is your feature request related to a problem? Please describe.

The feature requests come from comments on this PR: https://github.com/pytorch/serve/pull/1052

## Describe the solution
Add the following features to automation to facilitate better user experience:
Review notes:
1. Consider using https://pypi.org/project/mdutils/ if the report structure becomes complex.
2. Consider using boto3 for aws calls?
3. Make uuid more human readable.
4. Move some config items from __init__.py to a config file for easy manipulation.
5. Make 'ec2 Name' tag configurable for users to easily name their instances.
6. Add useful command line arguments i.e. '--run-only <test>'
7. call 'report.py' automatically.
8. Add appropriate logging to cloudwatch
9. Reduce duplication in test_files.

**Comment by dhanainme** [comment]
Can you also log the metrics with appropriate dimensions to cloudwatch aswell.

**Comment by nskool** [comment]
Considerations addressed/not addressed/punted as of pr #1099 

1. Consider using https://pypi.org/project/mdutils/ if the report structure becomes complex.
Addressed: the 3p utility need not be used as of PR #1099 as the format of the output markdown doesn't change, and is kept simple.
2. Consider using boto3 for aws calls?
Addressed: There is no advantage to using boto3 in the current implementation. It could only lead to more verbose code. This will be dropped from list of enhancement.
3. Make uuid more human readable
Addressed: the uuid is a unique combination of timestamp and several other factors. To make uuid more human readable, another method would need to be written. Since, the user does not directly interact with uuid, the existing implementation should serve well.
4. Move some config items from __init__.py to a config file for easy manipulation.: Done
5. Make 'ec2 Name' tag configurable for users to easily name their instances.: Done
6. Add useful command line arguments i.e. '--run-only <test>': Punted to phase 3 issue https://github.com/pytorch/serve/issues/1121
7. call 'report.py' automatically.
Addressed: report is now generated automatically after benchmarking completes
8. Add appropriate logging to cloudwatch: Punted to phase 3 issue https://github.com/pytorch/serve/issues/1121
9. Reduce duplication in test_files.
Addressed: Several functions were moved to a common location in PR #1099 , however more can be done. and hence also included in phase 3 https://github.com/pytorch/serve/issues/1121

**Comment by chauhang** [comment]
Remaining items to be addressed in 0.5.0
