### ISSUE TITLE
Worker restarts(thread error) and /ping shows: "partial healthy"

### ISSUE THREAD

**Issue by yashna-shravani** [pytorch/serve#1068]
Terminal Logs:
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/32808937/118482302-2d3aad00-b732-11eb-95e5-a5baa076de46.png">

/ping
<img width="308" alt="image" src="https://user-images.githubusercontent.com/32808937/118510657-c972ad00-b74e-11eb-9b28-137c4bf15a53.png">

I am deploying pretained SentenceTransformer('bert-base-nli-mean-tokens') model from hugginface used for sentence similarity. Even with these errors I am getting the correct inference from the REST api. 
OS: Mac Catalina
torchserve version:  0.3.1
Installed using source? [yes/no]: torchserve -yes , pulled pytorch/torchserve image for running torchserve
Are you using a docker container? [yes/no]: Yes

My process:
1) saved the pertained model -
 ```
from sentence_transformers import SentenceTransformer
bert_model = SentenceTransformer('bert-base-nli-mean-tokens')
bert_model.save('model-dir')
```
2) zipped all the contents of "model-dir" and named "pytorch_model.bin"
3) created MAR file:
```
torch-model-archiver --model-name sentence_Transformer_BERT --version 1.0 --serialized-file pytorch_model.bin --handler run_handler.py --extra-files handler.py --export-path /Users/yshravan/model_store --runtime python3 -f
```
files: 
[handler.py.txt](https://github.com/pytorch/serve/files/6493525/handler.py.txt)
[run_handler.py.txt](https://github.com/pytorch/serve/files/6493526/run_handler.py.txt)

4) Build a new docker image from existing pytorch/torchserve image to install requirements
[dockerfile.txt](https://github.com/pytorch/serve/files/6493545/dockerfile.txt)
docker build -t torchserve:v1 .

5) Ran the custom docker image and added config file
[config.properties.txt](https://github.com/pytorch/serve/files/6493547/config.properties.txt)

6) Final docker run:
```
docker run --rm -it -p 3000:8080 -p 3001:8081 -v /model_store:/home/model-server/model-store -v /config.properties:/home/model-server/config.properties torchserve:v1 torchserve --start --model-store model-store --models SBERT=sentence_Transformer_BERT.mar
```
Please let me know what I need to configure to run this final docker image in a production env? Currently it is throwing error messages when I run locally but the inference results are fine.

**Comment by msaroufim** [comment]
Partial Healthy gets thrown if the number of workers allocated are less than the number of workers scaled https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/util/ApiUtils.java#L351

I would suggest you initialize a model with 1 initial worker, try setting scale api to 1 worker and see if everything works - if it does scale to something larger than 1 and see if issue persists https://github.com/pytorch/serve/blob/master/docs/management_api.md

**Comment by yashna-shravani** [comment]
Thanks @msaroufim , I deployed this image on Openshift pod having 4GB RAM and 4 CPU cores (hence using 4 workers now) and it is showing healthy.
I also updated the config.properties to :
<img width="315" alt="image" src="https://user-images.githubusercontent.com/32808937/122349778-32299100-cf6a-11eb-9abb-681a62e7e102.png">
But now i see these new connection reset errors:
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/32808937/122350040-76b52c80-cf6a-11eb-86b8-90a50dbc4d91.png">
most of the time i do get the inference but some times due to this error api fails to return 200 status.
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/32808937/122350192-a106ea00-cf6a-11eb-81b3-5f6b5c4fd3d7.png">

What could be the reason? How to fix this?

**Comment by msaroufim** [comment]
Since it's a distributed system it's common to have individual workers fail - the important thing to make sure it that you can still correctly get an inference by running a curl request against the inference endpoint. Closing this for now since the main issue is resolved but feel free to open a seperate issue if you need help debugging the rest
