### ISSUE TITLE
Add support for custom metrics in /metrics endpoint and Prometheus

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#1092]
The support for getting the [custom metrics](https://github.com/pytorch/serve/blob/master/docs/metrics.md#custom-metrics-api) via the /metrics endpoint for viewing via in dashboards using  [Prometheus + Grafana](https://github.com/pytorch/serve/blob/master/docs/metrics_api.md#prometheus-server).

**Comment by msaroufim** [comment]
Duplicate of #1492
