### ISSUE TITLE
Multiple models inference on the same GPU

### ISSUE THREAD

**Issue by PMA65** [pytorch/serve#1093]
So we're using torchserve for serving one model for each machine with one GPU, 
but we want to increase throughput by having multiple instances of that model running on the same GPU but response time for concurrent requests is still the same as consecutive response time, now we are using default_workers_per_model=8 and we can see the GPU memory usage of 8 models but still when sending 8 concurrent requests it takes 8*one response time as if we're running the through the same instance, tried adding more number_of_netty_threads with no effect

Is this a bug in our code or is it still not possible to run concurrent models on GPU ?

**Comment by HamidShojanazeri** [comment]
@PMA65 would you please try increasing the batch size, to 4/8 and monitor the changes. Thanks.

**Comment by PMA65** [comment]
> @PMA65 would you please try increasing the batch size, to 4/8 and monitor the changes. Thanks.

you mean the inference batch size or which batch size ??

**Comment by HamidShojanazeri** [comment]
@PMA65 I mean increasing the batchsize when registering the model and then sending inference requests in batch.

**Comment by jayeshbankoti007** [comment]
@HamidShojanazeri I understand your perspective here to increase the batch size and allow batch inference. But I am also facing this issue I am expecting if have multiple models deployed in the system shouldn't it increase the throughput if i am using concurrent requests.
