### ISSUE TITLE
Getting Unknown exception Message size exceed limit, When tried to save few extra attributions methods response in Explain request using my custom handler file for CIFAR10 classification example.

### ISSUE THREAD

**Issue by Arvind-Ideas2IT** [pytorch/serve#1094]
I have a custom handler file in which I just override the get_insights function just to add two more attributions methods along with the default  Integrated Gradient attributions method and get the response. But I get the   "Unknown exception
io.netty.handler.codec.CorruptedFrameException: Message size exceed limit: 11144798 error". But when I built torchserve from the source and hardcoded the maxBufferSize value to a little bigger number which I get in the error, for example, 13,111,872 in https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/util/codec/ModelResponseDecoder.java#L15-L16 and it worked. I was able to get the entire response and save it.

* torchserve version:  0.4.0
* torch-model-archiver version: 0.4.0
* torch version: 1.8.1
* torchvision version: 0.9.1
* torchtext version: 0.9.1
* java version: 11.0.11
* Operating System and version: Ubuntu 18.04

## Your Environment
* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: no
* Is it a CPU or GPU environment?: cpu
* Using a default/custom handler? [If possible upload/share custom handler/model]:custom
* What kind of model is it e.g. vision, text, audio?: Cifar10 image classification
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: local models from the model-store
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: inference_address=http://127.0.0.1:8080
management_address=http://127.0.0.1:8081
NUM_WORKERS=1
default_num_workers=6
number_of_netty_threads=4
job_queue_size=10
service_envelope=kfserving
max_response_size =6553500
model_store=model_store
model_snapshot={"name":"startup.cfg","modelCount":1,"models":{"cifar10_test":{"1.0":{"defaultVersion":true,"marName":"cifar10_test.mar","minWorkers":1,"maxWorkers":8,"batchSize":2,"maxBatchDelay":200,"responseTimeout":300}}}}

## Expected Behavior
Expected torch serve should not throw this error. I did try adding max_response_size 6553500  in the config. properties which seem to way bigger than what size I get in the error, as suggested in some of the previous issues by @harshbafna for example  https://github.com/pytorch/serve/issues/734. But this did not work. How can torchserve take the optimal dynamic value of size to accommodate the explain req response as we don't know what size we would get from the explain if we use different attributions methods or a set of attributions methods in request in advance?

## Current Behavior
Keeping all the above issues in mind, I built torchserve from the source and hardcoded the maxBufferSize value to a little bigger number which I get in the error, for example, 13,111,872 in https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/util/codec/ModelResponseDecoder.java#L15-L16 and it worked. I was able to get the entire response and save it.

## Steps to Reproduce
Please see my get_insights function which I override to add extra attributions methods in my custom handler.

    def get_insights(self, tensor_data, _, target=0):
        explanation_ig = {}
        explanation_lgc = {}
        explanation_occ= {}
        attr_ig, _= self.attribute_image_features(self.ig, tensor_data, baselines=tensor_data * 0, return_convergence_delta=True)

        explanation_ig["attributions_ig"]=attr_ig.tolist()
        print("IntegratedGradients Calculation is done.")

        attributions_lgc = self.attribute_image_features(self.layer_gradcam,tensor_data)
        explanation_lgc["attributions_lgc"] =attributions_lgc.tolist()
        print("LayerGradCam Calculation is done.")
        attributions_occ= self.attribute_image_features(self.occlusion,tensor_data,strides=(3, 8, 8),
                                       sliding_window_shapes=(3,15, 15),
                                       baselines=tensor_data * 0)

        explanation_occ["attributions_occ"]=attributions_occ.tolist()

        print("Occlusion Calculation is done.")

        return [explanation_ig,explanation_lgc,explanation_occ]
...

## Failure Logs [if any]
You can see in the trace, I was able to get the right output from the get insights function but it fails to further due to the size issue.

33, 0.012458115816116333, 0.004078969359397888, 0.002580009400844574, 0.002580009400844574, 0.002580009400844574, 0.002580009400844574, 0.002580009400844574, 0.002580009400844574, 0.002580009400844574, 0.0010810494422912598, -0.0028875917196273804, -0.0028875917196273804, -0.0028875917196273804, -0.0028875917196273804, -0.0028875917196273804, -0.0028875917196273804, -0.0028875917196273804, -0.0068562328815460205, -0.0018280074000358582, -0.0018280074000358582, -0.0018280074000358582, -0.0018280074000358582, -0.0018280074000358582, -0.0018280074000358582, -0.0018280074000358582, 0.003200218081474304, -0.001702331006526947, -0.001702331006526947, -0.001702331006526947, -0.001702331006526947, -0.001702331006526947, -0.001702331006526947, -0.001702331006526947, -0.006604880094528198, -0.002984479069709778, -0.002984479069709778, -0.002984479069709778, -0.002984479069709778, -0.002984479069709778, -0.002984479069709778, -0.002984479069709778, 0.0006359219551086426, -0.01144874095916748, -0.01144874095916748, -0.01144874095916748, -0.01144874095916748, -0.01144874095916748, -0.01144874095916748, -0.01144874095916748, -0.023533403873443604, -0.014534354209899902, -0.014534354209899902, -0.014534354209899902, -0.014534354209899902, -0.014534354209899902, -0.014534354209899902, -0.014534354209899902, -0.005535304546356201, 9.697675704956055e-05, 9.697675704956055e-05, 9.697675704956055e-05, 9.697675704956055e-05, 9.697675704956055e-05, 9.697675704956055e-05, 9.697675704956055e-05, 0.005729258060455322, 0.005051501095294952, 0.005051501095294952, 0.005051501095294952, 0.005051501095294952, 0.005051501095294952, 0.005051501095294952, 0.005051501095294952, 0.0043737441301345825, -0.0008461847901344299, -0.0008461847901344299, -0.0008461847901344299, -0.0008461847901344299, -0.0008461847901344299, -0.0008461847901344299, -0.0008461847901344299, -0.006066113710403442, -0.011048756539821625, -0.011048756539821625, -0.011048756539821625, -0.011048756539821625, -0.011048756539821625, -0.011048756539821625, -0.011048756539821625, -0.016031399369239807, -0.022506482899188995, -0.022506482899188995, -0.022506482899188995, -0.022506482899188995, -0.022506482899188995, -0.022506482899188995, -0.022506482899188995, -0.028981566429138184, -0.022789694368839264, -0.022789694368839264, -0.022789694368839264, -0.022789694368839264, -0.022789694368839264, -0.022789694368839264, -0.022789694368839264, -0.016597822308540344, -0.019163645803928375, -0.019163645803928375, -0.019163645803928375, -0.019163645803928375, -0.019163645803928375, -0.019163645803928375, -0.019163645803928375, -0.021729469299316406, -0.016129814088344574, -0.016129814088344574, -0.016129814088344574, -0.016129814088344574, -0.016129814088344574, -0.016129814088344574, -0.016129814088344574, -0.010530158877372742]]]]}]
2021-05-24 11:55:01,800 [ERROR] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - Unknown exception
io.netty.handler.codec.CorruptedFrameException: Message size exceed limit: 11144798
	at org.pytorch.serve.util.codec.CodecUtils.readLength(CodecUtils.java:24)
	at org.pytorch.serve.util.codec.ModelResponseDecoder.decode(ModelResponseDecoder.java:72)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:138)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-24 11:55:02,590 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_MODEL_LOADED
2021-05-24 11:55:02,590 [DEBUG] W-9000-cifar10_test_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_MODEL_LOADED
2021-05-24 11:55:02,593 [DEBUG] W-9000-cifar10_test_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
	at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:188)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Thank you in advance for any help you can provide!

**Comment by maaquib** [comment]
@Arvind-Ideas2IT Can you set the [max_response_size](https://github.com/pytorch/serve/blob/master/docs/configuration.md#other-properties) to a larger value when starting the server and let us know if it works

**Comment by yurkoff-mv** [comment]
I have a similar problem when I transfer embeddings of dimension [batch_size x 256 x 768] from the BERT model to the subsequent model, which is a full connect layer. I meant that the data should go along the graph continuously and there is no unloading at intermediate stages.
`
Message size exceed limit: 11428070
`

**Comment by Arvind-Ideas2IT** [comment]
> @Arvind-Ideas2IT Can you set the [max_response_size](https://github.com/pytorch/serve/blob/master/docs/configuration.md#other-properties) to a larger value when starting the server and let us know if it works

Hi @maaquib, Yes after setting  max_response_size to a larger value(i.e 655350000 ),The issue get resolved. Though I am curious to know in little detail why it is happening, I did a very simple sanity check, When I make explain req with the default Integrated gradient, the request gives the response, but when I added a simple extra dict with one key and value(ie. {"extra_attri":2} along with default response in get_insights function, that time also I get the message to exceed error. How come a simple extra output can give the above error though max_response_size by default is 6553500 which anyway was bigger than the combined response, what I observed.

**Though  after setting  max_response_size to a larger value(i.e 655350000 )** I am able to save all my three attributions response. Thanks

**Comment by msaroufim** [comment]
So max response size you set is about 64MB, do you mind as a sanity check recursively checking the size of the response using this snippet? https://code.activestate.com/recipes/577504/ 

If you're working on deploying multiple models that talk to each other I'd suggest you take a look at our new workflow feature https://github.com/pytorch/serve/tree/master/examples/Workflows

**Comment by IamMohitM** [comment]
Actually ignore the above comment. This happened because my docker command didn't have the path to the mounted config  instead used the path to the local config.

**Comment by msaroufim** [comment]
Hmm I think we should print out the used config in logs to make debugging easier
