### ISSUE TITLE
Cannot invoke TorchServe from SageMaker Notebook

### ISSUE THREAD

**Issue by seraconlp** [pytorch/serve#1097]
Hi, I deployed a model using **SageMaker Native TorchServe Integration**.

That is, it uses Amazon Deep Learning Container.

Now, I wanted to try the TorchServe REST APIs from SageMaker Notebook.

When I try for example calling **!curl http://localhost:8080/ping** , it is getting

_curl: (7) Failed to connect to localhost port 8080: Connection refused_

Any guidance would be appreciated.

This model deployment used PyTorchModel and model.deploy().

**Comment by seraconlp** [comment]
As this method of model deployment created TorchServe-powered SageMaker endpoint, I have to try also this in the model deployer SageMaker Notebook:

!curl http://runtime.sagemaker.us-east-1.amazonaws.com/endpoints/{endpoint_name}:8080/ping

However, it looks like not responding at all. Just the hour glass / kernel running display.

**Comment by msaroufim** [comment]
Hi @seraconlp which tutorial are you following exactly? This one? https://torchserve-on-aws.workshop.aws/en/

Regardless of tutorial can you confirm which steps you followed and where things stopped working as expected? Logs and screenshots would be very helpful

**Comment by seraconlp** [comment]
Hello @msaroufim, ah yes build from that tutorial too.

Essentially the "**Deployment that uses the Amazon SageMaker SDK for natively model serving with TorchServe.**" part.
=> https://torchserve-on-aws.workshop.aws/en/400.html

I got to call TorchServe APIs (http://localhost:808X/{REST API}) when installing it locally in the SageMaker notebook instance.

Where I am confused now is, if deployed the latter way, how to invoke TorchServe APIs now.

Have you experienced the same before? Anybody from AWS TorchServe team knows?

I think it not generating CloudWatch logs.
Just the message below. I have to vary APIs with correct and incorrect ones and getting same error result.
_curl: (7) Failed to connect to localhost port 8080: Connection refused_

When I invoke SageMaker endpoint externally with proper SageMaker session / boto3... able to get predictions.

**Comment by HamidShojanazeri** [comment]
CC @lxning @maaquib

**Comment by maaquib** [comment]
@seraconlp If you are deploying the container on SageMaker (SM) you'd have to use the SM `invocation` api. The native TorchServe APIs are not exposed on SM. You **have** to use the SM apis. You can use either [boto3.sagemakerruntime](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker-runtime.html#SageMakerRuntime.Client.invoke_endpoint) or [awscli](https://docs.aws.amazon.com/cli/latest/reference/sagemaker-runtime/invoke-endpoint.html)

**Comment by seraconlp** [comment]
Hello @maaquib @HamidShojanazeri @msaroufim, thank you for your replies.

Is this what you mean?

`client = boto3.client('sagemaker-runtime')
endpoint_name = ‘{endpoint_name}’
body = json.dumps({“key1: “value1”}))
response = client.invoke_endpoint(
                EndpointName=endpoint_name,
                ContentType='application/json',
                Accept="application/json",
                Body=body)
response['Body'].read()
`

Does `invoke_endpoint` have other parameters or do I have to append to `endpoint_name` value?

I wanted to call these TorchServe APIs: **https://pytorch.org/serve/rest_api.html**

Yes, this is SageMaker deploying automatically its Deep Learning Container. I didn't bring any custom container.

**Comment by seraconlp** [comment]
Looking at this now: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker-runtime.html#SageMakerRuntime.Client.invoke_endpoint

I hope you can provide me specific example for invoking one of TorchServe's REST APIs.

**Comment by maaquib** [comment]
```
client = boto3.client('sagemaker-runtime')

response = client.invoke_endpoint(
            EndpointName=endpoint,
            Body=body,
            ContentType='application/json')

result = response['Body'].read().decode('utf8')
```

> I wanted to call these TorchServe APIs: https://pytorch.org/serve/rest_api.html

As mentioned earlier, once the container is deployed in SageMaker you cannot call the TorchServe APIs, they are not exposed. Only the SageMaker APIs are callable i.e. the invoke_endpoint

**Comment by seraconlp** [comment]
Oh wow. Does it mean we loose all the TorchServe REST API benefits?

Use cases like, adding models, versioning models, increasing worker threads, consuming metrics, ...

Is there a way to access these TS APIs like going inside the container where TS is running?

Or do you mean -- before the container is deployed to SageMaker, one can TS REST APIs?

However, native SageMaker deployment via SM Python SDK will only create this container on the fly when you do `model.deploy(...)`.

Pardon if I have gaps in my understanding. What I wanted is the ease of deploying models with SageMaker TorchServe integration yet be able to make use of TorchServe APIs.

If that's impossible at all, what usually is your best practice to using TS in SageMaker with most benefits intact?

If there are benefits to be dropped, can you help enumerate it for us?

Thanks again!

**Comment by seraconlp** [comment]
Would it best then to do BYOC in SageMaker with TorchServe backing?

Then before deploying BYOC to SageMaker... do any necessary TS API calls?

Would this be the best reference to use? 

https://aws.amazon.com/blogs/machine-learning/deploying-pytorch-models-for-inference-at-scale-using-torchserve/

**Comment by maaquib** [comment]
SageMaker allows customers to deploy custom model server not just the default ones. As such it has a contract that all model server should implement to be able to run in SageMaker. TorchServe is just one specific model server. As such, only the common set of APIs that SageMaker exposes are callable. It doesn't matter if it is a BYOC container or the default TS one. Also, there is no way of logging on the host if you are running the container on SageMaker.

That said, is there anything specific you are trying to do with the a particular TS API that is not possible via the SageMaker APIs?

**Comment by seraconlp** [comment]
I think I am understanding it better now. Thank you for this helpful information.

All the while I thought I am going to use TS REST APIs even when it is used as model server in SageMaker.

My understanding now with your help is that, SageMaker SDK has these similar APIs that I should use instead.

TorchServe on its own is PyTorch model serving and its REST APIs are useful when not using SageMaker.

Please correct me if I am wrong. 

I will explore the SM SDK. If you can point me to SM SDK doc URL that function like TS APIs, that would help me.

If I still don't get it, maybe point me to a good resource to understand it better.

Thank you @maaquib!

**Comment by seraconlp** [comment]
Planning to read these two PRs as well:

[SageMaker changed their default PyTorch model server into TorchServe]
1. https://github.com/aws/sagemaker-pytorch-inference-toolkit/pull/79
2. https://github.com/aws/deep-learning-containers/pull/347

**Comment by maaquib** [comment]
> I think I am understanding it better now. Thank you for this helpful information.
> 
> All the while I thought I am going to use TS REST APIs even when it is used as model server in SageMaker.
> 
> My understanding now with your help is that, SageMaker SDK has these similar APIs that I should use instead.
> 
> TorchServe on its own is PyTorch model serving and its REST APIs are useful when not using SageMaker.
> 
> Please correct me if I am wrong.
> 
> I will explore the SM SDK. If you can point me to SM SDK doc URL that function like TS APIs, that would help me.
> 
> If I still don't get it, maybe point me to a good resource to understand it better.
> 
> Thank you @maaquib!

Your understanding is correct. If there is some specific TS API that you are not able to replicate the behaviour of in SM do let us know. 

Docs
* https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_runtime_InvokeEndpoint.html
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker-runtime.html
