### ISSUE TITLE
No work  parameter workflow-store in config.properties

### ISSUE THREAD

**Issue by yurkoff-mv** [pytorch/serve#1102]
## Context

* torchserve version: 0.4.0
* torch-model-archiver version: 0.4.0
* torch version: 1.8.1+cu111
* torchvision version [if any]: 0.9.1+cu111
* torchtext version [if any]: 0.9.1
* torchaudio version [if any]: 0.8.1
* java version: OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
* Operating System and version: Windows 10

## Your Environment

* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: yes
* What kind of model is it e.g. vision, text, audio?: text
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: local models from model-store
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: 
```
model_store=./model_store
workflow-store=./wf_store
number_of_gpu=1
max_request_size=655350000
max_response_size=655350000
```
* Link to your project [if any]: -

## Expected Behavior
After I started the service with the command:
`torchserve --start --ts-config config.properties`
I try to register the stream with the command:
`curl -X POST "http://127.0.0.1:8081/workflows?url=my_workflow.war`
The file my_workflow.war is in the directory wf_store.
I'm expecting for the my_workflow to register.

## Current Behavior
I am getting 404 error:
```
{
  "code": 404,
  "type": "WorkflowNotFoundException",
  "message": "Workflow not found in workflow store: my_workflow.war"
}
```
However, if you do the same for mar-files in the model-strorage, everything works correctly.

**Comment by lxning** [comment]
@yurkoff-mv u need provide workflow store when u start torchserve. Please follow [workflow exqmple](https://github.com/pytorch/serve/tree/master/examples/Workflows/nmt_tranformers_pipeline#commands-to-create-the-models-and-the-workflow)

**Comment by yurkoff-mv** [comment]
Yes, but it works for the model-strorage. The following command works:
`torchserve --start --workflow-store wf_store/ --ts-config config.properties`

### config.properties
```
model_store=./model_store
workflow-store=./wf_store
number_of_gpu=1
max_request_size=655350000
max_response_size=655350000
```
The documentation says that it is possible to specify a directory **workflow-store** in a file **сonfig.properties**:
[Advanced configuration](https://github.com/pytorch/serve/blob/master/docs/configuration.md)
