### ISSUE TITLE
How should ResourceNotFoundException be solved ?

### ISSUE THREAD

**Issue by husnain-ali21** [pytorch/serve#1123]
Hello! I am trying to deploy a  model on an aws ec2 instance using torchserve and I am unable to  understand the following raised exception there is no documentation / guide / FAQ or an issue regarding such case , when I make a request  using 
`curl -X POST http://127.0.0.1:8081/predictions/modelv3_im2lat -T /home/ubuntu/TEST_IMAGE.jpg`  I get this output
```
{
  "code": 404,
  "type": "ResourceNotFoundException",
  "message": "Requested resource is not found, please refer to API document."
}

```

`curl http://localhost:8081/models` shows following result 

```
{
  "models": [
    {
      "modelName": "model",
      "modelUrl": "model.mar"
    }
  ]
}
```

and `curl http://localhost:8080/ping`
 shows an unhealthy status although the model seems to be running.

Thanks!

**Comment by msaroufim** [comment]
Hi @husnain-ali21 yeah that's a frustrating error message - do you mind sharing repro instructions so I can debug? The bug template we have when you open an issue is good https://github.com/pytorch/serve/issues/new?assignees=&labels=&template=bug_template.md

**Comment by vuongdanghuy** [comment]
may be prediction URL `curl -X POST http://127.0.0.1:8081/predictions/modelv3_im2lat -T /home/ubuntu/TEST_IMAGE.jpg` is not correct? I think it should be port 8080 instead of 8081.

**Comment by maaquib** [comment]
From the output of `curl http://localhost:8081/models` the model is registered with the name `model`. The prediction should be `curl -X POST http://127.0.0.1:8081/predictions/model -T /home/ubuntu/TEST_IMAGE.jpg`
