### ISSUE TITLE
Improving the Workflow Documentation

### ISSUE THREAD

**Issue by HamidShojanazeri** [pytorch/serve#1124]
## 📚 Documentation
In cases like issue #1103, type of workflows are targeted that requires a model to be registered in the pre-processing node of the workflow DAG to enable the user sending the features/embeddings to the heads/other models in the DAG. This needs to be investigated and Documented accompanied by  small sample code how this can be done in case its supported in the current version.

**Comment by maaquib** [comment]
Added correspondance https://github.com/pytorch/serve/issues/1103#issuecomment-877367598

**Comment by HamidShojanazeri** [comment]
@maaquib it seems in cases similar to issue #1103 there might be another option that would be interesting to explore, as in both workflows the features are coming from a base model and then there are two heads for different tasks, the possibility of having one DAG that uses a base model as feature extractor and two heads for different tasks make a better use of resources (reduce the memory consumption of loading base model two time in two workflows). 

In case this is supported in the current workflow version we can add another example.
