### ISSUE TITLE
Custom Requirements installation failed

### ISSUE THREAD

**Issue by shrinath-suresh** [pytorch/serve#1130]
Please have a look at [FAQ's](../../docs/FAQs.md) and [Troubleshooting guide](../../docs/Troubleshooting.md), your query may be already addressed.

Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

We are using torchserve to deploy, predict and explain pytorch lightning models in kubelow.

For the inference service, we are using the official docker hub image - `pytorch/torchserve-kfs:0.4.0`

Since the docker image doen't contain `pytorch-lightning` package. We are added it in `requirements.txt` and bundling it using `torch-model-archiver`. 

When `install_py_dep_per_model` is set to `true` the packages listed in the `requirements.txt` are **not getting installed**. The issue is getting reproduced in both standalone and docker images.

* torchserve version: 0.4.0
* torch-model-archiver version: 0.4.0
* torch version: 1.8.1
* torchvision version [if any]: 0.9.1
* torchtext version [if any]: 0.9.1
* torchaudio version [if any]:
* java version: 
ubuntu@ubuntu-ThinkPad-L490:~/Documents/facebook/phase2/mlflow-torchserve/examples/IrisClassification$ java --version
openjdk 11.0.11-ea 2021-04-20
OpenJDK Runtime Environment (build 11.0.11-ea+4-Ubuntu-0ubuntu3.16.04.1)
OpenJDK 64-Bit Server VM (build 11.0.11-ea+4-Ubuntu-0ubuntu3.16.04.1, mixed mode, sharing)

* Operating System and version: Ubuntu - 16.04

## Your Environment

* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom
* What kind of model is it e.g. vision, text, audio?: vision/text
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: local model
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Expected Behavior
When `install_py_dep_per_model` is set to `true`, pytorch lightning should be installed and model should load successfully.

## Current Behavior
when `install_py_dep_per_model` is set to `true`, torchserve is throwing the error (attached logs)

It is strange that, even if `pytorch_lightning` is present in the environment and `install_py_dep_per_model` is set to `true`, the same error is getting reproduced.

## Steps to Reproduce

[iris.zip](https://github.com/pytorch/serve/files/6677618/iris.zip)

1. Unzip iris.zip - It contains `iris.mar` and `config.properties` file
2. Create a directory `model-store`
3. copy iris.mar inside `model-store`
4. set `install_py_dep_per_model=false` in config.properties
5. Install pytorch lightning using pip - `pip install pytorch_lightning==1.3.2`
5. start torchserve with following command
`torchserve --start --ts-config config.properties`
6. Model will be loaded successfully.
7. Stop the torchserve - `torchserve --stop`
8. Uninstall pytorch lightining using `pip uninstall pytorch-lightning`
9. set `install_py_dep_per_model` to true now.
10. start torchserve with following command
`torchserve --start --ts-config config.properties`

## Failure Logs [if any]
Failure logs are attached in ts-failure.txt
[ts-failure.txt](https://github.com/pytorch/serve/files/6677666/ts-failure.txt)

Success scenario log
[ts-success.txt](https://github.com/pytorch/serve/files/6677678/ts-success.txt)

**Comment by lxning** [comment]
@shrinath-suresh I reproduced the issue and found that pytorch_lightning was installed when install_py_dep_per_model is set as true. 

Here is my setting:
- config.properties
inference_address=http://0.0.0.0:8085
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8086
install_py_dep_per_model=true
model_store=model-store

- cmd: torchserve --start --ncs --model-store model_store/ --models iris.mar --ts-config=config.properties

Result:
- pip freeze|grep lig
pytorch-lightning @ git+https://github.com/PyTorchLightning/pytorch-lightning@7a48db591e25fa43d372d4092bfc26c66b72df88

- Error: I got error similar as what you got.

According to the log, it also shows that pytorch-lightning was installed. However, pytorch-lightning is not "1.3.2". Please check your requirements.txt.

**Comment by shrinath-suresh** [comment]
> @shrinath-suresh I reproduced the issue and found that pytorch_lightning was installed when install_py_dep_per_model is set as true.
> 
> Here is my setting:
> 
> * config.properties
>   inference_address=http://0.0.0.0:8085
>   management_address=http://0.0.0.0:8081
>   metrics_address=http://0.0.0.0:8086
>   install_py_dep_per_model=true
>   model_store=model-store
> * cmd: torchserve --start --ncs --model-store model_store/ --models iris.mar --ts-config=config.properties
> 
> Result:
> 
> * pip freeze|grep lig
>   pytorch-lightning @ git+https://github.com/PyTorchLightning/pytorch-lightning@7a48db591e25fa43d372d4092bfc26c66b72df88
> * Error: I got error similar as what you got.
> 
> According to the log, it also shows that pytorch-lightning was installed. However, pytorch-lightning is not "1.3.2". Please check your requirements.txt.

Thanks for the reply. I have follow-up questions on this. if you notice the mar file which i have shared in the issue, the pytorch lightning version is pinned to `1.3.2`.  When `install_py_dep_per_model` is set to `true`, pytorch lightning 1.3.2 should be installed (which is not happening).

The problem here is on `install_py_dep_per_model`. May be if you think pytorch lightning is version specific. I tried out the same test with captum.

1. Uninstall `captum` from the environment - `pip uninstall captum`
2. Update the requirements.txt file inside mar file - 
[iris-captum.zip](https://github.com/pytorch/serve/files/6680493/iris-captum.zip)

3. I used the same `config.properties` file which you have shared and ran the same command to start torchserve.

Actual Result:

I am getting the same error mentioned in the issue and captum is not installed in my environemnt.

Expected Result:

The model should be loaded.

**Comment by shrinath-suresh** [comment]
> > @shrinath-suresh I reproduced the issue and found that pytorch_lightning was installed when install_py_dep_per_model is set as true.
> > Here is my setting:
> > 
> > * config.properties
> >   inference_address=http://0.0.0.0:8085
> >   management_address=http://0.0.0.0:8081
> >   metrics_address=http://0.0.0.0:8086
> >   install_py_dep_per_model=true
> >   model_store=model-store
> > * cmd: torchserve --start --ncs --model-store model_store/ --models iris.mar --ts-config=config.properties
> > 
> > Result:
> > 
> > * pip freeze|grep lig
> >   pytorch-lightning @ git+https://github.com/PyTorchLightning/pytorch-lightning@7a48db591e25fa43d372d4092bfc26c66b72df88
> > * Error: I got error similar as what you got.
> > 
> > According to the log, it also shows that pytorch-lightning was installed. However, pytorch-lightning is not "1.3.2". Please check your requirements.txt.
> 
> Thanks for the reply. I have follow-up questions on this. if you notice the mar file which i have shared in the issue, the pytorch lightning version is pinned to `1.3.2`. When `install_py_dep_per_model` is set to `true`, pytorch lightning 1.3.2 should be installed (which is not happening).
> 
> The problem here is on `install_py_dep_per_model`. May be if you think pytorch lightning is version specific. I tried out the same test with captum.
> 
> 1. Uninstall `captum` from the environment - `pip uninstall captum`
> 2. Update the requirements.txt file inside mar file -
>    [iris-captum.zip](https://github.com/pytorch/serve/files/6680493/iris-captum.zip)
> 3. I used the same `config.properties` file which you have shared and ran the same command to start torchserve.
> 
> Actual Result:
> 
> I am getting the same error mentioned in the issue and captum is not installed in my environemnt.
> 
> Expected Result:
> 
> The model should be loaded.

Even if all the packages are installed (say we install pytorch lightning 1.3.2 and captum using pip) , and run this example

with `install_py_dep_per_model=false` - model loads properly
with `install_py_dep_per_model=true` - throws error mentioned in the issue.

Can you please check if you are observing the same behaviour in your environment ?
