### ISSUE TITLE
Please document how this works and why it works that way

### ISSUE THREAD

**Issue by johann-petrak** [pytorch/serve#1131]
The torchserve library has very specific requirements and very specific ways of how things are done or must be provided and it is really hard to find out how to adapt it to different situations and what parts of the internal processing are really essential and why.

For example, the way how models must be provided, how everything gets zipped up, how it gets unzipped again later into temporary directories and how whatever gets unzipped is then used in which part of the process to actually load the model.
And how this could or should get adapted to different situations using one's one handler. 

For example the AWS SageMaker adaptation seems to based on a handler that uses the transform method to allow custom-loading of models. This looks extremely weird to me, but seems to be necessary because torchserving has no own simple way to supply one's own model loading handler. 

Torchserve is also VERY specific about what a loadable model file must be (architecture versus state dict) but WHY? There are frameworks out there where a "pytorch model" may be something completely different, e.g. a class that combines several pytorch-related components, where addtional files need to get loaded etc. 

I can see no support for this but there are several ways for how to "hack" this to make it work somehow. But it is unclear what may break because of those hacks since it is hard to understand why things are specifically done the way they are in the first place.

Why do models have to get zipped up into a mar file, cant we just use a directory populated with the content of the zip file directly? Why does the zip archive have to have the extensions "mar". 
What exactly does the java part do? Why do we even have to use Java there instead of something like FastApi or Flask?

**Comment by msaroufim** [comment]
Hi @johann-petrak we're very open on feedback on how we do things and what can be made simpler so feel free to reach out to me I'm happy to meet over Video Chat to discuss in more detail where you think the experience could be better so let me. That said here are my thoughts on your question.

> The torchserve library has very specific requirements and very specific ways of how things are done or must be provided and it is really hard to find out how to adapt it to different situations and what parts of the internal processing are really essential and why.

Just trying to better understand the ask here is you're having trouble understanding the inner workings of torchserve and which parts you can plug out with your own logic. Do you feel like the architecture diagram we had on the main README fell short, if so let me know what you'd like to elaborate more on.

> For example, the way how models must be provided, how everything gets zipped up, how it gets unzipped again later into temporary directories and how whatever gets unzipped is then used in which part of the process to actually load the model.
And how this could or should get adapted to different situations using one's one handler.

Archiving your model is about putting all your model, dependencies and handlers in the same place and a model only gets served when you start torchserve or use the management api to serve a model. The handler is really adding some logic on how you're turning your app level information into a tensor and then how you'd like your client to interpret that data. You could always have shell handlers do most of the pre and post processing outside of torchserve.

> For example, the way how models must be provided, how everything gets zipped up, how it gets unzipped again later into temporary directories and how whatever gets unzipped is then used in which part of the process to actually load the model.
And how this could or should get adapted to different situations using one's one handler.

So the reason everything gets zipped up is so you can have your model weights, handler, torchserve config and other relevant metadata like labels all in the same place. So once everything is in the same `mar` file you can deploy torchserve on a different machine or scale docker containers without worrying that things will break.

> For example the AWS SageMaker adaptation seems to based on a handler that uses the transform method to allow custom-loading of models. This looks extremely weird to me, but seems to be necessary because torchserving has no own simple way to supply one's own model loading handler

Is the handler you're refering to? https://github.com/aws-samples/amazon-sagemaker-endpoint-deployment-of-fastai-model-with-torchserve/blob/main/deployment/handler.py - It looks pretty similar to other non sagemaker handlers I've seen

> Torchserve is also VERY specific about what a loadable model file must be (architecture versus state dict) but WHY? There are frameworks out there where a "pytorch model" may be something completely different, e.g. a class that combines several pytorch-related components, where addtional files need to get loaded etc.

Do you feel like the handlers currently don't provide enough flexibility to do this? Generally I've seen in more bareboned setups like Flask apps people will end up building their own versions of something like an initializer, preprocess and postprocess function

>Why do models have to get zipped up into a mar file, cant we just use a directory populated with the content of the zip file directly? Why does the zip archive have to have the extensions "mar".

The mar files are indeed just plain old zipped files and you can confirm this by running `unzip` on them. I believe the mar terminology comes from something in the Java ecosystem, I'll confirm with some colleagues. 

> What exactly does the java part do? Why do we even have to use Java there instead of something like FastApi or Flask?

Torchserve exposes a RESTFUL API to manage everything about your models so you can use this API from a Flask app to do everything you need. Java is still great to manage large scale systems like Spark so yeah there's always an opportunity cost to explore rebuilding serve in another language so it'd be great to understand what you think the benefits from switching from Java would be

**Comment by johann-petrak** [comment]
Thank you for this answer! I will get back here with more detailed information about what I had trouble with later when I understand better what part of it my own confusions was.

But here one of issues that confused me most coming from the SageMaker Pytorch inference approach of doing things:
the documentation explains in some detail how one should either specify a architecture or a saved state dict for the model, but the SM approach is to just zip up everything as an "extras" directory only, not using either the serialized-file or mode-file parameter. When I use/have to use my own model loading approach, this is the much more flexible and useful approach, but it is not really easy to figure out that this is even a possible option. I initially thought that it is important for torch serve to get the model in one of the two formats, when in reality it is just an option offered for convenience (I think if one does not specify a model file the complaint does not explain that extras alone would also work). 

About the .mar archive: what I found confusing is that the whole process of zipping and unzipping to a different location is required even if I just want to run the model on the machine where the directory I am going to zip up originates. 
So the whole zipping, unzipping and storing the original, the zip, and the unzipped versions approach wastes time and space. 
Even in the SageMaker context this is really the case: SageMaker insists on getting the original model files archived in a tar.gz file which is then apparently unarchived, mounted for the container that runs torch serve where the directory is archived into the mar file, and ultimately getting unarchived again (I think two times: one ./model/ and one ./models/9999999999 directory, not sure why). 
This looks like both a waste of time and space and like something that makes the whole process more convoluted and less easy to understand. If the model directory is mounted into the container anyway, torch serve could just provide that directory to my handler for loading and skip all the archive and unarchive parts in between, one would think.
Maybe there is a good reason why not, but the documentation does not explain that reason.
I would have seen the task of distributing a model directory separate from the task of running inferencing from it (and indeed, SageMaker seems to do this in their own way, using tar.gz files)

Sorry about mentioning the SM handler here this has really nothing to do with torch serve, where it is possible to implement one's own strategy of loading a model in a much more straightforward and clear way than they choose to implement for SM Pytorch Inferencing.
