### ISSUE TITLE
how to serve model converted by hummingbird from sklearn?

### ISSUE THREAD

**Issue by aohan237** [pytorch/serve#1135]
if i have a sklearn model, and then use hummingbird (https://github.com/microsoft/hummingbird) to transfer as pytorch tensor model 

so the model structure is from hummingbird, but not by my own such as :

hummingbird.ml.containers.sklearn.pytorch_containers.PyTorchSklearnContainerClassification
so i dont have the model.py

how to use torch serve to serve this model?
i tried below:

torch-model-archiver --model-name aa --version 1.0 --handler text_classifier --serialized-file torch_hm_model_cuda.pth
torchserve --start --ncs --model-store model_store --models tt=aa.mar

it juse show :

Removing orphan pid file.
java.lang.NoSuchMethodError: java.nio.file.Files.readString(Ljava/nio/file/Path;)Ljava/lang/String;

no other messages.  thanks in advance.

**Comment by msaroufim** [comment]
The model.py is only needed for eager mode inference but if you can convert your model to torchscript then you can skip it

https://github.com/pytorch/serve/tree/master/model-archiver 

```
--model-file MODEL_FILE
                        Path to python file containing model architecture.
                        This parameter is mandatory for eager mode models.
                        The model architecture file must contain only one
                        class definition extended from torch.nn.modules.
```

So my suggestion is to try to take a look at torchscripting the model using instructions from here https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html

**Comment by HamidShojanazeri** [comment]
@aohan237 adding to @msaroufim point, in this case you are using the default handler, the other option would be to use/write a custom handler that initialize the model in the handler and then you can bypass the requirement of model.py.

**Comment by aohan237** [comment]
> The model.py is only needed for eager mode inference but if you can convert your model to torchscript then you can skip it
> 
> https://github.com/pytorch/serve/tree/master/model-archiver
> 
> ```
> --model-file MODEL_FILE
>                         Path to python file containing model architecture.
>                         This parameter is mandatory for eager mode models.
>                         The model architecture file must contain only one
>                         class definition extended from torch.nn.modules.
> ```
> 
> So my suggestion is to try to take a look at torchscripting the model using instructions from here https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html

if using torch.jit.trace it shows:
`RuntimeError: Could not get name of python class object`

**Comment by aohan237** [comment]
> @aohan237 adding to @msaroufim point, in this case you are using the default handler, the other option would be to use/write a custom handler that initialize the model in the handler and then you can bypass the requirement of model.py.



> The model.py is only needed for eager mode inference but if you can convert your model to torchscript then you can skip it
> 
> https://github.com/pytorch/serve/tree/master/model-archiver
> 
> ```
> --model-file MODEL_FILE
>                         Path to python file containing model architecture.
>                         This parameter is mandatory for eager mode models.
>                         The model architecture file must contain only one
>                         class definition extended from torch.nn.modules.
> ```
> 
> So my suggestion is to try to take a look at torchscripting the model using instructions from here https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html



> The model.py is only needed for eager mode inference but if you can convert your model to torchscript then you can skip it
> 
> https://github.com/pytorch/serve/tree/master/model-archiver
> 
> ```
> --model-file MODEL_FILE
>                         Path to python file containing model architecture.
>                         This parameter is mandatory for eager mode models.
>                         The model architecture file must contain only one
>                         class definition extended from torch.nn.modules.
> ```
> 
> So my suggestion is to try to take a look at torchscripting the model using instructions from here https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html

torch.jit.trace seems only with normal model, but a hummingbird's transfered model it seems have severay problems.
have to fix things to make it run, at last i give it up..

do i have any other options?

**Comment by aohan237** [comment]
> @aohan237 adding to @msaroufim point, in this case you are using the default handler, the other option would be to use/write a custom handler that initialize the model in the handler and then you can bypass the requirement of model.py.

i wrote a simple handler ,such as :

`
class MyModelHandler(object):
    """
    A custom model handler implementation.
    """

    def __init__(self):
        self._context = None
        self.initialized = False
        self.model = None
        self.device = None

    def initialize(self, context):
        """
        Invoke by torchserve for loading a model
        :param context: context contains model server system properties
        :return:
        """

        #  load the model
        properties = context.system_properties
        model_file = properties.get("model-file")
        self.device = torch.device("cuda:")
        if not os.path.isfile(model_file):
            raise RuntimeError("Missing the model.pt file")

        self.model = torch.load(model_file)

        self.initialized = True

    def handle(self, data, context):
        """
        Invoke by TorchServe for prediction request.
        Do pre-processing of data, prediction using model and postprocessing of prediciton output
        :param data: Input data for prediction
        :param context: Initial context contains model server system properties.
        :return: prediction output
        """
        pred_out = self.model.forward(data)
        return pred_out
`

it still shows `Removing orphan pid file.`

**Comment by aohan237** [comment]
and through the error messages, i cant know  how to fix it..
thanks

**Comment by aohan237** [comment]
exception:
```
          Removing orphan pid file.
          java.lang.NoSuchMethodError: java.nio.file.Files.readString(Ljava/nio/file/Path;)Ljava/lang/String;
	          at org.pytorch.serve.util.ConfigManager.readFile(ConfigManager.java:221)
	          at org.pytorch.serve.util.ConfigManager.<init>(ConfigManager.java:127)
	          at org.pytorch.serve.util.ConfigManager.init(ConfigManager.java:271)
	          at org.pytorch.serve.ModelServer.main(ModelServer.java:83)
```

it seems it has exception of 

`String version = readFile(getModelServerHome() + "/ts/version.txt");`
and what is "TS_MODEL_SERVER_HOME"
