### ISSUE TITLE
Archive snapshotted config files periodically 

### ISSUE THREAD

**Issue by mycpuorg** [pytorch/serve#115]
For context please refer: 

* https://github.com/pytorch/serve/issues/73 
* https://github.com/pytorch/serve/pull/111

To prevent a blowup of snapshots and configuration files? Do we simply archive them periodically?
Based on the discussions during snapshot implementation, this seems like a nice thing to have:
https://github.com/pytorch/serve/pull/111#discussion_r395806506

**Comment by dhaniram-kshirsagar** [comment]
@maaquib Could you please indicate the reason behind closing this issue? We thought it is an important issue.
