### ISSUE TITLE
Add TorchServe Kubernetes operator

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#116]
Add a TorchServe operator to make it easier for users to run inference jobs on Kubernetes clusters.

All the complexity to construct pods and services, manage jobs should be hidden from users. Users should be able define job spec instead of operate the entire stack.

**Comment by Jeffwan** [comment]
This would be very similar to other serving framework case. Basically, one deployment and service are good enough to start an application. There're not lot of resources to manage in this case. 

To better serve kubernetes customers, I think the concentration for next step is to make sure pytorch/serve work with most of serving inference build on top of low level frameworks. Like KFServing, Seldon-core, TensorRT etc. 

Having a complaint API definition and leverage existing framework to power `pytorch/serve` will be a good strategy. I will talk with team on this and come back to the issue.

**Comment by chauhang** [comment]
Closing this, use the TorchServe KFServing integration instead
