### ISSUE TITLE
outside of localhost can not access API

### ISSUE THREAD

**Issue by brainnnnup** [pytorch/serve#1161]
## 📚 Documentation
When I use the example image_classifier。The API can be accessed locally，other devices can not access API。

Non local：`{
  "code": 404,
  "type": "ModelNotFoundException",
  "message": "Model not found: densenet161"
}`

local：`{
  "tabby": 0.4666191339492798,
  "tiger_cat": 0.46449020504951477,
  "Egyptian_cat": 0.06614047288894653,
  "lynx": 0.0012924382463097572,
  "plastic_bag": 0.00022909714607521892
}`

**Comment by PushpakBhoge512** [comment]
I think you swapped the above cases, are you running the server at your local personal laptop or desktop?
in that case it won't work for other devices If you want it there are some router configuration you can do and them expose the ports but I think even then it will be only accessible to the devices connected to router

**Comment by msaroufim** [comment]
It's hard to debug without repro instructions do you mind filling up the issue template so I can help?

**Comment by brainnnnup** [comment]
> I think you swapped the above cases, are you running the server at your local personal laptop or desktop?
> in that case it won't work for other devices If you want it there are some router configuration you can do and them expose the ports but I think even then it will be only accessible to the devices connected to router

Sorry, I didn't reply in time.I don't quite understand setting the routing configuration.It seems that there is no such step when configuring torch serve. Can you explain it in detail. Thank you. @PushpakBhoge512

**Comment by brainnnnup** [comment]
> It's hard to debug without repro instructions do you mind filling up the issue template so I can help?
Sorry, I didn't reply in time. There are no repro instructions.  Another host in the LAN can't access the inference API of torch serve.
@msaroufim

**Comment by brainnnnup** [comment]
> I think you swapped the above cases, are you running the server at your local personal laptop or desktop?
> in that case it won't work for other devices If you want it there are some router configuration you can do and them expose the ports but I think even then it will be only accessible to the devices connected to router

I got it, thank you. I change the default inference_address=https://127.0.0.1:8443 to inference_address=https://0.0.0.0:8443, the problem is solved.

**Comment by Zitong-Xu** [comment]
Solved! I forget to register the model before inference, both 127.0.0.1 and 0.0.0.0 are works for me
