### ISSUE TITLE
ResourceNotFoundException: Requested resource is not found, please refer to API document

### ISSUE THREAD

**Issue by themissingCRAM** [pytorch/serve#1172]
Please have a look at [FAQ's](../../docs/FAQs.md) and [Troubleshooting guide](../../docs/Troubleshooting.md), your query may be already addressed.

Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

* torchserve version:
* torch-model-archiver version:
* torch version:
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
* Operating System and version:

## Your Environment

* Installed using source? [yes/no]: Yes
* Are you planning to deploy it using docker container? [yes/no]:no
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: object dectection
* What kind of model is it e.g. vision, text, audio?: computer vision from yolov5
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
I am using local model from model-store
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Steps to Reproduce

1. python ./ts_scripts/install_dependencies.py
python ./ts_scripts/install_dependencies.py --environment=dev
python ./ts_scripts/install_from_src.py

2.pip install torchserve torch-model-archiver torch-workflow-archiver
3.

## Failure Logs [if any]

{
  "code": 404,
  "type": "ResourceNotFoundException",
  "message": "Requested resource is not found, please refer to API document."
}

**Comment by isomov** [comment]
How did you solve that?
