### ISSUE TITLE
Torchserve 0.4.0 model & workflow management api unreachable

### ISSUE THREAD

**Issue by Silas606** [pytorch/serve#1174]
Hi,

I tried to start torchserve in a container but failed. Here is my config
```
cat ts.config
# Based on https://github.com/pytorch/serve/blob/master/docs/configuration.md
enable_envvars_config=true
decode_input_request=false
load_models=ALL
default_response_timeout=60
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8080
```
inference api and management api are sharing the same port. This is the common setting in AWS SageMaker.
torchserve  start cmd
```
torchserve --start --model-store ./ --ts-config ./sagemaker-ts.properties --models model.mar
```
I don't have `model.mar` in the `model-store` folder and just want to register models on the fly. However, I was not able to access `/models` or `/workflow`. When running
```
curl localhost:8080/models
```
I got
```
{
  "code": 404,
  "type": "ResourceNotFoundException",
  "message": "Requested resource is not found, please refer to API document."
}
```
This is pretty wired error since I am just trying to list available models and this api is clearly documented.

## Context

Torchserve branch: dev

torchserve==0.4.0
torch-model-archiver==0.4.0

Python version: 3.8 (64-bit runtime)
Python executable: /home/ubuntu/miniconda3/envs/py38/bin/python

Versions of relevant python libraries:
captum==0.4.0
future==0.18.2
numpy==1.21.1
nvgpu==0.9.0
psutil==5.8.0
pygit2==1.6.1
pylint==2.6.0
pytest==6.2.4
pytest-cov==2.12.1
pytest-mock==3.6.1
requests==2.26.0
sentencepiece==0.1.96
torch==1.9.0+cpu
torch-model-archiver==0.4.0b20210721
torch-workflow-archiver==0.1.0b20210721
torchaudio==0.9.0
torchserve==0.4.0b20210721
torchtext==0.10.0
torchvision==0.10.0+cpu
transformers==4.6.0
wheel==0.36.2
torch==1.9.0+cpu
torchtext==0.10.0
torchvision==0.10.0+cpu
torchaudio==0.9.0

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: N/A
CMake version: N/A

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: default
* What kind of model is it e.g. vision, text, audio?: None
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: No
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:

```
# Based on https://github.com/pytorch/serve/blob/master/docs/configuration.md
enable_envvars_config=true
decode_input_request=false
load_models=ALL
default_response_timeout=60
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8080
```
* Link to your project [if any]:

## Expected Behavior

```
curl localhost:8080/models
{
  "models": []
}
```

## Current Behavior

```
curl localhost:8080/models
{
  "code": 404,
  "type": "ResourceNotFoundException",
  "message": "Requested resource is not found, please refer to API document."
}
```

## Possible Solution

This is a bug in Torchserve 0.4.0 after introducing workflow api. With the config file, both inference and management api will share the same port. This will force `connector.ALL` in https://github.com/pytorch/serve/blob/7b1c6007cce0b4ed2caa2c20851b547b8827bee9/frontend/server/src/main/java/org/pytorch/serve/ModelServer.java#L386

The resultant `httpRequestHandlerChain` will have four elements
```
InferenceRequestHandler
WorkflowInferenceRequestHandler
ManagementRequestHandler
WorkflowMgmtRequestHandler
```
and they will be executed in order. However in `WorkflowInferenceRequestHandler` at https://github.com/pytorch/serve/blob/7b1c6007cce0b4ed2caa2c20851b547b8827bee9/frontend/server/src/main/java/org/pytorch/serve/workflow/api/http/WorkflowInferenceRequestHandler.java#L48 all `segments` with length shorter than three will be given `ResourceNotFoundException`. In this case, `/models` api call should be handled by `ManagementRequestHandler` after `WorkflowInferenceRequestHandler`. But `WorkflowInferenceRequestHandler` directly throw `ResourceNotFoundException` since `/models` call comes with length of 2.

The principle of throwing `ResourceNotFoundException` isn't quite correct here. This exception will break the handler chain and should only be thrown just before handing action, i.e. 100% sure that this api call should be handled here in this function. Or it should pass the handling logic to subsequent handler in the chain. 

## Steps to Reproduce
As shown in the beginning of this issue.

## Failure Logs [if any]

```
2021-07-17 03:03:34,332 [DEBUG] epollEventLoopGroup-3-1 io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
2021-07-17 03:03:34,332 [DEBUG] epollEventLoopGroup-3-1 io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
2021-07-17 03:03:34,332 [DEBUG] epollEventLoopGroup-3-1 io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
2021-07-17 03:03:34,332 [DEBUG] epollEventLoopGroup-3-1 io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
2021-07-17 03:03:34,332 [DEBUG] epollEventLoopGroup-3-1 io.netty.util.Recycler - -Dio.netty.recycler.delayedQueue.ratio: 8
2021-07-17 03:03:34,383 [INFO ] pool-1-thread-1 ACCESS_LOG - /127.0.0.1:41674 "GET /ping HTTP/1.1" 200 16
2021-07-17 03:03:34,384 [INFO ] pool-1-thread-1 TS_METRICS - Requests2XX.Count:1|#Level:Host|#hostname:ff48916ebbf5,timestamp:null
2021-07-17 03:03:46,250 [INFO ] epollEventLoopGroup-3-2 ACCESS_LOG - /127.0.0.1:41676 "GET /models HTTP/1.1" 404 2
2021-07-17 03:03:46,250 [INFO ] epollEventLoopGroup-3-2 TS_METRICS - Requests4XX.Count:1|#Level:Host|#hostname:ff48916ebbf5,timestamp:null
2021-07-17 03:04:23,464 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:ff48916ebbf5,timestamp:1626491063
2021-07-17 03:04:23,465 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:8.87264633178711|#Level:Host|
```

**Comment by HamidShojanazeri** [comment]
@Silas606 I believe the management and inference port needs to be different 8081/8080, please take a look at this [example](https://github.com/HamidShojanazeri/serve/tree/sagemaker_example/examples/Sagemaker) that shows how to serve a model on Sagemaker using customized container, you need to place the mar file in a S3 bucket and reference it  where you are creating the Sagemaker model.

**Comment by HamidShojanazeri** [comment]
cc @lxning

**Comment by Silas606** [comment]
I have made a mistake that `ManagementRequestHandler` isn't blocking `WorkflowMgmtRequestHandler`. I have revised the issue description. However, currently, `WorkflowInferenceRequestHandler` indeed blocks all subsequent handlers.
