### ISSUE TITLE
Slow connections with image detection

### ISSUE THREAD

**Issue by logan-markewich** [pytorch/serve#1182]
## Is your feature request related to a problem? Please describe.
Inference times with image detection seem to be slowed down by network times with large images. I'm on the same network as torchseve (on localhost), but transferring large images (2000x1500 in my case) to torchserve takes about 2 minutes before pre-processing even starts, compared to 2 seconds for inference. 

I could move the preprocessing outside of torchserve, but that kind of defeats the purpose of having all model-related code contained by torchserve. And even then, my preprocessing only resizes to 1024x1024

## Describe the solution
Can the code include strategies/options to reduce network transfer speeds of images? Maybe by changing the connection type?

## Describe alternatives solution
The documentation could also be updated to show how to mitigate this outside of torchserve (on the user end)

**Comment by msaroufim** [comment]
Interesting, I think this would be valuable for us to repro if you have anything we could use.

Is torchserve running on the same machine as where your images are? Any details you can provide would be super helpful

How are you measuring the transfer time vs preprocess time?

**Comment by logan-markewich** [comment]
I can attach a sample input image here:
![ELS_ENG_IJES_2011_V49_1-8](https://user-images.githubusercontent.com/22285038/128115429-24d78b2e-d5c7-4053-869a-fb5360658313.jpg)

Torchserve is running on the same machine as where my images are (and on the same disk!). So all data is being transferred over localhost connections.

To measure the time, I'm doing the following:
Once torchserve is running, here's the code I'm using to send the image (img is a bytes object at this point).

```
import requests
import datetime

print(datetime.datetime.now())
response = requests.post(url, files={'input_img': img})
```

Then, in my torchserve handler, I'm printing the time as soon as it hits the `preprocess()` function. Then similar time prints allow me to measure the time spent on `preprocess()`, `inference()`, and `postprocess()`.

**Comment by logan-markewich** [comment]
Wow, just found the problem... user error lol

max_batch_delay is not the response timeout, it's the wait time to fill a batch

Since I was always sending one image, it was always waiting the full max_batch_delay time

I'll close this issue then
