### ISSUE TITLE
Link to markdown anchors not properly working

### ISSUE THREAD

**Issue by mmeendez8** [pytorch/serve#1184]
## 📚 Documentation

Hello,

I was checking [custom_service](https://pytorch.org/serve/custom_service.html#installing-model-specific-python-dependencies) and I just realized both links at the bottom of the page are not working. 

I went to check markdown files in source code and everythings seems to be fine there: 
https://github.com/pytorch/serve/blob/master/docs/custom_service.md#installing-model-specific-python-dependencies

Source markdown code:

```
1) [Enable model specific python package installation](configuration.md#allow-model-specific-custom-python-packages)
2) [Supply a requirements file with the model-archive](../model-archiver/README.md#torch-model-archiver-command-line-interface).
```

1. First link is returning is returning a 404 error, this is related with using markdown anchors in the reference. So not sure if this should be replaced with full url to file
2. Second link creates an incorrect url https://pytorch.org/model-archiver/README.md#torch-model-archiver-command-line-interface . Following [index.md][https://github.com/pytorch/serve/blob/master/docs/index.md] style for this cases, relative url should be replaced with https://github.com/pytorch/serve/tree/master/model-archiver/README.md#torch-model-archiver-command-line-interface 

Thanks, I am willing to send a PR with neccessary changes!

**Comment by msaroufim** [comment]
Hi @mmeendez8 thank you for catching this. Would you like to make a PR with your fix? Tag me when it's ready and I'll approve it very quickly.

**Comment by mmeendez8** [comment]
Hi @msaroufim 

I am willing to fix it but there are quite a few broken links that we might be missing too. Basically all this warnings should be properly addressed because they are not working in the html version of the docs:
https://github.com/pytorch/serve/runs/3356216125?check_suite_focus=true#step:4:134

So I am not sure if a larger discussion about this should be started or I should just fix those two links I mentioned in the issue for now.

**Comment by msaroufim** [comment]
Thanks for spotting all these!

> I am willing to fix it but there are quite a few broken links that we might be missing too. Basically all this warnings should be properly addressed because they are not working in the html version of the docs:
https://github.com/pytorch/serve/runs/3356216125?check_suite_focus=true#step:4:134

Probably worth fixing all of them, in the `docs` subfolder it's been test to use absolute links, I thought I cleaned up all of them but seems like I missed a few

>Note recommonmark has been deprecated in favor of myst

cc'ing @brianjo who may be interested

**Comment by brianjo** [comment]
I'll take a look at this. The problem is that the documentation is set up to be readable as github markdown, so the links in github aren't actually broken, but when we look at the pages in Sphinx, they are. I'll see if I can do a new TOC on the docs that links everything and then fix the URLs with links that go to the documentation, rather than directly to the markdown files.

**Comment by mmeendez8** [comment]
Hi @brianjo 

You are right. Note some of the links such `index.md` get rendered to `index.html` which is nice. Problem happens when they point to some specific section in the markdown file such ' index.md#section1 where "rendered links" does not replace the `.md `with the `.html `extension.
