### ISSUE TITLE
[Question] GPU memory

### ISSUE THREAD

**Issue by p1x31** [pytorch/serve#1186]
Hi! Say I have about 10 models and a single GPU is it possible to load a model object for a specific task at the request time and then completely free up the memory for a different model object? For instance, completely deleting it and then reinitialize it when needed. I know this will increase the response time but the crucial part is the amount of VRAM left for the inference.

**Comment by HamidShojanazeri** [comment]
Hi @p1x31, you are able to register delete or scale the number of workers for each of you models through the [Management API](https://github.com/pytorch/serve/blob/master/docs/management_api.md#register-a-model) once you have started Torchserve. You can also set the configurations for each of your models using config.properties, please have a look at this [guide](https://github.com/pytorch/serve/blob/master/docs/configuration.md).

**Comment by p1x31** [comment]
Hi @HamidShojanazeri 
Let me paraphrase
How can I scale down workers to 0 after a single request and scale up to 1 when there is another request for that particular model? Essentially restarting a worker without doing it manually via Management API

- `config.properties:`
`# vmargs=-Xmx128m -XX:-UseLargePages -XX:+UseG1GC -XX:MaxMetaspaceSize=32M -XX:MaxDirectMemorySize=10m -XX:+ExitOnOutOfMemoryError
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
enable_metrics_api=true
metrics_format=prometheus
min_worker=0
max_worker=1
synchronous=true
number_of_netty_threads=0
job_queue_size=1
timeout=-1
initial_workers=0
max_response_size=2047093252
max_request_size=2047093252
install_py_dep_per_model=true
enable_envvars_config=true`

I've tried setting `timeout=-1` and `timeout=0` to remove workers only when all requests from the queue were completed
and setting `job_queue_size=1` but TorchServe doesn't scale down the number of workers
[ts_log.log](https://github.com/pytorch/serve/files/6947821/ts_log.log)
[model_log.log](https://github.com/pytorch/serve/files/6947823/model_log.log)

**Comment by HamidShojanazeri** [comment]
@p1x31 in this case, we need to call management API to scale up/ down the workers based on  custom logic, and this can be automated possibly using a shell script/ or other orchestrations tools.

**Comment by p1x31** [comment]
Yeah, thanks for clearing that up for me
I reckon I'd just initialize with `min_worker=0` and `max_worker=0`
And then scale them up with:

`curl -v -X PUT 'http://127.0.0.1:8081/models/esrgan?min_worker=1&max_worker=1&synchronous=true`

and scale them down with:

`curl -v -X PUT 'http://127.0.0.1:8081/models/esrgan?min_worker=0&max_worker=0&number_gpu=0&synchronous=true`

not bothering with `job_queue_size` and `timeout`
