### ISSUE TITLE
Config snapshot robustness

### ISSUE THREAD

**Issue by fbbradheintz** [pytorch/serve#119]
Preserving server config with config file snapshots (issue #73) will have a few issues at launch:

1) It won't support batch size configuration (see issue #64), as this is not yet supported in config files. This is part of server configuration that should be preserved.
2) It may not do well with the case where model stores and/or config file folders are shared with other instances.
3) There's currently nothing in place to guarantee atomicity of snapshot saves.

What we'll have in place for the first launch will be fine, but to make this a real enterprise tool, we should address these before v1.0.

**Comment by dhaniram-kshirsagar** [comment]
Related to #362

**Comment by harshbafna** [comment]
We have moved away from the initial design to a plugin-based architecture. And an out-of-box dynamo-db snapshot serializer plugin is under development. The recently released TorchServe `serving-sdk 0.0.4` already allows user to write their own custon snapshot serializer.

Refer #362  and corresponding PR #536
