### ISSUE TITLE
InvalidmodelException: Model name is not defined

### ISSUE THREAD

**Issue by Shobhit20** [pytorch/serve#1194]
I am trying to register an encrypted model from s3 url using management apis. But doing so throws an error below
```
< HTTP/1.1 400 Bad Request
< content-type: application/json
< x-request-id: 82f092ba-07c4-47e6-8256-ee6a34aa267a
< Pragma: no-cache
< Cache-Control: no-cache; no-store, must-revalidate, private
< Expires: Thu, 01 Jan 1970 00:00:00 UTC
< content-length: 96
< connection: close
<
{
  "code": 400,
  "type": "InvalidModelException",
  "message": "Model name is not defined."
}
* Closing connection 0
```

The way i am trying to register the model on local is by setting the access key and secret as env vars and using 
```
curl -v -X POST "http://localhost:9081/models?url=https://s3.amazonaws.com/{bucket}/{key_for_mar_file}&s3_sse_kms=true"
```

On specifying the model_name as one of the params in the above curl request to register the model the error changes to 
```
< HTTP/1.1 400 Bad Request
< content-type: application/json
< x-request-id: faa912ec-5ecb-4327-af5a-f2345daa769a
< Pragma: no-cache
< Cache-Control: no-cache; no-store, must-revalidate, private
< Expires: Thu, 01 Jan 1970 00:00:00 UTC
< content-length: 99
< connection: close
<
{
  "code": 400,
  "type": "InvalidModelException",
  "message": "Model version is not defined."
}
* Closing connection 0
```
and am not able to specify the model version here using the version param

Also, should I even be specifying the name and the version of the model when I am doing those things while archiving the model itself. In order to generate the mar file I am using the command below 

```
torch-model-archiver --model-name model_name --version 1.0 --serialized-file models_data/model.pth --extra-files models_data/model_config.yaml,utils.py,models_data/model_metadata.pkl,models_data/classification_model.h5 --handler ts_handler.py --export-path model-store -f 
```

using torchserve 0.4.2

**Comment by lxning** [comment]
@Shobhit20, please follow [archiver example](https://github.com/pytorch/serve/tree/master/model-archiver ).

**Comment by Shobhit20** [comment]
@lxning isn't the archiver example similar to what I did to generate the mar file?
The problem occurs when I try to load a model from s3. On using the torch run command for models on local, the model is served just fine but for my use case I want it to be loaded from an encrypted s3 bucket

**Comment by yopknopixx** [comment]
Hello! I would like to work on this. Please let me know how to proceed.

**Comment by Shobhit20** [comment]
@yopknopixx getting this error when using the url of a model in an encrypted bucket although both version and model name are defined while generating the mar file. The error occurs while registering the model though I am using the s3_sse_kms parameter

**Comment by lxning** [comment]
@Shobhit20 can you print out the manifest.json in the model mar file downloaded from s3?
