### ISSUE TITLE
TorchServe should not overwrite /usr/bin/python and /usr/bin/pip

### ISSUE THREAD

**Issue by sharvil** [pytorch/serve#1195]
https://github.com/pytorch/serve/blob/cdca64c821d4106b752a5e9421e205b685afbfda/ts_scripts/install_dependencies.py#L71-L72

Under no circumstances should an install script silently and without user consent forcibly relink system binaries.

**Comment by AdityaSoni19031997** [comment]
This has messed up my env, thanks for that.

**Comment by sharvil** [comment]
Is it possible to increase the priority on this bug? Silently breaking the systemwide Python on a user's machine is a very severe outcome.

**Comment by AdityaSoni19031997** [comment]
It broke my env, thanks 🙏. Took me a week to figure out what has happened and what caused it.
