### ISSUE TITLE
Getting a custom header value from an incoming request

### ISSUE THREAD

**Issue by veronikayurchuk** [pytorch/serve#1196]
Hi!

I am trying to get value of the custom header of incoming requests (after adding cors_allowed_headers to config.properties)
Based on the code, I see that it is technically possible using [_get_all_request_header_ method](https://github.com/pytorch/serve/blob/master/ts/context.py#L54), but I have troubles with using it.

Thanks for any help in advance.

Also, I would be happy to get any hints if there are alternative ways of implementing customer verification based on the customer's key.

**Comment by msaroufim** [comment]
In the `initialize` handler you can pass as the first argument as context, make it an attribute of the class and then call it in any handler you like

Here's an example https://github.com/pytorch/serve/blob/master/examples/Huggingface_Transformers/Transformer_handler_generalized.py
