### ISSUE TITLE
TorchServe does not honor CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by sharvil** [pytorch/serve#1197]
The `CUDA_VISIBLE_DEVICES` environment variable limits the visibility of GPUs to a process. TorchServe ignores the environment variable and goes directly to `nvidia-smi` to determine how many GPUs are physically installed on a machine. When `CUDA_VISIBLE_DEVICES` is less than the number of installed GPUs, we see errors like:

```2021-08-11 11:45:05,433 [INFO ] W-9001-foo_1.0-stdout MODEL_LOG - RuntimeError: Attempting to deserialize object on CUDA device 2 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.```

**Comment by lxning** [comment]
dup [#1136](https://github.com/pytorch/serve/issues/1136)
