### ISSUE TITLE
torch.package support

### ISSUE THREAD

**Issue by d4l3k** [pytorch/serve#1199]
As of pytorch 1.9.0 there's a new `torch.package` library used for building self contained model code + weights packages. https://pytorch.org/docs/stable/package.html 

This fits a similar role as torchserve model archiver but is part of core pytorch. This seems like it would be beneficial to have support for it if it becomes more widely adopted for model packaging.

Are there any existing plans to add support or any potential issues to supporting it as an extra option along with the existing MAR format?

**Comment by msaroufim** [comment]
Hi @d4l3k I'm curious to hear your thoughts on why you're interested in torch.package vs mar files. torch.package support is definitely something we're looking into for our roadmap but feel free to DM me any feedback.

**Comment by d4l3k** [comment]
@msaroufim no super urgent use cases, just observing that torch.package now exists and seems like torch::deploy supports it. 

To make things easier on users it'd be ideal to have standardization across all the pytorch projects so they're not recommended torch.package on the training side and then have to convert to a conceptually similar .mar format on inference side. Having two different package formats just adds friction to setting up an ML ops pipeline

Glad to hear you're looking into it!
