### ISSUE TITLE
How to add a custom Handler?

### ISSUE THREAD

**Issue by pablodz** [pytorch/serve#1203]
## 📚 Documentation

How to add custom handlers python files friendly and automatic?

By now, I understand that is necessary to modify `pytorch/serve` source code. is that correct?

In my case, I need a custom handler with
input: numpy array or json or list of numbers
output: numpy array or json or list of numbers

I just want to do the inference in  `pytorch/serve`  because I have complex preprocess and postprocess in other microservice

**Comment by msaroufim** [comment]
Hi @pablodz the best way to learn how to create a custom handleer is to look at an example of an existing one. This is a good examplee https://github.com/pytorch/serve/blob/master/examples/nmt_transformer/model_handler_generalized.py

You inherit from base handler and overload initialize, preprocess, inference and postprocess to do what you need

You don't need to change `pytorch/serve` source code and if your pre and post processing are handled by some other service you can basically do a noop passthrough in torchserve

**Comment by pablodz** [comment]
@msaroufim
Thanks for your answer, I really appreciate it!

**Comment by pablodz** [comment]
Also, I found this article that is really helpful! https://github.com/FrancescoSaverioZuppichini/torchserve-tryout.
