### ISSUE TITLE
benchmark code refactor

### ISSUE THREAD

**Issue by lxning** [pytorch/serve#1207]
## Is your feature request related to a problem? Please describe.

1. benchmark entry point should be pytorch/serve/benchmarks. All the code under "pytorch/serve/test/benchmark" should be migrated in pytorch/serve/benchmarks.
2. benchmark automation parameters should be configurable. Current all the files "pytorch/serve/test/benchmark/tests/test_XXX.py are highly duplicated. It is difficult for maintain and hard to extend. The following parameters should be configurable:

- ec2 instance
- s3 bucket
- model

**Comment by msaroufim** [comment]
There's a couple more things we should consider adding here - I'd love to create an aspirational list of dream features we'd like to see for benchmarks after which we can prioritize
1. Making it easier to run multiple experiments to grid search over torchserve parameters e.g: https://gist.github.com/msaroufim/84e1bfbf6440152deda7c8079ea0582e - this added the ability to not overwrite the `tmp` directory. I then created a bunch of configs and setup a shell script to loop over all of them, this process could be saner
2. Local benchmarks are still invaluable so we should take a second look at `ab-benchmark.py`. Right now config url for mar files needs be served by http but it could be made local
3. Archiving experiment results locally or having the option to upload to blob storage like S3
4. Enabling a trace from the Pytorch profiler as an option to debug OOM issues or low GPU utilization etc..
