### ISSUE TITLE
torchserve to support arm

### ISSUE THREAD

**Issue by nmohr192** [pytorch/serve#1213]
## Is your feature request related to a problem? Please describe.
I want to deploy my pytorch model with custom handling to nvidia jetson but apparrently torchserve does not support arm architecture.

## Describe the solution
provide docker image or pip package for armv8

## Describe alternatives solution
provide solution on how to build the package for arm. there are already nvidia pip-wheels for torch on arm but not torchserve.

**Comment by vdantu** [comment]
I am curious to see what error you are facing? AFAIK, the two main dependencies JAVA 11 and python 3 are supported ARMv8 (aarch64).
