### ISSUE TITLE
How to cache inferences with torchserve

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#1217]
Reference architecture showcasing how to cache inferences from torchserve

So potentially the `inference` handler would reach from some cloud cache or KV store

The benefit of this is it'd dramatically reduce latency for common queries

Probably a good level 3-4 bootcamp task for a specific kind of KV store like Redis or specific cloud cache in AWS.

**Comment by AdityaSoni19031997** [comment]
I am new to serve but i believe we would have to handle it ourselves for now using custom handlers, there we can make connections to some KV like Redis and hit that first before making the inference, right?

**Comment by msaroufim** [comment]
That is correct, if you have a reference example we can add the example for it in the repo

**Comment by AdityaSoni19031997** [comment]
I can try to sending a sample snip in upcoming weekend or following that.

Just wanted to know your thoughts,

It's a fair assumption that some (repetitive) ID will be present in the incoming request that can be looked up against some look-up table?

Otherwise, ID generation is incoming data specific which might make things complicated, right?

**Comment by msaroufim** [comment]
How would a client know that it's seen a request before?

One way would be to use input tensors as the key for the key value store but those are probably too big. 

I'm thinking the python `hash()` function could do the job just fine but open to any other suggestions

**Comment by AdityaSoni19031997** [comment]
> How would a client know that it's seen a request before?

Oh yes, I completely agree, it's the servers responsibility to figure out that it has seen this record before. But if someone changes a small value in a tensor, will `hash()` be able to pick it up? (as shown below)

<img width="356" alt="Screenshot 2021-09-21 at 10 20 57 AM" src="https://user-images.githubusercontent.com/22738086/134113241-2cde9084-0f6d-40b2-87b8-03f8fe62efed.png">

Similar issue on PyTorch's repo (computing hash of a tensor) -> https://github.com/pytorch/pytorch/issues/2569

Someone had suggested "surrogate hashing" trick on PyTorch forums [ref](https://discuss.pytorch.org/t/defining-hash-function-for-multi-dimensional-tensor/107531/4?u=ecdrid)

**Comment by msaroufim** [comment]
Oh wow that's a fascinating example, so yeah either you just use the whole tensor as the key (where I'd imagine the network cost to be higher than inference cost so breaks whole need for cache) or we find a smarter hash function

Probability of seeing a repeated tensor is use case specific but let's take as an example search or spelling correction where lots of usages are repeated

**Comment by AdityaSoni19031997** [comment]
IIRC, The worst part about using hash is that it keeps on changing if you keep on running the same example wrt each Python session as well. So it definitely cannot be used here I feel.

We need a better hash function for sure! Will search for more or maybe we can use Min-Hash idea here or hashlib hash functions.
