### ISSUE TITLE
Better document s3 support ("unknown protocol: s3")

### ISSUE THREAD

**Issue by dconathan** [pytorch/serve#1228]
## 📚 Documentation

It's unclear from the documentation that (to my knowledge) only s3 via http is supported.  In fact, the documentation on https://pytorch.org/serve/server.html seems to indicate the s3 protocol is supported:

> Model path can be mar file name in model store or URI (s3 link, or http link). s3 link: s3://S3_endpoint[:port]/… 

but if you try to use an s3:// uri you get:
```
Caused by: java.net.MalformedURLException: unknown protocol: s3
```

**Comment by HamidShojanazeri** [comment]
@dconathan This refers to a  URL of a mar file located on an S3 bucket, it doesn't support S3 URI.
