### ISSUE TITLE
Incorrect links in documentation

### ISSUE THREAD

**Issue by dconathan** [pytorch/serve#1229]
## 📚 Documentation

There are incorrect links throughout the documentation.  For example at bottom of:

https://pytorch.org/serve/custom_service.html#installing-model-specific-python-dependencies

> Enable model specific python package installation

Links to https://pytorch.org/serve/configuration.md#allow-model-specific-custom-python-packages

Which 404s.  It should link to:

https://pytorch.org/serve/configuration.html#allow-model-specific-custom-python-packages

(note the suffix is `.html` instead of `.md`)

**Comment by msaroufim** [comment]
Would you like to make a PR for this? If you just link the http docs I'll merge it
