### ISSUE TITLE
Separation of Snapshot's data members

### ISSUE THREAD

**Issue by mycpuorg** [pytorch/serve#125]
Currently a Snapshot looks like the following in its simplest form.
However, we need to separate the key-value pairs in a given snapshot into
+ Server Specific. Ex: `inference_address`
+ Machine/Env Specific. Ex: `num_workers`, `model_store`, ` number_of_gpu` etc

This will make the snapshot files portable, without this taking a snapshot on one machine/env and trying to restart on another machine/env with the same snapshot will result in unforeseen config failures. In the worst case, they can be very subtle to debug ex: number of workers can be sub-optimal for an instance type with a fewer number of CPU cores than the machine where snapshot was originally generated.

```
#Saving snapshot
#Wed Mar 25 13:50:47 UTC 2020
inference_address=https\://127.0.0.1\:8443
default_response_timeout=120
enable_envvars_config=true
load_models=noop.mar
private_key_file=src/test/resources/key.pem
NUM_WORKERS=4
model_store=../modelarchive/src/test/resources/models
async_logging=true
number_of_gpu=0
model_snapshot={\n  "name"\: "snapshot",\n  "modelCount"\: 0,\n  "created"\: 1585144247230,\n  "models"\: {}\n}
tsConfigFile=src/test/resources/config.properties
max_request_size=10485760
unregister_model_timeout=120
certificate_file=src/test/resources/certs.pem
management_address=unix\:/tmp/management.sock
```

**Comment by msaroufim** [comment]
Hi @mycpuorg just trying to understand your request better. What kinds of unforeseen config failures are you seeing? It seems like the request is also asking for something like `max_num_workers` that would be determined at runtime on each machine?

**Comment by lxning** [comment]
model level config is added in v0.4.1. @mycpuorg feel free to reopen if you think the issue still exists.
