### ISSUE TITLE
Deployment with customer handler on Google Cloud Vertex AI

### ISSUE THREAD

**Issue by Timonzimm** [pytorch/serve#1256]
Hello there,
I'm trying to deploy a TorchServe instance on Google Vertex AI platform but as per their documentation (https://cloud.google.com/vertex-ai/docs/predictions/custom-container-requirements#response_requirements), it requires the responses to be of the following shape:
```json
{
  "predictions": PREDICTIONS
}
```
Where **PREDICTIONS** is an array of JSON values representing the predictions that your container has generated.

Unfortunately, when I try to return such a shape in the `postprocess()` method of my custom handler, as such:
```python
def postprocess(self, data):
    return {
        "predictions": data
    }
```

 TorchServe returns:
```json
{
  "code": 503,
  "type": "InternalServerException",
  "message": "Invalid model predict output"
}
```
Please note that `data` is a list of lists, for example: [[1, 2, 1], [2, 3, 3]]. (Basically, I am generating embeddings from sentences)

Now if I simply return `data` (and not a Python dictionary), it works with TorchServe but when I deploy the container on Vertex AI, it returns the following error:  `ModelNotFoundException`. I assumed Vertex AI throws this error since the return shape does not match what's expected (c.f. documentation).

Did anybody successfully manage to deploy a TorchServe instance with custom handler on Vertex AI?

**Comment by chauhang** [comment]
@Timonzimm Please check the KFP examples and this blog for the details: https://cloud.google.com/blog/topics/developers-practitioners/scalable-ml-workflows-using-pytorch-kubeflow-pipelines-and-vertex-pipelines

**Comment by Timonzimm** [comment]
Both of your links refer to the same page.

For the 1st one, that's exactly the blog I followed through but the shape they take in and return do not match what's in the Vertex AI doc, namely it should take as an input:
```json
{
  "instances": INSTANCES,
  "parameters": PARAMETERS
}
```
and return a dictionary with "predictions" as a key (see my original post).

Do you happen to know why they don't need to match these shapes in their `preprocess` (for the input) or `postprocess` (for the output)?

**Comment by Timonzimm** [comment]
Actually, making sure that the TorchServe processes correctly the input dictionary (instances) solved the issue. It seems like what's on the [article](https://cloud.google.com/blog/topics/developers-practitioners/pytorch-google-cloud-how-deploy-pytorch-models-vertex-ai) did not work for me.
