### ISSUE TITLE
Snapshot for workflow

### ISSUE THREAD

**Issue by yurkoff-mv** [pytorch/serve#1264]
For a model, I can specify a snapshot to automatically register the model. For example in file config.properties:
```
model_snapshot={"name":"startup.cfg","modelCount":1,"models":{"mnist":{"1.0":{"defaultVersion":true,"marName":"mnist.mar","minWorkers":1,"maxWorkers":5,"batchSize":1,"maxBatchDelay":5000,"responseTimeout":120}}}}
```
Can I do this for Workflow?
This is required for use in KFServing, because it does [not support model registration service](https://github.com/kserve/kserve/issues/1798#issuecomment-922499645).

**Comment by msaroufim** [comment]
Adding @maaquib to comment
