### ISSUE TITLE
add `ast.literal.eval()` to documentation

### ISSUE THREAD

**Issue by lgiommi** [pytorch/serve#1267]
I have created my custom handler, taking the default `base_handler.py` and adding just few lines, for my signal vs background discrimination use-case. So in my use-case I don't want to make inference on images but simply on lists of floats. From what I understood the entry point for the default handler is the `handle` function, which takes as argument `data` defined as `data (list): The input data that needs to be made a prediction request on`.
Because my input data is a json file where is stored a specific event in the form `{"keys":["key_1", "key_2"], "values":[value_1, value_2]}`, how can I properly make inference?
Firstly I added `file=json.load(open(data))` at the beginning of the `handle` function and I launched in the terminal a command like this `curl http://localhost:8080/predictions/pytorch_physics_3 -T predict_signal.json` and I got this error `TypeError: expected str, bytes or os.PathLike object, not list`.
I tried multiple ways (e.g. use `data[0]`, passing directly the list of floats of the event) but it seems that I didn't properly understand what is `data` and how I can use the json file passed during the request of inference.
In any case, if I use the local path of the json file instead of using `data` in `file=json.load(open(data))` all the pipeline works well giving back the correct result of prediction.

Thanks.

**Comment by msaroufim** [comment]
Hi @lgiommi the way to think of this workflow is that you have some input data that needs to be turned into a tensor so you can do an inference with a Pytorch model https://github.com/pytorch/serve/blob/master/ts/torch_handler/base_handler.py

So you have a preprocess handler which needs to take in some data and turn it into an `input` torch.tensor whether that be an image or text

Then an inference handler which basically runs `output= model(input)`

And finally a postprocess handler that turns `output` a tensor into something more usable like a float label or text or image

So your preprocess handler can take it a JSON you just need to parse it and turn it into a torch.tensor otherwise the inference handler won't know what to do with it

**Comment by lgiommi** [comment]
Hi @msaroufim thanks for your reply.
Actually, the workflow you described is exactly what I tried to reproduce starting from https://github.com/pytorch/serve/blob/master/ts/torch_handler/base_handler.py

Summing up, I have the following lines of code divided in handle, preprocess, inference, and postprocess functions (I left the other functions almost the same):
```
def preprocess(self, data):
        return torch.as_tensor(data, device=self.device)

def inference(self, data, *args, **kwargs):
        marshalled_data = data.to(self.device)
        with torch.no_grad():
            results = self.model(marshalled_data, *args, **kwargs)
        return results

def postprocess(self, data):
        return data.tolist()

def handle(self, data, context):
        self.context = context
        metrics = self.context.metrics

        data=json.load(open("/my_path/predict_bkg.json"))
        data=data["values"]
        data_preprocess = self.preprocess(data)

        if not self._is_explain():
            output = self.inference(data_preprocess)
            output = self.postprocess(output)
        else :
            output = self.explain_handle(data_preprocess, data)
        return output
```
This code is fine, I got the right prediction for the `predict_bkg.json` file but now I would like to pass the path of the file directly in the curl call, while in the handle function replace `data=json.load(open("/my_path/predict_bkg.json"))` with `data=json.load(open(data))`. But it seems that something goes wrong...

**Comment by msaroufim** [comment]
Ok so it looks like your question is about to POST JSON data to torchserve

Apologies if you've seen this already but has this worked for you? https://stackoverflow.com/a/7173011 You need to `curl --header "Content-Type: application/json" \`

Also where are you getting that error `TypeError: expected str, bytes or os.PathLike object, not list`? 

If you can share a simplified version of the model and your input data so I can fully repro, I can take a look if the above doesn't work.

**Comment by msaroufim** [comment]
Thank you for your patience @lgiommi, changed the title of your issue to make this improvement
