### ISSUE TITLE
Using log4j with an external logging service appender

### ISSUE THREAD

**Issue by benjtlv** [pytorch/serve#1275]
Please have a look at [FAQ's](../../docs/FAQs.md) and [Troubleshooting guide](../../docs/Troubleshooting.md), your query may be already addressed.

When trying to use an external logging service (Coralogix), I use an appender: com.coralogix.sdk.appenders.CoralogixLog4j1Appender

Error:
java.lang.ClassNotFoundException: com.coralogix.sdk.appenders.CoralogixLog4j1Appender

Solution: Use the coralogix appender in the log4j.properties and install the coralogix sdk as part of the JAVA envrionment (How can we add a JAVA dependency inside the torchserve envrionment ?)

Example:
```
log4j.appender.ts_log = com.coralogix.sdk.appenders.CoralogixLog4j1Appender
log4j.appender.ts_log.companyId=${CORALOGIX_COMPANY_ID}
log4j.appender.ts_log.privateKey=${CORALOGIX_PRIVATE_KEY}
log4j.appender.ts_log.applicationName=${CORALOGIX_APP_NAME}
log4j.appender.ts_log.subsystemName=${CORALOGIX_SUBSYSTEM}
log4j.appender.ts_log.layout = org.apache.log4j.PatternLayout
log4j.appender.ts_log.layout.ConversionPattern = %d{ISO8601} [%-5p] %t %c - %m%n
```

I tried to add coralogix dependencies (as much as possible) in the pom.xml located under serve/serving-sdk/
```
    <dependency>
      <groupId>com.coralogix.sdk</groupId>
      <artifactId>coralogix-sdk</artifactId>
      <version>2.0.3</version>
    </dependency>
    <dependency>
      <groupId>com.coralogix.sdk</groupId>
      <artifactId>appenders</artifactId>
      <version>2.0.3</version>
      <type>pom</type>
    </dependency>
   ...
```

And more.

I then ran inside serve/serving-sdk the command: mvn clean install
I saw there some generated files under target.

I then assumed that building a new image would take the above changes in consideration.
So I ran: ./build_image.sh -bt dev -g -cv cu111 -t torchserve:dev-gpu

and then ran the image: 
docker run --gpus all --rm -it -p 8080:8080 -p 8081:8081 --name mar -v ./config:/home/model-server/config/ -v ./model-store:/home/model-server/model-store/ torchserve:dev-gpu torchserve --model-store=/home/model-server/model-store --ts-config=/home/model-server/config/config.properties --log-config /home/model-server/config/log4j.properties

I get the following error at the beginning:
log4j:ERROR Could not instantiate class [com.coralogix.sdk.appenders.CoralogixLog4j1Appender].
java.lang.ClassNotFoundException: com.coralogix.sdk.appenders.CoralogixLog4j1Appender

log4j.properties:

```
# Primary logger
log4j.rootLogger = DEBUG, console

log4j.appender.console = org.apache.log4j.ConsoleAppender
log4j.appender.console.Target = System.out
log4j.appender.console.layout = org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern = %d{ISO8601} [%-5p] %t %c - %m%n

log4j.appender.access_log = com.coralogix.sdk.appenders.CoralogixLog4j1Appender
log4j.appender.access_log.companyId=${CORALOGIX_COMPANY_ID}
log4j.appender.access_log.privateKey=${CORALOGIX_PRIVATE_KEY}
log4j.appender.access_log.applicationName=${CORALOGIX_APP_NAME}
log4j.appender.access_log.subsystemName=${CORALOGIX_SUBSYSTEM}
log4j.appender.access_log.layout = org.apache.log4j.PatternLayout
log4j.appender.access_log.layout.ConversionPattern = %d{ISO8601} - %m%n

log4j.appender.ts_log = com.coralogix.sdk.appenders.CoralogixLog4j1Appender
log4j.appender.ts_log.companyId=${CORALOGIX_COMPANY_ID}
log4j.appender.ts_log.privateKey=${CORALOGIX_PRIVATE_KEY}
log4j.appender.ts_log.applicationName=${CORALOGIX_APP_NAME}
log4j.appender.ts_log.subsystemName=${CORALOGIX_SUBSYSTEM}
log4j.appender.ts_log.layout = org.apache.log4j.PatternLayout
log4j.appender.ts_log.layout.ConversionPattern = %d{ISO8601} [%-5p] %t %c - %m%n

log4j.appender.ts_metrics = com.coralogix.sdk.appenders.CoralogixLog4j1Appender
log4j.appender.ts_metrics.companyId=${CORALOGIX_COMPANY_ID}
log4j.appender.ts_metrics.privateKey=${CORALOGIX_PRIVATE_KEY}
log4j.appender.ts_metrics.applicationName=${CORALOGIX_APP_NAME}
log4j.appender.ts_metrics.subsystemName=${CORALOGIX_SUBSYSTEM}
log4j.appender.ts_metrics.layout = org.apache.log4j.PatternLayout
log4j.appender.ts_metrics.layout.ConversionPattern = %d{ISO8601} - %m%n

log4j.appender.model_log = com.coralogix.sdk.appenders.CoralogixLog4j1Appender
log4j.appender.model_log.companyId=${CORALOGIX_COMPANY_ID}
log4j.appender.model_log.privateKey=${CORALOGIX_PRIVATE_KEY}
log4j.appender.model_log.applicationName=${CORALOGIX_APP_NAME}
log4j.appender.model_log.subsystemName=${CORALOGIX_SUBSYSTEM}
log4j.appender.model_log.layout = org.apache.log4j.PatternLayout
log4j.appender.model_log.layout.ConversionPattern = %d{ISO8601} [%-5p] %t %c - %m%n

log4j.appender.model_metrics = com.coralogix.sdk.appenders.CoralogixLog4j1Appender
log4j.appender.model_metrics.companyId=${CORALOGIX_COMPANY_ID}
log4j.appender.model_metrics.privateKey=${CORALOGIX_PRIVATE_KEY}
log4j.appender.model_metrics.applicationName=${CORALOGIX_APP_NAME}
log4j.appender.model_metrics.subsystemName=${CORALOGIX_SUBSYSTEM}
log4j.appender.model_metrics.layout = org.apache.log4j.PatternLayout
log4j.appender.model_metrics.layout.ConversionPattern = %d{ISO8601} - %m%n

log4j.logger.org.pytorch.serve = DEBUG, ts_log
log4j.logger.ACCESS_LOG = INFO, access_log
log4j.logger.TS_METRICS = ALL, ts_metrics
log4j.logger.MODEL_METRICS = ALL, model_metrics
log4j.logger.MODEL_LOG = ALL, model_log

log4j.logger.org.apache = OFF
log4j.logger.io.netty = ERROR
```

I really don't know what to do in order to pass the Coralogix SDK to java.
I tried using one of generated jar, with vmargs=-jar <file>.jar and it didn't work either.

I would really love some help with this guys

**Comment by benjtlv** [comment]
Hello
Sure we can do that.
I'd love to test this locally but I would be happy to know how.

Basically after I run mvn clean install, I get files in target/. But how can I update torchserve the right way so it takes the changes into account ? 

I know that the build produces torchserve-plugins-sdk-0.0.4.jar so I thought I could just give that jar to the wmargs but it says there is no main manifest attribute. I know it seems naive but I'm no java expert so I don't see no other way.

You are part of the team that built torchserve with Java so you might be able to tell me what to do after the build.
At some point, you guys created the pom.xml, and made something about it to build torchserve. So if we add some dependencies we should be able to reproduce every step.

Waiting for an answer

**Comment by lxning** [comment]
@benjtlv the cmd: " ./build_image.sh -bt dev -g -cv cu111 -t torchserve:dev-gpu" picks the branch master to build the docker image. Your changes(ie, pom.xml) will not be picked up by docker image if your changes is not in master branch. Check [ref](https://github.com/pytorch/serve/tree/master/docker#create-torchserve-docker-image)

**Comment by lxning** [comment]
@benjtlv build_image.sh always picks up code from remote branch (ie. origin/xxx).

**Comment by lxning** [comment]
@benjtlv you can follow the following steps.

1.  Run TS in docker container

- fork Torchserve
- update your own repo
* update SDK 
* change the repo to your repo at  https://github.com/pytorch/serve/blob/master/docker/Dockerfile.dev#L53 
* check in your changes into your repo
* run build_image.sh 

2. Run TS on local host

- python ts_scripts/install_dependencies.py --environment=dev
- python ts_scripts/install_from_src.py

**Comment by benjtlv** [comment]
> @benjtlv you can follow the following steps.
> 
> 1. Run TS in docker container
> 
> * fork Torchserve
> * update your own repo
> 
> * update SDK
> * change the repo to your repo at  https://github.com/pytorch/serve/blob/master/docker/Dockerfile.dev#L53
> * check in your changes into your repo
> * run build_image.sh
> 
> 1. Run TS on local host
> 
> * python ts_scripts/install_dependencies.py --environment=dev
> * python ts_scripts/install_from_src.py

Thank you very much, I will try that ASAP

**Comment by benjtlv** [comment]
So I tried the 2nd solution (run TS) on localhost and I still get the com.coralogix.sdk.appenders.CoralogixLog4j1Appender class not found... I double verified that my pom was edited with the new dependency, I even ran mvn clean install. What is going wrong here ? Maybe you guys can try on your side with another SDK ?

**Comment by benjtlv** [comment]
Okay so it seems that I managed to resolve the issue of dependency.
All I had to do is add: 

```
implementation group: 'com.coralogix.sdk', name: 'coralogix-sdk', version: '2.0.3'
implementation group: 'com.coralogix.sdk', name: 'log4j-appender', version: '2.0.3
```

in the build.gradle (notice log4j-appender instead of log4j2appender)

So let me recall what the log4j.properties look like:

```
# Primary logger
log4j.rootLogger = DEBUG, console, access_log, ts_log, ts_metrics, model_log, model_metrics

log4j.appender.console = org.apache.log4j.ConsoleAppender
log4j.appender.console.Target = System.out
log4j.appender.console.layout = org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern = %d{ISO8601} [%-5p] %t %c - %m%n

log4j.appender.access_log = com.coralogix.sdk.appenders.CoralogixLog4j1Appender
log4j.appender.access_log.companyId=8458
log4j.appender.access_log.privateKey=${CORALOGIX_PRIVATE_KEY}
log4j.appender.access_log.applicationName=${CORALOGIX_APP_NAME}
log4j.appender.access_log.subsystemName=${CORALOGIX_SUBSYSTEM}
log4j.appender.access_log.layout = org.apache.log4j.PatternLayout
log4j.appender.access_log.layout.ConversionPattern = %d{ISO8601} - %m%n

log4j.appender.ts_log = com.coralogix.sdk.appenders.CoralogixLog4j1Appender
log4j.appender.ts_log.companyId=8458
log4j.appender.ts_log.privateKey=${CORALOGIX_PRIVATE_KEY}
log4j.appender.ts_log.applicationName=${CORALOGIX_APP_NAME}
log4j.appender.ts_log.subsystemName=${CORALOGIX_SUBSYSTEM}
log4j.appender.ts_log.layout = org.apache.log4j.PatternLayout
log4j.appender.ts_log.layout.ConversionPattern = %d{ISO8601} [%-5p] %t %c - %m%n

log4j.appender.ts_metrics = com.coralogix.sdk.appenders.CoralogixLog4j1Appender
log4j.appender.ts_metrics.companyId=8458
log4j.appender.ts_metrics.privateKey=${CORALOGIX_PRIVATE_KEY}
log4j.appender.ts_metrics.applicationName=${CORALOGIX_APP_NAME}
log4j.appender.ts_metrics.subsystemName=${CORALOGIX_SUBSYSTEM}
log4j.appender.ts_metrics.layout = org.apache.log4j.PatternLayout
log4j.appender.ts_metrics.layout.ConversionPattern = %d{ISO8601} - %m%n

log4j.appender.model_log = com.coralogix.sdk.appenders.CoralogixLog4j1Appender
log4j.appender.model_log.companyId=8458
log4j.appender.model_log.privateKey=${CORALOGIX_PRIVATE_KEY}
log4j.appender.model_log.applicationName=${CORALOGIX_APP_NAME}
log4j.appender.model_log.subsystemName=${CORALOGIX_SUBSYSTEM}
log4j.appender.model_log.layout = org.apache.log4j.PatternLayout
log4j.appender.model_log.layout.ConversionPattern = %d{ISO8601} [%-5p] %t %c - %m%n

log4j.appender.model_metrics = com.coralogix.sdk.appenders.CoralogixLog4j1Appender
log4j.appender.model_metrics.companyId=8458
log4j.appender.model_metrics.privateKey=${CORALOGIX_PRIVATE_KEY}
log4j.appender.model_metrics.applicationName=${CORALOGIX_APP_NAME}
log4j.appender.model_metrics.subsystemName=${CORALOGIX_SUBSYSTEM}
log4j.appender.model_metrics.layout = org.apache.log4j.PatternLayout
log4j.appender.model_metrics.layout.ConversionPattern = %d{ISO8601} - %m%n

log4j.logger.org.pytorch.serve = DEBUG, ts_log
log4j.logger.ACCESS_LOG = INFO, access_log
log4j.logger.TS_METRICS = ALL, ts_metrics
log4j.logger.MODEL_METRICS = ALL, model_metrics
log4j.logger.MODEL_LOG = ALL, model_log

log4j.logger.org.apache = ON
log4j.logger.io.netty = ERROR
```

I don't see the logs in the coralogix interface though. What should I change in the properties ?
