### ISSUE TITLE
Avoid redundant copies of Model members

### ISSUE THREAD

**Issue by mycpuorg** [pytorch/serve#130]
[Snapshot Feature](https://github.com/pytorch/serve/pull/111/files/a2a8d17552664161a31b7fa2a54abc9607215039#) introduces a new class in the following file.
`frontend/server/src/main/java/org/pytorch/serve/snapshot/ModelInfo.java`

It is unclear how this is different from `class Model`, it seems redundant? If it's redundant, we should remove it. If it's not redundant, then why are moving `class ModelInfo` under snapshot. Since `class Snaphot` should, in theory, not be concerned about specifics of the model as per the documentation.

This results in duplication of members in memory. This implementation is OK for as long as the number of models is low. The moment we start scaling things the larger memory occupant members will also be duplicated. AFAIK, currently we are not using any data members that occupy large amounts of memory in ModelInfo that may not always be the case.

Instead, if we can use a class that only references members which are already loaded into memory of, say `class Model`, in memory that might be efficient.  The urgency of this problem is unclear, depending on a "typical" usage scenario the impact of this will vary.

**Comment by lokeshgupta1975** [comment]
@mycpuorg Can you define the next action on this in the context of #152 and see if this issue can be closed?

**Comment by mycpuorg** [comment]
The changes look good. Please submit the PR following the template (what was tested etc). Thanks.

**Comment by mycpuorg** [comment]
Reopening this since the changes have not made it to `master` branch yet

**Comment by harshbafna** [comment]
Closing as this has been merged to master in 0.1.1 release.
