### ISSUE TITLE
Question about Batch Inference

### ISSUE THREAD

**Issue by osmanager** [pytorch/serve#1301]
Hello guys, thank you for supporting TorchServe 👍 

I have a question about the Batch Inference

I understand that `batch size` mean the number of training examples utilized in one iteration.
So I expected `Batch Inference` will worked with more than one inputs.

Let see example 👀 
https://pytorch.org/serve/batch_inference_with_ts.html#batch-inference-of-resnet-152-configured-through-config-properties
batchSize is set 3 but input has a just one file
`$ curl http://localhost:8080/predictions/resnet-152-batch_v2 -T kitten.jpg`

Than in this case, what is different from case of batshSize set 1 ❔

Here is my expecting run way (just example)
`$ curl http://localhost:8080/predictions/resnet-152-batch_v2 -F 'image=@file1.gif' -F 'image2=@file2.gif'`

Am I misunderstanding? 😢

**Comment by msaroufim** [comment]
Hi @osmanager so the way batch sizes work is they also use a delay to decide how long to wait for examples to fill a batch

So for example if you have batch size 3 and only send one example, then torchserve will wait until that batch delay and process only that one example. Similarly if you send a synchronous request then that's also like sending an example and just waiting until the batch delay.

So instead try sending requests in this fashion and see if that solves your problem https://github.com/pytorch/serve/issues/1235#issuecomment-938414534



https://github.com/pytorch/serve/blob/master/docs/batch_inference_with_ts.md#torchserve-model-configuration

**Comment by osmanager** [comment]
Dear @msaroufim 
I understand how the TorchServe works and the usage of `max_batch_delay`

Thank you for your detail comment!! 👍 👍 

Best Regards
Seungmin Oh

**Comment by braindotai** [comment]
@osmanager @msaroufim on sending multiple requests, I'm getting this error:
```
model: face-detection, number of batch response mismatched, expect: 2, got: 1
```
below's my config file:
```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
load_models=all
install_py_dep_per_model=true

models={\
  "face-recognition": {\
    "1.0": {\
        "defaultVersion": true,\
        "marName": "face-recognition.mar",\
        "minWorkers": 1,\
        "maxWorkers": 5,\
        "batchSize": 64,\
        "maxBatchDelay": 200,\
        "responseTimeout": 500\
    }\
  },\
  "face-detection": {\
    "1.0": {\
        "defaultVersion": true,\
        "marName": "face-detection.mar",\
        "minWorkers": 1,\
        "maxWorkers": 5,\
        "batchSize": 64,\
        "maxBatchDelay": 200,\
        "responseTimeout": 500\
    }\
  }\
}
```
And here's my handler:
```python
import base64
from ts.torch_handler.base_handler import BaseHandler
from torchvision import transforms
from PIL import Image
import cv2
import numpy as np
import logging

class ModelHandler(BaseHandler):
    def initialize(self, context):
        super().initialize(context)

        self.transform = transforms.Compose([
            transforms.Resize((72, 54)),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
        ])

    def preprocess(self, data):
        encoded_bytes = data[0].get("data") or data[0].get("body")
        cv2_decoded_bytes = base64.b64decode(encoded_bytes)
        cv2_decoded = np.frombuffer(cv2_decoded_bytes, dtype = np.uint8)
        cv2_image = cv2.imdecode(cv2_decoded, 1)

        image = Image.fromarray(cv2_image)
        image = self.transform(image)

        return image.unsqueeze(0)

    def postprocess(self, inference_output):
        return inference_output.tolist()
```

Just using requests library to send the requests which is as simple as:
```python
response = requests.post("http://localhost:8080/predictions/face-detection/", data = cv2_encoded_bytes)
```
When I run this same script from 2 separate terminals I get the error batch response mismatched.

Please someone help, Im having very hard time getting around this issue.

Thanks for your time.

**Comment by msaroufim** [comment]
On my phone now so will be brief but requests makes calls in a synchronous manner even if from multiple shells. Try using curl in the way I suggest in my last comment or using an async library
