### ISSUE TITLE
Trouble deploying Yolov5 model in Torch Serve environment

### ISSUE THREAD

**Issue by atinesh-s** [pytorch/serve#1315]
I am trying to deploy the [Yolov5](https://github.com/ultralytics/yolov5) model in the [Torch Serve](https://github.com/pytorch/serve) environment but on sending the below request to the endpoint I am not getting any response, the request seems to get stuck 

`$ curl http://127.0.0.1:8080/predictions/yolov5 -T /home/atinesh/Desktop/COCO_val2014_000000562557.jpg`

**Command to compile and deploy the model**

Starting container

```
$ sudo docker run -d --rm -it \
-p 8080:8080 -p 8081:8081 -p 8082:8082 \
--name torchserve-cpu \
-v $(pwd)/model-server/model-store:/home/model-server/model-store \
-v $(pwd)/model-server/examples:/home/model-server/examples \
pytorch/torchserve:latest
```

Logging in the container and compiling `.mar` file using _Torch Model Archiver_

```
$ sudo docker exec -u root -it torchserve-cpu /bin/bash

root@<container-id>:<path># torch-model-archiver --model-name yolov5 \
--version 1.0 \
--serialized-file /home/model-server/examples/object_detector/yolov5/yolov5x.pt \
--handler /home/model-server/examples/object_detector/yolov5/torchserve_handler.py \
--export-path /home/model-server/model-store \
--extra-files /home/model-server/examples/object_detector/yolov5/torchserve_handler.py
```

Registering the model
`$ curl -X POST "http://localhost:8081/models?url=/home/atinesh/model-server/model-store/yolov5.mar"`

Scaling the worker
`$ curl -v -X PUT "http://localhost:8081/models/yolov5?min_worker=1"`

Deployed model is running properly, on checking model health I am getting below response
```
$ curl "http://localhost:8081/models/yolov5"
[
  {
    "modelName": "yolov5",
    "modelVersion": "1.0",
    "modelUrl": "/home/atinesh/model-server/model-store/yolov5.mar",
    "runtime": "python",
    "minWorkers": 1,
    "maxWorkers": 1,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": false,
    "workers": [
      {
        "id": "9001",
        "startTime": "2021-11-11T05:09:57.190Z",
        "status": "READY",
        "memoryUsage": 0,
        "pid": 507,
        "gpu": false,
        "gpuUsage": "N/A"
      }
    ]
  }
]
```

**Other information**

[Yolov5](https://github.com/ultralytics/yolov5) (XLarge) model is trained on custom [COCO](https://cocodataset.org/#home) dataset to detect 2 objects _person_ & _bicycle_, below is the link of the trained model file

[yolov5x.pt](https://www.dropbox.com/s/seu4ckvtuckhrpl/yolov5x.pt?dl=0)

Image used for Inference: [COCO_val2014_000000562557.jpg](https://www.dropbox.com/s/v4lst105hkfzv0n/coco_val2014_000000562557.jpg?dl=0)

I have tried two different handler files [handler #1](https://github.com/louisoutin/yolov5_torchserve/blob/master/ressources/torchserve_handler.py), [handler #2](https://gist.github.com/joek13/b895db0cd50a7c71a123611885057c69) but the same issue persists

**Comment by msaroufim** [comment]
Hi @atinesh-s I'm not sure what the issue is exactly? did you try running an inference against that model and what error did you get then? Does the model work without torchserve?

Or is the issue that GPU is not being used? I see you've named your container `torchserve-cpu` but just double checking

I'd suggest creating a `config.properties` and passing it the number of workers and then when you start torchserve you can pass in this flag `--ts-config config.properties` without having to call scale workers

I also noticed you don't seem to have an `inference` function in any of your handlers? Is that accurate? https://github.com/louisoutin/yolov5_torchserve/blob/master/ressources/torchserve_handler.py

**Comment by atinesh-s** [comment]
> Hi @atinesh-s I'm not sure what the issue is exactly? did you try running an inference against that model and what error did you get then? Does the model work without torchserve?
> 
> Or is the issue that GPU is not being used? I see you've named your container `torchserve-cpu` but just double checking
> 
> I'd suggest creating a `config.properties` and passing it the number of workers and then when you start torchserve you can pass in this flag `--ts-config config.properties` without having to call scale workers
> 
> I also noticed you don't seem to have an `inference` function in any of your handlers? Is that accurate? https://github.com/louisoutin/yolov5_torchserve/blob/master/ressources/torchserve_handler.py

Hello @msaroufim model work well outside the torchserve environment below is the inference result

[![COCO-val2014-000000562557.jpg](https://i.postimg.cc/J0rT88ZD/COCO-val2014-000000562557.jpg)](https://postimg.cc/qhFcc9m4)

I am creating a `torchserve-cpu` container using torchserve cpu image so it should not suppose to use GPU anyway

I am not sure about the `inference` function in handler files, those handler files were working earlier as users mentioned in their repositories [Repo #1](https://github.com/louisoutin/yolov5_torchserve), [Repo #2 ](https://gist.github.com/joek13/b895db0cd50a7c71a123611885057c69)

I will try to use `config.properties` as you suggested and check if it helps
