### ISSUE TITLE
request-specific http error codes in batch 

### ISSUE THREAD

**Issue by sharvil** [pytorch/serve#1316]
It would be nice if custom handlers could return a status code + json response in case of error. There are situations where, for instance, a handler can't preprocess the input as provided and the caller needs to take action to remediate the problem before trying again.

**Comment by msaroufim** [comment]
One way arorund this is in the the postt process handler you can return an arbitrary list so that list can contain

`[inferences, debug_data]` where debug data can be an an arbitrary data structure like a dict where you can the problem in - does that work or were you thinking of something else?

**Comment by sharvil** [comment]
Thanks for the suggestion. Unfortunately, that doesn't quite work because it means the client will get a `200 OK` even though the request failed. If torchserve is used as an API server it needs to provide a semantically meaningful HTTP response in case of failure.

For example, if the client provided bad input that's detected during preprocessing, the handler should be able to tell torchserve to reply with `400 Bad Request` and a response body containing more specific details.

Batched requests will also require proper demuxing. If multiple clients' requests are batched together and one of them fails, only that client should get the error and the others should get success responses.

**Comment by msaroufim** [comment]
Just to be clear torchserve won't give back a `200` response if the preprocess function fails. Batch inferencing is a more peculiar use case which I can get back to you on as far as returning custom status code to each client

As far as returning a custom HTTP code, I'm adding @lxning who may know of some existing workaround

**Comment by msaroufim** [comment]
@sharvil does this solve your problem https://github.com/pytorch/serve/pull/1311

**Comment by sharvil** [comment]
That's a step in the right direction for sure, but doesn't quite go far enough.

Error reporting should be per-request, not per-batch -- otherwise, one bad client can trivially DoS the entire server. Raising a `PredictionException` doesn't allow for fine-grained error reporting.

Also, I'm not sure if I missed it but it's unclear to me from that PR how the `PredictionException` text gets mapped to the HTTP response. Does it end up in the body? If not, it would be good to provide a mechanism to return some more context about the error.

**Comment by msaroufim** [comment]
Makes sense - I will change the title of this request to track it

**Comment by sharvil** [comment]
Was this issue accidentally closed? The associated PR is still open and I don't see any other activity in here.

**Comment by jamessocure** [comment]
I had a similar requirement. After digging into the code, I noticed that torchserve already supports it. It probably needs to be documented. The below is a minimal example:

```python
class Handler(object):
  
  def initialize(self, context):
    pass
  
  def handle(self, data, context):
    item0_response = {'score': 0.99}
    context.set_response_status(code=200, idx=0)

    item1_response = {'code': 600, 'code': 'UUID is missing'}
    context.set_response_status(code=400, idx=1)
    
    return [
      item0_response,
      item1_response
    ]
```

**Comment by msaroufim** [comment]
> I had a similar requirement. After digging into the code, I noticed that torchserve already supports it. It probably needs to be documented. The below is a minimal example:
> 
> 
> 
> ```python
> 
> class Handler(object):
> 
>   
> 
>   def initialize(self, context):
> 
>     pass
> 
>   
> 
>   def handle(self, data, context):
> 
>     item0_response = {'score': 0.99}
> 
>     context.set_response_status(code=200, idx=0)
> 
> 
> 
>     item1_response = {'code': 600, 'code': 'UUID is missing'}
> 
>     context.set_response_status(code=400, idx=1)
> 
>     
> 
>     return [
> 
>       item0_response,
> 
>       item1_response
> 
>     ]
> 
> ```

Would you like to make a PR to add this in our docs folder about batching?
