### ISSUE TITLE
Serving throughput should not scale with memory usage of GPU

### ISSUE THREAD

**Issue by misrasaurabh1** [pytorch/serve#1320]
We are serving transformer models with TorchServe and to improve throughput we increased the `default_workers_per_model` parameter to 3. We chose the number 3 because any larger number will lead to the GPU running out of memory. 
This leads to an observation that scaling throughput with TorchServe is incorrectly linked to loading multiple copies of a model in memory and serving them independently. This should be very inefficient from a GPU's perspective because multiple copies of a model will lead to excessive memory read operations and cache thrashing for each new request. Also transformer models could be huge so one cannot load many replicas in GPU memory. So if GPU memory only allows for 1 model replica then Torch serve just synchronously serves requests leading to a very low throughput that is bottlenecked by serving by a single CPU core which blocks by just waiting for GPU to finish processing most of the time.

If different workers were able to use a single model by sharing the same CUDA queue, then with just a fixed amount of memory the performance of the server could scale to the same effect and potentially much more. Currently the max number of workers is limited by the amount of GPU memory and if all the workers shared the same model then we could spawn even more number of workers which could increase throughput.

The expectation is that the throughput of a single GPU server should not scale with the amount of GPU memory consumed and the number of CPU workers should all use the same GPU model. What are your thoughts on such a server architecture? I believe this is important to result in a high performance model server.

**Comment by msaroufim** [comment]
Hi, @misrasaurabh1 you are correct. As of now the best way to scale GPU throughput is to either increase the batch size or number of workers until you run out of memory. Depending on the model there are also some custom optimizations we have available like faster-transformer for BERT.

But your question is really about how to share model weights among workers. We are actively working on a method to share model weights with an optimized `frontend` in c++. Out of curiosity what's your use case? We could use it as a baseline for our benchmarks.

**Comment by misrasaurabh1** [comment]
Thanks for your consideration. Our use case is serving a large generative huggingface transformer model with top-P sampling for generating 3 sentences for every request.

**Comment by msaroufim** [comment]
For performance we've since learned a lot since this PR was made. There are some simple configs you can try but also lots of model optimizations like using optimized runtimes which will help. Start here and feel free to reopen another issues if you'd like to ask me more questions https://github.com/pytorch/serve/blob/master/docs/performance_guide.md
