### ISSUE TITLE
Torchserve built in a Dockerfile with apex?

### ISSUE THREAD

**Issue by ytsheng** [pytorch/serve#1335]
I need to package a model library that uses apex, but unfortunately unable to do so. Currently all the docker file examples uses pytorch's `runtime` rather than `devel` images. According to the apex [documentation](https://github.com/NVIDIA/apex/tree/master/examples/docker), a `devel` image is necessary. I am curious if anyone can share a Dockerfile that has the two working together. (apex and torchserve).

**Comment by msaroufim** [comment]
Hi @ytsheng PyTorch has native support for apex so you shouldn't need to install any other packages. Any particular features that you didn't find available in stock Pytorch

https://twitter.com/PyTorch/status/1450502326834368516?s=20
https://pytorch.org/blog/accelerating-training-on-nvidia-gpus-with-pytorch-automatic-mixed-precision/
https://pytorch.org/tutorials/recipes/recipes/amp_recipe.html#inference-evaluation

In your `inference()` all you'd need to do is something like

```
with torch.cuda.amp.autocast():
  model.forward(input)
```

If you're looking at BERT optimizations you may also be interested in checking out https://github.com/pytorch/serve/tree/master/examples/FasterTransformer_HuggingFace_Bert

**Comment by ytsheng** [comment]
If we have to use apex, is this possible? Given that the container types (from the examples provided in github and the examples provided in apex) require different image types. If it is possible, could you share an example?

**Comment by HamidShojanazeri** [comment]
@ytsheng in that sense we might need a custom container, but as discussed offline and @msaroufim mentioned probably Pytorch amp package should address the issue.

**Comment by msaroufim** [comment]
Hi @ytsheng sorry I lost track of this ask, were you able to merge the 2 dockerfiles and solve your problem?
