### ISSUE TITLE
Exception when starting Torchserve

### ISSUE THREAD

**Issue by cyberkostas1984** [pytorch/serve#1348]
## Context
Hi, 

I'm trying to deploy a Detectron2 model using Torchserve, but I'm getting a generic excetion when starting torchserve.

Could you please let me know if there is anything that I'm missing or I could try?

Thanks

```
torch                   1.10.0
torch-model-archiver    0.5.0
torch-workflow-archiver 0.2.0
torchaudio              0.10.0
torchserve              0.5.0
torchtext               0.11.0
torchvision             0.11.1
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
OS: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```
## Your Environment

* Installed using source? [yes/no]: `no`
* Are you planning to deploy it using docker container? [yes/no]:`yes`
* Is it a CPU or GPU environment?:`GPU`
* Using a default/custom handler? `[If possible upload/share custom handler/model]:custom&default has been tested (current is custom)`
* What kind of model is it e.g. vision, text, audio?:`vision`
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?`both`
  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: [config-handler.zip](https://github.com/pytorch/serve/files/7609488/config-handler.zip)
* Link to your project [if any]:

## Expected Behavior

Torchserve API endpoint should be running successfully 
## Current Behavior

Torchserve API endpoint throws a generic exception

## Steps to Reproduce

1. Model creation: https://detectron2.readthedocs.io/en/latest/tutorials/getting_started.html
https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5
2. Model conversion
```bash
torch-model-archiver --model-name d2_model \
--version 1.0 \
--serialized-file model_final.pth \
--extra-files config.yaml \
--handler detectron2_handler.py -f
```
3. Starting torchserve:
```bash
torchserve --start --ncs --model-store model_store --models d2_model.mar
```

Initial author for handler: https://github.com/facebookresearch/detectron2/issues/1289#issuecomment-675022985

## Failure Logs [if any]

[ts_log.log](https://github.com/pytorch/serve/files/7609400/ts_log.log)

**Comment by marvinfds** [comment]
Try checking your torch handler script. There might be a programming error if you have modified anything.

**Comment by lxning** [comment]
According the attached ts_log.log ("2021-11-26 14:41:08,903 [WARN ] W-9000-d2_model_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: d2_model, error: Worker died."), it shows that there is something wrong with the model. 

Pls check if there are any detail information about the model error in the log model_log.log.
