### ISSUE TITLE
torchserve in a video streaming scenario?

### ISSUE THREAD

**Issue by Haydnspass** [pytorch/serve#1355]
Hey,
Maybe that is a stupid question but I was wondering if it is possible (and if so, how) to use torchserve in a video streaming scenario where the model utilises sequential information?

Imagine a device with a webcam where inference should be performed on the respective stream. 
If my model not only operates on single frames but also on a frame window of 3 frames in total (so let's say the current frame t0, t0 - 1 and t0 - 2) how would one do this? If I use the REST API like in the examples I would basically need to cache the frames locally and send 3 times the amount of frames to an inference server. 

Any advice on how to use torchserve with streaming data?

**Comment by lxning** [comment]
@Haydnspass There are 2 options:

Option1: batch on client side.
client batach 3 frames and send one request to TS via either REST API or gRPC API.

Option2: set batch_size=3 in model registration
client send 1 frame per request to TS via either REST API or gRPC API.

**Comment by Haydnspass** [comment]
@lxning thanks for your response

Option 1: still sending 3 times the data no? Cause the batches would need to be: 
[-2, -1, 0], [-1, 0, 1], [0, 1, 2] etc. (frame index in the brackets)

Option 2: conflicts with statelessness of REST API no? there could be multiple clients sending requests for the same model?
Reading https://github.com/pytorch/serve/blob/master/docs/batch_inference_with_ts.md to me looks like batch is only for maximizing the GPU utilization and not to combine multiple requests no?

**Comment by lxning** [comment]
@Haydnspass 
option1: batching on client side
client can combine 3 frames into one request if your model can identify each frame.

option2: batching on TS side.
TS batching supports both CPU and GPU. However, it batches requests from all clients together, not per client.

According to your use case, you can choose option1 if there are multiple clients sending requests to the same TS host.

**Comment by chauhang** [comment]
Please see example: https://github.com/pytorch/serve/tree/master/examples/image_classifier/near_real_time_video
