### ISSUE TITLE
Log 4j Vulnerability found, need an implementation to remove log4j dependencies

### ISSUE THREAD

**Issue by suleman-px** [pytorch/serve#1369]
* torchserve version: 0.4.2 
* torch version: 1.10.0

**Comment by dconathan** [comment]
Looks like this is addressed by  https://github.com/pytorch/serve/pull/1364 and will be released in v0.5.1?

**Comment by nskool** [comment]
Hi, that is correct. It's underway currently, and will be updating soon.

**Comment by suleman-px** [comment]
Hi, that's great to hear. is it possible for you to provide an estimated timeline for this?

**Comment by lxning** [comment]
v0.5.1 is released today.
