### ISSUE TITLE
gRPC Client ~4x slower than http requests in docker

### ISSUE THREAD

**Issue by braindotai** [pytorch/serve#1375]
Im running the containerized torchserve to deploy a simple face recognition model.
I have a 20mb torchscript model, that takes an input image of size 3x72x53 and returns K dimensional features as the embeddings.
Now by simply using the requests library in python, my inference runtime is 0.02 seconds (which is very good since its very close to running the same torchscript model locally), but while running the same model with gRPC client as described in the docs its taking > 0.07 seconds.

Now out of curiosity, I ran the same client script inside the docker container for both http and grpc, and I found that grpc is equally faster if not more. This means that the issue has something to do with the docker port forwarding I suppose.

Here's my config.properties:
```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
load_models=all
install_py_dep_per_model=true # since I have cv2 dependency
```
This is my handler:
```python
import torch
import base64
from ts.torch_handler.base_handler import BaseHandler
from torchvision import transforms
from PIL import Image
import cv2
import numpy as np

class ModelHandler(BaseHandler):
    def initialize(self, context):
        super().initialize(context)

        self.transform = transforms.Compose([
            transforms.Resize((72, 54)),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
        ])

    def preprocess(self, data):
        images = []
        for instance in data:
            try:
                cv2_encoded_bytes = instance.get("data") or instance.get("body")
            except:
                cv2_encoded_bytes = instance

            if isinstance(cv2_encoded_bytes, (bytearray, bytes)):
                cv2_decoded_bytes = base64.b64decode(cv2_encoded_bytes)
                cv2_decoded = np.frombuffer(cv2_decoded_bytes, dtype = np.uint8)
                cv2_image = cv2.imdecode(cv2_decoded, 1)

                # Im sending cv2.imcode as the model inputs to have fewer network bottlenecks
                # hence using cv2.imdecode to get back the image

                image = Image.fromarray(cv2_image)
                image = self.transform(image)
            else:
                image = torch.FloatTensor(image)

            images.append(image)

        return torch.stack(images).to(self.device)

    def postprocess(self, inference_output): # same as BaseHandler
        return inference_output.tolist()
```

And below is my client file that has the logic of calling the model from http and grpc:
```python
import cv2
import base64
import numpy as np
import requests
from time import time

import grpc
import inference_pb2
import inference_pb2_grpc
import management_pb2_grpc

cv2_image = np.ones((512, 512, 3), dtype = np.uint8)
h, w, c = cv2_image.shape
has_encoded, cv2_encoded = cv2.imencode('.jpg', cv2_image, [int(cv2.IMWRITE_JPEG_QUALITY), 50])
cv2_encoded_bytes = base64.b64encode(cv2_encoded)

def infer(stub, model_name, model_input):
    return stub.Predictions(
        inference_pb2.PredictionsRequest(
            model_name = model_name,
            input = {'data': model_input}
        )
    )

if __name__ == '__main__':
    channel = grpc.insecure_channel('localhost:7070')
    stub = inference_pb2_grpc.InferenceAPIsServiceStub(channel)

    times = []
    for _ in range(100):
        start = time()
        response = requests.post("http://localhost:8080/predictions/face-recognition/", data = cv2_encoded_bytes)
        # response = infer(stub, 'face-recognition', cv2_encoded_bytes)
        took = time() - start
        times.append(took)
        print(f'Took \t: {took}')

    times = np.array(times)
    print(f'Mean time \t: {np.mean(times)}')
    print(f'Median time \t: {np.median(times)}')
```

Outputs with http when running from host:
```
Mean time       : 0.025488979816436767
Median time     : 0.023711800575256348
```
Outputs with grpc when running from host:
```
Mean time       : 0.07445537805557251
Median time     : 0.07411670684814453
```
----------

Outputs with http when running within the container:
```
Mean time       : 0.02136315107345581
Median time     : 0.02019190788269043
```
Outputs with grpc when running within the container:
```
Mean time       : 0.019478685855865478
Median time     : 0.01735556125640869
```

Any way I can get around this latency?

Thanks for your time.

**Comment by lxning** [comment]
@braindotai grpc default port is  7070 / 7071 (see[ref](https://github.com/pytorch/serve/tree/master/docker#running-torchserve-in-a-production-docker-environment) ).

**Comment by braindotai** [comment]
@lxning yes that's right, and `grpc_inference_port` is set to 7070 by default unless we change in the config.properties which I'm not. And I'm doing the port forwarding while running the docker container as usual. 
I'm able to perform the grpc inference, no issues in that, its just that grpc inference seems too slow when compared to http.

**Comment by lxning** [comment]
@braindotai I did test on my end. It shows latency is slightly higher when client is outside of docker container, but not significant. Here are the steps what I did.

1. start torchserve in docker: 
`docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8080:8080 -p8081:8081 -p8082:8082 -p7070:7070 -p7071:7071 --mount type=bind,source=/home/ubuntu/serve/model_store,target=/tmp/models torchserve:0.5.2-gpu torchserve --model-store=/tmp/models`

2. register model: 
`python ts_scripts/torchserve_grpc_client.py register densenet161 https://torchserve.pytorch.org/mar_files/densenet161.mar`

3. run client inside docker container:
`model-server@bbab254b4a7a:~/serve$ python ts_scripts/torchserve_grpc_client.py infer densenet161 examples/image_classifier/kitten.jpg
Took 	: 0.10868501663208008
{
  "tiger_cat": 0.46933549642562866,
  "tabby": 0.4633878469467163,
  "Egyptian_cat": 0.06456155329942703,
  "lynx": 0.001282822573557496,
  "plastic_bag": 0.00023323034110944718
}`

4. run client outside docker container:
`python ts_scripts/torchserve_grpc_client.py infer densenet161 examples/image_classifier/kitten.jpg
Took 	: 0.12198972702026367
{
  "tiger_cat": 0.46933549642562866,
  "tabby": 0.4633878469467163,
  "Egyptian_cat": 0.06456155329942703,
  "lynx": 0.001282822573557496,
  "plastic_bag": 0.00023323034110944718
}`

**Comment by lxning** [comment]
@braindotai pls check your environment when you test the performance and let me know if the issue is still there.

**Comment by braindotai** [comment]
@lxning I've found someone interesting, I'm on windows, so when I do the same testing in the wsl 2 Ubuntu terminal, I'm not able to reproduce the issue.
But on running same scripts in the windows bash I can see the 4x speed difference.
So I believe it's not a torchserve issue, but possibly something to do with the windows docker, but I'm confused since even the wsl uses the same docker desktop so why the performance difference.

**Comment by lxning** [comment]
@braindotai Thank you for the update. The [docker image](https://hub.docker.com/r/pytorch/torchserve) is built on ubuntu. You can try building a docker image on windows to see if it can help.

**Comment by lxning** [comment]
@braindotai pls feel free to reopen this ticket if there are any further issues.

**Comment by ndvbd** [comment]
[braindotai](https://github.com/braindotai) all, I am seeing the same thing, on Ubuntu 22, with no docker. I'm running a simple pretrained huggingface T5 model, sending to it 3 words, and it's much slower with gRPC than simple curl command. Can you reopen the issue? It takes a lot of time (4 seconds!) until the torchserve even prints something in its logs...
