### ISSUE TITLE
A parameter to set per process gpu memory limit/fraction

### ISSUE THREAD

**Issue by Vincentwei1021** [pytorch/serve#1383]
## Is your feature request related to a problem? Please describe.
We are currently deploying a model to production server using torchserve, it is utilizing a GPU. There are some other processes using the GPU at the same time, and we would like to set a limit on the model so that it will make sure there is such amount of GPU memory available before starting the worker, and will limit the maximum gpu memory used by the single model. Somthing similar to per_process_gpu_memory_fraction in tensorflow serving

**Comment by HamidShojanazeri** [comment]
@Vincentwei1021 can you please elaborate a bit more on your use-case. TFserving at the beginning it takes up all the gpu memory and thats why there is flag to set a limitation on the amount it takes, where as in Torchserve each worker has a copy of model weights + CUDA runtime + input batch_size ( memory doesn't grow beyond this for each model).

I am interested to know if you are looking to:
1. Torchserve instance ( its multi-model serving, so it can have multi models and each model multi workers) wouldn't take more than a specified amount of memory.  
2.  Or inside Torchserve you want to make sure each model/worker would not take memory beyond the limit.

**Comment by Vincentwei1021** [comment]
> @Vincentwei1021 can you please elaborate a bit more on your use-case. TFserving at the beginning it takes up all the gpu memory and thats why there is a flag to set a limitation on the amount it takes, where as in Torchserve each worker has a copy of model weights + CUDA runtime + input batch_size ( memory doesn't grow beyond this for each model/worker).
> 
> I am interested to know if you are looking to:
> 
> 1. Torchserve instance ( its multi-model serving, so it can have multi models and each model multi workers) wouldn't take more than a specified amount of memory.
> 2. Or inside Torchserve you want to make sure each model/worker would not take memory beyond the limit.

Thanks for you reply! @HamidShojanazeri I got your point and that answered one of our questions.

Our another use case is for example, a Torchserve instance is serving a single model on a 16G GPU, the model itself takes 2G memory and additional 1G during inference time. Suppose the same GPU is used by some other processes as well, and sometimes those processes will take up 14G of the GPU memory. In this case, the torchserve can still serve the model, but druing inference, it will cause cuda out of memory which makes the service unavailable. 

So is it possible to have a parameter to occupy certain amount of GPU memory at start time, so that we can make sure it will not be occupied by other processes and cause OOM during inference？Thanks

**Comment by HamidShojanazeri** [comment]
> 

Thanks @Vincentwei1021 for the explanations, I wonder if in the scenario that you described that extra 1GB during inference is coming from batch of inputs (consider in the current version each workers will load the CUDA runtime separately as well, this can take up some memory based on type of GPU). If thats the case then you need to make sure you are setting the right batch size.  Overall in this scenario that model takes 2GB +( CUDA runtime 400MB - ~ 1GB)+ batched input, and hence if other process is taking 14GB, this model can not be served. 

In this case if we have a parameter to set the limit you need to calculate all these factors to set the actual memory limit, otherwise the model can not be served.

Generally, my understanding is that your use-case suggests a limit on the memory that totally a Torchserve instance would take (regardless of how many models its serving at a time) which would be the first item in my question above, is that correct?

**Comment by Vincentwei1021** [comment]
> > 
> 
> Thanks @Vincentwei1021 for the explanations, I wonder if in the scenario that you described that extra 1GB during inference is coming from batch of inputs (consider in the current version each workers will load the CUDA runtime separately as well, this can take up some memory based on type of GPU). If thats the case then you need to make sure you are setting the right batch size. Overall in this scenario that model takes 2GB +( CUDA runtime 400MB - ~ 1GB)+ batched input, hence if other process is taking 14GB, this model can not be served.
> 
> In this case if we have a parameter to set the limit you need to calculate all these factors to set the actual memory limit, otherwise the model can not be served.
> 
> Generally, my understanding is that your use-case suggests a limit on the memory that totally a Torchserve instance would take (regardless of how many models its serving at a time) which would be the first item in my question above, is that correct?

Yes that's correct. We are more concerning about the use case on a Torchserve instance. But personally I'm also quite interested in how torchserve manages GPU usage for multiple models serving on a single card?

**Comment by HamidShojanazeri** [comment]
@Vincentwei1021 Torchserve tries to register each model with specified number of workers on a single gpu( it uses round robin in case of multi-gpus). Each worker as mentioned before would hold a copy of model weights + CudaRT. It doesn't pre-allocate the memory for input batch (as doesn't know the input size). So it keeps registering models until it saturates the gpu memory.

**Comment by Flyingdog-Huang** [comment]
@HamidShojanazeri 
hi I want to ask a question:
when I use docker torchserve:0.5.2-cpu, model inference(with CPU) cost time:27s, and post process(with CPU) cost time:7s;

when I use docker torchserve:0.5.2-gpu, model inference(with GPU) cost time:1.7s, and post process(with CPU) cost time:55s.

why are there so much differences between docker -cpu and docker -gpu when I post process with same CPU?

can docker -cpu and docker-gpu use CPU with the same way?
thanks a lot .

**Comment by msaroufim** [comment]
Our suggestion here is to rely on Kubernetes deployments or docker for resource isolation https://github.com/pytorch/serve/tree/master/kubernetes
