### ISSUE TITLE
How to decode response after post process?

### ISSUE THREAD

**Issue by MinsuKim3095** [pytorch/serve#1385]
Hello.  I'm using custom bert model on my custom handler using Korean.

When I request input text, handler encodes it and process like this.

``` {'body': bytearray(b'[\n\t\t\t["\xec\x9a\x94\xec\xa6\x98 \xeb\xb6\x80\xeb\xaa\xa8\xeb\x8b\x98\xea\xb3\xbc \xeb\xa7\x8e\xec\x9d\xb4 \xeb\xb6\x80\xeb\x94\xaa\xed\x98\x80.",\n\t\t\t "\xec\x96\xb4\xeb\x96\xa4 \xec\x9d\xbc\xeb\xa1\x9c ... ```

 But results in custom model came out with Korean.

Problem is response.

Althought my custom model gives Korean Results, 
Torch serve's response is encoded again.

How can I fix this?

Thank you.

**Comment by lxning** [comment]
Torchserve encodes utf-8 if the inference response body is string.

For your case, the post processing returns a string. There are two options to get  Korean text.

Option1: client side decode utf-8.
eg. 
>>> b'[\n\t\t\t["\xec\x9a\x94\xec\xa6\x98 \xeb\xb6\x80\xeb\xaa\xa8\xeb\x8b\x98\xea\xb3\xbc \xeb\xa7\x8e\xec\x9d\xb4 \xeb\xb6\x80\xeb\x94\xaa\xed\x98\x80.",\n\t\t\t "\xec\x96\xb4\xeb\x96\xa4 \xec\x9d\xbc\xeb\xa1\x9c]]'.decode('utf-8')
'[\n\t\t\t["요즘 부모님과 많이 부딪혀.",\n\t\t\t "어떤 일로]]'

Option2: post processing converts string to bytes, and client decode it according to post-processing encoder.
eg.
post-processing run:
s3=u'많이부딪혀'.encode('utf-8')

client run:
>>> s4=s3.decode('utf-8')
>>> print(s4)
많이부딪혀

**Comment by MinsuKim3095** [comment]
Thank you. I solved it that way. Close the issue.
