### ISSUE TITLE
Add one example of serving hugginface text-generation models

### ISSUE THREAD

**Issue by DineshReddyK** [pytorch/serve#1386]
## Is your feature request related to a problem? Please describe.
Couldn't find any examples for hosting the HuggungFace text-generation models using pytorch.

## Describe the solution
Please add at least one example of serving text-generation models in pytorch to [examples](https://github.com/pytorch/serve/tree/master/examples/Huggingface_Transformers)

## Describe alternatives solution
NA

**Comment by msaroufim** [comment]
Hi @DineshReddyK it's a good contribution if you're interested in making it - you would just need to extend the example you linked

**Comment by Tegzes** [comment]
Hello, if you didn't start yet, I would like to work on this one!
Please let me know

**Comment by msaroufim** [comment]
Go for it happy to merge your PR whenever you're ready. You can extend the existing huggingface example or create a new one if most of the code is not shared

**Comment by Tegzes** [comment]
I created the PR, I will update the documentation for this example once its approved

**Comment by msaroufim** [comment]
Sounds good left some review comments
