### ISSUE TITLE
how to determine number of workers and batch size to obtain best performance?

### ISSUE THREAD

**Issue by orkunozturk** [pytorch/serve#1389]
I have one model and 3 gpus. I register my model with the command:
curl -X POST "localhost:8444/models?url=yoyo_ai.mar&**batch_size=8**&max_batch_delay=8000&**initial_workers=8**"

In this setup, gpu:0 is assigned 2 workers and others are assigned 3 workers. (2 + 3 + 3)
I make requests with the following code where data_batch is a list holding 64 images (i assume each worker to handle 8 images):

async def do_post(session, url, image):
    async with session.post(url, data=image) as response:
        return await response.text()

async def make_predictions(data_stack, model_url):
    async with aiohttp.ClientSession() as session:
        post_tasks = []
        # prepare the coroutines that post
        for img in data_stack:
            post_tasks.append(do_post(session, model_url, img))
        # now execute them all at once
        responses = await asyncio.gather(*post_tasks)
        return responses

def get_predictions(data_batch, model_url):
    loop = asyncio.get_event_loop()
    predictions = None
    try:
        predictions = loop.run_until_complete(make_predictions(data_batch, model_url))
    finally:
        return predictions

While making requests in an endless loop this is the memory usage i get:
![Screenshot from 2022-01-06 10-51-02](https://user-images.githubusercontent.com/45604971/148348602-5ed1ff68-3f71-416d-a31a-e482c5f3bb55.png)

If i further increase the batch size to 12 because of high memory usage of gpu:0  torchserve throws exception. Same happens if i keep batch size as 8 but increase number of workers (e.g. 9). This time each gpu gets 3 workers and gpu:0 fails to handle it. On the other hand, if i set the number of workers to 6 and keep batch size as 8, total processing time not become worse compared to 8/8 setup. Meanwhile, either 8/6 or 8/8 setup don't use memory at full capacity. As a final note, gpu utilization keeps going back and forth between %0 and %100 during inference (not at 100% or %80/%90 all time).

Is there a way to use gpus at full capacity? I wonder how should i register my model with the best batch size and number of workers combination to use gpus optimally. Or do i have a problem at making requests?

Thank you very much for any help

**Comment by lxning** [comment]
@orkunozturk here is some information which may be helpful for you to tune performance.

1. Torchserve support dynamic batching on server side. For example, assuming your model can handle batch data, you set batch_size=8 during model registration. Your client sends inference request(ie. 1 image) one by one. Torchserve will transparently batch the incoming requests and assign a worker to process.  

You need set batch_size=1 during model registration if your client batches 64 images together and sends to Torchserve.

2. Torchserve uses round-robin strategy to assign GPUs to workers. So the behavior (ie. gpu:0 is assigned 2 workers and others are assigned 3 workers. (2 + 3 + 3)) is correct.

3. async_logging=true can improve performance (see [ref](https://github.com/pytorch/serve/blob/master/docs/logging.md#enable-asynchronous-logging)).

4. You can start with 3 workers and batch_size=1 to tune performance.
