### ISSUE TITLE
Extending management API describe to get custom meta-data from handler

### ISSUE THREAD

**Issue by HamidShojanazeri** [pytorch/serve#1406]
Currently, management describe API collect a fix set info from front-end and there is no way to collect meta-data from backend/handler. 

The proposal here is to add meta-data collected in the handler to the response and extend the describe API to work with backend and access the collected meta-data.

**Comment by lxning** [comment]
@HamidShojanazeri A model can have multiple workers. A worker is a process at backend. Here, the customized metadata is fetched from backend worker. There are two scenarios. Could you pls clarify which scenario needs to be supported?

Case 1: the metadata is consistent among the workers. In this case, a describeModel request only needs to be sent to any single worker once.

Case 2: the metadata is different among the workers. In this case, a describeModel request needs to be sent to all workers.

**Comment by HamidShojanazeri** [comment]
Thanks @lxning for the explanation, I believe Case2 is a more generalized solution and provide more flexibility. There might be some sort of meta-data like time stamp for receiving a request/ generating a response that could be different among workers.
