### ISSUE TITLE
Docker run only creates an image 

### ISSUE THREAD

**Issue by KyloRen1** [pytorch/serve#1422]
Trying to run torchserve model in docker using following code
`sudo docker run --rm -it -v $(pwd)/config.properties:/tmp/config.properties  -v $(pwd)/output:/home/model-server/model-store -p 8080:8080 -p 8081:8081 pytorch/torchserve:latest  torchserve --start --model-store model-store --models detection=classifier.mar  --ts-config /tmp/config.properties`
It is running already for hours and nothing happens

when I check docker containers 
it creates a container however, the container is not running. 

What can be an issue? Thanks!

**Comment by msaroufim** [comment]
I just tried running

```
docker run --rm -it -v $(pwd)/config.properties:/tmp/config.properties -v $(pwd)/output:/home/model-server/model-store -p 8080:8080 -p 8081:8081 pytorch/torchserve:latest torchserve --start --model-store model-store --models detection=classifier.mar --ts-config config.properties
```

And got a bunch of logs printed out so container is running - could you retry a fresh environment?

<img width="566" alt="Screen Shot 2022-02-09 at 11 49 08 AM" src="https://user-images.githubusercontent.com/3282513/153278983-23f987ec-52ca-43af-94b5-80bcc43488e9.png">

**Comment by KyloRen1** [comment]
@msaroufim thanks for your reply.
![Screenshot from 2022-02-10 07-58-19](https://user-images.githubusercontent.com/35574157/153347241-9d0cb371-3242-492d-acb8-4ecba1ba7a14.png)

I have tried to run in a different configuration, with the image pulled from docker hub, and it still freezes.

**Comment by msaroufim** [comment]
Can you run `htop` in a seperate window? I wonder if your system memory, disk or CPU is being throttled

**Comment by chauhang** [comment]
@KyloRen1 Please clean the docker cache and try again, check out this [article](https://renehernandez.io/snippets/cleaning-local-docker-cache/) for details. Further note that If your network is very slow that may also cause the docker image from downloading to your machine.

**Comment by lxning** [comment]
@KyloRen1 pls feel free to reopen if this issue is still there
