### ISSUE TITLE
Cleanup benchmark folder and unused/outdated scripts

### ISSUE THREAD

**Issue by maaquib** [pytorch/serve#1446]
## 📚 Documentation

We no longer use jmeter for benchmarking and the instructions along with the scripts are outdated. These need to be removed to avoid confusion

Tasks:
1. delete automated folder
2. delete benchmark automated dockerfile
3. delete benchmark automated buildspec

**Comment by msaroufim** [comment]
I can take care of this, I enjoy deleting things
