### ISSUE TITLE
Typo of example alexnet README

### ISSUE THREAD

**Issue by swartz-k** [pytorch/serve#1462]
https://github.com/pytorch/serve/blob/a4518bd1c404debced360fbace32b46c98fb219a/examples/image_classifier/alexnet/README.md?plain=1#L9

may this should be 
```
 mv alexnet.mar model_store/
```

**Comment by msaroufim** [comment]
Would you like to make the PR to fix this? I'd be happy to merge

**Comment by swartz-k** [comment]
> Would you like to make the PR to fix this? I'd be happy to merge

Sure. Thanks for your kindness.
