### ISSUE TITLE
Model Zoo Revamp

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#1470]
## Problem
As of now our model zoo doesn't make it clear which models are available `docs/model_zoo.md` is not well maintained example doesn't include BERT or MMF. It doesn't show how users can submit a new model to the zoo (Making a PR is not enough since the S3 bucket is not publicly available and we don't show users instructions on how to upload things, we assume they know how to use the `aws` api)

This creates problems since 
1. Submitted examples can't have good test cases, we can't check in mar files
2. Limits code reuse between teams in open source, can't share mar files with each other and it's not clear what's been done before or not

## Solution

A better solution needs to make sure the zoo is public, searchable, automatically updated, allow user submissions and needs to worry about preventing user spam like spamming unwanted or harmful objects to an S3 bucket we maintain

Should we use something like pytorch model hub? hf hub? use a homegrown basic s3 hub?

### Current Experience 
The current experience is the torchserve team maintains an S3 bucket where only they have write access to common models users care about

Pros
1. Curated models that work

Cons
1. Doesn't allow community contributions which prevents rich set of examples, higher quality unit tests and growth overall

### Pytorch hub

Pros
1. PyTorch brand, curated

Cons
1. May require some work to support a `mar` file format
2. Cannot host weights without code review, does not allow arbitrary files to be stored

### HuggingFace Hub
Pros
1. Can upload arbitrary files including mar files from either a web UI or CLI
2. Model Hub discovery is good  
3. No code review process, 

Cons
1. anyone can submit (not sure how they deal with spam and harmful content)

### Homegrown Hub

Create our own model hub, or maybe standardize `mar` format more and revamp torch hub?

Pros
1. Most flexible, can support any data format we like

Cons
1. Need to host a service so community members can submit and inspect available models
3. Need to deal with security, spam and harmful content since if users can submit anything it's a security risk to just unzip a random file from the internet

**Comment by soumith** [comment]
If hosting weights is a bottleneck, you should point users to services / ways to host weights for free.
Github Releases, HuggingFace Hub are good options.

About curation of models, PyTorch Hub or HuggingFace Hub makes sense -- Homegrown Hub wont be better than either of those two in my opinion.

**Comment by msaroufim** [comment]
That's good feedback, 

I'm thinking I'll just update the model_zoo docs with a tutorial on how to use pre-trained weights from the huggingface hub or pytorch and use a default base handler that does nothing except run `model.forward`. Maybe make this the getting started guide too.

**Comment by lxning** [comment]
@msaroufim current [model zoo page](https://github.com/pytorch/serve/blob/master/docs/model_zoo.md) is maintained manually. It is easily to cause [model zoo page](https://github.com/pytorch/serve/blob/master/docs/model_zoo.md) out-of-sync with [link](https://torchserve.pytorch.org/mar_files) when new mar files are added into S3 bucket. 

In my opinion, ideally [model zoo page](https://github.com/pytorch/serve/blob/master/docs/model_zoo.md) is generated automatically. The process can be:

1. Upload mar file to S3:
- add metadata such as model_name, model_type, dataset, size, sample_input, model_mode

2. Host model zoo page separately (similar as nightly build page) for public readonly access.

3. Write a script to update the above model zoo page
This script go through all mar/war files, fetch mar/war file metadata, and then create the model zoo table.

4. nightly update the model zoo page automatically. 




6. Pu

**Comment by msaroufim** [comment]
@lxning I would actually argue for us to kill the model zoo completely at this point. If the main utility is tests then a model zoo actually does more harm than good since people can't update `examples/` without knowing for sure if the code will break

So a better solution is in every unit test create a mar file from scratch and test it instead of having a model zoo where we're not sure who created the model, how and whether it still works

**Comment by osanseviero** [comment]
Hey all, Omar from HF Here :hugs: 

We'd love to support your use case on the Hugging Face Hub if it makes sense! Just for clarification, the Hub is not constrained to :hugs: `transformer` models (or models created with `Trainer`). The Hub uses git-based repositories that anyone can create and upload models to, we actually have integrations with [different libraries](https://huggingface.co/docs/hub/libraries), many of which are not transformers nor NLP-focused.

One thing that you might find useful is that [model cards](https://huggingface.co/docs/hub/model-repos#model-card-metadata) have metadata that allow reporting things such as the dataset, metrics, tags, etc. This can help with discoverability and even comparison of evaluation results. 

There is also the community Inference API that enables widgets to try out the models directly in the browser (or through HTTP requests), or Spaces for fancier demos such as the ones at https://huggingface.co/pytorch.

Let us know if we can help :smile: :llama: 

cc @LysandreJik @julien-c

**Comment by osanseviero** [comment]
Hey there! This doc has instructions of uploading your files to a repo: https://huggingface.co/docs/hub/adding-a-model, both using the web UI or through the terminal. Happy to help if you have any questions!

**Comment by msaroufim** [comment]
Quick update here - it was relatively easy to add a new model and tags and documentation. Probably quickest to just manually update everything for now https://huggingface.co/torchserve

So now users can actually see what's inside a file before downloading it and navigate to a root index where they can see which models are available where every model would have some card with some extra instructions and metadata

Somewhere in the torchserve docs I also need to make it clearer how I expect people to upload their own examples so something like

`torch-model-archiver ...`
`upload *.mar` file` by using instructions from https://huggingface.co/docs/hub/adding-a-model

**Comment by osanseviero** [comment]
This is great @msaroufim! As a note, I think it makes sense to have an organization instead of a user for this. Then each individual from the core team can have access + we could add a nice organization card such as [this one](https://huggingface.co/spacy)

**Comment by julien-c** [comment]
very cool @msaroufim! Yes, we can migrate this user to an org and add you to it if you'd like.

**Comment by Flyingdog-Huang** [comment]
hi I want to ask a question:
when I use docker torchserve:0.5.2-cpu, model inference(with CPU) cost time:27s, and post process(with CPU) cost time:7s;
cpu

when I use docker torchserve:0.5.2-gpu, model inference(with GPU) cost time:1.7s, and post process(with CPU) cost time:55s.
gpu

why are there so much differences between docker -cpu and docker -gpu when I post process with same CPU?

can docker -cpu and docker-gpu use CPU with the same way?
thanks a lot .
