### ISSUE TITLE
Profiler integration not working

### ISSUE THREAD

**Issue by suraj813** [pytorch/serve#1480]
## Context

Profiler/tensorboard integration as detailed in the [MNIST example](https://github.com/pytorch/serve/tree/master/examples/image_classifier/mnist#serve-a-custom-model-on-torchserve) is not working. `/tmp/pytorch_profiler` folder is not created, nor does the profiler output show up on the console/logs.

* torchserve version: 0.5.0
* torch version: 1.10
* Operating System and version: Ubuntu 18.04 (AWS)

## Your Environment

* Installed using source? [yes/no]:
* Are you planning to deploy it using docker container? [yes/no]: no
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: no
* What kind of model is it e.g. vision, text, audio?: 
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Expected Behavior
According to https://github.com/pytorch/serve/tree/master/examples/image_classifier/mnist#serve-a-custom-model-on-torchserve 
a) I should see the profiler outputs in `/tmp/pytorch_profiler`.
b) The profiler output should show up in the ts logs / stdout

## Current Behavior
The `pytorch_profiler` directory does not exist. Profiler outputs are not displayed in either the log files or in stdout.

## Steps to reproduce
```
# set up
cd examples/image_classifier/resnet_152_batch
wget https://download.pytorch.org/models/resnet152-394f9c45.pth
torch-model-archiver --model-name resnet-152-batch --version 1.0 --model-file model.py --serialized-file resnet152-394f9c45.pth --handler image_classifier --extra-files index_to_name.json
mkdir model-store
mv resnet-152-batch.mar model-store/

# start torchserve with profiler enabled
export ENABLE_TORCH_PROFILER=true
echo enable_envvars_config=true >> config.properties
curl -X POST "localhost:8081/models?model_name=resnet152&url=resnet-152-batch.mar&batch_size=4&max_batch_delay=5000&initial_workers=3&synchronous=true"

# test
curl http://127.0.0.1:8080/predictions/resnet152 -T images/croco.jpg &
curl http://127.0.0.1:8080/predictions/resnet152 -T images/dog.jpg &
curl http://127.0.0.1:8080/predictions/resnet152 -T images/kitten.jpg &
```

cc @msaroufim @shrinath-suresh

**Comment by shrinath-suresh** [comment]
Pytorch Profiler is working with `torchserve==0.5.3". Can you please update to the latest version and check

![pytorchprofiler](https://user-images.githubusercontent.com/63862647/156550751-c0b91929-709d-4903-bd4e-8664363dd143.gif)

**Comment by lxning** [comment]
@suraj813 pls feel free to reopen if the issue is still there.
