### ISSUE TITLE
how to get model.py file ?

### ISSUE THREAD

**Issue by jaffe-fly** [pytorch/serve#1487]
`https://github.com/pytorch/serve/blob/master/docker/README.md#create-torch-model-archiver-from-container` in 
the 4 step ,how to get model.py file？

I followed the doc step by step ，but in step 4 
`torch-model-archiver --model-name densenet161 --version 1.0 --model-file /home/model-server/examples/image_classifier/densenet_161/model.py --serialized-file /home/model-server/examples/image_classifier/densenet161-8d451a50.pth --export-path /home/model-server/model-store --extra-files /home/model-server/examples/image_classifier/index_to_name.json --handler image_classifier`

error because no model.py file.
where to get this model.py file

**Comment by msaroufim** [comment]
This looks like a documentation issue - this is the file you need https://github.com/pytorch/serve/tree/master/examples/image_classifier/densenet_161/model.py

**Comment by jaffe-fly** [comment]
doc need to corrected to be more beginner friendly

**Comment by msaroufim** [comment]
> doc need to corrected to be more beginner friendly

Would you be interested in making a PR to improve it? I can merge it quickly. Problem with maintaining a library is I sometimes forget what it's like to be a beginner
