### ISSUE TITLE
torchserve failed to load model if the model dir is input

### ISSUE THREAD

**Issue by lxning** [pytorch/serve#1498]
Please have a look at [FAQ's](../../docs/FAQs.md) and [Troubleshooting guide](../../docs/Troubleshooting.md), your query may be already addressed.

Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

* torchserve version:
* torch-model-archiver version:
* torch version:
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
* Operating System and version:

## Your Environment

* Installed using source? [yes/no]:
* Are you planning to deploy it using docker container? [yes/no]:
* Is it a CPU or GPU environment?:
* Using a default/custom handler? [If possible upload/share custom handler/model]:
* What kind of model is it e.g. vision, text, audio?:
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Expected Behavior

According to original source code, the following scenarios should work:

1. "torchserve --ncs --start --model-store model_store --models noop" should work if noop is a dir (ie, extracted mar file dir).
tree model_store
model_store
└── noop
    ├── MAR-INF
    │   └── MANIFEST.json
    ├── model.pt
    └── service.py

2.  "torchserve --ncs --start --model-store model_store --models "noop" should work
tree model_store
model_store
└── noop
    ├── model.pt
    └── service.py

3. "torchserve --ncs --start --model-store model_store --models "models/noop" should work
In this case
tree models
models
└── noop
    ├── MAR-INF
    │   └── MANIFEST.json
    ├── model.pt
    └── service.py

4. "torchserve --ncs --start --model-store model_store --models "models/noop" should work
In this case
tree models
models
└── noop
     ├── model.pt
    └── service.py

the case 2/3 will break snapshot. In other words, model can not be loaded during torchserve restart b/c model is not in model_store.

## Current Behavior

got exception: 
case1/2 : Model not found at: noop

case3/4: Model version is not defined

## Steps to Reproduce

1.
3.
...

**Comment by HamidShojanazeri** [comment]
> "torchserve --ncs --start --model-store model_store --models BERTSeqClassification" should work if BERTSeqClassification is a dir (ie, extracted mar file dir).

@lxning isn't it supposed to be the mar file name by convention?

**Comment by maaquib** [comment]
This seems like a change in behaviour? Are we supporting any directory (`--models "frontend/archive/src/test/resources/models/noop_no_archive_no_version/noop"`) going forward. I though we only supported directories which were created with `no-archive` option.
If we are, we should should document this?

**Comment by lxning** [comment]
@HamidShojanazeri @maaquib I updated the expected behavior section to list all the scenarios the existing source code was trying to support if the input model is a directory. The current behavior shows the error due to bug.

**Comment by alar0330** [comment]
is this documented anywhere?
