### ISSUE TITLE
[Educational] Typing `.py` files iteratively with pyre

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#1512]
We're looking to add types to torchserve to detect more bugs and issues statically and increase code readability.

Since there's a lot of `.py` files which would be impossible to merge in a single code review I pulled out the 20 files with most commits and we can use them as a roadmap for what to do

If you've never contributed to torchserve before this is a great place to start, pick one of the files here and add types to it, make a PR and make sure linting passes.  Do not submit more than 1 PR or fixes to more than 1 lines this issue is mainly open for educational purposes

Start by learning how to set types in python https://pyre-check.org/docs/getting-started/

0. From root `serve` run `pyre init` and `pyre infer -i`
1. Start with the file you want to type
2. Visually inspect the file and make sure the types make sense, returning `Any` is fine if you have no idea what a type is but try to avoid it. Add missing annotations as needed 
3. Make your PR and comment on this thread saying which of the below tasks should be closed. Only `git add` a single file at a time otherwise we won't be able to code review
4. If all the tasks are done increase `head -n 20` to a bigger integer and pick a file there to contribute

The most important files to add types to are the ones that change the most often i.e have the most commits

`git rev-list --objects --all | awk '$2 ~ /\.py/' | awk '{print $2}' | sort -k2 | uniq -c | sort -rn | head -n 20`

Number of commits, file

* [ ] 59 ts_scripts/install_dependencies.py
* [ ] 57 ts/torch_handler/base_handler.py
* [ ] 52 ts/model_service_worker.py
* [ ] 47 examples/Huggingface_Transformers/Transformer_handler_generalized.py
* [ ] 42 ts_scripts/sanity_utils.py
* [ ] 41 test/pytest/test_handler.py
* [ ] 35 ts_scripts/tsutils.py
* [ ] 34 ts/model_server.py
* [ ] 34 benchmarks/benchmark-ab.py
* [ ] 29 ts_scripts/marsgen.py
* [ ] 29 ts/model_loader.py
* [ ] 28 model-archiver/model_archiver/model_packaging.py
* [ ] 28 benchmarks/benchmark.py
* [ ] 24 torchserve_sanity.py
* [ ] 23 ts/torch_handler/object_detector.py
* [ ] 23 model-archiver/model_archiver/model_packaging_utils.py
* [ ] 22 setup.py
* [ ] 21 ts_scripts/torchserve_grpc_client.py
* [ ] 21 model-archiver/model_archiver/manifest_components/model.py
* [ ] 21 model-archiver/model_archiver/arg_parser.py

**Comment by DragonEarin** [comment]
FULL ACCESS CAN I JOIN

**Comment by josephcalise** [comment]
I would love to take care of this issue on any files that need type annotations in serve/ts, are there any specific ones that are still open? I am new to contributing to open source, I have identified serve/ts/model_server.py as something I am able to complete right now, and will continue to look into the rest of the files to try to understand the types and complete any other files I can. 

Thank you!
