### ISSUE TITLE
Add arm64 docker image

### ISSUE THREAD

**Issue by RobinFrcd** [pytorch/serve#1515]
Hi,
I'm currently using locally torchserve on an ARM64 machine, and it works well, thanks !

However, I'd like to use docker to deploy my service. And currently, images on [dockerhub](https://hub.docker.com/r/pytorch/torchserve/tags) are build for `linux/amd64` only. Would it be possible to add `arm64` too ?

Thanks

**Comment by msaroufim** [comment]
Interesting, I don't have much experience building multi platform images but does this look good to you? https://developer.arm.com/documentation/102475/0100/Multi-architecture-images

If it is, I can look at adding images for our next release

**Comment by RobinFrcd** [comment]
In my experience, `buildx` works pretty well, yes! :+1: 

However, I don't know if it'll be enough. When having a look at https://github.com/pytorch/serve/issues/1363, it doesn't seem that easy :sweat_smile:

**Comment by msaroufim** [comment]
Can you try this? https://github.com/pytorch/serve/issues/1363#issuecomment-1112769676

**Comment by lxning** [comment]
close this ticket due to dup #1363
