### ISSUE TITLE
About cuda 11.3 support

### ISSUE THREAD

**Issue by nightheronry** [pytorch/serve#1520]
## 📚 Documentation

According to https://github.com/pytorch/serve/blob/master/docker/README.md#create-torchserve-docker-image, it seems to support cuda 113. But I get an error as below. It caused by this commit 
https://github.com/pytorch/serve/commit/8c3e966fd1602199fcd3a94614768af9c5ecd885#diff-e8d79698745dd86b8364c1a6111076d296b04a7f1d184f4c19493ec869f9206eL181

`

./build_image.sh -bt dev -g -cv cu113
[+] Building 129.6s (9/11)
 => [internal] load build definition from Dockerfile.dev                                                                                                                                               0.0s
 => => transferring dockerfile: 42B                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => resolve image config for docker.io/docker/dockerfile:experimental                                                                                                                                  0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.3.0-cudnn8-runtime-ubuntu18.04                                                                                                               0.0s
 => CACHED [compile-image 1/3] FROM docker.io/nvidia/cuda:11.3.0-cudnn8-runtime-ubuntu18.04@sha256:47b883215de9f66292bc3713d995b4304a33443064858580e9adf30845c3c5ac                                    0.0s
 => => resolve docker.io/nvidia/cuda:11.3.0-cudnn8-runtime-ubuntu18.04@sha256:47b883215de9f66292bc3713d995b4304a33443064858580e9adf30845c3c5ac                                                         0.0s
 => [compile-image 2/3] RUN --mount=type=cache,id=apt-dev,target=/var/cache/apt     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y     fakeroot     117.1s
 => [compile-image 3/3] RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1     && update-alternatives --install /usr/local/bin/pip pip /usr/local/bin/pip3.8 1              0.5s
 => ERROR [dev-image 1/2] RUN if [ "gpu" = "gpu" ]; then export USE_CUDA=1; fi     && git clone https://github.com/pytorch/serve.git     && cd serve     && git checkout master     && python3.8 -m   11.7s
------
 > [dev-image 1/2] RUN if [ "gpu" = "gpu" ]; then export USE_CUDA=1; fi     && git clone https://github.com/pytorch/serve.git     && cd serve     && git checkout master     && python3.8 -m venv /home/venv     && python -m pip install -U pip setuptools     && if [ -z "cu113" ]; then python ts_scripts/install_dependencies.py --environment=dev; else python ts_scripts/install_dependencies.py --environment=dev  --cuda cu113; fi     && python ts_scripts/install_from_src.py     && useradd -m model-server     && mkdir -p /home/model-server/tmp     && cp docker/dockerd-entrypoint.sh /usr/local/bin/dockerd-entrypoint.sh     && chmod +x /usr/local/bin/dockerd-entrypoint.sh     && chown -R model-server /home/model-server     && cp docker/config.properties /home/model-server/config.properties     && mkdir /home/model-server/model-store && chown -R model-server /home/model-server/model-store     && chown -R model-server /home/venv:
#9 0.402 Cloning into 'serve'...
#9 9.169 Already on 'master'
#9 9.169 Your branch is up to date with 'origin/master'.
#9 10.80 Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (22.0.4)
#9 11.16 Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (60.10.0)
#9 11.57 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 11.67 usage: install_dependencies.py [-h] [--cuda {cu92,cu101,cu102,cu111}]
#9 11.67                                [--environment {prod,dev}] [--force]
#9 11.67 install_dependencies.py: error: argument --cuda: invalid choice: 'cu113' (choose from 'cu92', 'cu101', 'cu102', 'cu111')
------
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to build LLB: executor failed running [/bin/sh -c if [ "$MACHINE_TYPE" = "gpu" ]; then export USE_CUDA=1; fi     && git clone https://github.com/pytorch/serve.git     && cd serve     && git checkout ${BRANCH_NAME}     && python3.8 -m venv /home/venv     && python -m pip install -U pip setuptools     && if [ -z "$CUDA_VERSION" ]; then python ts_scripts/install_dependencies.py --environment=dev; else python ts_scripts/install_dependencies.py --environment=dev  --cuda $CUDA_VERSION; fi     && python ts_scripts/install_from_src.py     && useradd -m model-server     && mkdir -p /home/model-server/tmp     && cp docker/dockerd-entrypoint.sh /usr/local/bin/dockerd-entrypoint.sh     && chmod +x /usr/local/bin/dockerd-entrypoint.sh     && chown -R model-server /home/model-server     && cp docker/config.properties /home/model-server/config.properties     && mkdir /home/model-server/model-store && chown -R model-server /home/model-server/model-store     && chown -R model-server /home/venv]: runc did not terminate sucessfully
`

**Comment by msaroufim** [comment]
We're adding CUDA 11.3 support in the next release 0.6. Should be out in about 3 weeks

**Comment by msaroufim** [comment]
This is now available
