### ISSUE TITLE
Documentation inaccuracy

### ISSUE THREAD

**Issue by BraginIvan** [pytorch/serve#1526]
## 📚 Documentation

[For example, if you cloned the repository into /home/my_path/serve, run the steps from /home/my_path](https://github.com/pytorch/serve/tree/master/examples/image_classifier/resnet_18) should be [For example, if you cloned the repository into /home/my_path/serve, run the steps from /home/my_path/serve](https://github.com/pytorch/serve/tree/master/examples/image_classifier/resnet_18) 

On other pages like:
https://github.com/pytorch/serve/tree/master/examples/image_classifier/densenet_161
https://github.com/pytorch/serve/tree/master/examples/image_classifier/resnet_152_batch

it is correct

**Comment by BraginIvan** [comment]
https://github.com/pytorch/serve/tree/master/examples/image_classifier/mnist
same problem here

**Comment by BraginIvan** [comment]
another problem is [here](https://github.com/pytorch/serve/blob/master/docs/inference_api.md)

`res = requests.post("http://localhost:8080/predictions/squeezenet1_1", files={'data': open('docs/images/dogs-before.jpg', 'rb'), 'data': open('docs/images/kitten_small.jpg', 'rb')})`
should be
`
res = requests.post("http://localhost:8080/predictions/squeezenet1_1", files=[('data', open('docs/images/dogs-before.jpg', 'rb')), ('data', open('docs/images/kitten_small.jpg', 'rb'))])`

**Comment by msaroufim** [comment]
Hi @BraginIvan would you like to make a PR fixing these issues? I can merge them quickly

**Comment by BraginIvan** [comment]
Ok, will do it on Monday
