### ISSUE TITLE
Resnet-152 example handles GPUs incorrectly

### ISSUE THREAD

**Issue by fbbradheintz** [pytorch/serve#153]
In the `staged_release` branch, the custom model handler for batch-mode ResNet-152 `resnet152_handler.py` checks for GPU and grabs the default GPU device if one is available. This may fail on multi-GPU devices, because it is not taking in a device number from its initialization context.

**Comment by harshbafna** [comment]
Reopening the ticket as the custom handler still does not loads the model on GPU. Even though the device is properly initialized with the gpu id, the model will always be loaded in the default device i.e., CPU. Will put a PR with the fix.

**Comment by chauhang** [comment]
@mycpuorg Please see the related issue for [broken steps](https://github.com/pytorch/serve/issues/324) for torchscripted model .mar file creation in this example.
