### ISSUE TITLE
Need proper mechanism for restarts from last known snapshot for production deployment

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#156]
For production deployment one has to specify the inference_address setting for things to work, and it requires using config file to launch. I started TS with
torchserve --start --ts-config ./config.properties
Added few models
Stopped TS
restarted using above command and it did not load the snapshoted states. 

For production use case if one has to identify the correct snapshot config file to restart TS, it will be too much overhead on OPs teams to keep doing this manually. We need an automated mechanism to pick up the last config file for restart.

Please provide proper steps for initial launch of TorchServe the first time, and then how to restart for production settings. The restart command should not require manual changes to specify last snapshoted config file name on each restart.

**Comment by fbbradheintz** [comment]
There is a deeper issue we should discuss here, which is the lack of feature parity among the *four* methods of configuring TorchServe - command line, config file, env var, and Management API.

**Comment by fbbradheintz** [comment]
Self-assigned to check whether we can close this.
