### ISSUE TITLE
Migrate all CI to github actions

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#1568]
If we migrate all CI to github actions we can disable the sagemaker neobot, have CI status directly show up on PR. Shouldn't be too tricky given we're using github actions for all our nightly builds, docs and soon benchmarks

PR #1576 discusses how to make this work assuming we provision a GPU machine on AWS 

But there's a lot of[ other low hanging fruit improvements](https://github.blog/2021-11-18-7-advanced-workflow-automation-features-with-github-actions/) we can make to our current Github Action setup to speed them up
* Cache dependencies, we spend tons of time running `install_dependencies.py`
* Store benchmark results in artifacts and then use those artifacts and render them on a github.io page
* Use `{{}}` context and `if` conditions to have a single script for both GPU and CPU which would create a matrix in a single page which would launch 2 jobs that are visualizable in the same plane
* Use `needs` keyword, caching dependencies and then several sub jobs to create various nightly builds
* Create a local staging environment so we don't need to fork a repo or change the code in a github action before deploying it
* Add README instructions to make it easier for people to debug CI issues using a tmate action
* Use a build matrix to build support binaries for each CUDA version in docker
* Cancel previous runs of a job if new commit is made https://github.com/marketplace/actions/cancel-workflow-action

FYI: @maaquib @lxning

**Comment by nijkah** [comment]
To my knowledge, github does not currently support CI runners with GPU resources. Is it enough to test torchserve with pytorch cpuonly?

**Comment by msaroufim** [comment]
It's possible to have custom runners with GPUs. Issue is I need to maintain those servers
