### ISSUE TITLE
[Suggestion] use 'Squash and mege' for PR merge policy

### ISSUE THREAD

**Issue by nijkah** [pytorch/serve#1569]
## Is your feature request related to a problem? Please describe.
Currently, the repository seems to adopt the 'Create a merge commit' for the PR merge policy.
But, 'Create a merge commit' makes commit history quite messy and difficult to track changes because it shows all non-linear histories.

In contrast, 'Squash and merge' is quite a nice option to track the commit history.
It makes 'A Pull Request' as **one commit** in the main commit history.
If you want to check the actual commit history of the PR, then you can check the commits by tracking the pull request URL.

<img width="303" alt="image" src="https://user-images.githubusercontent.com/25769408/163672218-216ef30a-a36c-43bf-a605-10909f1dd2a5.png">

Example repositories:
- https://github.com/pytorch/pytorch/commits/master
- https://github.com/apache/airflow/commits/main
- https://github.com/open-mmlab/mmdetection/commits/master

## Describe the solution
How about limiting the pull request policy?
You can set this in `settings/Pull Requests` in the repository.
<img width="724" alt="image" src="https://user-images.githubusercontent.com/25769408/163672236-db64e505-a915-4de8-9012-893a22cae514.png">

**Comment by msaroufim** [comment]
I really like this suggestion. Sure lemme enable
