### ISSUE TITLE
Asynchronous inference

### ISSUE THREAD

**Issue by kouta-kun** [pytorch/serve#1578]
## Describe the solution
Hi! I wanted to ask if there's any sort of support planned for asynchronous inference in torchserve, such that I can queue up an inference request (maybe even a workflow) and have it POST to a callback once all the processing is done. I think it can be done through some custom handlers and threadpools but it would be better for it to be natively supported.

**Comment by msaroufim** [comment]
Just to clarify do you mean batch inference? https://github.com/pytorch/serve/blob/master/docs/batch_inference_with_ts.md

Otherwise, do you mind elaborating a bit more on what you're trying to do?

**Comment by kouta-kun** [comment]
Not exactly.

So suppose you have an edge device which captures data and sends it to torchserve. If the device itself does nothing with the result of the inference, it's useless for it to wait on the response and pass it on to another service. I was thinking of some way for the device to make a request which submits the data to be processed to torchserve and immediately gets an OK response. Torchserve would batch it up, pass it through a model or a workflow, and send the result to the service that the edge device would've initially sent it to, or store it in some database to read afterwards

**Comment by msaroufim** [comment]
Hi @kouta-kun a good option here would be to leverage `asyncio` that way you can code up whatever logic to handle inference results from torchserve. As of now I don't think it makes sense for us to explicit support for this in torchserve
