### ISSUE TITLE
Dockerfile - Errors

### ISSUE THREAD

**Issue by MatzeFix** [pytorch/serve#1590]
Please have a look at [FAQ's](../../docs/FAQs.md) and [Troubleshooting guide](../../docs/Troubleshooting.md), your query may be already addressed.

Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

Dockerfile can not be used to build up the torchserve:latest-gpu image
./build_image.sh -bt test_3 -g -cv cu113

Running on Docker with Version Docker version 20.10.14, build a224086
docker-compose version 1.29.2, build 5becea4c

* torchserve version: build image from cuda-version cu113 and base image 18.04  - dont know exactly because I do not get out the version from Dockerfile
* torch-model-archiver version: not used at the moment
* torch version: 
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
* Operating System and version: Host-System Ubuntu 20.04

## Your Environment

Following Info are not filled, because error is coming while building image

* Installed using source? [yes/no]: -
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: - 
* What kind of model is it e.g. vision, text, audio?: - 
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.? -
  [If public url then provide link.]: -
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: - 
* Link to your project [if any]: -

## Expected Behavior

Build should be successfull

## Current Behavior

Build cannot be finished because of unknown command -m and missing semicolon in Dockerfile

## Possible Solution

Remove "python -m" in Dockerfile Line 64; 69; 72; 74
Add ";" Semicolon in Line 69
69: "python -m pip install --no-cache-dir -r https://raw.githubusercontent.com/pytorch/serve/master/requirements/common.txt \" <- Semicolon at the end is missing

## Steps to Reproduce

1. git clone torchserve repository
2. build image for GPU with default values: ./build_image.sh -b dev t test_image -g -cv cu113

## Failure Logs [if any]

Sry, cannot give detailed logs... because of not having control on the host anymore....
1. no command with -m found
2. "else" command not found

**Comment by willyfh** [comment]
I just want to report my findings here.
In CPU environment, without semicolon in line 69, the torchvision could not be installed
Adding  ";" Semicolon in Line 69 solved my problem.
However, I did not get the problem of unknown command -m. So I do not need to remove the "python -m".

**Comment by msaroufim** [comment]
Just made a PR to fix the missing `;`

On the missing `-m` that's kind of strange, `python -m pip install ...` is a fairly common pattern to make sure the package you're installing is linked to your actual python version.

Does `which python` give you a hint as to what's going on?

**Comment by MatzeFix** [comment]
> Just made a PR to fix the missing `;`
> 
> On the missing `-m` that's kind of strange, `python -m pip install ...` is a fairly common pattern to make sure the package you're installing is linked to your actual python version.
> 
> Does `which python` give you a hint as to what's going on?

Hey ho,

I was testing it again, the python error was (I think) coming from the semicolon :)

I think everything is okey now - thank you for your response and your Time :)
