### ISSUE TITLE
How to set model batch size with TS_ environmental var

### ISSUE THREAD

**Issue by austinmw** [pytorch/serve#1609]
## 📚 Documentation

Hi, I can't seem to figure out how to set the batch size with an environmental parameter. 

My `config.properties` looks like this:

```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
number_of_netty_threads=32
enable_envvars_config=true
job_queue_size=1000
model_store=/opt/ml/model
load_models=all
enable_metrics_api=false
models={\
  "model": {\
    "1.0": {\
        "defaultVersion": true,\
        "marName": "model.mar",\
        "runtime": "python3",\
        "minWorkers": 1,\
        "maxWorkers": 4,\
        "batchSize": 16,\
        "maxBatchDelay": 50,\
        "responseTimeout": 120\
    }\
  }\
}
```

But I would like to be able to override `batchSize` with an env variable so that load testing is more simple (just creating endpoints with different env params instead of needing to generate different config files)

**Comment by maaquib** [comment]
@austinmw `batchSize` is a per model parameter and we only support env variables for server level parameters. Alternatively, you could de-register the model and re-register it with a different `batchSize` using the [api](https://github.com/pytorch/serve/blob/master/docs/management_api.md#register-a-model)

**Comment by austinmw** [comment]
Thanks will do!
