### ISSUE TITLE
Upgrade to Java 17

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#1619]
## Is your feature request related to a problem? Please describe.
Java 17 has latency upgrades so it may be time to upgrade https://blogs.oracle.com/javamagazine/post/its-time-to-move-your-applications-to-java-17-heres-why-and-heres-how

## Describe the solution
Update this to Java 17 https://github.com/pytorch/serve/blob/master/ts_scripts/install_dependencies.py#L139

We actually don't need a cask anymore either and can just run `brew install openjdk@17`

**Comment by rohithkrn** [comment]
- [] https://github.com/pytorch/serve/issues/1730
- [] https://github.com/pytorch/serve/issues/1731
- [] https://github.com/pytorch/serve/issues/1732
- [] https://github.com/pytorch/serve/issues/1733

**Comment by msaroufim** [comment]
Thanks @rohithkrn !
