### ISSUE TITLE
Limit number of CPUs

### ISSUE THREAD

**Issue by ngocpham97** [pytorch/serve#1625]
## 📚 Documentation

With GPUs we use the number_of_gpu parameter in the config.properties file to limit GPUs. By default torchserve will use all CPUs, how to limit the number of CPUs used when serving models.

**Comment by msaroufim** [comment]
The easiest way to do so now is to change the `workers` param in `config.properties` https://github.com/pytorch/serve/blob/master/docs/performance_guide.md

But there'll be better guarantees on CPU performance once https://github.com/pytorch/serve/pull/1401 is merged
