### ISSUE TITLE
add OMP_NUM_THREADS default as 1 for CPU device in config.properties

### ISSUE THREAD

**Issue by lxning** [pytorch/serve#1642]
## Is your feature request related to a problem? Please describe.

According to [known issue](https://github.com/pytorch/pytorch/issues/3146), it can optimize performance for CPU to set "OMP_NUM_THREADS". So it is convenient for users to set  "OMP_NUM_THREADS" in TS config.properties.
 
## Describe the solution

1.  add OMP_NUM_THREADS in config.properties. (default value: 1)
2. set environment variable "OMP_NUM_THREADS" if TS is running on CPU.

**Comment by msaroufim** [comment]
We have more sophisicated heuristics as part of this PR https://github.com/pytorch/serve/pull/1401

Although I do agree that OM_NUM_THREAD=1 is a reasonable default
