### ISSUE TITLE
Server does not start on mac when jdk is installed 

### ISSUE THREAD

**Issue by nikunjbjj** [pytorch/serve#1644]
Please have a look at [FAQ's](../../docs/FAQs.md) and [Troubleshooting guide](../../docs/Troubleshooting.md), your query may be already addressed.

Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context
 Run the server using the following command and getting the following error- 

```
torchserve --start            --ncs            --ts-config deployment/config.properties            --model-store deployment/m
odel-store

```

```
java.lang.NoSuchMethodError: java.nio.file.Files.readString(Ljava/nio/file/Path;)Ljava/lang/String;
	at org.pytorch.serve.util.ConfigManager.readFile(ConfigManager.java:235)
	at org.pytorch.serve.util.ConfigManager.<init>(ConfigManager.java:139)
	at org.pytorch.serve.util.ConfigManager.init(ConfigManager.java:285)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:83)

```

```
python --version
Python 3.9.4
```

```
pip list | grep torch
torch                           1.11.0
torch-model-archiver            0.2.0
torch-model-archiver-nightly    2022.5.21
torch-workflow-archiver         0.2.4
torch-workflow-archiver-nightly 2022.5.21
torchserve                      0.2.0
torchserve-nightly              2022.5.21
torchsummary                    1.5.1
torchvision                     0.12.0

```

* torchserve version:
* torch-model-archiver version:
* torch version:
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
```
java -version
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Homebrew (build 18.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.1+0, mixed mode, sharing)

```
* Operating System and version:
macOS Catalina 10.15.7 (19H1519)

## Your Environment

* Installed using source? [yes/no]: pip
* Are you planning to deploy it using docker container? [yes/no]:no
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: default
* What kind of model is it e.g. vision, text, audio?: vision
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.? 
  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Expected Behavior

Server should start

## Current Behavior

```
torchserve --start            --ncs            --ts-config deployment/config.properties            --model-store deployment/m
odel-store

```

```
java.lang.NoSuchMethodError: java.nio.file.Files.readString(Ljava/nio/file/Path;)Ljava/lang/String;
	at org.pytorch.serve.util.ConfigManager.readFile(ConfigManager.java:235)
	at org.pytorch.serve.util.ConfigManager.<init>(ConfigManager.java:139)
	at org.pytorch.serve.util.ConfigManager.init(ConfigManager.java:285)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:83)

```

## Steps to Reproduce

1.
2.
...

**Comment by msaroufim** [comment]
Yeah for now we official support JDK 11 but did look into updating versions here #1619

**Comment by lxning** [comment]
@nikunjbjj pls run torchserve on java 11. Feel free to open this ticket if there are any issues.
