### ISSUE TITLE
Unable to build a CPU based image

### ISSUE THREAD

**Issue by BeMarinoGit** [pytorch/serve#1646]
Please have a look at [FAQ's](../../docs/FAQs.md) and [Troubleshooting guide](../../docs/Troubleshooting.md), your query may be already addressed.

Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context
I was trying to build a CPU based image but running the `./build_image.sh` script leads to the following error:

![Screenshot from 2022-05-23 11-29-01](https://user-images.githubusercontent.com/62105342/169789067-73710ffb-1358-478f-af7c-d5f89bbe8347.png)

I solved by adding `RUN apt-get update && apt-get install -y gnupg2`

* Operating System and version: Ubuntu 22.04 LTS

## Your Environment

* Installed using source? [yes/no]:
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]:default
* What kind of model is it e.g. vision, text, audio?: text
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Possible Solution

Add ` RUN apt-get update && apt-get install -y gnupg2` as first line of Dockerfile.

## Steps to Reproduce

1. clone the repository
2. run `cd serve/docker`
3. run `./build_image.sh`

**Comment by BeMarinoGit** [comment]
I tried to follow your suggestion, specifically i used the ubuntu:22.04 as base image but unfortunately the issue is still present.

**Comment by pjerryhu** [comment]
I'm experiencing the same issue. 
I haven't touched anything yet, so I believe build docker image is currently broken for master too

**Comment by msaroufim** [comment]
@pjerryhu are you observing this issue for Ubuntu 22.04 as well?

**Comment by lxning** [comment]
@BeMarinoGit Pls feel free to try the fixing and reopen this ticket if there is any issue.
