### ISSUE TITLE
Text to speeh synthesizer predict failed.

### ISSUE THREAD

**Issue by fullscratchlove** [pytorch/serve#1669]
I served waveglow_synthesizer and predict.
$ curl http://127.0.0.1:8080/predictions/waveglow_synthesizer -T sample_text.txt -o audio.wav
But I get the following error and cannot generate audio.

```
2022-06-03T07:43:12,809 [INFO ] W-9000-waveglow_synthesizer_1.0-stdout MODEL_LOG -   File "/tmp/models/2667bafea5ca4afa97f87dfd26aca97a/waveglow_handler.py", line 94, in inference
2022-06-03T07:43:12,810 [INFO ] W-9000-waveglow_synthesizer_1.0-stdout MODEL_LOG -     _, mel, _, _ = self.tacotron2_model.infer(data)
2022-06-03T07:43:12,810 [INFO ] W-9000-waveglow_synthesizer_1.0-stdout MODEL_LOG - TypeError: infer() missing 1 required positional argument: 'input_lengths'

```
If you have a sample of the correct execution, could you please let us know?
Thanks.

**Comment by lxning** [comment]
@fullscratchlove I followed the [instruction](https://github.com/pytorch/serve/tree/master/examples/text_to_speech_synthesizer) on GPU EC2 instance and it works for me.

```
cd examples/text_to_speech_synthesizer/
./create_mar.sh
mkdir model_store
mv waveglow_synthesizer.mar model_store/
torchserve --start --model-store model_store --models waveglow_synthesizer.mar

curl http://127.0.0.1:8080/predictions/waveglow_synthesizer -T sample_text.txt -o audio.wav
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:100   114  100    89  100    25   2617    735 --:--:-- --:--:-- --:--:--  3352
```

Are you using GPU host?

**Comment by fullscratchlove** [comment]
@lxning  Thanks.
I checked the model status and the GPU was set to true.

```
$ curl "http://127.0.0.1:8081/models/waveglow_synthesizer"
[
  {
    "modelName": "waveglow_synthesizer",
    "modelVersion": "1.0",
    "modelUrl": "waveglow_synthesizer.mar",
    "runtime": "python",
    "minWorkers": 1,
    "maxWorkers": 1,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": true,
    "workers": [
      {
        "id": "9000",
        "startTime": "2022-06-08T07:23:45.218Z",
        "status": "READY",
        "memoryUsage": 5055823872,
        "pid": 24276,
        "gpu": true,
        "gpuUsage": "gpuId::0 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::3368 MiB"
      }
    ]
  }
]
```

The error message I saw was a mismatch in the arguments passed to infer(), and I couldn't figure out why that would happen.

**Comment by lxning** [comment]
@fullscratchlove Here is the information of my environment.

1. model:
-rw-rw-r--  1 ubuntu ubuntu 1114353653 Jun  7 20:37 waveglow_synthesizer.mar
3. cuda: cuda 10.2
4. torch:
pip freeze|grep torch
torch==1.11.0
torch-model-archiver @ file:///home/ubuntu/serve/model-archiver
torch-workflow-archiver @ file:///home/ubuntu/serve/workflow-archiver
torchaudio==0.11.0
torchserve @ file:///home/ubuntu/serve
torchtext==0.12.0
torchvision==0.12.0

Note: I used "[create_mar.sh](https://github.com/pytorch/serve/blob/master/examples/text_to_speech_synthesizer/create_mar.sh) to create model mar file.

Could you re-run the [steps](https://github.com/pytorch/serve/tree/master/examples/text_to_speech_synthesizer) on a fresh environment?
