### ISSUE TITLE
Unable to build a CPU based image - version recognition error

### ISSUE THREAD

**Issue by pjerryhu** [pytorch/serve#1673]
### 🐛 Describe the bug

Running `bash build_docker.sh` will give no matching distribution error

```
#18 0.741 Looking in links: https://download.pytorch.org/whl/torch_stable.html
#18 1.574 ERROR: Could not find a version that satisfies the requirement torch==1.11.0+cpu (from versions: 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
#18 1.574 ERROR: No matching distribution found for torch==1.11.0+cpu
```

### Error logs

```
jerryhu@Jerrys-MacBook-Pro docker % bash build_image.sh -t torchserve:local
[+] Building 3.6s (17/26)                                                                               
 => [internal] load build definition from Dockerfile                                               0.0s
 => => transferring dockerfile: 4.88kB                                                             0.0s
 => [internal] load .dockerignore                                                                  0.0s
 => => transferring context: 2B                                                                    0.0s
 => resolve image config for docker.io/docker/dockerfile:experimental                              0.5s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a08  0.0s
 => [internal] load metadata for docker.io/library/ubuntu:18.04                                    0.4s
 => [internal] load build context                                                                  0.0s
 => => transferring context: 80B                                                                   0.0s
 => [compile-image  1/12] FROM docker.io/library/ubuntu:18.04@sha256:478caf1bec1afd54a58435ec681c  0.0s
 => CACHED [compile-image  2/12] RUN apt-get update && apt-get install -y gnupg2                   0.0s
 => CACHED [compile-image  3/12] RUN apt-key del 7fa2af80                                          0.0s
 => CACHED [compile-image  4/12] RUN apt-key adv --fetch-keys https://developer.download.nvidia.c  0.0s
 => CACHED [compile-image  5/12] RUN apt-key adv --fetch-keys https://developer.download.nvidia.c  0.0s
 => CACHED [compile-image  6/12] RUN --mount=type=cache,id=apt-dev,target=/var/cache/apt     apt-  0.0s
 => CACHED [compile-image  7/12] RUN update-alternatives --install /usr/bin/python python /usr/bi  0.0s
 => CACHED [compile-image  8/12] RUN python3.8 -m venv /home/venv                                  0.0s
 => CACHED [compile-image  9/12] RUN python -m pip install -U pip setuptools                       0.0s
 => CACHED [compile-image 10/12] RUN export USE_CUDA=1                                             0.0s
 => ERROR [compile-image 11/12] RUN TORCH_VER=$(curl --silent --location https://pypi.org/pypi/to  2.4s
------                                                                                                  
 > [compile-image 11/12] RUN TORCH_VER=$(curl --silent --location https://pypi.org/pypi/torch/json | python -c "import sys, json, pkg_resources; releases = json.load(sys.stdin)['releases']; print(sorted(releases, key=pkg_resources.parse_version)[-1])") &&     TORCH_VISION_VER=$(curl --silent --location https://pypi.org/pypi/torchvision/json | python -c "import sys, json, pkg_resources; releases = json.load(sys.stdin)['releases']; print(sorted(releases, key=pkg_resources.parse_version)[-1])") &&     if echo "ubuntu:18.04" | grep -q "cuda:"; then         if [ "" ]; then             python -m pip install --no-cache-dir torch==$TORCH_VER+ torchvision==$TORCH_VISION_VER+ -f https://download.pytorch.org/whl/torch_stable.html;         else             python -m pip install --no-cache-dir torch torchvision;         fi;         python -m pip install --no-cache-dir -r https://raw.githubusercontent.com/pytorch/serve/master/requirements/common.txt;     else         python -m pip install --no-cache-dir torch==$TORCH_VER+cpu torchvision==$TORCH_VISION_VER+cpu -f https://download.pytorch.org/whl/torch_stable.html;     fi:
#18 0.741 Looking in links: https://download.pytorch.org/whl/torch_stable.html
#18 1.574 ERROR: Could not find a version that satisfies the requirement torch==1.11.0+cpu (from versions: 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
#18 1.574 ERROR: No matching distribution found for torch==1.11.0+cpu
------
executor failed running [/bin/sh -c TORCH_VER=$(curl --silent --location https://pypi.org/pypi/torch/json | python -c "import sys, json, pkg_resources; releases = json.load(sys.stdin)['releases']; print(sorted(releases, key=pkg_resources.parse_version)[-1])") &&     TORCH_VISION_VER=$(curl --silent --location https://pypi.org/pypi/torchvision/json | python -c "import sys, json, pkg_resources; releases = json.load(sys.stdin)['releases']; print(sorted(releases, key=pkg_resources.parse_version)[-1])") &&     if echo "$BASE_IMAGE" | grep -q "cuda:"; then         if [ "$CUDA_VERSION" ]; then             python -m pip install --no-cache-dir torch==$TORCH_VER+$CUDA_VERSION torchvision==$TORCH_VISION_VER+$CUDA_VERSION -f https://download.pytorch.org/whl/torch_stable.html;         else             python -m pip install --no-cache-dir torch torchvision;         fi;         python -m pip install --no-cache-dir -r https://raw.githubusercontent.com/pytorch/serve/master/requirements/common.txt;     else         python -m pip install --no-cache-dir torch==$TORCH_VER+cpu torchvision==$TORCH_VISION_VER+cpu -f https://download.pytorch.org/whl/torch_stable.html;     fi]: exit code: 1
```

### Installation instructions

Install Torchserve from source: Yes. I followed this guide - https://github.com/pytorch/serve/blob/master/docs/getting_started.md

Are you using docker? Yes. I ran `bash build_image.sh -t torchserve:local` and already run into error

### Model Packaing

Not applicable

### config.properties

inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
workflow_store=/home/model-server/wf-store
models=all

### Versions

erryhu@Jerrys-MacBook-Pro torchserve % python ts_scripts/print_env_info.py 

------------------------------------------------------------------------------------------
Environment headers
------------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.6.0
torch-model-archiver==0.6.0

Python version: 3.9 (64-bit runtime)
Python executable: /opt/homebrew/opt/python@3.9/bin/python3.9

Versions of relevant python libraries:
captum==0.5.0
future==0.18.2
numpy==1.22.4
nvgpu==0.9.0
psutil==5.9.1
requests==2.27.1
torch==1.11.0
torch-model-archiver==0.6.0
torch-workflow-archiver==0.2.4
torchaudio==0.11.0
torchserve==0.6.0
torchtext==0.12.0
torchvision==0.12.0
wheel==0.37.1
torch==1.11.0
torchtext==0.12.0
torchvision==0.12.0
torchaudio==0.11.0

Java Version:

OS: Mac OSX 12.2.1 (arm64)
GCC version: N/A
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: N/A

Versions of npm installed packages:
**Warning: newman, newman-reporter-html markdown-link-check not installed...

### Repro instructions

1. clone the repo
2. run `bash build_docker.sh`

### Possible Solution

remove `+cpu` in line 77 of file https://github.com/pytorch/serve/blob/master/docker/Dockerfile#L77

However, Docker build seems to pass fine, but docker run is erroring out
```
jerryhu@Jerrys-MacBook-Pro docker % docker run --rm -it -p 8080:8080 -p 8081:8081 --name mar -v $(pwd)/model-store:/home/model-server/model-store -v $(pwd)/examples:/home/model-server/examples pytorch/torchserve:latest-cpu
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at org.pytorch.serve.util.ConfigManager.setModelConfig(ConfigManager.java:799)
	at org.pytorch.serve.util.ConfigManager.<init>(ConfigManager.java:231)
	at org.pytorch.serve.util.ConfigManager.init(ConfigManager.java:285)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:83)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 6 more
```

**Comment by lxning** [comment]
@pjerryhu After fixing #1646, i ran the following command on my mac. it works for me. Could you pull the latest master branch and try again ?

./build_image.sh -t torchserve:local
[+] Building 407.7s (25/25) FINISHED
 => [internal] load build definition from Dockerfile     0.0s
 => => transferring dockerfile: 4.50kB                   0.0s
 => [internal] load .dockerignore                        0.0s
 => => transferring context: 2B                          0.0s
 => resolve image config for docker.io/docker/dockerfil  1.8s
 => [auth] docker/dockerfile:pull token for registry-1.  0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:e  0.0s
 => [internal] load metadata for docker.io/library/ubun  2.0s
 => [auth] library/ubuntu:pull token for registry-1.doc  0.0s
 => [internal] load build context                        0.0s
 => => transferring context: 541B                        0.0s
 => [compile-image 1/8] FROM docker.io/library/ubuntu:  11.7s
 => => resolve docker.io/library/ubuntu:18.04@sha256:47  0.0s
 => => sha256:478caf1bec1afd54a58435ec6 1.41kB / 1.41kB  0.0s
 => => sha256:8da4e9509bfe5e09df6502e7a8e93 529B / 529B  0.0s
 => => sha256:ad080923604aa54962e903125 1.46kB / 1.46kB  0.0s
 => => sha256:09db6f815738b9c8f25420 26.71MB / 26.71MB  10.5s
 => => extracting sha256:09db6f815738b9c8f25420c47e093f  1.0s
 => [compile-image 2/8] RUN --mount=type=cache,id=apt  179.0s
 => [runtime-image 2/9] RUN --mount=type=cache,target  275.4s
 => [compile-image 3/8] RUN update-alternatives --insta  0.3s
 => [compile-image 4/8] RUN python3.8 -m venv /home/ven  1.9s
 => [compile-image 5/8] RUN python -m pip install -U p  71.4s
 => [compile-image 6/8] RUN export USE_CUDA=1            0.5s
 => [compile-image 7/8] RUN TORCH_VER=$(curl --silent   90.9s
 => [runtime-image 3/9] RUN useradd -m model-server      0.4s
 => [compile-image 8/8] RUN python -m pip install -U s  28.2s
 => [runtime-image 4/9] COPY --chown=model-server --fro  3.9s
 => [runtime-image 5/9] COPY dockerd-entrypoint.sh /usr  0.0s
 => [runtime-image 6/9] RUN chmod +x /usr/local/bin/doc  0.5s
 => [runtime-image 7/9] COPY config.properties /home/mo  0.0s
 => [runtime-image 8/9] RUN mkdir /home/model-server/mo  0.3s
 => [runtime-image 9/9] WORKDIR /home/model-server       0.0s
 => exporting to image                                  10.1s
 => => exporting layers                                 10.1s
 => => writing image sha256:46ac4af11e767f36ec6f89b29a0  0.0s
 => => naming to docker.io/library/torchserve:local      0.0s

 docker images
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
torchserve   local     46ac4af11e76   48 minutes ago   1.49GB

**Comment by lxning** [comment]
@pjerryhu yeah, I think so. The root cause is mac M1 according to PyTorch installation instruction.

# MacOS Conda binaries are for x86_64 only, for M1 please use wheels
conda install pytorch torchvision torchaudio -c pytorch

**Comment by pjerryhu** [comment]
Hey @lxning , thank you for responding! the `docker buildx` command solved my problem. Thank you so much!
