### ISSUE TITLE
torchserve docker image with tag 'latest' and '0.6.0' still using previous torchserve version '0.5.3'

### ISSUE THREAD

**Issue by mansigoel** [pytorch/serve#1681]
Latest docker releases of torchserve (version 0.6.0) are still using previous torchserve library version '0.5.3'
Can the latest docker images be updated to reflect the latest torchserve library version 0.6.0?

```
Command: docker run --rm -it -v $(pwd):/mnt/models docker.io/pytorch/torchserve:0.6.0-cpu torchserve --start --model-store /mnt/models/model-store 
```

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2022-06-10T18:55:31,140 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2022-06-10T18:55:31,336 [INFO ] main org.pytorch.serve.ModelServer -
**Torchserve version: 0.5.3**
TS Home: /home/venv/lib/python3.8/site-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
```

**Comment by msaroufim** [comment]
Yeah our bad, like like the PR to update the version number was merged in after the release https://github.com/pytorch/serve/pull/1592

**Comment by lxning** [comment]
@msaroufim according to the [link](https://github.com/pytorch/serve/commit/9aeb8af7a11a18a4aca6b81d2f0a239a500ca252#diff-0377cd7efa39189d481ea81cd7c45057e164e01393c2316560bc6bf677b21517), the docker images are tagged as latest-cpu and latest-gpu in v0.6.0.

@mansigoel sorry for the confusion. Please find v0.6.0 docker images

- [latest-gpu](https://hub.docker.com/layers/torchserve/pytorch/torchserve/latest-gpu/images/sha256-56aabc4c7319241dd015324b82bbff1521bd50efb9207fbc792d1e387b8a1ab2?context=explore)
- [latest-cpu](https://hub.docker.com/layers/torchserve/pytorch/torchserve/latest-cpu/images/sha256-1b5060687eb0a9a25b6c41b5020430150dd0f94773494db8aba271ac5e6f2595?context=explore)

**Comment by msaroufim** [comment]
This should be fixed now
