### ISSUE TITLE
Error in loading model in Windows os

### ISSUE THREAD

**Issue by DPeled** [pytorch/serve#1686]
I've noticed that there is an error in the code:
https://github.com/pytorch/serve/blob/a4d5090e114cdbeddf5077a817a8cd02d129159e/ts/model_loader.py#L92

There is an attempt to read the `MANIFEST.json` file, and there is use of the `/` charecter which used as a seperator in the Linux os, and in Windows there is use of the back-slash `\`, so this line creates always an invalid path so the loader does not find the manifest file.

I would change it to use the function `os.path.join` (which already in use) to write something like this:
```python
manifest_file = os.path.join(model_dir, "MAR-INF", "MANIFEST.json") 
```

I'm not changing this by myself in a PR beacause I don't know if there is another lines in the code which this error occurs.

**Comment by maaquib** [comment]
@DPeled Thanks for pointing out the bug. Would you like to send out the fix as a PR?

**Comment by DPeled** [comment]
@maaquib I can, but waht if there is more errors like this? in another PR?

**Comment by maaquib** [comment]
You are right. I did a quick search and found a few more [1](https://github.com/pytorch/serve/blob/873edc50cc6059c47830a5d30bbbdbe1e1a3d9bb/test/pytest/test_handler.py#L11) [2](https://github.com/pytorch/serve/blob/7a69e4018f3d694891c1415e2ab01413452fb009/test/pytest/test_metrics_kf.py#L15) [3](https://github.com/pytorch/serve/blob/dd2d48525e10ca401092b4abad0792191f7469b9/ts/model_server.py#L95) [4](https://github.com/pytorch/serve/blob/5b96c5fb6201e459a5e8417a09984638332e1533/benchmarks/utils/gen_md_report.py#L26) [5](https://github.com/pytorch/serve/blob/04c873f31abf5345eba8c93e6856a621b8a9398d/test/pytest/test_utils.py#L12) [6](https://github.com/pytorch/serve/blob/7a69e4018f3d694891c1415e2ab01413452fb009/test/pytest/test_metrics_kf.py#L15)
If you'd like to contribute, feel free to send a PR
