### ISSUE TITLE
Performance Benchmark Doc Missing

### ISSUE THREAD

**Issue by Hegelim** [pytorch/serve#1696]
### 📚 The doc issue

https://github.com/pytorch/serve/blob/master/docs/performance_guide.md
Here, the link https://github.com/pytorch/serve/tree/master/benchmarks/automated is missing

![image](https://user-images.githubusercontent.com/55818214/174655162-ff7d883b-66d6-450f-8c23-4bbecb426d9a.png)

**Comment by Hegelim** [comment]
I think the link is still missing?
![image](https://user-images.githubusercontent.com/55818214/174849662-bc04bbe2-b2f0-4c26-a33b-7b798591684a.png)

**Comment by msaroufim** [comment]
PR is out but not merged yet
