### ISSUE TITLE
Inference call with bogus version gives 500 instead of 404

### ISSUE THREAD

**Issue by fbbradheintz** [pytorch/serve#170]
If I put up version 1.0 of a model called `r18`, the following happens:

* If I call `curl -X POST http://localhost:8080/predictions/r18/1.0 -T kitten.jpg`, I get a 200 and an inference result. (This is correct.)
* If I call `curl -X POST http://localhost:8080/predictions/r18/1.2 -T kitten.jpg`, I get a 404 - the model can't be found. (This is correct.)
* If I call `curl -X POST http://localhost:8080/predictions/r18/1p0 -T kitten.jpg`, I get:

```
{
  "code": 500,
  "type": "NumberFormatException",
  "message": "For input string: \"1p2\""
}
```

This should be a 404.

**Comment by harshbafna** [comment]
@fbbradheintz This is already fixed in master. Can we close this ticket?

**Comment by harshbafna** [comment]
@lokeshgupta1975 @mycpuorg : The corresponding PR is already merged in the master branch. We can close this ticket.

**Comment by dhaniram-kshirsagar** [comment]
Related PR has been merged hence closing this.
