### ISSUE TITLE
Can't use `ts` library inside docker image

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#1702]
Does this section of the docs need to be updated to reflect that you can't import from `ts` in the pytorch docker images? 

https://pytorch.org/serve/custom_service.html

I'm trying to use a custom handler like so and running into this error

```bash
torch-model-archiver --model-name mdv5 --version 1.0.0 --serialized-file ../models/megadetectorv5/md_v5a.0.0.torchscript --extra-files index_to_name.json --handler ../api/megadetectorv5/mdv5_handler.py
```

_Originally posted by @rbavery in https://github.com/pytorch/serve/issues/1695#issuecomment-1161313611_

**Comment by msaroufim** [comment]
@rbavery did I understand your question correctly that if you try a line like `from ts import *` that this fails in your docker image? That's not expected behavior we have in our `Dockerfile` a line to install torchserve explicitly https://github.com/pytorch/serve/blob/master/docker/Dockerfile#L74

**Comment by rbavery** [comment]
thanks a bunch for answering @msaroufim 

it looks like it depends on the method of importing in the docker image. What I had in my custom handler does not work

```
→ docker run --rm -it -p 8080:8080 -p 8081:8081 -p 8082:8082 -p 7070:7070 -p 7071:7071 pytorch/torchserve:latest /bin/bash  
python
>>> from ts.torch_handler.objectdetector import ObjectDetector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ts.torch_handler.objectdetector'

```

but as you indicate, * importing does work

```
>>> from ts import *
```
