### ISSUE TITLE
Netty Threads don't change even set explicitly in config.properties

### ISSUE THREAD

**Issue by Hegelim** [pytorch/serve#1714]
https://github.com/pytorch/serve/issues/1700#issuecomment-1164746780

Any ideas why?

**Comment by msaroufim** [comment]
Both of those parameters are parameters to TorchServe and not to a specific model see this for an example https://github.com/pytorch/serve/blob/master/docker/config.properties#L1-L7

And in your code you've shown them as model specific parameters

```
models={\
  "ABINet": {\
    "1.0": {\
         ...
        "number_of_netty_threads": 8,\
```

**Comment by Hegelim** [comment]
Ahh thanks! Finally figured it out!
