### ISSUE TITLE
Clarify that TorchServe supports KServe V2 Inference API

### ISSUE THREAD

**Issue by ankit-db** [pytorch/serve#1721]
### 🚀 The feature

Hey folks - I was wondering whether TorchServe has considered supporting the Inference V2 API proposed by KServe (https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md) It seems Triton, TFServing, and MLServer all support this API. 

Please let me know if I'm missing that this is already on a public roadmap.

### Motivation, pitch

It seems KServe V2 Prediction API is on the cusp of being a standard across the major inference servers. This would make it really easy to generalize inference formats

### Alternatives

Stay only with support of KServe V1 protocol

**Comment by msaroufim** [comment]
We already support the v2 API - there's more information in docs here https://github.com/pytorch/serve/tree/master/kubernetes/kserve

I think we can make this clearer in the `README.md`

**Comment by ankit-db** [comment]
Oh great! Good to hear. My confusion originated from this docs page in case that helps: https://pytorch.org/serve/inference_api.html
