### ISSUE TITLE
Wring codecov binary is used in macos CI

### ISSUE THREAD

**Issue by mreso** [pytorch/serve#1757]
### 🐛 Describe the bug

We're using codecov linux binaries in our MacOS CI pipeline which fails to execute.

### Error logs

![image](https://user-images.githubusercontent.com/13337103/180519640-1ba5e259-4623-44bf-80c2-ff2ab2ab4cab.png)

### Installation instructions

Run CI

### Model Packaing

None

### Versions

master

### Repro instructions

See https://github.com/pytorch/serve/runs/7474441442?check_suite_focus=true

**Comment by msaroufim** [comment]
Interesting how Windows runs :/ - just fixed this
