### ISSUE TITLE
Cant find  org.pytorch.serve.grpc.inference

### ISSUE THREAD

**Issue by JafarBadour** [pytorch/serve#1771]
### 📚 The doc issue

Cant find the grpc inference java code?

**Comment by agunapal** [comment]
@JafarBadour Can you please clarify what is the context and what you are looking for

**Comment by JafarBadour** [comment]
I am trying to understand torchserve code base and it seems it is missing this part

**Comment by agunapal** [comment]
Got it . Thanks
