### ISSUE TITLE
Unsupported model output data type

### ISSUE THREAD

**Issue by hungtooc** [pytorch/serve#1782]
### 📚 The doc issue

Where is list of supported data type? How could I return numy-array, tensor, or bytes in postprocess()?

**Comment by maaquib** [comment]
@hungtooc For returning custom data types, you can serialize it to a bytearray and then deserialize it on the client side. For instance, for numpy array, you could use `np.save` and `np.load` to do this.

I'll leave this issue open to add this to the custom_service documentation
