### ISSUE TITLE
Question regarding multiple inputs / batching

### ISSUE THREAD

**Issue by mhashas** [pytorch/serve#1783]
### 📚 The doc issue

Hello! 

I am a bit confused about the internal workings of torchserve regarding batching and multiple inputs. I will try to best explain my questions.

Let's start with the first question, which regards batching (let's disregard multiple inputs for now).

1. Is it true that requests can be batched together by TorchServe? i.e. user A under user B both make a request, in order to be more efficient torchserve batches together these requests to only do one forward pass through the model.

Assuming the answer is yes, then:

In the VisionHandler (https://github.com/pytorch/serve/blob/master/ts/torch_handler/vision_handler.py#L38), you loop over rows of data. This leads me to believe that my custom handler code should work for batches and not only a single example. i.e. I need to make sure my code can handle batches and this is not done automatically by torchserve. 

However, in the TextClassifier (https://github.com/pytorch/serve/blob/master/ts/torch_handler/text_classifier.py#L49), only the first row is taken. Does this mean that the textclassifier does not support batching requests? 

I am a bit confused whether the responsability of handling batching is done internally by torchserve or is done explicitly by the handler.

2. I am working on an inpainting model which needs to receive two inputs: an image and a mask. From what I can see, it's not possible to send a dict {"image": bytearray, "mask": bytearray} as input. https://pytorch.org/serve/inference_api.html#curl-example here it seems to suggest that I should just send a dict that overrides the same key (its quite confusing to be honest) and does not seem to work. How can I handle multiple inputs?

**Comment by mhashas** [comment]
I seem to have found the answer to the second.

In my case I can indeed send a dict `{"image": bytes, "mask": bytes}` and in the handler I can do:

```
data = data[0]
img = data["image"]
mask = data["mask"]
```


https://github.com/pytorch/serve/blob/5c03e711a401387a1d42fc01072fcc38b4995b66/frontend/server/src/main/resources/proto/inference.proto#L17.

**Comment by mhashas** [comment]
Regarding the first, as I can see the 'maxBatchDelay and batchSize' config properties seem to control whether inputs are batched, correct? However, it's still my code's responsability to handle > 1 batch size? Can this behaviour be disabled by setting batchSize to 1? In the case of the text_classifier, batch size should always be 1?

Thank you

**Comment by maaquib** [comment]
> Regarding the first, as I can see the 'maxBatchDelay and batchSize' config properties seem to control whether inputs are batched, correct? However, it's still my code's responsability to handle > 1 batch size? Can this behaviour be disabled by setting batchSize to 1? In the case of the text_classifier, batch size should always be 1?
> 
> Thank you

@mhashas There are two ways of disabling server side batching. You can set batchSize=1 during registering your model or set them up in the `config.properties` file. ([doc](https://github.com/pytorch/serve/blob/master/docs/batch_inference_with_ts.md#torchserve-model-configuration)). Feel free to re-open if you need any more info

**Comment by mhashas** [comment]
@maaquib Thanks for the answer. Regarding if its my responsability to handle > 1 batch size or it's handled automatically by torchserve? 

In the VisionHandler (https://github.com/pytorch/serve/blob/master/ts/torch_handler/vision_handler.py#L38), you loop over rows of data. This leads me to believe that my custom handler code should work for batches and not only a single example. i.e. I need to make sure my code can handle batches and this is not done automatically by torchserve.

However, in the TextClassifier (https://github.com/pytorch/serve/blob/master/ts/torch_handler/text_classifier.py#L49), only the first row is taken. Does this mean that the textclassifier does not support batching requests?

**Comment by tripathiarpan20** [comment]
Hi @mhashas 
I have been learning Torchserve with AWS past few days too and have read a fair bit of documentation too.

The Line 5 of [TextClassifier](https://github.com/pytorch/serve/blob/master/ts/torch_handler/text_classifier.py#L5) indeed mentions that it does not support batching, not sure why though as I haven't looked into it.

Your understanding of dynamic batching is also along the lines of [this doc](https://github.com/pytorch/serve/blob/master/docs/batch_inference_with_ts.md#batch-inference-with-torchserves-default-handlers), you can read it for useful insights.

As for sending multiple inputs, this AWS Example repo seems pretty useful for both [writing custom handlers](https://github.com/aws-samples/amazon-sagemaker-endpoint-deployment-of-siamese-network-with-torchserve#custom-handler) without even using the [BaseHandler](https://github.com/pytorch/serve/blob/master/ts/torch_handler/base_handler.py) ([README](https://github.com/pytorch/serve/blob/master/docs/custom_service.md)).

You can see how they give two inputs (`left` and `right`) in the `preprocess` function of their [handler](https://github.com/aws-samples/amazon-sagemaker-endpoint-deployment-of-siamese-network-with-torchserve/blob/main/deployment/handler.py#L150) and during [POST requests](https://github.com/aws-samples/amazon-sagemaker-endpoint-deployment-of-siamese-network-with-torchserve#torchserve-in-action)(`left@` and `right@`).

**Comment by mhashas** [comment]
Hi @tripathiarpan20,

First of all thanks a lot for the awesome resources and for clearing things up for me. Best of luck in your learning journey.

**Comment by Alonelymess** [comment]
I have a weird experience that if I batch on the client side. Suppose I have 2 cameras, each camera I batch 4 images then send them. I create 2 threads to send data from 2 cameras in parallel. Surprisingly, the data I receive on the server automatically concatenate those request to 1 array of 8 images, they are indeed in order like frame1-cam1, frame2-cam1, ... frame4-cam2. The model still infer fine, but when the server send result back, I got error say that it expected batch=2, got 1. So I assume that torchserve when requesst in parallel, it automatically consider the input is a batch with size = num of requests. How to disable this feature?

**Comment by Alonelymess** [comment]
> I have a weird experience when I batch on the client side. Suppose I have 2 cameras, each camera I batch 4 images then send them. I create 2 threads to send data from 2 cameras in parallel. Surprisingly, the data I receive on the server automatically concatenate those request to 1 array of 8 images, they are indeed in order like frame1-cam1, frame2-cam1, ... frame4-cam2. The model still infer fine, but when the server send result back, I got error say that it expected batch=2, got 1. So I assume that torchserve when requesst in parallel, it automatically consider the input is a batch with size = num of requests. How to disable this feature?

Update: I change the batchSize in the config file to 1 and it works. It still weird that if I remain my batchSize=4 in my config and only send 1 image at a time, torchserve still return the output
