### ISSUE TITLE
Change serving-sdk namespace to pytorch.org

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#179]
The serving-sdk is still under software.amazon.ai.mms namespace. Change to org.pytorch.serve namespace

**Comment by lokeshgupta1975** [comment]
@vdantu has created a PR #261 for this, but the PR needs more work, he is looking it.

**Comment by chauhang** [comment]
@vdantu Verified can be closed after merge

**Comment by maaquib** [comment]
PR tested and merged

**Comment by maaquib** [comment]
PR tested and merged
