### ISSUE TITLE
image size limitation

### ISSUE THREAD

**Issue by jack-gits** [pytorch/serve#1806]
### 🐛 Describe the bug

whether there's a limitation of image size? when the image is bigger, app can't pass the image to the torchseve.

### Error logs

there's no any log in the torchseve. seem it didn't receive the access request.

### Installation instructions

yes, using docker 0.6.0gpu version

### Model Packaing

use torch-model-archiver

### Versions

0.6.0gpu

### Repro instructions

when I call the inference model by http://xxxx.xxx.xxx.xxx:8080/predictions/{modelname}

**Comment by msaroufim** [comment]
There is an image size limit that you can change in your `config.properties` https://github.com/pytorch/serve/blob/master/docs/configuration.md#other-properties

**Comment by jack-gits** [comment]
fixed!!
