### ISSUE TITLE
Explanation/comparison between default_response_timeout and responseTimeout in config.properties

### ISSUE THREAD

**Issue by hgong-snap** [pytorch/serve#1833]
### 📚 The doc issue

`default_response_timeout`  and `responseTimeout` looks very similar. Should we add more details about those two? e.g. what's the behavior if timeout is reached? will backend worker die/restart? or just timeout status received from HTTP/GRPC response but backend worker is still fine/alive?    

Example would be also great. e.g., if 100ms is my P99 response time for model, given default timeout is 120s, I guess best practice should be overwriting `default_response_timeout` or `responseTimeout` to some reasonable time? (say, 200ms)

**Comment by msaroufim** [comment]
The main difference between `default_response_timeout` and `responseTimeout` is that the first applies to TorchServe and applies to **all models** and the latter applies to a **specific model**. I can make this clearer in the docs but to keep backwards compatibility with a name change we'd need to support both. Regardless lemme make the doc PR for this now 

I do agree that the our current defaults are not reasonable, so the best way to handle this would be for us to decrease it and then make sure none of our benchmark scripts fail by running #1798 and first fixing #1834.
