### ISSUE TITLE
How can I get the value of the "--extra-files" option in the handler?

### ISSUE THREAD

**Issue by Shin-ichi-Takayama** [pytorch/serve#1838]
For example, the value of the "--serializedFile" option can be obtained with the following code
```Python
#Initialization functions in the handler class
def initialize(self, context):
        self.manifest = context.manifest
        serialized_file = self.manifest['model']['serializedFile']
```

How can I get the value of the "--extra-files" option?

Best regards.

**Comment by msaroufim** [comment]
This should work
        
```python
model_dir = properties.get("model_dir")
extra_file_path = os.path.join(model_dir, "path_to_extra_file")
```

Here's an example https://github.com/pytorch/serve/blob/master/examples/Huggingface_Transformers/Transformer_handler_generalized.py#L53

**Comment by Shin-ichi-Takayama** [comment]
@msaroufim 
Thank you for your response.

> model_dir = properties.get("model_dir")
> extra_file_path = os.path.join(model_dir, "path_to_extra_file")

I think this method would require rewriting the handler directly.
I would like to get the value of the "--extra-files" option in the handler.

Best regards.

**Comment by msaroufim** [comment]
Sounds good, just curious how you'd like the experience to be like instead?

Let's say we have something like then you'd still need to change your handler file

```python
extra_files : List = properties.get("extra_files")
for file in extra_files:
  if extra_file == "extra_file_name:
    do_x()
  ...
```

**Comment by Shin-ichi-Takayama** [comment]
@msaroufim 
Thank you for your response.
Suppose the coefficient file (pth file) and the model configuration file (yaml file) are tied together.
For example, if I want to run a model with setting A, I archive the model as follows
> torch-model-archiver --model-name **denoise_transformer_modelA** --version 1.0 --model-file /usr/local/lib/python3.8/dist-packages/espnet2/bin/enh_inference.py --serialized-file **modelA.pth** --export-path model_store --extra-files **modelA_setting.yaml** --handler model_handler.py

If I want to run a model with setting B, I archive the model as follows
> torch-model-archiver --model-name **denoise_transformer_modelB** --version 1.0 --model-file /usr/local/lib/python3.8/dist-packages/espnet2/bin/enh_inference.py --serialized-file **modelB.pth** --export-path model_store --extra-files **modelB_setting.yaml** --handler model_handler.py

The first method you suggested would require rewriting the code.
However, I would prefer to just change the command as above.

Also, I could not get the contents of `extra_files` with the following method.
```Python
extra_files : List = properties.get("extra_files")
for file in extra_files:
  if extra_file == "extra_file_name":
    do_x()
  ...
```

**Comment by lxning** [comment]
@Shin-ichi-Takayama existing model archiver only includes extra-files input from[ cmd-line](https://github.com/pytorch/serve/tree/master/model-archiver#arguments), does not add sth like "extraFiles" in manifest [model item](https://github.com/pytorch/serve/blob/master/model-archiver/model_archiver/manifest_components/model.py#L33). 

So there is no way for you to write code such as 
```
extra_files : List = properties.get("extra_files")
for file in extra_files:
  if extra_file == "extra_file_name":
    do_x()
  ...
```

Let's assume you are mar file creator. You know the extra files. Then you can directly access the extra files in handler via [model_dir](https://github.com/pytorch/serve/blob/master/ts/torch_handler/base_handler.py#L80)/extra-fileXXX.

**Comment by Shin-ichi-Takayama** [comment]
@lxning 
Thank you for your response.
So you are saying that it is not possible to get the value of the `--extra-files` option in the handler?
Does it mean that I need to directly mention the filename in the handler?

**Comment by lxning** [comment]
@Shin-ichi-Takayama In the existing code, there is no API for users to retrieve the input value of "--extra-files". However, users can directly access the extra files via mode_dir/your_extra_file_name in handler.

**Comment by Shin-ichi-Takayama** [comment]
@lxning 
Thank you very much.
I understand now. My question has been answered and I will close this issue.
