### ISSUE TITLE
--ncs flag, what exactly does it do?

### ISSUE THREAD

**Issue by joemal1234** [pytorch/serve#1840]
### 📚 The doc issue

can't serve the new model i want to serve with torchserve --start without the --ncs flag

What is it's purpose and what is it doing?
What exactly is the benefit of having it? 

I've found it to be very confusing, and I can't see clear documentation on what it does.

**Comment by msaroufim** [comment]
`--ncs` stands for no config snapshot https://github.com/pytorch/serve/blob/master/ts/arg_parser.py#L52

Snapshots are a way to resume inferences in case a deployment goes down or needs to be stopped. For local experimentation it makes more sense to disable it and for prod deployments it makes more sense to enable it
