### ISSUE TITLE
docker image built with`-bt  prodction`  throws permission denied on `/usr/local/bin/dockerd-entrypoint.sh`

### ISSUE THREAD

**Issue by Chichilele** [pytorch/serve#1843]
### 🐛 Describe the bug

After building the docker image with production built type as follows:
```bash
$ ./build_image.sh -bt production --gpu --tag torchserve:cuda113 -cv cu11
```
The container runs into the following error at startup:
```bash
$ docker run -it -p8080:8080 -p8081:8081 -p8082:8082 \
     -v $(pwd)/model_store:/home/model-server/model-store \
     torchserve:cuda113 \
     torchserve --model-store model-store --models mymodel=mymodel.mar

/bin/bash: /usr/local/bin/dockerd-entrypoint.sh: Permission denied
```
Note that it works fine with `--bt dev`

### Error logs

```bash
$ docker run -it -p8080:8080 -p8081:8081 -p8082:8082 \
     -v $(pwd)/model_store:/home/model-server/model-store \
     torchserve:cuda113 \
     torchserve --model-store model-store --models mymodel=mymodel.mar

/bin/bash: /usr/local/bin/dockerd-entrypoint.sh: Permission denied
```

### Installation instructions

```bash
$ git clone git@github.com:pytorch/serve.git
```

### Model Packaing

```bash
torch-model-archiver --model-name mymodel \
    --version 1.0 \
    --serialized-file "model_scripted.pt" \
    --handler image_segmenter \
    --export-path model_store -f

```
or equivalent but not relevant as it works in 3 different contexts

### Versions

master at commit `695b90e5acc8b1afc08cb0f73f8f58b8915b9b52`

### Repro instructions

```bash
$ cd serve/docker
$ ./build_image.sh -bt production --gpu --tag torchserve:cuda113 -cv cu11
$ docker run -it -p8080:8080 -p8081:8081 -p8082:8082 \
     -v /home/ubuntu/model_store:/home/model-server/model-store \
     torchserve:cuda113 \
     torchserve --model-store model-store --models mymodel=mymodel.mar
```

### Possible Solution

Just don't set the entrypoint maybe as it's not in the Dockerfile.dev

**Comment by msaroufim** [comment]
I believe there's just a simple bug here

https://github.com/pytorch/serve/blob/master/docker/Dockerfile#L101

That should be fixed by doing `COPY docker/dockerd-entrypoint.sh /usr/local/bin/dockerd-entrypoint.sh` - if that works lmk and if you like make a PR for it

**Comment by Chichilele** [comment]
The `COPY` works fine, it it looks like it's more to do with how the permissions are set. I managed to get it to work. I bumped into another permission error with the config file. Just add a read permission to the entrypoint and change the ownership of the config file as follows:
```Dockerfile
COPY dockerd-entrypoint.sh /usr/local/bin/dockerd-entrypoint.sh

RUN chmod +x /usr/local/bin/dockerd-entrypoint.sh \
    && chown -R model-server /home/model-server

COPY config.properties /home/model-server/config.properties
RUN mkdir /home/model-server/model-store && chown -R model-server /home/model-server/model-store
```
to 
```Dockerfile
COPY dockerd-entrypoint.sh /usr/local/bin/dockerd-entrypoint.sh

COPY config.properties /home/model-server/config.properties

RUN mkdir /home/model-server/model-store \
    && chmod +rx /usr/local/bin/dockerd-entrypoint.sh \
    && chown -R model-server /home/model-server
```

Should I open a PR wit this? I didn't run all the tests you ask for but I managed to serve a model and run an inference

**Comment by msaroufim** [comment]
Yup opening a PR sounds great

**Comment by lxning** [comment]
@Chichilele I tested the docker prod, it works fine. Here are the steps what i did.

- cd docker
- mkdir model_store
- cd model_store
- wget https://torchserve.pytorch.org/mar_files/mnist_v2.mar
- ./build_image.sh -bt production --gpu --tag torchserve:cuda113 -cv cu113
- docker run -it -p8080:8080 -p8081:8081 -p8082:8082 -v /home/ubuntu/serve/docker/model_store/:/home/model-server/model-store torchserve:cuda113 torchserve --model-store  /home/model-server/model-store --models all

I can see there are some cmd error in your steps. 
```
./build_image.sh -bt production --gpu --tag torchserve:cuda113 -cv cu11 
docker run -it -p8080:8080 -p8081:8081 -p8082:8082 \
     -v $(pwd)/model_store:/home/model-server/model-store \
     torchserve:cuda113 \
     torchserve --model-store model-store --models mymodel=mymodel.mar
```

should be 
```
./build_image.sh -bt production --gpu --tag torchserve:cuda113 -cv cu113
docker run -it -p8080:8080 -p8081:8081 -p8082:8082 \
     -v $(pwd)/model_store:/home/model-server/model-store \
     torchserve:cuda113 \
     torchserve --model-store /home/model-server/model-store --models mymodel=mymodel.mar
```

Can you test on your end again?

**Comment by Chichilele** [comment]
As you can see in the picture below, the file is executable but not readable.
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/17325189/188953129-0927dfbb-d8e7-4409-9737-29781a9cb1ec.png">

**Comment by Chichilele** [comment]
As you can see in the picture below, the file is executable but not readable.
![Screenshot 2022-09-07 at 19 23 34](https://user-images.githubusercontent.com/17325189/188953859-8d443cd1-6adb-4616-812e-13e559dee0f8.png)

**Comment by Chichilele** [comment]
As you can see in the picture below, the file is executable but not readable.
<img width="1722" alt="Screenshot 2022-09-07 at 19 39 13" src="https://user-images.githubusercontent.com/17325189/188953923-26aed2df-0c6a-4e17-9169-56ad9734abd0.png">

**Comment by lxning** [comment]
@Chichilele I still can not reproduce your case. And also I don't understand "+X" mode prevents you to start container. Screen Shot 2022-09-08 at 2.54.18 PM

**Comment by Chichilele** [comment]
It looks like your layers are cached so changes may not be applied. Try adding a ‘—no-cache’ to the production docker build command in the script. The +x is already there. My change adds a +r to make the file readable for anyone (file mode 755)

**Comment by Chichilele** [comment]
up? I've been building my tochserve images this way for about a month now and it works just fine. Otherwise probably best to close this issue.
