### ISSUE TITLE
Remove some redundant lines in model_loader

### ISSUE THREAD

**Issue by sadra-barikbin** [pytorch/serve#1844]
Hi, in model_loader, lines
https://github.com/pytorch/serve/blob/695b90e5acc8b1afc08cb0f73f8f58b8915b9b52/ts/model_loader.py#L113-L123

could be removed because service and entrypoint are constructed later again.

Besides, line 
https://github.com/pytorch/serve/blob/695b90e5acc8b1afc08cb0f73f8f58b8915b9b52/ts/model_loader.py#L129
is redundant as well because the same thing is done earlier in the code.

**Comment by msaroufim** [comment]
Thank you! Just triggered CI to see if we missed anything
