### ISSUE TITLE
Confusing Sequence Classification Example for HuggingFace 

### ISSUE THREAD

**Issue by mod-cpu** [pytorch/serve#1848]
### 📚 The doc issue

In the sequence classification example in examples/Huggingface_Transformers, the model results in a binary classification 'Accepted' or 'Not Accepted' as defined in `index_to_name.json`. The example query in `sample_text_captum_input.txt` will results in a 'Not Accepted' classification.. If I am new to torchserve and working through the example for the first time, this looks like a error - as in "the input that you gave was not accepted by the torchserve API" when really it is the correct classification from the model

### Suggest a potential alternative/fix

I would suggest either 

1. changing `index_to_name.json` to result in a different binary classification besides 'Accepted'/'Not Accepted' 
2. changing the documentation to make it explicitly clear that the binary classification will result in an 'Accepted'/'Not Accepted'  classification, and that 'Not accepted' is not some internal torchserve error

**Comment by msaroufim** [comment]
I agree! If you'd like to make a PR better names I'd be happy to merge it

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the fix will be like and pointing me to some resources to get started.

**Comment by msaroufim** [comment]
@sreenath-tm
1. Run this example https://github.com/pytorch/serve/tree/master/examples/Huggingface_Transformers
2. Think of better names to give to the labels instead of Accepted vs Not Accepted and change them here https://github.com/pytorch/serve/blob/master/examples/Huggingface_Transformers/index_to_name.json
3. Change
