### ISSUE TITLE
High utilization of hardware 

### ISSUE THREAD

**Issue by Vert53** [pytorch/serve#1851]
HI, I'm trying to use torchserve as a backend with a custom hardware setup. How do you suggest to run such that the hardware is maximally utilized? For example I tried using the benchmarks-ab.py script to test the server for throughput on resnet18 but only achieved ~200 requests per second (tried different batch sizes) while the hardware is capable of crunching at least 10,000 images per second.

Thanks for any help.

**Comment by msaroufim** [comment]
Hi @Vert53 I need a bit more context to properly answer your question. What kind of hardware are you using? Which model? The template in the Github issue is a good start. If for whatever reason you can't share more details and work for a custom hardware provider would be happy to chat more via email so lmk

**Comment by Vert53** [comment]
@msaroufim Chatting privately would be great as we are looking to support torchserve for our processor. Where can I contact you?

**Comment by msaroufim** [comment]
First Name last name at fb.com
