### ISSUE TITLE
I can't import torchserve

### ISSUE THREAD

**Issue by joemal1234** [pytorch/serve#1853]
### 🐛 Describe the bug

I can use torchserve in my terminal

I need access the ts folder in torchserve
currently i just took the code from here can copied it in. But i would rather it get it from the package directly

```
import torch
from ts.torch_handler.image_classifier import ImageClassifier
from torchvision import transforms
import torchvision.transforms as T
import torch.nn.functional as F
from ts.torch_handler.vision_handler import VisionHandler
from ts.utils.util  import map_class_to_label
```
```
I want to get ts form torchserve

import torchserve

ModuleNotFoundError: No module named 'torchserve'
```

### Error logs

ModuleNotFoundError: No module named 'torchserve'

### Installation instructions

poetry installed torchserve

### Model Packaing

taking custom handler which inherits from default of a handler in torchserve for classification

### Versions

-

### Repro instructions

-

**Comment by msaroufim** [comment]
Can you please try running 

`python ./ts_scripts/install_dependencies.py` first

**Comment by joemal1234** [comment]
just realised it works with import ts directly
