### ISSUE TITLE
fsspec for batch inference example

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#1891]
### 🚀 The feature

fsspec gives the ability to work with remote file systems like S3, GCS or Azure Blog storage with a single unified API

See this recent example for how broadly useful it is https://github.com/pytorch/data/pull/812

We can create an example with some large dataset in some remote cloud storage, stream that data to some local client which then creates requests to torchserve for some larger scale batch inference with a large batch size

### Motivation, pitch

See above

**Comment by kirkpa** [comment]
Hi @msaroufim, Can you add me as a collaborator/contributor to pytorch/serve project. I would like to submit PR for this issue. Thanks

**Comment by msaroufim** [comment]
Hi @kirkpa there is no need for that you can can create your own fork of pytorch/serve and then make a PR to this repo
