### ISSUE TITLE
passport of root

### ISSUE THREAD

**Issue by jack-gits** [pytorch/serve#1894]
### 🐛 Describe the bug

what's the password of root?

![image](https://user-images.githubusercontent.com/30545972/194740560-e69bb9ee-ae91-47c7-8a2d-367e29b11aa0.png)

### Error logs

![image](https://user-images.githubusercontent.com/30545972/194740564-da52e455-303a-4c47-90e8-ea9e79612598.png)

### Installation instructions

![image](https://user-images.githubusercontent.com/30545972/194740567-580d64ce-7e3c-4d8d-9b89-796ab928647d.png)

### Model Packaing

![image](https://user-images.githubusercontent.com/30545972/194740569-56801e82-6f59-428c-bc79-b6aa244cc5d4.png)

### Versions

最新版本

### Repro instructions

None

**Comment by msaroufim** [comment]
You need to login as the root user when you create your container. See this https://www.baeldung.com/ops/root-user-password-docker-container#2-using-the-root-user

**Comment by maaquib** [comment]
Resolving. @jack-gits Please reopen if this is still an issue
