### ISSUE TITLE
Multiple node inference

### ISSUE THREAD

**Issue by BDHU** [pytorch/serve#1900]
### 📚 The doc issue

I'm trying to find guides on how to deploy a single model across multiple nodes but find little information, Any potential hint will be appreciated!

**Comment by msaroufim** [comment]
You can setup a server per node and then create a load balancer yourself between them. This is kind of hard to do manually so I'd recommend checking out this cloudformation template https://github.com/pytorch/serve/tree/master/examples/cloudformation#multi-node-ec2-deployment-behind-elastic-loadbalancer-elb
