### ISSUE TITLE
gRPC List API error

### ISSUE THREAD

**Issue by somizgh** [pytorch/serve#1901]
hi
I have a problem when trying to get a list of registerd model from torchserve
I'm using both of REST API and gRPC API but only gRPC API don't work when using ListModelsRequest

in REST API
---
```python
requests.get("http://0.0.0.0:18091/models")
```
returns model list successfully

'models': [{'modelName': 'aaa', 'modelUrl': 'aaa.mar'}, {'modelName': 'bbb', 'modelUrl': 'bbb.mar'}]}

but in gRPC API
---
```python
def list_models(stub, t):
    params = {'next_page_token':int(t)}
    try:
        response = stub.ListModels(management_pb2.ListModelsRequest(**params))
        return response.msg
    except grpc.RpcError as e:
        logger.error("Failed to gRPC list models.")
        logger.info(str(e.details()))
        exit(1)

grpc_func.list_models(grpc_func.get_management_stub(), 0)
```

returns empty list
{
  "nextPageToken": "0",
  "models": []
}

I'm using exactly same proto file in 
https://github.com/pytorch/serve/tree/master/frontend/server/src/main/resources/proto

please help

**Comment by msaroufim** [comment]
Are you able to reproduce this error with 2 toy models for example our densenet example from our getting started guide?

**Comment by somizgh** [comment]
@msaroufim 
I followed this guide
https://github.com/pytorch/serve/blob/master/docs/getting_started.md

I use mac OS and run it using cpu

and changed some codes in torchserve_grpc_client.py to use listmodels
```python
def list_models(stub):
    params = {}
    try:
        response = stub.ListModels(management_pb2.ListModelsRequest(**params))
        return response.msg
    except grpc.RpcError as e:
        exit(1)


if __name__ == '__main__':
    # args:
    # 1-> api name [infer, register, unregister]
    # 2-> model name
    # 3-> model input for prediction
    args = sys.argv[1:]
    if args[0] == "infer":
        infer(get_inference_stub(), args[1], args[2])
    elif args[0] =="list":
        print(list_models(get_management_stub()))
        import requests
        print(requests.get("http://localhost:8081/models").content)
    else:
        api = globals()[args[0]]
        if args[0] == "register":
            api(get_management_stub(), args[1], args[2])
        else:
            api(get_management_stub(), args[1])
```

and typed 
```cmd
python ts_scripts/torchserve_grpc_client.py list
````
prints 
{
  "nextPageToken": "0",
  "models": []
}
b'{\n  "models": [\n    {\n      "modelName": "densenet161",\n      "modelUrl": "densenet161.mar"\n    }\n  ]\n}\n'

the result of gRPC above returns empty
and result of rest below returns "densenet161" successfully

**Comment by vdogmcgee** [comment]
response = stub.ListModels(management_pb2.ListModelsRequest(limit=100)

**Comment by somizgh** [comment]
@vdogmcgee 
it worked! 
thanks for your help
from torchserve api document below
limit - (optional) the maximum number of items to return. It is passed as a query parameter. The default value is 100.
I thought I do not had to specifiy limit argument, but Its not.

**Comment by vdogmcgee** [comment]
yes , its comments do not match the code , i  also try many times
