### ISSUE TITLE
Is it possible to use Torchserve for Huggingface transformers` VisionEncoderDecoderModel?

### ISSUE THREAD

**Issue by kangsan0420** [pytorch/serve#1902]
Hi, I'm wondering whether I can use Torchserve for the below model.
(I'd like to use it for TrOCR)

```python
from transformers import VisionEncoderDecoderModel
encoder_decoder = ('google/vit-base-patch16-224-in21k', 'kykim/bert-kor-base')
model = VisionEncoderDecoderModel.from_encoder_decoder_pretrained(*encoder_decoder)
```

**Comment by msaroufim** [comment]
@agunapal has recently looked at video models, it should be entirely possible - just need to expand on the huggingface custom handler to support this
