### ISSUE TITLE
Add steps for how to run gpu docker container

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#191]
Please add the steps for running GPU docker container in the docker readme. Steps should describe how to specify the gpus to be used on a multi-gpu machine 

eg 

`docker run --rm -it --gpus device=0 -p 8080:8080 -p 8081:8081  torchserve:v0.1-gpu-latest`

where device=0,1,2,3 selects GPUs indexed by ordinals 0,1,2 and 3, respectively. torchserve will see only these GPUs. If you specify device=all, then the torchserve will see all the available GPUs.

**Comment by fbbradheintz** [comment]
I just checked `docker/README.md`, and it looks like it contains the required examples for GPU usage. @aaronmarkham , I assigned to you so you can verify the content is up to standard - you can close this issue if you're satisfied.

**Comment by maaquib** [comment]
Steps added to README as part of #308
