### ISSUE TITLE
How can I change the inference_address?

### ISSUE THREAD

**Issue by Hanyu-Jin** [pytorch/serve#1911]
### 📚 The doc issue

I run the steps in [Getting Started]( https://github.com/pytorch/serve/blob/master/docs/getting_started.mdl). When I run the `torchserve --start --ncs --model-store model_store --models densenet161.mar`, I find that http://127.0.0.1:8080 is already in use and I cannot kill the process that uses the port.
I tried to change 8080 to 8085 in all files but it didn't work. The command torchserve still tried to bing to 127.0.0.1:8080. How can I change the inference_address?

**Comment by harshbafna** [comment]
@Hanyu-Jin : The default inference port for TorchServe is `8080`. Please refer the [advanced configuration](https://github.com/pytorch/serve/blob/master/docs/configuration.md#configure-torchserve-listening-address-and-port) on how to configure the listening address and port for TorchServe
