### ISSUE TITLE
Is it possible to use torch serve for deploying a Face Recognition model?

### ISSUE THREAD

**Issue by VikasNeoito** [pytorch/serve#1921]
Hi, I am wondering whether I can use TorchServe to deploy a PyTorch FaceNet model. How do I set something that needs to take an image, pass it through the model to get the encodings, and then compare them to every image encoding in the database and output the closest one.?
Which is the most efficient way to do this?

**Comment by samils7** [comment]
I deployed a similar workflow with torchserve and working pretty well.
This Workflow simply needs 3 components (torchserve models)

1. Face Detector: inputs an image path and download it (maybe save to disk for later use), detect faces and pass face bbox coordinates in a dictionary to the next model.
2. Feature Extractor: inputs the same image path and crops face boxes on it, batch all faces and extract face features. Adding feature vectors (embeddings) to dict and pass to the next.
3. Database-KNN: Gets embeddings and query to a database, (FAISS would be a good choice), returns nearest neighbors.

**Comment by maaquib** [comment]
@samils7 Thanks for the response and the details about your workflow details
@VikasNeoito Please reopen if you need any help in additiona to @samils7 suggestion
