### ISSUE TITLE
Nvidia images changed name so Docker build fails

### ISSUE THREAD

**Issue by EgonFerri** [pytorch/serve#1929]
### 🐛 Describe the bug

I followed the standard installation. 

I tried to run the code to build an image with cuda 11.1

 ./build_image.sh -bt dev -g -cv cu111 

I got an error. Debugging i noticed that the error was caused by the fact that nvidia changed images from 11.1 to 11.1.1.

You may want to correct this behaviour.

Have a nice day.

### Error logs

[+] Building 2.7s (5/5) FINISHED                                                                                                                            
 => [internal] load .dockerignore                                                                                                                      0.1s
 => => transferring context: 2B                                                                                                                        0.1s
 => [internal] load build definition from Dockerfile.dev                                                                                               0.1s
 => => transferring dockerfile: 4.32kB                                                                                                                 0.1s
 => resolve image config for docker.io/docker/dockerfile:experimental                                                                                  1.3s
 => docker-image://docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5                    0.6s
 => => resolve docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5                        0.0s
 => => sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5 1.69kB / 1.69kB                                                         0.0s
 => => sha256:3c244c0c6fc9d6aa3ddb73af4264b3a23597523ac553294218c13735a2c6cf79 528B / 528B                                                             0.0s
 => => sha256:b587adb6abfd8d6c87b1f649c2e924d53f148ae1c7f0ceaaded70b27b44dccb5 1.21kB / 1.21kB                                                         0.0s
 => => sha256:d7f0373ffb1d5ac3477b10ab7f91cba7c5df586c72e7e4a12649024efdc0d531 9.64MB / 9.64MB                                                         0.2s
 => => extracting sha256:d7f0373ffb1d5ac3477b10ab7f91cba7c5df586c72e7e4a12649024efdc0d531                                                              0.2s
 => ERROR [internal] load metadata for docker.io/nvidia/cuda:11.1-cudnn8-runtime-ubuntu18.04                                                           0.3s
------
 > [internal] load metadata for docker.io/nvidia/cuda:11.1-cudnn8-runtime-ubuntu18.04:
------
failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = docker.io/nvidia/cuda:11.1-cudnn8-runtime-ubuntu18.04 not found

### Installation instructions

git clone https://github.com/pytorch/serve.git

### Model Packaing

not correlated to model

### Versions

python serve/ts_scripts/print_env_info.py
/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
------------------------------------------------------------------------------------------
Environment headers
------------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.6.0
torch-model-archiver==0.6.0

Python version: 3.7 (64-bit runtime)
Python executable: /opt/conda/bin/python

Versions of relevant python libraries:
future==0.18.2
numpy==1.21.6
psutil==5.8.0
pytorch-lightning==1.2.9
requests==2.25.1
requests-oauthlib==1.3.0
torch==1.8.0+cu111
torch-model-archiver==0.6.0
torch-workflow-archiver==0.2.4
torchaudio==0.8.0
torchmetrics==0.2.0
torchserve==0.6.0
torchtext==0.9.0
torchvision==0.9.0+cu111
wheel==0.36.2
torch==1.8.0+cu111
torchtext==0.9.0
torchvision==0.9.0+cu111
torchaudio==0.8.0

Java Version:
**Warning: java not installed...

OS: Debian GNU/Linux 10 (buster)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: N/A
CMake version: version 3.13.4

### Repro instructions

git clone https://github.com/pytorch/serve.git
./build_image.sh -bt dev -g -cv cu111

### Possible Solution

Correct names.

**Comment by agunapal** [comment]
Thanks @EgonFerri  for reporting this. Looks like only 11.1.1 images are available now. Will update accordingly
