### ISSUE TITLE
gradle.properties version too low for M1 Mac when installing from source

### ISSUE THREAD

**Issue by GavinPHR** [pytorch/serve#1942]
### 🐛 Describe the bug

Dev install doesn't work currently on M1 Mac (MacOS 12.6) because of the version of grpc and protoc do not work with M1 Mac.

In `serve/frontend/gradle.properties`:
```
grpc_version=1.31.1
protoc_version=3.13.0
```

### Error logs

N/A

### Installation instructions

N/A

### Model Packaing

N/A

### Versions

------------------------------------------------------------------------------------------
Environment headers
------------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.6.0b20221103
torch-model-archiver==0.6.0b20221103

Python version: 3.10 (64-bit runtime)
Python executable: /Users/haoranpeng/mambaforge/bin/python

Versions of relevant python libraries:
captum==0.5.0
future==0.18.2
numpy==1.23.4
nvgpu==0.9.0
psutil==5.9.3
pygit2==1.10.1
pylint==2.6.0
pytest==7.2.0
pytest-cov==4.0.0
pytest-mock==3.10.0
requests==2.28.1
requests-toolbelt==0.10.1
torch==1.12.0
torch-model-archiver==0.6.0b20221103
torch-workflow-archiver==0.2.4b20221103
torchaudio==0.12.0
torchserve==0.6.0b20221103
torchtext==0.13.0
torchvision==0.13.0
transformers==4.11.0
wheel==0.37.1
torch==1.12.0
torchtext==0.13.0
torchvision==0.13.0
torchaudio==0.12.0

Java Version:

OS: Mac OSX 12.6 (arm64)
GCC version: N/A
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: N/A

Versions of npm installed packages:
**Warning: newman, newman-reporter-html markdown-link-check not installed...

### Repro instructions

Run the provided install from source command on M1 Mac `python ./ts_scripts/install_from_src.py`

### Possible Solution

The versions that worked for me:
```
grpc_version=1.49.1
protoc_version=3.18.0
```

**Comment by msaroufim** [comment]
Thanks for spotting this, wanna make a PR for it?

**Comment by lxning** [comment]
@GavinPHR  we don't have M1 at hand now. Thank you for testing and contribution.

**Comment by GavinPHR** [comment]
There are actually two additional problem I encountered when installing. Fixes for these are perhaps outside of our control, but list here anyway for reference:
- the rust compiler was required to install `tokenizers` (solved by `homebrew install rust`)
- didn't manage to install `pygit2` (after installing `libgit2`), so I removed it from requirements

**Comment by msaroufim** [comment]
I think the right solution here will be to add M1 as our custom runner per @lxning's ticket here https://github.com/pytorch/serve/issues/1678 - seems like demand is there. I will personally be getting an M1 hopefully sometime in January as well to try things out locally.
