### ISSUE TITLE
typo torschripted

### ISSUE THREAD

**Issue by Nishikoh** [pytorch/serve#1950]
### 📚 The doc issue

There are typo maybe.
https://github.com/pytorch/serve/blob/3a7187cf9b5a405e0a725654790afe24564b03dd/docs/index.md?plain=1#L3
https://github.com/pytorch/serve/blob/031c44c6cf7e0f4702baaa77462768ecc5a0db99/ts_scripts/spellcheck_conf/wordlist.txt#L88

### Suggest a potential alternative/fix

Fix to `torchscripted`  in `/docs/index.md`. And remove line in `wordlist.txt`.

**Comment by msaroufim** [comment]
This is correct usage as far as I know
