### ISSUE TITLE
Worker startTime doesn't get updated on retries

### ISSUE THREAD

**Issue by mbercin** [pytorch/serve#1986]
### 🐛 Describe the bug

When worker process dies and gets retried/respawned, `startTime` attribute of `WorkerThread` instance does not get updated since the instance is submitted as it is to the ModelManager.
https://github.com/pytorch/serve/blob/36a8cb834eaf0e801a4dba938bb65d14e6db90de/frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java#L157
https://github.com/pytorch/serve/blob/36a8cb834eaf0e801a4dba938bb65d14e6db90de/frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java#L441-L442 

### Error logs

There is no crash, but an unexpected behavior when Model workers are queried and startTimes are inspected.

### Installation instructions

Installed 0.4.2 via pip

### Model Packaing

N/A

### config.properties

N/A

### Versions

0.4.2

### Repro instructions

- Kill a worker a few minutes after it is launched
- Wait for the worker to get retried/replaced
- Check it's `startTime`

### Possible Solution

When the WorkerThread instance is getting submitted to the ModelManager, `startTime` class attribute can be modified with a new timestamp.

**Comment by msaroufim** [comment]
afaik that's by design, we don't want you to worry about specific workers since those are expected to fail. Perhaps @maaquib or @lxning have more context to share

**Comment by msaroufim** [comment]
Will close for now, please reopen if you have any further questions
