### ISSUE TITLE
Unexpected nvidia-smi response.

### ISSUE THREAD

**Issue by jack-gits** [pytorch/serve#2000]
### 🐛 Describe the bug

I want to use the docker in a normal EC2 without GPU, but it raise an error Unexpected nvidia-smi response:

docker image version: pytorch/torchserve:0.6.0-gpu

### Error logs

java.lang.AssertionError: Unexpected nvidia-smi response.
	at org.pytorch.serve.util.ConfigManager.getAvailableGpu(ConfigManager.java:740)
	at org.pytorch.serve.util.ConfigManager.<init>(ConfigManager.java:207)
	at org.pytorch.serve.util.ConfigManager.init(ConfigManager.java:285)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:83)

### Installation instructions

FROM pytorch/torchserve:0.6.0-gpu

### Model Packaing

FROM pytorch/torchserve:0.6.0-gpu

### config.properties

inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
number_of_netty_threads=10
job_queue_size=100
model_store=/home/model-server/model-store
workflow_store=/home/model-server/model-store
async_logging=true
vmargs=-Dlog4j.configurationFile=./log4j2.xml
default_workers_per_model=2
limit_max_image_pixels=false

### Versions

pytorch/torchserve:0.6.0-gpu

### Repro instructions

pytorch/torchserve:0.6.0-gpu

**Comment by msaroufim** [comment]
How did you launch your docker image? Does it have access to your GPU? If you just ssh into your container does `nvidia-smi` work?

**Comment by jack-gits** [comment]
My host don't have GPU, still need nvidia-smi?

**Comment by jack-gits** [comment]
![image](https://user-images.githubusercontent.com/30545972/203686084-d529c631-6b71-4faf-9db7-002404e3f661.png)

**Comment by jack-gits** [comment]
how to let "getAvailableGpu" return 0 if host don't have GPU?

**Comment by jack-gits** [comment]
I get a workaround solution that export CUDA_VISIBLE_DEVICES=','. 
it works.
do you have any other better solution?

**Comment by lxning** [comment]
@jack-gits set environment var "CUDA_VISIBLE_DEVICES" via option ["-e"](https://docs.docker.com/engine/reference/commandline/run/) when you start docker.
