### ISSUE TITLE
object_detector default handler does not seem to be using multiple GPUs

### ISSUE THREAD

**Issue by fbbradheintz** [pytorch/serve#201]
The other default handlers seem to work on many GPUs without difficulty, but CloudWatch is telling me that only GPU 0 is being used by `object_detector`.

**Comment by fbbradheintz** [comment]
Covered by @harshbafna in #265, requested changes pending.

**Comment by mycpuorg** [comment]
Closing this because https://github.com/pytorch/serve/pull/265

**Comment by mycpuorg** [comment]
Reopening because the changes have not made it to `master` yet
