### ISSUE TITLE
Workers vs Models

### ISSUE THREAD

**Issue by david-waterworth** [pytorch/serve#2023]
### 📚 The doc issue

I have a single model, say `text_classifier`, and I configured it as follows:

```
default_workers_per_model=8
models = {\
    "text_classifier": {\
      "1.0.0": {\
        "defaultVersion": true,\
        "marName": "text_classifier.mar",\
        "minWorkers": 1,\
        "maxWorkers": 8,\
        "batchSize": 1,\
        "maxBatchDelay": 500,\
        "responseTimeout": 120\
      }\
    }\
  }
```

I expect this will create 8 workers for the same model - i.e. 8 separate processes and the ability to handle 8 requests in parallel?

Looking at the logs, though, I don't see anything indicating that there's more than a single instance of `text_classifier` running - am I misunderstanding what worker is? Are workers more like threads?

I also don't see any change in throughput when I switch from 1 to 8 workers. I'm sending requests using async/await so in theory they should be in parallel. At startup I see a single message

2022-12-06T16:22:10,103 [INFO ] W-9000-text_classifier_1.0.0-stdout MODEL_LOG - Torch worker started.

and the model log contains a single message

2022-12-06T16:22:10,102 [INFO ] W-9000-text_classifier_1.0.0-stdout MODEL_LOG - [PID]633535

All the evidence I can see indicates that there's only one handler - i.e. when I ran two copies of my test client in separate shells, the throughput of each was exactly half what I observed with a single client running. And when I ran the server with 1 rather than 8 workers the throughput was exactly the same?

**Comment by msaroufim** [comment]
Try changing  `"minWorkers": 1,` to 8 and you should be able to see separate processes in `top` or `nvidia-smi`. If your load is low then you should expect a smalleer number of workers to actually be instantiated

**Comment by david-waterworth** [comment]
Thanks @msaroufim when I set "minWorkers" to 8 I can see it's utilising the CPU much more heavily and the throughput increases by a factor of approximately 5 times.

But then why is it not increasing the number of workers when minWorkers is 1 and maxWorkers is 8 in the first case? And `default_workers_per_model=8` didn't seem to help either?

**Comment by msaroufim** [comment]
> Thanks @msaroufim when I set "minWorkers" to 8 I can see it's utilising the CPU much more heavily and the throughput increases by a factor of approximately 5 times.

Makes sense there's diminishing returns from too many workers depending on the model size

> But then why is it not increasing the number of workers when minWorkers is 1 and maxWorkers is 8 in the first case? And default_workers_per_model=8 didn't seem to help either?

Was this for a microbenchmark or did you try a significant scale?

**Comment by david-waterworth** [comment]
Depends on how you define scale; I'm using client batching. I'm sending batches of 128, and the total task contains 37,700 records. I'm trying to send batches as fast as possible (ie 37700//128 requests). The server is configured with a batch size of 1.

I adapted the code from https://github.com/pytorch/serve/issues/1235#issuecomment-1318658202 to ensure that the batches are sent without waiting for the response. I'm not sure if this can be improved, but it sends requests at a much higher rate than a naive synchronous loop or other examples I found that used futures. It's certainly enough to keep eight workers busy, but as I mentioned, it doesn't appear to cause the front end to increase the number of workers automatically.

**Comment by namannandan** [comment]
If the model is loaded at the time of starting torchserve, for example:
```
torchserve --start --model-store <model_store_dir_path> --ts-config <cutom_config_path> --models text_classifier=text_classifier.mar
```
or custom configuration file has the line ```load_models=text_classifier=text_classifier.mar```
then, the ```minWorkers``` and ```maxWorkers``` if specified in the custom configuration will override the value specified for ```default_workers_per_model```. I believe that is the reason you see that torchserve scales up the number of workers to ```minWorkers``` which is set to ```1```.

Whereas, if torchserve is started without loading the model:
```
torchserve --start --model-store <model_store_dir_path> --ts-config <cutom_config_path>
```
and then the model is registered without specifying ```initial_workers```:
```
 curl -X POST "http://localhost:8081/models?url=text_classifier.mar&model_name=text_classifier&version=1.0"
```
then both ```minWorkers``` and ```maxWorkers``` will use the value of ```default_workers_per_model``` causing ```8``` workers to be created.

**Comment by namannandan** [comment]
On the topic of automatically scaling the actual number of workers between the fixed configured values of ```minWorkers``` and ```maxWorkers```, I believe torchserve does not do this currently.

There are essentially 3 scenarios:

1. If the actual number of workers lies in-between ```minWorkers``` and ```maxWorkers``` then, no change is made to the actual number of workers.
2. When scaling up, i.e increasing ```minWorkers```, the actual number of workers follows the value of ```minWorkers```.
3. When scaling down, i.e decreasing ```maxWorkers```, the actual number of workers follows the value of ```maxWorkers```.

(Reference: [code](https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/wlm/WorkLoadManager.java#L137))

**Comment by david-waterworth** [comment]
Thanks @namannandan - I see how it works now.

**Comment by cjidboon94** [comment]
@namannandan @msaroufim  Does this mean that if you set minWorkers =1 and maxWorkers =5 for a model and initialize it with 1 worker, that no matter the load it will never actually scale up to 5 workers?
