### ISSUE TITLE
enable_envvars_config appears to do nothing

### ISSUE THREAD

**Issue by fbbradheintz** [pytorch/serve#204]
AFAICT, the `enable_envvars_config` config file setting does nothing. The `LOG_LOCATION`, `METRICS_LOCATION`, and `TS_CONFIG_FILE` env vars are all picked up by TorchServe on startup. I tried this three ways in my `config.properties`:

* No `enable_envvars_config` entry
* `enable_envvars_config=true`
* `enable_envvars_config=false`

In all three trials, the env var behavior was as it should be for the case the docs describe for `enable_envvars_config=true`.

**Comment by mohammedayub44** [comment]
I'm trying to find the same. Where are the log and metrics files generated and stored when i start the server ?

**Comment by shivamshriwas** [comment]
> I'm trying to find the same. Where are the log and metrics files generated and stored when i start the server ?

@mohammedayub44  log and metrics files are generated in logs folder, located at path from where torchserve was started.
logs and metrics location can be configured by env variable, LOG_LOCATION and METRICS_LOCATION.

These can also be configured through custom log4j.properties file, please refer [logging.md](https://github.com/pytorch/serve/blob/master/docs/logging.md) for more details.

**Comment by shivamshriwas** [comment]
@fbbradheintz 
when enable_envvars_config property is set true , all the properties mentioned in config.properties only can be controlled using this flag.

Note:
for setting these as env this format should be used "TS_<PROPERTY>"
eg: inference_address -> TS_INFERENCE_ADDRESS

we will be updating documentation for the same.

**Comment by mohammedayub44** [comment]
@shivamshriwas Thanks will take a look.

**Comment by dhaniram-kshirsagar** [comment]
Related PR has been merged hence closing it
