### ISSUE TITLE
Docker 0.7 Security issues 

### ISSUE THREAD

**Issue by jack-gits** [pytorch/serve#2042]
### 🐛 Describe the bug

we found some security issues base of 0.7.0 release.

below is the founds:
![image](https://user-images.githubusercontent.com/30545972/208887170-07dd835a-46cd-4b04-b777-748f292a3e3d.png)

### Error logs

None

### Installation instructions

FROM pytorch/torchserve:0.7.0-gpu

### Model Packaing

FROM pytorch/torchserve:0.7.0-gpu

### Versions

0.7.0

### Repro instructions

None

**Comment by msaroufim** [comment]
Which tool are you using to find these vulnerabilities?

For the 0.7 release we looked at issues highlighted by
* https://deps.dev/pypi/torchserve
* https://github.com/pytorch/serve/security/dependabot

Happy to track more

**Comment by jack-gits** [comment]
@msaroufim we're using AQUA CLOUD NATIVE.

by the way, I can't open https://github.com/pytorch/serve/security/dependabot

**Comment by jack-gits** [comment]
@msaroufim do you have plan to fix these security issues?

**Comment by msaroufim** [comment]
Yeah but I'm on PTO and so is most of the team until the first week of January. Will find an owner then

**Comment by msaroufim** [comment]
I just enabled docker security scanning on dockerhub and should have the first report by tomorrow's nighlies

**Comment by msaroufim** [comment]
I'm not sure what the exit criteria would be since we don't use AQUA CLOUD NATIVE. I just enabled Snyk support and it looks like a large chunk of issues go away if we just use `ubuntu:rolling` instead, is that sufficient for you for now? #2064 #2065 #2066

These are all the security issues I'm tracking for next release https://github.com/pytorch/serve/issues?q=is%3Aissue+is%3Aopen+label%3Asecurity if there's anything more specific that we have to fix

**Comment by jack-gits** [comment]
can you provide a docker image base on ubuntu:rolling now? I can help test it by AQUA CLOUD NATIVE.

**Comment by jack-gits** [comment]
@msaroufim is it possible to provide a temporary docker image for security scanning?

**Comment by msaroufim** [comment]
Pushed it here for you https://hub.docker.com/repository/docker/marksaroufim/torchserve/general it's the latest GPU image

Just for reference you can build our docker images locally, this is the exact command we use for our nightlies 

https://github.com/pytorch/serve/blob/master/docker/docker_nightly.py#L37

with the full instructions here https://github.com/pytorch/serve/tree/master/docker

So for example in this case I ran 

```
git checkout snyk-fix-e1077ba036875975fd0ab47e0f5bffb7
./build_image.sh -bt dev -g -cv cu117 -t msaroufim/torchserve:gpu-test
```

So feel free to test this but in the future it might be more efficient for you to build locally, run whatever tests you like and then open up a PR if you see any issues

**Comment by jack-gits** [comment]
great, thanks.

**Comment by msaroufim** [comment]
Next nightlies should be using ubuntu:rolling

**Comment by jack-gits** [comment]
@msaroufim 
I'm trying to fix the security issues and PR. https://github.com/pytorch/serve/pull/2081

**Comment by jack-gits** [comment]
There're still many security issues, for example linux-libc-dev, I have no idea how to fix it.

![image](https://user-images.githubusercontent.com/30545972/213394268-22f0e378-a840-4d29-8a45-7cd709d182c5.png)

**Comment by jack-gits** [comment]
@msaroufim any suggestion?
