### ISSUE TITLE
Docs are not complete

### ISSUE THREAD

**Issue by MohamedAliRashad** [pytorch/serve#2048]
### 📚 The doc issue

the `vision-handler` and `text-handler` are not presented:
https://pytorch.org/serve/api/ts.torch_handler.html#ts-torch-handler-text-handler-module

### Suggest a potential alternative/fix

Provide good docs

**Comment by sekyondaMeta** [comment]
Closing issue as packages in question (as well as other ts.handler packages) are now documented.
