### ISSUE TITLE
Ubuntu 20.04 image has been very flaky

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#2053]
### 🐛 Describe the bug

The Ubuntu 20.04 has been very flaky in CI while it should be our most reliable job. Some options of what we can do is
1. Downgrade back to 18.04 which will have some incompatibilities with our nightly docker builds but are not a deal breaker
2. Use a custom image with a large disk: Note the flakes might be similar to the flakes we observed for Windows but never diagnosed properly
3. Use Ubuntu 22.04: I suspect the same issue will occur but worth investigating more

@ankithagunapal do you have bandwidth to take a look?

### Error logs

See any recent CI run

### Installation instructions

n

### Model Packaing

n

### Versions

n

### Repro instructions

n

**Comment by agunapal** [comment]
So, I tried with ubuntu 22.04. Ran CI twice. 1 Pass, 1 Fail. I propose just updating the CI github action to ubuntu 18.04. Will try it out and send a PR
