### ISSUE TITLE
Add a system diagram

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#206]
Add a system architecture diagram in the docs that explains the inner workings of torchserve and its components - the front end clients, job processing queue, backend workers. Details should also cover the details about the interplay between the number_of_netty_threads, netty_client_threads, workers/model, job_queue_size.

**Comment by aaronmarkham** [comment]
Background/proposal info with some of this info (surely needs updating, but better than nothing): 
* https://github.com/pytorch/pytorch/issues/27610
* https://torchserve-docs.s3-us-west-2.amazonaws.com/docs/torchserve_architecture_v0.pdf

**Comment by fbbradheintz** [comment]
I have some system diagrams coming, one of which may fill the need here. Will report back once i have them.

**Comment by fbbradheintz** [comment]
Will this do?

![AWS_pytorch_v2-01](https://user-images.githubusercontent.com/28989374/80761436-6ab0a600-8aef-11ea-937a-b52a61c38960.jpg)

**Comment by maaquib** [comment]
Will create another PR for adding diagrams for netty/worker interplay

**Comment by csukuangfj** [comment]
> * https://torchserve-docs.s3-us-west-2.amazonaws.com/docs/torchserve_architecture_v0.pdf

@aaronmarkham 
The link to the pdf file is broken. Could you update it? Thanks!

**Comment by msaroufim** [comment]
You can check out docs/internals.md to see the diagram
