### ISSUE TITLE
Remove dependency on future

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [pytorch/serve#2063]
### 🐛 Describe the bug

There is an advisory due to the future package: https://github.com/advisories/GHSA-v3c5-jqr6-7qm8
It seems to me like the _future_ package serves no purpose anymore. See discussion in https://github.com/PythonCharmers/python-future/issues/612.
Is it possible to solve the security problem by just removing the dependency on future and doing a new serve release?

In our project executing `poetry show --tree --why future` we get the output:
```
torchserve 0.6.1 TorchServe is a tool for serving neural net models for inference
└── future *
```

### Error logs

See above links.

### Installation instructions

poetry

### Model Packaing

NA

### config.properties

NA

### Versions

0.6.1

### Repro instructions

NA

### Possible Solution

Perhaps remove `future` line from dependencies.

**Comment by msaroufim** [comment]
Yeah this makes sense, we are doing a security centric release next so this is timely
