### ISSUE TITLE
Multiple images per request

### ISSUE THREAD

**Issue by spyrosavl** [pytorch/serve#2068]
### 🚀 The feature

I could not find anything related in the docs, so I am asking here. Is it possible to post a batch of images for inference in a single request and then aggregate the result during postprocessing?

### Motivation, pitch

I want to pass a batch of images through a model, get an embedding for each image, and then get the mean of the embeddings as a response.

**Comment by agunapal** [comment]
@spyrosavl Please find an example for batch processing here: https://github.com/pytorch/serve/tree/master/examples/image_classifier/resnet_152_batch and https://github.com/pytorch/serve/tree/master/examples/image_classifier/near_real_time_video

**Comment by spyrosavl** [comment]
Thank you @agunapal!
