### ISSUE TITLE
Model zoo migration

### ISSUE THREAD

**Issue by namannandan** [pytorch/serve#2088]
### Summary
The Torchserve model zoo, i.e the S3 bucket (https://torchserve.s3.amazonaws.com/) will need to be migrated across AWS accounts. Since S3 bucket names are required to be unique across accounts and regions, the torchserve bucket will need to be deleted in the source account and then created in the target account. S3 bucket name reuse could potentially have a delay of around 2 hours. This is expected to cause the model zoo to be unavailable during the migration. Ideally, once the migration is successful, no change will need to be made to the Torchserve code or other references to the model zoo artifacts since the goal is to replicate the S3 bucket name. In the case that there are any issues or delays with the migration, a backup bucket has been prepared which can be used only if required.

### Impact
The following resources will be impacted while the migration is in progress:
1. Sanity tests that use artifacts from the model zoo
2. CI stages that require model zoo artifacts. This will prevent PRs from being merged.
3. Nightly regression runs
4. References to model zoo:
    a. https://pytorch.org/serve/model_zoo.html
    b. https://github.com/pytorch/serve/blob/master/docs/model_zoo.md

### Schedule
Duration: 3 hours
Expected start time: Wednesday, 25 January 2023, 9:00 AM PST
Expected end time: Wednesday, 25 January 2023, 12:00 PM PST

**Comment by namannandan** [comment]
If there are any concerns regarding the schedule of this migration or any suggestions/comments about the migration process please feel free to share them.

**Comment by msaroufim** [comment]
LGTM, I think we should start this ASAP since we're planning a security centric release at the end of the month. So a start date of Jan 24 or 25 seems like the most reasonable next step to me

**Comment by namannandan** [comment]
Sounds good, updated the schedule to start migration on 25th morning.

**Comment by namannandan** [comment]
Starting model zoo migration at Wednesday, 25 January 2023, 9:15 AM PST

**Comment by namannandan** [comment]
Successfully completed migration on Wednesday, 25 January 2023, 11:45 AM PST.
Checking sanity test, regression tests and other references to model zoo to ensure there is no impact.

**Comment by namannandan** [comment]
Sanity test:
- CPU: [cpu_sanity_post_model_zoo_migration_log.txt](https://github.com/pytorch/serve/files/10504694/cpu_sanity_post_model_zoo_migration_log.txt)
- GPU: [gpu_sanity_post_model_zoo_migration_log.txt](https://github.com/pytorch/serve/files/10504697/gpu_sanity_post_model_zoo_migration_log.txt)

Regression test:
- CPU: [cpu_regression_post_model_zoo_migration_log.txt](https://github.com/pytorch/serve/files/10504699/cpu_regression_post_model_zoo_migration_log.txt)
- GPU: [gpu_regression_post_model_zoo_migration_log.txt](https://github.com/pytorch/serve/files/10504701/gpu_regression_post_model_zoo_migration_log.txt)

Other references to model zoo artifacts:
- https://pytorch.org/serve/model_zoo.html: Working as expected
- https://github.com/pytorch/serve/blob/master/docs/model_zoo.md: Working as expected
