### ISSUE TITLE
Wildcard support for torch-model-archiver --extra-file parameter (better Large Language Model support)

### ISSUE THREAD

**Issue by SaschaHeyer** [pytorch/serve#2111]
### 🚀 The feature

The torch-model-archiver takes a parameter --extra-file that takes a comma-separated list of additional files. I propose extending it to support wildcards. 

Instead of
````

--extra-files ",/home/model-server/pytorch_model-00001-of-00089.bin, /home/model-server/pytorch_model-00002-of-00089.bin, /home/model-server/pytorch_model-00003-of-00089.bin, /home/model-server/pytorch_model-00004-of-00089.bin
... list continues till all shards are included
````

I propose a wildcard solution

````

--extra-files ",/home/model-server/**.bin
````

_** | Match any number of characters across directory boundaries. When used as part of a local file path, the ** wildcard should always be immediately preceded by a directory delimiter. For example, directory/**.txt is valid, but directory/abc** is not._

### Motivation, pitch

Large Language Models like Bloom, for example, consist of hundreds of sharded model files. Integrating all the model files as extra-files parameters is a cumbersome process. Wildcard support would help to solve this quickly.

**Comment by msaroufim** [comment]
This makes a lot of sense and is a good first issue if someone wants to tackle it

**Comment by HamidShojanazeri** [comment]
@SaschaHeyer , its a great suggestion currently using [zipped files](https://github.com/pytorch/serve/blob/master/examples/Huggingface_Largemodels/custom_handler.py#L52)  is the workaround, adding this feature aligns with our work more on distributed model inference as well.

**Comment by gustavhartz** [comment]
Hi @SaschaHeyer 

I would like to tackle it. I was thinking of utilizing the [glob](https://docs.python.org/3/library/glob.html) module to allow for unix style search. I would add the feature as a third condition in the file processing starting [here](https://github.com/pytorch/serve/blob/master/model-archiver/model_archiver/model_packaging_utils.py#L159). I don't know if it should also include a new test, but from reading through the existing [PyTests](https://github.com/pytorch/serve/blob/master/test/pytest/test_model_archiver.py) it does not seem like any of the existing ones test this functionality.

**Comment by SaschaHeyer** [comment]
Hi @gustavhartz 
like the idea of using glob as this is what a lot of people are used to.
Wanna unite work on that?

**Comment by gustavhartz** [comment]
Sure! I will make a draft for it and ping you once it's done. Will have some time tonight.

**Comment by gustavhartz** [comment]
@SaschaHeyer wrote a solution for it where all the "," separated paths are passed through glob. 1 line of code is changed. Will make a PR for it once #2132 is merged and I can commit.

**Comment by gustavhartz** [comment]
@SaschaHeyer Let me know what you think. Very simple modification and adds the full functionality of glob while maintaining the original function.
