### ISSUE TITLE
pytorch/torchserve-kfs:0.7.1 No module named 'tornado'

### ISSUE THREAD

**Issue by lnguyen46** [pytorch/serve#2123]
### 🐛 Describe the bug

No module named 'tornado' on image pytorch/torchserve-kfs:0.7.1

The tornado package is needed for using with KServe.

### Error logs

```
File "/home/model-server/kserve_wrapper/__main__.py", line 7, in <module>
from TorchserveModel import TorchserveModel
File "/home/model-server/kserve_wrapper/TorchserveModel.py", line 9, in <module>
import tornado.web
ModuleNotFoundError: No module named 'tornado'
```

### Installation instructions

Install torchserve from source: No
Using Docker: Yes. Pulling the image from dockerhub.

### Model Packaing

.

### Versions

.

### Repro instructions

```
docker pull pytorch/torchserve-kfs:0.7.1

docker run -it --rm pytorch/torchserve-kfs:0.7.1 bash

pip show tornado
```

**Comment by msaroufim** [comment]
Ok there are 2 separate problems here
1. we don't test our kserve code in CI and really should
2. I'm not convinced we need the tornado dependency if it's only use case is raising HTTP errors

But the workaround should be easy, either build the kserve images from scratch by adding tornado here https://github.com/pytorch/serve/blob/master/kubernetes/kserve/requirements.txt

Or create a new dockerfile with this in it

```
FROM pytorch/torchserve-kfs:0.7.1
RUN pip install tornado
```

Build the image and then run it
