### ISSUE TITLE
Reduce CUDA context overhead with NVIDIA MPS in multi worker deployments

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#2128]
## Proposal

Since the Volta Architecture, NVIDIA has added support for Multi-Process Service (MPS) https://docs.nvidia.com/deploy/mps/index.html

We should seriously consider running the MPS daemon on our benchmark machines and recommend it in our docs `nvidia-cuda-mps-control –d`. Enabling this feature is just that one liner and should not require any code changes to torchserve but we could also easily make `torchserve` CLI enable this command before it does the rest if it sees a GPU deployment.

![image](https://user-images.githubusercontent.com/3282513/218633275-5bdaff0b-0e5f-4f56-9859-18dbf8d553d0.png)

## Problem

Today in TorchServe when we launch multiple workers on GPU we end up having a CUDA context per GPU. This is obviously fine for the single-worker use case but for multiple workers consider that each CUDA context is about 500MB https://discuss.pytorch.org/t/cuda-context-size-per-process/79976 which for 4 workers means 2GB and 32 workers means 16GB!

## Why do this work

Using less memory means
* More workers so more throughput
* More models
* Bigger models

So the exit criteria would be to run an experiment with a typical model like BERT or our builtin vision handler, then for workers=1,2,4,8,16 measure the corresponding memory overhead with nvidia-smi after running  `nvidia-cuda-mps-control –d`. The experiment will be a success if we see the memory overhead reducing as we increase the number of workers.

This should be a quick experiment and we might get pleasantly surprised by large memory savings

## Alternative solutions
* We can do selective builds and avoid packaging kernels we don't need https://github.com/pytorch/pytorch/issues/93955
* We can use MIG on Ampere architecture to isolate GPU resources but MIG still has the problem of needing to share CUDA contexts. Although I'm potentially interested in seeing how MIG interacts with MPS

**Comment by lxning** [comment]
@msaroufim AWS internally investigated MPS in 2020. The major drawback is MPS is only able to support 48 processes. This is a major blocker for TorchServe python backend to support multi-workers and multi-models.

**Comment by msaroufim** [comment]
Do you mind sharing more? If we follow our existing docs then it suggests to set `#workers = #gpu < 8 << 48`

**Comment by mreso** [comment]
Delivered through #2184 (see https://github.com/pytorch/serve/blob/master/docs/mps.mdfor information how to implement and benchmarks)
