### ISSUE TITLE
problem deploying with service_envelope=json

### ISSUE THREAD

**Issue by veronikayurchuk** [pytorch/serve#2155]
I wrote a custom handler that receives a list of dictionaries in `preprocess` method with the following structure
```
request = {
    'metadata': str,
    'image_0': bytes,
    'image_1': bytes
}
```
and processes it correspondingly.

Next, I wanted to run my model on Vertex AI following this [guide](https://cloud.google.com/blog/topics/developers-practitioners/pytorch-google-cloud-how-deploy-pytorch-models-vertex-ai), which includes adding `service_envelope=json` to `config.properties`. As far as I understood, it leads to the change of request structure.
Following the new schema, my request looks like
```
{
	"instances": [{
			"image_0": {
				"b64": 'str'
			}
		},
		{
			"image_1": {
				"b64": 'str'
			}
		}
	],
	"parameters": {}
}
```
I debugged locally my custom handler using [this 'envelope convertor'](https://github.com/pytorch/serve/blob/b8f52d8047071138f3c5d380feeae2782b3e4c25/ts/torch_handler/request_envelope/json.py#L37) as an intermediate step and sent the output of `_from_json` to my `preprocess`. Everything looked correct and `preprocess` in my custom handler received a list of `dicts`.

However, when I run docker (base is pytorch/torchserve:0.7.0-gpu) as in the blog post and send a request it doesn't work. I see that the data that I receive in `preprocess` is a list of `ints`, not a list of `dicts` as I expected.

Could you please point out where I missing something?

**Comment by agunapal** [comment]
@veronikayurchuk  you can refer to this example for passing dictionary in TorchServe https://github.com/pytorch/serve/blob/master/examples/image_classifier/near_real_time_video/request.py#L116

**Comment by veronikayurchuk** [comment]
Hi, @agunapal !

Thanks for your reply. That is exactly what I used for sending the request
```
def get_images_dict(path):
    images_dict = {}
    images_pathes = sorted([os.path.join(path, x) for x in os.listdir(path) if x.endswith(".jpg")])
    for (i, image_path) in enumerate(images_pathes):
        with open(image_path, 'rb') as f:
            image_read = f.read()
            image_64_encode = base64.b64encode(image_read)
            bytes_array = image_64_encode.decode("utf-8")
            images_dict["image_{}".format(i)] = bytes_array
    return images_dict

request = {"instances": [{k: {"b64": v}} for k, v in get_images_dict(path).items()], 
                "parameters": request_metadata}
```

**Comment by agunapal** [comment]
@veronikayurchuk Could you please share your handler code.

**Comment by veronikayurchuk** [comment]
@agunapal sure.

I have included a reference here.
But it seems that the problem occurs even earlier, as the data that I receive in my `preprocess` is already a list of ints, not a list of dicts.

Before adding `service_envelope=json`, my `preprocess` received a list of dicts and worked correctly.


```
@dataclass
class ImageHolder:
    array: np.ndarray

    @classmethod
    def from_content(cls, content: bytes):
        buf = io.BytesIO(content)
        image = Image.open(buf).convert('RGB')
        return ImageHolder(array=np.array(image))


class Custom_Model(BaseHandler):
    def preprocess(self, requests: List):
        """
        :param requests: expects a list of requests. Each request is a dict
        request = {
            "metadata": str,
            "image_0": bytes,
            "image_1" bytes
        }
        :return:
        """
        print("________________Received {} request in batch________________".format(len(requests)))
        batch_request: List[tuple[List, EventMetadata]] = []
        for k, request in enumerate(requests):
            image_arrays = []
            metadata = None
            for i in sorted(list(request.keys())):
                if i.startswith("image"):
                    image_bytes = request[i]
                    image_array = ImageHolder.from_content(image_bytes)
                    image_arrays.append(image_array)
                elif i == 'metadata':
                    data = request[i]
                    metadata = json.loads(data)
                    metadata = EventMetadata(**metadata)
            output = (image_arrays, metadata)
            print("________________Received {} images in request________________".format(len(image_arrays)))
            batch_request.append(output)
        return batch_request
```

**Comment by agunapal** [comment]
This might be a bug
@lxning Has this been implemented.

Looking at the code here, seems like we always read the data as bytes

https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/util/codec/ModelRequestEncoder.java#L53:L58

@veronikayurchuk  Is there a specific reason why you need to use service_envelope.

**Comment by veronikayurchuk** [comment]
@agunapal service_envelope is mandatory to deploy torch serve in vertex AI. `[see here](https://pytorch.org/serve/request_envelopes.html?highlight=envelop)`

**Comment by veronikayurchuk** [comment]
The issue was on my side. I deeply apologize for the distraction.

**Comment by agunapal** [comment]
@veronikayurchuk No problem, do you mind sharing what the problem was?

**Comment by veronikayurchuk** [comment]
Sure. The problem was related to the way I was sending requests.
I am using `aiohttp` library and I incorrectly sent a request using
```
async with session.post('http://35.231.31.183:7080/predictions/fa', data=request_data) as resp
``` 
instead of 
```
async with session.post('http://35.231.31.183:7080/predictions/fa', json=request_data) as resp
```
