### ISSUE TITLE
 Custom API documentation is missing

### ISSUE THREAD

**Issue by kkashilk** [pytorch/serve#2204]
### 📚 The doc issue

The `serving sdk` and `plugins` links are broken here - https://pytorch.org/serve/FAQs.html#how-can-i-add-a-custom-api-to-an-existing-framework

Steps to reproduce the behavior (if applicable):

1. Go to https://pytorch.org/serve/FAQs.html#how-can-i-add-a-custom-api-to-an-existing-framework
2. Click on [serving sdk](https://pytorch.org/serving-sdk) or [plugins](https://pytorch.org/plugins) links
3. See 404 error

### Suggest a potential alternative/fix

Add info that's available here - https://github.com/pytorch/serve/tree/master/plugins

**Comment by lxning** [comment]
@msaroufim i checked the links in [FAQ](https://github.com/pytorch/serve/blob/master/docs/FAQs.md#how-can-i-add-a-custom-api-to-an-existing-framework) . it works fine.

It seems https://pytorch.org/serve/FAQs.html#how-can-i-add-a-custom-api-to-an-existing-framework needs sync up. could you help?

**Comment by sekyondaMeta** [comment]
@msaroufim Can you assign this issue to me. I might be able to fix it in the same way I did the others although this is a different issue.
