### ISSUE TITLE
Perform batched inference

### ISSUE THREAD

**Issue by BDHU** [pytorch/serve#2217]
### 📚 The doc issue

The documentation ([https://pytorch.org/serve/batch_inference_with_ts.html](https://pytorch.org/serve/batch_inference_with_ts.html)) explains how to set up torch serve for batched inference. But it's really counter-intuitive when the example only uses one image, which defeats the purpose of batching and makes it really confusing for starters to understand how to do batching.

### Suggest a potential alternative/fix

Use 2 or more images to demonstrates how to properly perform batched inference using serve.

**Comment by agunapal** [comment]
@BDHU You can find an example here https://github.com/pytorch/serve/tree/master/examples/image_classifier/near_real_time_video
