### ISSUE TITLE
torch-model-archiver doesn't accept the `--config-file` argument

### ISSUE THREAD

**Issue by evgeny-doubleme** [pytorch/serve#2225]
### 🐛 Describe the bug

According to the torch-model-archiver [docs](https://github.com/pytorch/serve/blob/master/model-archiver/README.md#arguments), the tool accepts a `-c, --config-file` argument, but the tool doesn't recognize the argument. 

### Error logs

```sh
usage: torch-model-archiver [-h] --model-name MODEL_NAME [--serialized-file SERIALIZED_FILE] [--model-file MODEL_FILE] --handler HANDLER [--extra-files EXTRA_FILES] [--runtime {python,python3}] [--export-path EXPORT_PATH]
                            [--archive-format {tgz,no-archive,default}] [-f] -v VERSION [-r REQUIREMENTS_FILE]
torch-model-archiver: error: unrecognized arguments: --config-file model_config.yml
```

### Installation instructions

Docker image built from source with the ./build_image.sh script

### Model Packaing

Use `torch-serve-archiver`

### Versions

```
torchserve = "0.7.1"
```

### Repro instructions

Run the `torch-serve-archiver` tool with the ` -c, --config-file` argument. You don't need a working model, as the CLI fails immediately. 

E.g. 

```sh
torch-model-archiver \
	--model-name model-demo \
	--version 1.0.0 \
	--handler serve/model/handler.py \
	--export-path ./model-store \
	--config-file serve/model/config.yml
```

**Comment by msaroufim** [comment]
This was just made available in the nightlies so will be available in the next official release
