### ISSUE TITLE
Model is stuck on loading at startup

### ISSUE THREAD

**Issue by cjidboon94** [pytorch/serve#2238]
Hi there, I am trying to containerize my model in a torchserve container.

It seems to have been succesfully built, but when I try to run the container, it gets stuck (no matter how long I wait) on the following:

My command is: `torchserve --start --ts-config=config.properties` and these are the contents of my config:
```
install_py_dep_per_model=true
service_envelope=json
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
load_models=all
model_store=/home/model-server/model-store
```

In my container there is only 1 .mar file, `detectron.mar` 

```WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-04-18T14:56:14,760 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2023-04-18T14:56:14,893 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.7.1
TS Home: /usr/local/lib/python3.8/dist-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Metrics config path: /usr/local/lib/python3.8/dist-packages/ts/configs/metrics.yaml
Number of GPUs: 1
Number of CPUs: 20
Max heap size: 11976 M
Python executable: /usr/bin/python3.8
Config file: /home/model-server/config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://0.0.0.0:8082
Model Store: /home/model-server/model-store
Initial Models: all
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: true
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: true
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: /home/model-server/model-store
Model config: N/A
2023-04-18T14:56:14,900 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2023-04-18T14:56:14,913 [DEBUG] main org.pytorch.serve.ModelServer - Loading models from model store: detectron.mar
2023-04-18T14:56:20,907 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 0.1 for model detectron
2023-04-18T14:56:20,907 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 0.1 for model detectron
```

Finally, if I try the same config locally, there is also a delay of about 2 minutes before I start seeing logs and then the model is loaded.

If I start torchserve (in the container or locally) without loading any models on startup, but instead using the management api `POST :8081/models?url=./detectron.mar`, followed by `PUT :8081/models/detectron?minWorkers=1`, then I have the following behaviour:
the POST hangs, but I can cancel it on my side as when I query it with `GET :8081/models` the model _is_ listed and then the PUT still creates a worker and the model is loaded and is ready for inference.

Not sure how to continue from here. Let me know if any info is missing. The .mar file is about 624MB.

**Comment by cjidboon94** [comment]
Dug a bit deeper. I think this happens when I set
`install_py_dep_per_model=true` in the config.
Without it, the register endpoint (POST :8081/models) returns with a few milliseconds and the model gets loaded.
Closing this issue as I think I have overcome my problem, but still not sure why that was the cause.

**Comment by cjidboon94** [comment]
> Dug a bit deeper. I think this happens when I set `install_py_dep_per_model=true` in the config. Without it, the register endpoint (POST :8081/models) returns with a few milliseconds and the model gets loaded. Closing this issue as I think I have overcome my problem, but still not sure why that was the cause.

Yup. Also in Docker it now loads, no problem. Instead of trying to have torchserve install it via the enabling the config, I just install it into my docker's general environment (only 1 model right now).

The requirements.txt in my .mar is:
```numpy
git+https://github.com/facebookresearch/detectron2.git 
gs-wrap
[private index-url]
[private package]
--extra-index-url https://download.pytorch.org/whl/cu116
torch==1.12.1+cu116
torchvision==0.13.1+cu116
torchserve
```

**Comment by msaroufim** [comment]
We just discussed this at our weekly meeting, there's a few reasons why model initialization can be slow
1. `torch.load()` overhead - not something we can improve
2. CUDA context launch overhead - not something we can control
3. `install_py_dep_per_model=true` is mostly meant for local development, in a production environment you should preinstall your dependencies or cluster your models by dependencies in case they're very different
4. The model archiver has an overhead to compress and decompress models, the compression is on by default because historically torchserve came out of sagemaker needs which involve loading and unloading tons of models stored in cloud buckets. But for users with smaller deployments choosing `--no-archive` in archiver is a good bet
5. Sometimes the overhead can be multiplied over the number of workers, in these situations loading weights from a remote object store is worthwhile, something @mreso was experimenting it which we might have a solution for soon

**Comment by cjidboon94** [comment]
Nice. @msaroufim Thank you. I will try out different options of the model archive of point 4 to see if it will make a difference in performance for me. 

However, I would like to make clear that when I do **not** set `install_py_dep_per_model=true` in the configuration (locally or in docker), my model loads within reasonable times at startup. 

When I do set `install_py_dep_per_model`, the model loading hangs in docker (have waited upto an hour before deciding to kill the container) and locally is significantly slower (takes upto 5-10 minutes to load). Is there any other side-effect involved with `install_py_dep_per_model` that could explain this? This also happens when I preinstall all my requirements into the environment, so there isn't really anything to install additionally.

**Comment by msaroufim** [comment]
It sort of works like a force reinstall so it would basically run pip install requirements.txt before your model loads. If this includes torch with cuda alone that's already a couple of GB of download

**Comment by cjidboon94** [comment]
> It sort of works like a force reinstall so it would basically run pip install requirements.txt before your model loads. If this includes torch with cuda alone that's already a couple of GB of download

Oh! I see. I have a couple ideas on how to refactor the requirements and see if it improves the loading speed

**Comment by cjidboon94** [comment]
@msaroufim One last question, is there a way to see logs of any subprocess that is installing the requirements?
