### ISSUE TITLE
How to send a json body to Torchserve

### ISSUE THREAD

**Issue by nihiluis** [pytorch/serve#2242]
I'd like to do a post request to torch serve with application/json as its content-type, instead of a file. data could be `{"text": "hi"}`. Is that possible?

In the docs it is shown how you can send binary file data

```
import requests

res = requests.post("http://localhost:8080/predictions/squeezenet1_1", files={'data': open('docs/images/dogs-before.jpg', 'rb'), 'data': open('docs/images/kitten_small.jpg', 'rb')})
```

Can't get anything like this to work:

```
import requests
import io

str = "oi321op4"

raw_data = io.BytesIO(str.encode())
files = {"data": raw_data}
res = requests.post("myurl", files=files)
res.json()
```

**Comment by nihiluis** [comment]
Works like this, had some serious tunnel vision there.

```
import requests
import io
import json

str = json.dumps({"text": "hi"})

raw_data = io.StringIO(str)
files = {"data": raw_data}
res = requests.post("myurl", files=files)
res.content
```

**Comment by agunapal** [comment]
You can check this example https://github.com/pytorch/serve/blob/master/examples/image_classifier/near_real_time_video/request.py#L65
