### ISSUE TITLE
Troubled me too, How to solve this problem in TorchServe 0.7.1

### ISSUE THREAD

**Issue by Z863058** [pytorch/serve#2253]
Just to let you know that I have the same kind of issue on Windows server 2019, with TorchServe 0.7.1. 

From Anaconda Prompt (ran as admninistrator), I run `torchserve --start ...`, everything goes fine including the inference test on the served model. I stop the `torchserve --start ...` command with CTRL+C. 

I guess the SIGINT is not catched by `torchserve.exe` on Windows to delete the `.model_server.pid` from `%APP_DATA%\Local\Temp\1\` so I have to delete it manually before running the next `torchserve --start ...` command.

_Originally posted by @khelkun in https://github.com/pytorch/serve/issues/1866#issuecomment-1425916308_

**Comment by msaroufim** [comment]
Our windows binaries are community supported now since we don't have too much windows expertise on the team, if you'd like to make a PR for this would be happy to merge it
