### ISSUE TITLE
Performance Optimization guide updates

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#2334]
### 📚 The doc issue

Add a performance optimization guide consolidating all the best practices in one place with links to relevant references

[Current Performance Tuning Guide](https://pytorch.org/serve/performance_guide.html?highlight=performance)
[TorchServe Performance Tuning](https://pytorch.org/blog/torchserve-performance-tuning/) Sketch Animator case study
[Better Transformers](https://github.com/pytorch/serve/tree/master/examples/Huggingface_Transformers#speed-up-inference-with-better-transformer)
[Intel CPU Performance Optimizations for TorchServe](https://pytorch.org/tutorials/intermediate/torchserve_with_ipex#grokking-pytorch-intel-cpu-performance-from-first-principles)
[Nvidia MPS support](https://pytorch.org/serve/performance_guide.html?highlight=performance) for optimizing bin packing on GPUs for smaller models

**Comment by sekyondaMeta** [comment]
This sounds like a good idea. I will work on a doc plan for this. I assume the plan is to add this to the Torchserve site.

**Comment by chauhang** [comment]
Performance guide has been updated
