### ISSUE TITLE
Document the docker settings for running in production mode

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#234]
Document the steps for running docker in production mode, with parameters like `--shm-size=1g --ulimit memlock=-1 --ulimit stack=32505856` that will be needed for proper functioning with production workloads

**Comment by aaronmarkham** [comment]
Please add me to the review when the steps are fully fleshed out. "with parameters like" isn't ready for a doc update.

**Comment by dhaniram-kshirsagar** [comment]
@chauhang Tried to understand how and which other similar system parameters for 'run command' could be useful. However, need more details to understand the following aspect - 
- Are we looking to specify certain optimum values for these parameters for torchserve?  
- I think the values of these will vary based on the use case of torchserve. 
- There are other parameters like memory, swapiness, security config.. Do we have to consider some of these as well?
 
Went over a few available resources such as [NVIDIA docker user guide](https://docs.nvidia.com/deeplearning/frameworks/user-guide/index.html) and [docker run command.](https://docs.docker.com/engine/reference/run/).
