### ISSUE TITLE
adding additional endpoints

### ISSUE THREAD

**Issue by rbavery** [pytorch/serve#2352]
### 📚 The doc issue

there is an issue for this but the link no longer exists https://github.com/pytorch/serve/issues/716  I'm also curious if there is a way to add additional endpoints in the handler.py without adding jar files as this issue references https://github.com/pytorch/serve/issues/716

This is for adding arbitrary custom endpoints, not additional models. In my case, I'd like to add an endpoint to the server where a user submits a prediction and some geospatial metadata and gets returned georeferenced prediction that can be plotted on a map. I want to retain the option of keeping the model endpoint separate so that non geospatial imagery can still be submitted to the endpoint.

### Suggest a potential alternative/fix

Not sure what the alternative would be here besides using a more flexible web server in the case this is not supported. Or using two .mars and having two model endpoints but seems redundant

**Comment by lxning** [comment]
@rbavery One alternative is that you can add parameters in the payload and extend backend handler by parsing the parameters if you don't want to add jar files.

for example:
`
json payload: {
        "endpoint": georeferenced,
        "image": img_bytes,
        "gen_args": gen_args
        }
def handle():
    ....
     if endpoint == georeferenced:
         georeferenced(...)

`
