### ISSUE TITLE
Error when start the torchserve, stuck!

### ISSUE THREAD

**Issue by blaoke** [pytorch/serve#2353]
### 🐛 Describe the bug

when I run `torchserve --start --ncs --model-store ./out_faster --models faster.mar` It's stuck, it seems this serve not start, help !

### Error logs

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-05-19T14:55:41,742 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2023-05-19T14:55:41,785 [INFO ] main org.pytorch.serve.metrics.configuration.MetricConfiguration - Successfully loaded metrics configuration from /home/lb/miniconda3/envs/gfocalv1_torchserve/lib/python3.8/site-packages/ts/configs/metrics.yaml
2023-05-19T14:55:41,906 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.8.0
TS Home: /home/lb/miniconda3/envs/gfocalv1_torchserve/lib/python3.8/site-packages
Current directory: /home/lb/wendang/znjs/small_obj/hd/tools/deployment
Temp directory: /tmp
Metrics config path: /home/lb/miniconda3/envs/gfocalv1_torchserve/lib/python3.8/site-packages/ts/configs/metrics.yaml
Number of GPUs: 1
Number of CPUs: 16
Max heap size: 3968 M
Python executable: /home/lb/miniconda3/envs/gfocalv1_torchserve/bin/python
Config file: config.properties
Inference address: https://127.0.0.1:8443
Management address: https://127.0.0.1:8444
Metrics address: https://127.0.0.1:8445
Model Store: /home/lb/wendang/znjs/small_obj/hd/tools/deployment/out_faster
Initial Models: faster.mar
Log dir: /home/lb/wendang/znjs/small_obj/hd/tools/deployment/logs
Metrics dir: /home/lb/wendang/znjs/small_obj/hd/tools/deployment/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: true
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Enable metrics API: true
Metrics mode: log
Disable system metrics: false
Workflow Store: /home/lb/wendang/znjs/small_obj/hd/tools/deployment/out_faster
Model config: N/A
2023-05-19T14:55:41,910 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2023-05-19T14:55:41,924 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: faster.mar
2023-05-19T14:55:45,604 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
	at org.pytorch.serve.archive.utils.ArchiveUtils.readYamlFile(ArchiveUtils.java:66)
	at org.pytorch.serve.archive.model.ModelArchive.getModelConfig(ModelArchive.java:196)
	at org.pytorch.serve.wlm.Model.<init>(Model.java:68)
	at org.pytorch.serve.wlm.ModelManager.createModel(ModelManager.java:269)
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:140)
	at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:264)
	at org.pytorch.serve.ModelServer.startRESTserver(ModelServer.java:396)
	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:118)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:99)

### Installation instructions

pip install

### Model Packaing

I use mmdet to get .mar file

`python mmdet2torchserve.py /home/lb/wendang/znjs/small_obj/GFocalV2-mmdet2.18.1/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py /home/lb/wendang/znjs/small_obj/mmdetection/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --output-folder ./out_faster --model-name faster`

### config.properties

NO

### Versions

------------------------------------------------------------------------------------------
Environment headers
------------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.8.0
torch-model-archiver==0.8.0

Python version: 3.8 (64-bit runtime)
Python executable: /home/lb/miniconda3/envs/gfocalv1_torchserve/bin/python

Versions of relevant python libraries:
numpy==1.24.3
nvgpu==0.10.0
psutil==5.9.5
pytest==7.3.1
requests==2.25.1
torch==1.10.1+cu113
torch-model-archiver==0.8.0
torch-workflow-archiver==0.2.8
torchaudio==0.10.1+cu113
torchserve==0.8.0
torchvision==0.11.2+cu113
wheel==0.36.2
torch==1.10.1+cu113
**Warning: torchtext not present ..
torchvision==0.11.2+cu113
torchaudio==0.10.1+cu113

Java Version:

OS: Ubuntu 20.04.5 LTS
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
CMake version: version 3.16.3

Is CUDA available: Yes
CUDA runtime version: 11.3.109
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 470.182.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1

### Repro instructions

--2023-05-19 15:21:24--  http://mar_file.mar/
正在解析主机 mar_file.mar (mar_file.mar)... 失败：未知的名称或服务。
wget: 无法解析主机地址 “mar_file.mar”
usage: torch-model-archiver [-h] --model-name MODEL_NAME [--serialized-file SERIALIZED_FILE]
                            [--model-file MODEL_FILE] --handler HANDLER [--extra-files EXTRA_FILES]
                            [--runtime {python,python3}] [--export-path EXPORT_PATH]
                            [--archive-format {tgz,no-archive,zip-store,default}] [-f] -v VERSION
                            [-r REQUIREMENTS_FILE] [-c CONFIG_FILE]
torch-model-archiver: error: the following arguments are required: --model-name, --handler, -v/--version
Removing orphan pid file.
Missing mandatory parameter --model-store

### Possible Solution

no

**Comment by lxning** [comment]
@blaoke the log exception shows there are errors in the model config yaml file. Please check your config file based on the [instruction](https://github.com/pytorch/serve/tree/master/model-archiver#config-file) or [here](https://github.com/pytorch/serve/blob/master/docs/configuration.md#config-model).

sorry, what is mmdet2torchserve.py? could you follow [this](https://github.com/pytorch/serve/tree/master/model-archiver#torch-model-archiver-command-line-interface) to create mar file? It would be

**Comment by mayman99** [comment]
I had the same issue, had to downgard torchserve to 0.7.1 for it to work

**Comment by yfq512** [comment]
我遇到了同样的问题，也是部署mmdet项目报错，作者这个问题解决了么？

**Comment by JookerLoo** [comment]
> 我遇到了同样的问题，也是部署mmdet项目报错，作者这个问题解决了么？

怎么样，您解决了么？
