### ISSUE TITLE
Torchserve-kserve 0.8.0-gpu image is missing several dependencies

### ISSUE THREAD

**Issue by cjidboon94** [pytorch/serve#2354]
### 🐛 Describe the bug

I'm in the process of upgrading my torchserve runtime on KServe to 0.8.0, for this I updated my Inferenceservice's image to:
https://hub.docker.com/layers/pytorch/torchserve-kfs/0.8.0-gpu

However, on startup it seems that Tornado is not installed and the following error occurs: `ModuleNotFoundError: No module named 'tornado'`

```Traceback (most recent call last):
  File "/home/model-server/kserve_wrapper/__main__.py", line 7, in <module>
    from TorchserveModel import TorchserveModel
  File "/home/model-server/kserve_wrapper/TorchserveModel.py", line 9, in <module>
    import tornado.web
```

### Error logs

```Traceback (most recent call last):
  File "/home/model-server/kserve_wrapper/__main__.py", line 7, in <module>
    from TorchserveModel import TorchserveModel
  File "/home/model-server/kserve_wrapper/TorchserveModel.py", line 9, in <module>
    import tornado.web
```

### Installation instructions

I pulled the image from https://hub.docker.com/layers/pytorch/torchserve-kfs/0.8.0-gpu

### Model Packaing

Does not seem relevant as this happens before model loading occurs.

### config.properties

Not relevant

### Versions

See the docker image `pytorch/torchserve-kfs:0.8.0-gpu`

### Repro instructions

`docker run --rm --gpus=all pytorch/torchserve-kfs:0.8.0-gpu`

### Possible Solution

Installing tornado

**Comment by cjidboon94** [comment]
BTW, KServe has moved away from Tornado in favor of FastApi/Uvicorn: https://github.com/kserve/kserve/pull/2444 
Might be better to make the necessary changes to match that instead of just installing tornado

**Comment by cjidboon94** [comment]
For now, implemented workaround from https://github.com/pytorch/serve/issues/2123

**Comment by cjidboon94** [comment]
Probably would be fixed by: https://github.com/pytorch/serve/pull/2175

**Comment by cjidboon94** [comment]
Building torchserve-kfs:0.8.0-gpu based on #2175 works for me.

**Comment by msaroufim** [comment]
Alright I merged that PR - cc @ankithagunapal we need to release the binaries

**Comment by agunapal** [comment]
@msaroufim So, should we revert this https://github.com/pytorch/serve/pull/2355

**Comment by msaroufim** [comment]
I don't believe #2355 was merged

**Comment by agunapal** [comment]
@cjidboon94 Thanks for reporting the issue and finding the solution. Republished the images. Please check.

**Comment by agunapal** [comment]
I dont see the import error when I run the docker run command

**Comment by cjidboon94** [comment]
@agunapal Thanks! It works for me too. Good to be able to use the officially released image again

**Comment by cjidboon94** [comment]
@agunapal  @msaroufim  Btw, you might want to rebuild the 0.7.1 torchserve-kserve images too, as this issue also seems to be occurring there: https://github.com/pytorch/serve/issues/2123
