### ISSUE TITLE
Worker does not recover after 'failed' request

### ISSUE THREAD

**Issue by cjidboon94** [pytorch/serve#2357]
### 🐛 Describe the bug

I am not sure what is going on but with certain requests, my model workers die and do not recover.
Am I passing too much data? Should I set a higher timeout for my requests?

I am also trying to increase the number of workers. 

### Error logs

First error when worker dies during/at the end of the request:
```
Backend worker error
org.pytorch.serve.wlm.WorkerInitializationException: Backend worker did not respond in given time
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:224) [model-server.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

then during recovery it keeps repeating the following:
```
INFO 2023-05-22T12:20:15.644644595Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,644 [DEBUG] W-9001-maskrcnn_0.1 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/home/venv/bin/python, /home/venv/lib/python3.9/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /home/model-server/tmp/.ts.sock.9001, --metrics-config, /home/venv/lib/python3.9/site-packages/ts/configs/metrics.yaml]
INFO 2023-05-22T12:20:15.651335814Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,650 [INFO ] W-9000-maskrcnn_0.1-stdout MODEL_LOG - s_name_part0=/home/model-server/tmp/.ts.sock, s_name_part1=9000, pid=352
INFO 2023-05-22T12:20:15.651554926Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,651 [INFO ] W-9000-maskrcnn_0.1-stdout MODEL_LOG - Listening on port: /home/model-server/tmp/.ts.sock.9000
INFO 2023-05-22T12:20:15.660896628Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,660 [INFO ] W-9000-maskrcnn_0.1-stdout MODEL_LOG - Successfully loaded /home/venv/lib/python3.9/site-packages/ts/configs/metrics.yaml.
INFO 2023-05-22T12:20:15.661043157Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,660 [INFO ] W-9000-maskrcnn_0.1-stdout MODEL_LOG - [PID]352
INFO 2023-05-22T12:20:15.661196457Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,661 [INFO ] W-9000-maskrcnn_0.1-stdout MODEL_LOG - Torch worker started.
INFO 2023-05-22T12:20:15.661261405Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,661 [INFO ] W-9000-maskrcnn_0.1-stdout MODEL_LOG - Python runtime: 3.9.16
INFO 2023-05-22T12:20:15.661318510Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,661 [DEBUG] W-9000-maskrcnn_0.1 org.pytorch.serve.wlm.WorkerThread - W-9000-maskrcnn_0.1 State change WORKER_STOPPED -> WORKER_STARTED
INFO 2023-05-22T12:20:15.661494288Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,661 [INFO ] W-9000-maskrcnn_0.1 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9000
INFO 2023-05-22T12:20:15.662381481Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,662 [INFO ] W-9000-maskrcnn_0.1-stdout MODEL_LOG - Connection accepted: /home/model-server/tmp/.ts.sock.9000.
INFO 2023-05-22T12:20:15.662404927Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,662 [INFO ] epollEventLoopGroup-5-2 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
INFO 2023-05-22T12:20:15.662720060Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,662 [DEBUG] W-9000-maskrcnn_0.1 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
INFO 2023-05-22T12:20:15.663234764Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,662 [DEBUG] W-9000-maskrcnn_0.1 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
INFO 2023-05-22T12:20:15.663245633Z [resource.labels.containerName: kserve-container] java.lang.InterruptedException: null 
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1679) ~[?:?] 
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:515) ~[?:?] 
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:677) ~[?:?] 
	at org.pytorch.serve.wlm.Model.pollBatch(Model.java:260) ~[model-server.jar:?] 
	at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:34) ~[model-server.jar:?] 
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:186) [model-server.jar:?] 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?] 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?] 
	at java.lang.Thread.run(Thread.java:833) [?:?]
INFO 2023-05-22T12:20:15.663451517Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,663 [DEBUG] W-9000-maskrcnn_0.1 org.pytorch.serve.wlm.WorkerThread - W-9000-maskrcnn_0.1 State change WORKER_STARTED -> WORKER_STOPPED
INFO 2023-05-22T12:20:15.663483458Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,663 [WARN ] W-9000-maskrcnn_0.1 org.pytorch.serve.wlm.WorkerThread - Auto recovery failed again
INFO 2023-05-22T12:20:15.663960878Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,663 [WARN ] W-9000-maskrcnn_0.1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-maskrcnn_0.1-stderr
INFO 2023-05-22T12:20:15.664129845Z [resource.labels.containerName: kserve-container] 2023-05-22T12:20:15,664 [WARN ] W-9000-maskrcnn_0.1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-maskrcnn_0.1-stdout
```

### Installation instructions

I'm running torchserve in KServe, using the torchserve-kfs:0.8.0-gpu image

### Model Packaing

We have a custom handler. I can't share a gist, but it's similar in structure as https://gist.github.com/elb3k/0a9f8ade4be99442c9ea7aed0d83ce71

### config.properties

inference_address=http://0.0.0.0:8085
management_address=http://0.0.0.0:8085
metrics_address=http://0.0.0.0:8082
grpc_inference_port=7070
grpc_management_port=7071
enable_metrics_api=true
metrics_format=prometheus
number_of_netty_threads=4
job_queue_size=10
enable_envvars_config=true
default_workers_per_model=5
install_py_dep_per_model=false
model_store=/mnt/models/model-store
model_snapshot={"name":"startup.cfg","modelCount":1,"models":{"maskrcnn":{"0.1":{"defaultVersion":true,"marName":"maskrcnn.mar","minWorkers":2,"maxWorkers":5,"batchSize":1,"maxBatchDelay":10,"responseTimeout":120}}}}

### Versions

The default torch versions from torchserve-kfs:0.8.0 (torch 2, torchvision 0.15 etc.)

### Repro instructions

NOTE: Since I can't share the mar or exact handler, I'm not sure if this is reproducible by others.

- Install KServe
- Create a KServe inferenceservice with the Torchserve runtime (point to image 0.8.0) and the mar/config.properties
- Start sending requests with large amount of images

### Possible Solution

-

**Comment by cjidboon94** [comment]
Increasing the `responseTimeout` value for the model for the value seems to have fixed my issue. Also, allowed me to have more workers at the same time

**Comment by cjidboon94** [comment]
```
INFO 2023-05-23T13:56:20.225527915Z [resource.labels.containerName: kserve-container] 2023-05-23T13:56:20,225 [INFO ] W-9002-maskrcnn_0.1 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9002
INFO 2023-05-23T13:56:20.226467148Z [resource.labels.containerName: kserve-container] 2023-05-23T13:56:20,226 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9002 Worker disconnected. WORKER_STARTED
INFO 2023-05-23T13:56:20.226523376Z [resource.labels.containerName: kserve-container] 2023-05-23T13:56:20,226 [INFO ] W-9002-maskrcnn_0.1-stdout MODEL_LOG - Connection accepted: /home/model-server/tmp/.ts.sock.9002.
```
Looking at this bit of logs, it seems to suggest that the WorkerThread disconnects right before/after the connection with service worker is accepted.

Seems to be happening here: https://github.com/pytorch/serve/blob/4450287d9a8322e5a670c5f473c37e192de92dc1/frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java#L366-L383

and  https://github.com/pytorch/serve/blob/4450287d9a8322e5a670c5f473c37e192de92dc1/ts/model_service_worker.py#L215-L221

But not sure why

**Comment by agunapal** [comment]
@cjidboon94 I am curious if you are seeing this issue with standalone torchserve. Also is this running on CPU. Any pointers on the size of the payload being sent to the model would be helpful. Is it single request or batched and whats the frequency of the requests

**Comment by cjidboon94** [comment]
> @cjidboon94 I am curious if you are seeing this issue with standalone torchserve. Also is this running on CPU. Any pointers on the size of the payload being sent to the model would be helpful. Is it single request or batched and whats the frequency of the requests

I will try to reproduce this on a standalone torchserve!
This is running on a GPU (NVIDIA L4, g2-standard-8 machine https://cloud.google.com/compute/docs/accelerator-optimized-machines#g2-standard-vms ). 
This for individual requests. I am sending one request after the other (so waiting for one request to complete before the next one starts). I see this issue occuring for both the case when I have 1 worker and multiple workers.

The request payload itself is a couple kilobytes (not more than 10 kB) with filepaths to a bucket that get downloaded during the preprocessing step. These files get deleted again after postprocessing is done.

**Comment by cjidboon94** [comment]
Using the same image as above, but instead of using the kserve wrapper, 
I now ran TorchServe standalone (or as standalone as it gets in the image) to start with `torchserve --start --ts-config=/mnt/models/config/config.properties`. 

After running a small load test where I keep sending the same data repeatedly for 6 minutes (30s with 1 client, 30 seconds with 2 clients, 4 minutes with 4 clients, then scale down of clients. The issue/Interruption exception happened this time during the scaledown of the load test) while running torchserve with 5 workers this same issue happened, so it doesn't seem kserve related in this case. 
I will do the test as well one more time using torchserve standalone on the host machine to see if I can reproduce it there as well.

I have one question, though I am not sure if this is relevant to the issue: What is the role of Netty threads and Netty client threads in Torchserve (not too familiar with java networking packages)? I have Netty client threads configured to 0 (default, I think) and Netty threads to 10 (increased from 4 in OP config). Should changing either have any impact on the behaviour I am seeing?

**Comment by cjidboon94** [comment]
Ran another Load test, this time 30s with 1 client, 6min with 4 clients and using a standalone torchserve on the host machine where I have the model requirements installed + torchserve/torch

During this load test the issue occured again, and instead of the usual 503 status (what I was seeing when running it on kubernetes), I got a 507 status (Insufficient Storage). Double checked the access_log of the previous load test and it seems that I got a 507 there as well.

Next up another load test but this time with the kserve inference service I already had setup. Going to see if it is also a 507 status there.

**Comment by cjidboon94** [comment]
So the reason why one of the workers was killed was because of a Cuda Out Of Memory (too many workers on the GPU essentially). Scaled it down, now it doesn't happen anymore. However, I was not able to figure out why this would cause a state that the thread cannot recover from.
