### ISSUE TITLE
Could it possible to explain about broker part for TorchServe workflow

### ISSUE THREAD

**Issue by RTae** [pytorch/serve#2367]
### 📚 The doc issue

Recently, my team tried the TorchServe workflow, and it did the job quite well. However, I would like to know what TorchServe workflow' broker is used, or is it just a memory queue?

**Comment by agunapal** [comment]
@RTae Please refer to this code

https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/workflow/WorkflowManager.java#L377-L379

In summary, we create a DAG from the workflow and then run inference on the DAG created.

**Comment by RTae** [comment]
@agunapal Thank you
