### ISSUE TITLE
Convert fairseq to torchscript

### ISSUE THREAD

**Issue by arnavmehta7** [pytorch/serve#2404]
### 🚀 The feature

Convert a fairseq model to torchscript model to deploy to torchserve to enjoy features like microbatching.

### Motivation, pitch

Fairseq models deployments is a bit tough and I would like to enjoy the extra-benifits of torchserve like microbatching.

**Comment by msaroufim** [comment]
Torchscript is in community support now would recommend you take a look at `torch.compile` or `torch.export`
