### ISSUE TITLE
Sentencepiece in README.md

### ISSUE THREAD

**Issue by zhangguanheng66** [pytorch/serve#242]
It seems that sentencepiece is missing from the conda install command. Since examples run sentencepiece related APIs from torchtext, sentencepiece dependency is a must in this case. Right now in the conda install command, there is only a `powerai` channel but not sentencepiece library. Here is the relevant PR in torchtext https://github.com/pytorch/text/pull/733

For pip install command, sentencepiece is in the `setup.py` file of torchtext as the dependency. So we don't to explicitly mention sentencepiece in the pip install command.

Hopefully, this is clear. Nice job for the release.

**Comment by aaronmarkham** [comment]
If the general instructions for Conda are updated to use the yml files and commands in #288, then this issue will be resolved.
