### ISSUE TITLE
Torchserve 0.8.1: ONNX GPU models not working

### ISSUE THREAD

**Issue by dt-subaandh-krishnakumar** [pytorch/serve#2425]
### 🐛 Describe the bug

I recently updated the torchserve version from 0.7.1-gpu to 0.8.1-gpu.

#### Current setup

I used `torchserve:0.7.1-gpu` from the source and build a docker image with `torch2.0+cpu`. The onnx GPU models and were running and the models used ~8.5 Memory and ~4GB GPU (cuda 11.7).

#### Bug
1. After a recent update to `torchserve 0.8.1` the `torch 2.0+cpu` no longer worked and failed with the following error:

```
[W:onnxruntime:Default, onnxruntime_pybind_state.cc:578 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
```

2. I managed to fix this by using `torch2.0` with gpu dependencies but doing so increased the Memory(~13GB ) and GPU (~6GB) consumption.

The models were not updated. I built torchserve0.8.1 with `./build_image.sh -py 3.8 -cv cu117 -g -t torchserve_py38`  

### Error logs

[W:onnxruntime:Default, onnxruntime_pybind_state.cc:578 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.

### Installation instructions

Yes I ran ./build_image.sh -py 3.8 -cv cu117 -g -t torchserve_py38

```
FROM torchserve_py38

RUN pip install torch==2.0 (for cpu version --extra-index-url https://download.pytorch.org/whl/cpu)
RUN pip install onnxruntime-gpu==1.13.1
...
...

```

### Model Packaing

I converted pytorch models to onnx and served them using Custom Handler.

#### Working

```
Torchserve branch: 

torchserve==0.7.1b20230208
torch-model-archiver==0.7.1b20230208

Python version: 3.8 (64-bit runtime)
Python executable: /usr/bin/python

Versions of relevant python libraries:
captum==0.6.0
intel-extension-for-pytorch==1.13.0
numpy==1.22.2
nvgpu==0.9.0
psutil==5.6.7
pygit2==1.11.1
pylint==2.6.0
pytest==7.2.1
pytest-cov==4.0.0
pytest-mock==3.10.0
requests==2.31.0
requests-toolbelt==0.10.1
sentencepiece==0.1.97
torch==2.0.0+cpu
torch-model-archiver==0.7.1b20230208
torch-workflow-archiver==0.2.7b20230208
torchaudio==0.13.1+cu117
torchserve==0.7.1b20230208
torchtext==0.14.1
torchvision==0.15.1+cpu
transformers==4.10.0
wheel==0.40.0
torch==2.0.0+cpu
torchtext==0.14.1
torchvision==0.15.1+cpu
torchaudio==0.13.1+cu117

Java Version:


OS: Ubuntu 20.04.5 LTS
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
CMake version: version 3.26.4
```

#### Bug
```
-----------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.8.1
torch-model-archiver==0.8.1

Python version: 3.8 (64-bit runtime)
Python executable: /home/venv/bin/python

Versions of relevant python libraries:
captum==0.6.0
numpy==1.22.2
nvgpu==0.10.0
psutil==5.6.7
requests==2.31.0
sentencepiece==0.1.97
torch==2.0.0
torch-model-archiver==0.8.1
torch-workflow-archiver==0.2.9
torchaudio==2.0.2+cu117
torchdata==0.6.1
torchserve==0.8.1
torchtext==0.15.2+cpu
torchvision==0.15.1
transformers==4.10.0
wheel==0.40.0
torch==2.0.0
torchtext==0.15.2+cpu
torchvision==0.15.1
torchaudio==2.0.2+cu117

Java Version:


OS: Ubuntu 20.04.6 LTS
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
CMake version: version 3.26.4

Is CUDA available: Yes
CUDA runtime version: N/A
GPU models and configuration: 
GPU 0: Tesla T4
Nvidia driver version: 470.161.03
cuDNN version: None
```

#### Issue 1
1. Convert a PyTorch model to onnx and run it with `python3.8`, `onnxruntime-gpu==1.13.1`, `torchserve0.7.1-gpu` and `torch2.0.0+cpu`. (Take note of GPU, Memory consumption)
2. Build a new torchserve image with this command `./build_image.sh -py 3.8 -cv cu117 -g -t torchserve_py38`. Run the same model with (`onnxruntime-gpu==1.13.1` and `torch2.0.0+cpu`).

#### Issue 2
3. Use `torch2.0` instead of `torch 2.0+cpu` the memory and GPU consumption will increase.

**Comment by msaroufim** [comment]
So the logic for whether to use the ONNX CUDA environment is controlled here

https://github.com/pytorch/serve/blob/master/ts/torch_handler/base_handler.py#L80-L84

Both on CPU and GPU I see the base test passing

# Bug 1
What's confusing me about your setup is using both onnx gpu runtime and torch cpu?

```
[W:onnxruntime:Default, onnxruntime_pybind_state.cc:578 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
```

It seems to me like what's happening is in your handler your `map_location` is cuda so make sure that's not not the case https://github.com/pytorch/serve/blob/master/ts/torch_handler/base_handler.py#L112

# Bug 2
Are you using the same dependencies for onnx and onnx runtime when measuring the extra memory overhead? torch 2.0 in general has way more dependencies but the overhead you're seeing is significant


I suspect you should be able to repro your errors without torchserve in the loop which will make debugging this a bit easier. Let me know if this all makes sense

**Comment by msaroufim** [comment]
Seems like an NVIDIA driver issue - see this for example https://github.com/NVIDIA/k8s-device-plugin/issues/331

Try updating this line https://github.com/pytorch/serve/blob/master/docker/build_image.sh#L46 to `nvidia/cuda:11.7.0-cudnn8-runtime-ubuntu20.04` and then run the build_image.sh script

**Comment by msaroufim** [comment]
Thanks @dt-subaandh-krishnakumar I believe that sounds like a separate issue - tagging @namannandan who owns this

Might make sense to open a seperate issue for this though so we don't lose this

**Comment by hungtrieu07** [comment]
I faced this issue, you need to install CUDA 11.8 and corresponding torch version with CUDA 11.8.
