### ISSUE TITLE
is TS_JOB_QUEUE_SIZE a valid environment variable?

### ISSUE THREAD

**Issue by sreeprasannar** [pytorch/serve#2446]
### 📚 The doc issue

[This page](https://pytorch.org/serve/configuration.html) says environment variables are equivalent to server configuration set in `config.properties`
Setting `TS_JOB_QUEUE_SIZE` as an environment variable has no effect in Docker version 0.8.0

```
Torchserve version: 0.8.0
TS Home: /home/venv/lib/python3.9/site-packages
Current directory: /app
Temp directory: /home/model-server/tmp
Metrics config path: /app/config/metrics.yaml
Number of GPUs: 0
Number of CPUs: 4
Max heap size: 7952 M
Python executable: /home/venv/bin/python
Config file: /app/config/config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://0.0.0.0:8082
Model Store: /app/model_store
Initial Models: ALL
Log dir: /app/logs
Metrics dir: /app/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: true
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Enable metrics API: true
Metrics mode: prometheus
Disable system metrics: false
Workflow Store: /app/model_store
Model config: N/A
```

**Comment by sreeprasannar** [comment]
`JOB_QUEUE_SIZE` has no effect either

**Comment by sreeprasannar** [comment]
And yes, I have `enable_envvars_config=true` in my `config.properties`

**Comment by sreeprasannar** [comment]
Also what does `job_queue_size` even mean?
```
Number inference jobs that frontend will queue before backend can serve. Default: 100.
```
* Does `before backend can serve` mean that the queue will accumulate before inference workers can processing? That sounds counter-intuitive so maybe not
* Or does it mean that's the maximum queue size after which requests will not be queued anymore i.e. 503 responses will be sent for the following requests outside the queue?

**Comment by agunapal** [comment]
@sreeprasannar Yes, `job_queue_size` is the maximum queue size after which requests will not be queued anymore

**Comment by agunapal** [comment]
Will try out env variables in docker and get back

**Comment by arnavmehta7** [comment]
Does this env variable leaks memory?

**Comment by lxning** [comment]
@sreeprasannar, @arnavmehta7 v0.8.1 allows for model level config (see [model config yaml](https://github.com/pytorch/serve/tree/master/model-archiver#config-file)).

- define `jobQueueSize` per model. (see [details](https://github.com/pytorch/serve/pull/2350))

**Comment by arnavmehta7** [comment]
Hi @lxning I'm curious that rn if the model ever releases memory from the queue. 

It seems that it stores somewhere all the intermediate information processed in them.

**Comment by lxning** [comment]
@arnavmehta7 I'm not fully understand your question. The background information is
1. the job queue is used to store incoming inference request of a model. the request is de-queued and processed.
2. The memory occupied by a model is released only if the unload or reduce worker command is received.  

Could you please provide the detail information you observed about memory usage.

**Comment by arnavmehta7** [comment]
@lxning I will highly appreciate if you could look into this https://github.com/pytorch/serve/issues/2453 .
