### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by madkote** [pytorch/serve#2447]
### 🚀 The feature

Allow sending data via websockets

### Motivation, pitch

Using Torch models for ASR (as an example) will require to send many http request with chunks of audio (for real time streaming). With websockets, the connection would be persistent, chunks would be processed and replies are sent to the client

**Comment by mreso** [comment]
Hi @madkote, this use case is now supported with our streaming API in combination with stateful inference where clients can send a stream/chunks of data to the same model. See [this example](https://github.com/pytorch/serve/tree/master/examples/stateful) for details.
