### ISSUE TITLE
Bad links in docs

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/serve#245]
Hi, 
Just a brief report on bad links on examples from this page : http://pytorch.org/serve/default_handlers.html

PS: Cool project ! Thanks !

**Comment by fbbradheintz** [comment]
Thank you!

**Comment by eslesar-aws** [comment]
This was fixed in source, awaiting a publish refresh on the PyTorch docs site:

https://github.com/pytorch/serve/commit/580c0532fa13954258d314fd9312ceec8cb36084
