### ISSUE TITLE
Read manifest inside _infer_with_profiler method

### ISSUE THREAD

**Issue by pedrogengo** [pytorch/serve#2480]
### 🚀 The feature

Add a line to read the manifest file inside the [method ](https://github.com/pytorch/serve/blob/754c2f9a550ff57790e586c199dc8b7a842af159/ts/torch_handler/base_handler.py#L354-L401) `_infer_with_profiler` if `self.manifest` is None (this can happen in cases the user overwrites the `initialize` method).

If you think this makes sense, Im more than happy to contribute with it :)

### Motivation, pitch

I'm working in some projects where we are overwriting the `initialize` method from base handler and we weren't creating the `self.manifest` attribute on it. When I tried to run the torch profiler, the request broke because `self.manifest` was None. IMO, as this attribute is used for other methods we should guarantee that we will have that or if the attribute is None we can read the file inside the `_infer_with_profiler` method.

This issue will happen to some examples too, like [this one](https://github.com/pytorch/serve/blob/7e5857fee8eb502559da97ff808041749282e868/examples/text_to_speech_synthesizer/waveglow_handler.py#L55C1-L55C1).

### Alternatives

- If `self.manifest` is None, read the file inside `_infer_with_profiler`;
- Update documentation to be explicit that you need to have the `self.manifest` defined in your `initialize` method.

**Comment by agunapal** [comment]
Hi @pedrogengo  Thanks for the proposal. I think it makes sense. Please feel free to send a PR.

**Comment by pedrogengo** [comment]
Tomorrow I will open a PR for that, tks for your quick reply

**Comment by pedrogengo** [comment]
@agunapal I opened a PR for this :)

**Comment by agunapal** [comment]
Thanks! Will review it tomorrow

**Comment by pedrogengo** [comment]
I decided to don't change anything in the `_infer_with_profiler`, but delegate the manifest checking to `handle`, as it is the method that call the `_infer_with_profiler`. Let me know what you think :)
