### ISSUE TITLE
Organize HTTP and GRPC response streaming together in LMI section

### ISSUE THREAD

**Issue by lxning** [pytorch/serve#2496]
### 📚 The doc issue

There are 2 instruction links for streaming support in TS.
- GRPC response streaming : https://github.com/pytorch/serve/blob/master/docs/grpc_api.md#grpc-server-side-streaming
- Http response streaming: https://github.com/pytorch/serve/blob/master/docs/inference_api.md#curl-example-1

It is not easy for user to find this feature when they run LMI.

### Suggest a potential alternative/fix

Add a section streaming support in LMI doc to include the HTTP and GRPC information.

**Comment by sekyondaMeta** [comment]
The PR below adds this information to the LMI doc and cleans it up as well. There were some minor changes that Mark had requested and most are done. @lxning feel free to review the PR and let me know if there is anything else you want added.
pr #2468
