### ISSUE TITLE
Import error in torch-tensorrt

### ISSUE THREAD

**Issue by sachanub** [pytorch/serve#2500]
### 🐛 Describe the bug

I am a part of the Model Serving team at AWS. I am trying to follow this [PR](https://github.com/pytorch/serve/pull/2483#pullrequestreview-1538186325) to install Torch-TensorRT on the TorchServe Docker image i.e. `763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:2.0.1-gpu-py310-cu118-ubuntu20.04-ec2`. However, upon trying to import torch-tensorrt in the container, it fails with an error. I need help to debug this issue. Thanks!

### Error logs

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/torch_tensorrt/__init__.py", line 86, in <module>
    from torch_tensorrt._compile import *
  File "/opt/conda/lib/python3.10/site-packages/torch_tensorrt/_compile.py", line 2, in <module>
    import torch_tensorrt.ts
  File "/opt/conda/lib/python3.10/site-packages/torch_tensorrt/ts/__init__.py", line 1, in <module>
    from torch_tensorrt.ts._compiler import *
  File "/opt/conda/lib/python3.10/site-packages/torch_tensorrt/ts/_compiler.py", line 5, in <module>
    import torch_tensorrt._C.ts as _C
ImportError: /opt/conda/lib/python3.10/site-packages/torch_tensorrt/lib/libtorchtrt.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs
```

### Installation instructions

I am running TorchServe with this Docker image: `763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:2.0.1-gpu-py310-cu118-ubuntu20.04-ec2`

### Model Packaing

Not packaged any model yet.

### Versions

N/A

### Repro instructions

1. Launch container of TorchServe Docker image: `docker run -it --gpus=all 763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-inference:2.0.1-gpu-py310-cu118-ubuntu20.04-ec2 /bin/bash`
2. Inside container, install `tensorrt==8.5.3.1` and `torch-tensorrt==1.4.0`: `pip3 install tensorrt==8.5.3.1 torch-tensorrt=1.4.0`
3. Launch Python3 and try to import tensorrt and torch-tensorrt: `import tensorrt; import torch_tensorrt`

**Comment by agunapal** [comment]
Hi @sachanub can you please install torchserve-nightly in the docker container or you can call `import torch_tensorrt` in your custom handler

**Comment by sachanub** [comment]
Hi @agunapal . I tried installing torchserve-nightly in the Docker container and then tried importing `torch_tensorrt` in python3. I am still getting the same error. The main issue is that I am unable to create the Torch-TensorRT artifact (similar to how it was done in this [PR](https://github.com/pytorch/serve/pull/2483/files)). Until I am able to import `torch_tensorrt`, I can not create the model artifact.
The Torchserve version in the Docker container is 0.8.1.

**Comment by agunapal** [comment]
Hi @sachanub  I was able to get `import torch_tensorrt` working with a specific combination as show in the example.
Do you have cuDNN installed? Also, please install cuDNN before tensorrt/torch_tensorrt. 
Also, I have not tried this with CUDA 11.8. I used CUDA 11.7 in the example.

**Comment by sachanub** [comment]
Hi @agunapal I have tried installing cuDNN but even with that it failed. I have not tried CUDA 11.7 yet. I will try that too. Are there any other dependencies for `torch-tensorrt` which I should be mindful about for this task?

**Comment by agunapal** [comment]
nothing else. If I get a chance to try it with CUDA 11.8 , will update the example

**Comment by sachanub** [comment]
Hi @agunapal. I was able to get the example working with CUDA 11.7. However, it is definitely worth investigating why it fails with CUDA 11.8. According to this [release page](https://github.com/pytorch/TensorRT/releases), Torch-TensorRT 1.4.0 should be supported with CUDA 11.8.

**Comment by agunapal** [comment]
Thanks for confirming!  Do you mind filing an issue with torch_tensorrt as this is not related to torchserve?.

**Comment by sachanub** [comment]
Sure that sounds good. Thanks @agunapal
