### ISSUE TITLE
RegisterModel of ManagementAPI Fails to Read ModelName from .mar on GCS

### ISSUE THREAD

**Issue by topazape** [pytorch/serve#2510]
### 🐛 Describe the bug

I successfully made a Register Model API request using `curl -X POST "http://localhost:8081/models?url=https://torchserve.pytorch.org/mar_files/squeezenet1_1.mar"` as per the official documentation. However, when I tried the same with the  official `queezenet1_1.mar` file hosted on GCS, it failed. I have confirmed that the `squeezenet1_1.mar` file is located at `/home/model-server/model-store/squeezenet1_1.mar` within the Docker container.

### Error logs

I downloaded the `queezenet1_1.mar` file from `https://torchserve.pytorch.org/mar_files/squeezenet1_1.mar` and uploaded it to my GCS bucket. When I tried to set the model URL in the API, it failed. Here's the command I used and the error message I received:
```
curl -X POST "http://localhost:8081/models?url=https://storage.cloud.google.com/<BUCKET_NAME>/squeezenet1_1.mar"
{
  "code": 400,
  "type": "InvalidModelException",
  "message": "Model name is not defined."
}
```

### Installation instructions

Install torchserve from source: No
Are you using Docker: Yes, I used [pytorch/torchserve:0.8.1-cpu](https://hub.docker.com/layers/pytorch/torchserve/0.8.1-cpu/images/sha256-4135174332c7b92505659b4b38688e9c92576b3679a1358dfdb0bdece88e7491?context=explore)

### Model Packaing

officially packed model file: `https://torchserve.pytorch.org/mar_files/squeezenet1_1.mar` but it's hosted on GCS.

### config.properties

default `config.properties`

### Versions

```
model-server@cf74b74f4e29:~$ /home/venv/bin/torchserve --version
TorchServe Version is 0.8.1
```

### Repro instructions

1. Download official `squeezenet1_1.mar` mar file.
```
curl -LO https://torchserve.pytorch.org/mar_files/squeezenet1_1.mar
```
2. Upload it to any GCS bucket.
3. Obtain authenticated GCS URL for the uploaded file.
4. Set this URL as the "Model archive download url" in the API.

**Comment by lxning** [comment]
@topazape could you run the following steps to debug?
- empty model_store at local
- start TorchServe
- run curl -X POST "http://localhost:8081/models?url=https://storage.cloud.google.com/<BUCKET_NAME>/squeezenet1_1.mar"
- ls -al model_store
- unzip squeezenet1_1.mar
- ls -al squeezenet1_1
- cat squeezenet1_1/MAR-INF/MANIFEST.json
