### ISSUE TITLE
can not start torchserve: "Removing orphan pid file".

### ISSUE THREAD

**Issue by NazSaleh** [pytorch/serve#2512]
### 🐛 Describe the bug

when I run below command:

!torchserve --start --ncs \
--model-store "$model_store" \
--ts-config "$model_config" 

I receive below message and torchserver doesn't start: 
"Removing orphan pid file."

### Error logs

"Removing orphan pid file."

### Installation instructions

pip install torchserve torch-model-archiver torch-workflow-archiver --force

### Model Packaing

   .bin file

### config.properties

inference_address=http://0.0.0.0:****
management_address=http://0.0.0.0:****
metrics_address=http://0.0.0.0:****

### Versions

[Errno 2] No such file or directory

### Repro instructions

torch-model-archiver
torchserve --start

**Comment by msaroufim** [comment]
What does your `log/model_log.log` say?

**Comment by NazSaleh** [comment]
Thanks for your message. I could solve it. The problem was in my handler.py.

**Comment by msaroufim** [comment]
We could probably add a better warning for this. Cc @agunapal
