### ISSUE TITLE
Grammatical Issues in the Docs

### ISSUE THREAD

**Issue by jeffreyksmithjr** [pytorch/serve#252]
There are several docs pages with various grammatical errors. Some are trivial, but some prevent easy comprehension of the material.

# Examples
https://github.com/pytorch/serve/blob/1f16a7e5989e046f0e5ce5a9f4c73182f63c4573/docs/server.md
* PyTorch is not consistently camel-cased
* "focus" where "focuses" should be used
* Shows up on pytorch.org as "Running the TorchServe" not "Running TorchServe" for some reason
* Inconsistent use of first, second, and third person

https://github.com/pytorch/serve/blob/master/docs/batch_inference_with_ts.md
* There should be no "the" in the phrase "in machine learning/deep learning"
* Neither machine learning nor deep learning should be capitalized or hyphenated
* Missing word in "This functionality provides customer using TorchServe..."
* "lesser" should be "less than"
* Several compound adjectives needing hyphenation
* More I didn't have time to write up

https://github.com/pytorch/serve/blob/master/docs/custom_service.md
* "Model Server" shouldn't be capitalized
* The phrase "by Model Server for PyTorch (TorchServe)" is ungrammatical, unclear, and implies the existence of only one model server for PyTorch of any kind
* "...using a initialize() method..." should be an "an"
* "... that is where you would normally..." unclear what "that" means, but either "that" or "where" is not a grammatical word choice. It's unclear which.

**Comment by brianjo** [comment]
Thanks for the detailed information Jeff. We'll do an edit pass and fix it up.

**Comment by jspisak** [comment]
@aaronmarkham - can you look at this?

**Comment by aaronmarkham** [comment]
A lot of these things were already fixed but merged into a staging branch.
https://github.com/pytorch/serve/pull/177
https://github.com/pytorch/serve/pull/176
https://github.com/pytorch/serve/pull/175
https://github.com/pytorch/serve/pull/174
https://github.com/pytorch/serve/pull/173

Stay tuned... Eric will create a new PR to bring back all of those edits that didn't make it in (a hold was put on any further updates from staging, at the cost of losing all of these docs edits).

**Comment by jeffreyksmithjr** [comment]
Great to see that these were already identified. The doc review looks to have been much broader and deeper than I was able to go. Glad that we were able to recover that work and get it in. Looks better.
