### ISSUE TITLE
Broken images in serve/mps.html

### ISSUE THREAD

**Issue by domef** [pytorch/serve#2541]
### 📚 The doc issue

The images are not shown in https://pytorch.org/serve/mps.html

![image](https://github.com/pytorch/pytorch/assets/38183728/d301b2ff-b256-41a1-8322-363e98f3759d)

cc @svekars @carljparker @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by awgu** [comment]
@malfet sorry about that

**Comment by msaroufim** [comment]
@mreso @sekyondaMeta could one of you please take a look and fix please? also could we rename this file to `nvidia_mps`

**Comment by sekyondaMeta** [comment]
> @mreso @sekyondaMeta could one of you please take a look and fix please? also could we rename this file to `nvidia_mps`

Will take a look
