### ISSUE TITLE
Add torch, torchvision, captum and PyYAML to dependencies in the quickstart tutorial

### ISSUE THREAD

**Issue by holma91** [pytorch/serve#2553]
### 📚 The doc issue

If you follow everything line by line in https://pytorch.org/serve/getting_started.html, you will not get to a working example. After debugging multiple dependency errors after one another, I concluded that in addition to the dependencies listed in the tutorial: `pip install torchserve torch-model-archiver torch-workflow-archiver`

You also have to do `pip install torch torchvision captum PyYAML`. 

Without them, the worker just dies and if you run `curl http://127.0.0.1:8080/predictions/densenet161 -T kitten_small.jpg` you'll get:
```json
{
  "code": 500,
  "type": "InternalServerException",
  "message": "Worker died."
}
```

With them, you'll get something like:
```json
{
  "tabby": 0.47816699743270874,
  "lynx": 0.20013423264026642,
  "tiger_cat": 0.16822901368141174,
  "tiger": 0.06191278621554375,
  "Egyptian_cat": 0.05113617330789566
}
```

I'm doing all of this on an M1 mac and on Python 3.11.4, if that matters.

### Suggest a potential alternative/fix

change the line `pip install torchserve torch-model-archiver torch-workflow-archiver` to `pip install torch torchvision captum PyYAML torchserve torch-model-archiver torch-workflow-archiver`

**Comment by msaroufim** [comment]
I suspect this is some bug with our `install_dependencies.py` script that's not making it work on M1 - FWIW we haven't officially supported M1 yet but we probably should
