### ISSUE TITLE
Create Model Zoo with examples

### ISSUE THREAD

**Issue by adityabindal** [pytorch/serve#257]
Add and fix model zoo (removed in https://github.com/pytorch/serve/pull/187)

**Comment by chauhang** [comment]
@harshbafna Can you please describe:

1.  How the index_to_name.json is handled for the modelzoo models. What mappings have been bundled in the .mar files? 
2. Clarify which models are Eager vs TorchScripted models
3. For the text classifier model that uses a vocabulary - please provide reference or details for it in the model zoo doc page
4. Add link of the new model_zoo.md file into the main docs/README.md

**Comment by harshbafna** [comment]
@chauhang : PFB my answers 

> 1. How the index_to_name.json is handled for the modelzoo models. What mappings have been bundled in the .mar files?

All the mar files in the model zoo are created using the [torchserve examples](https://github.com/pytorch/serve/tree/master/examples) . These examples are based on the default handlers. 
For image classification example, please refer following code for image_to_name.json : https://github.com/pytorch/serve/blob/master/ts/torch_handler/image_classifier.py#L59

We use following mapping for image classification, which is the standard imagenet mapping :
https://github.com/pytorch/serve/blob/master/examples/image_classifier/index_to_name.json

> 2. Clarify which models are Eager vs TorchScripted models

In the current model zoo, all the models are eager mode models only.

> 3. For the text classifier model that uses a vocabulary - please provide reference or details for it in the model zoo doc page

We provide a detailed description about the text_classification model in its [documentation](https://github.com/pytorch/serve/tree/master/examples/text_classification) 

We have also have added a comment (with link) to refer examples for details on all the models present in the model_zoo doc https://github.com/pytorch/serve/blob/staging_0_1_1/docs/model_zoo.md

> 4. Add link of the new model_zoo.md file into the main docs/README.md

We have added a link in [ Learn More section](https://github.com/pytorch/serve/tree/staging_0_1_1#learn-more)
