### ISSUE TITLE
jemalloc error

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#2582]
x posting from https://discuss.pytorch.org/t/inference-speed-discrepancies-in-torch-serve/185753/6?u=marksaroufim

**Comment by min-jean-cho** [comment]
Hi @ryan6310, could you try installing the latest Jemalloc? You can install via `conda install -c conda-forge jemalloc`. When using jemalloc with torchserve via `cpu_launcher_enable=true` `cpu_launcher_args=--enable_jemalloc`, the `MALLOC_CONF` will be set to `"oversize_threshold:1,background_thread:true,metadata_thp:auto"`. There shouldn't be such warnings.

**Comment by ryan6310** [comment]
Hey,

That fixed it.  Thanks.
