### ISSUE TITLE
Is there any plan to provide RPC style API for inference?

### ISSUE THREAD

**Issue by mqway** [pytorch/serve#263]
as we know, there are many High-throughput inference job usually. So  Is there any plan to provide RPC API for batch inference scenario?

**Comment by dhanainme** [comment]
The documentation related to for batch inference can be found at 
https://github.com/pytorch/serve/blob/master/docs/batch_inference_with_ts.md

**Comment by lokeshgupta1975** [comment]
@mqway Currently we do not have any plans to provide RPC Style APIs, however as suggested by @dhanainme above, please look at the documentation for batch inference.
