### ISSUE TITLE
Metric non-default unit is not set in Metric object in versions 0.6.1 onwards

### ISSUE THREAD

**Issue by namannandan** [pytorch/serve#2637]
### 🐛 Describe the bug

In versions prior to `0.6.1`, the `unit` for metric objects when a non-default value which is not defined in [unit.py](https://github.com/pytorch/serve/blob/master/ts/metrics/unit.py) is provided is set to the value provided as argument:

https://github.com/pytorch/serve/blob/4236a86dc0a018198ecd3fe261e835b416df739e/ts/metrics/metric.py#L46-L48

In versions `0.6.1` onward, the `unit` attribute is not set when a value not defined in [unit.py](https://github.com/pytorch/serve/blob/master/ts/metrics/unit.py) is provided as argument:

https://github.com/pytorch/serve/blob/0510772a8490fc3e3ea394c21d36858234900287/ts/metrics/metric_abstract.py#L43-L44

Potential fix: The above code snippet in `metric_abstract.py` must also include `self.unit = unit` if the `unit` argument is not defined in [unit.py](https://github.com/pytorch/serve/blob/master/ts/metrics/unit.py).

### Error logs

AttributeError: 'CachingMetric' object has no attribute 'unit'

### Installation instructions

Install torchserve versions `0.6.1` or above.

### Model Packaing

Any model can be used, with code in the handler to emit metrics with units not defined in [unit.py](https://github.com/pytorch/serve/blob/master/ts/metrics/unit.py)

### Versions

Torchserve versions `0.6.0` onwards.

### Repro instructions

Any model can be used, with code in the handler to emit metrics with units not defined in [unit.py](https://github.com/pytorch/serve/blob/master/ts/metrics/unit.py)

**Comment by msaroufim** [comment]
One other weird thing was that the arguments were flipped so if someone is not using keyword arguments they will get BC issues

```
    -def add_metric(self, name, value, idx=None, unit=None, dimensions=None):
    +def add_metric(self, name, value, unit, idx=None, dimensions=None):
```

**Comment by namannandan** [comment]
Did a search on the history of method signature for `add_metric` and found the following:

Up to version `0.6.0`
https://github.com/pytorch/serve/blob/4236a86dc0a018198ecd3fe261e835b416df739e/ts/metrics/metrics_store.py#L183

Changed in version `0.6.1` to enable caching metric implementation
https://github.com/pytorch/serve/blob/0510772a8490fc3e3ea394c21d36858234900287/ts/metrics/metric_cache_yaml_impl.py#L97-L103

Changed in version `0.8.1` to enable backwards compatibility
https://github.com/pytorch/serve/blob/04e0b37dafbd9f98a60d040bbc36f64016fc2c8d/ts/metrics/metric_cache_abstract.py#L73-L81

@msaroufim could you please point me to the diff where you see the `idx` and `unit` arguments are flipped. We'll need to update documentation in that case.

**Comment by msaroufim** [comment]
It's this PR https://github.com/pytorch/serve/pull/1954
