### ISSUE TITLE
Should not copy the code from awslabs/multi-model-server

### ISSUE THREAD

**Issue by tobegit3hub** [pytorch/serve#270]
Currently most of the code of this project are copied from [awslabs/multi-model-server](https://github.com/awslabs/multi-model-server). Just refer to the source of InferenceRequestHandler.java in [serve](http://t.cn/A6wsMOOY) / [multi-model-server](http://t.cn/A6wsMOO8) and model_service_worker.py in [serve](http://t.cn/A6wsXAN6) / [multi-model-server](http://t.cn/A6wsXANi) etc.

This project should not be the fork of `awslabs/multi-model-server` and we can reuse the same abstraction by deploying the common modules or just extend the functionality of `awslabs/multi-model-server`. Copying the source code is dangerous and make it difficult to maintain when we want to fix the issues or improve the performance.

**Comment by adityabindal** [comment]
TorchServe was initially ported over from the open source Multi-Model Server project (we have an issue to acknowledge MMS here #259 ). But TorchServe is now an independent project that will grow within the PyTorch community based on PyTorch user needs. All new features and enhancements will be implemented natively in TorchServe, and where appropriate, we will learn from other open source projects, including MMS. AWS continues to maintain and support users of the Multi-Model Server project independently.

**Comment by tobegit3hub** [comment]
Thanks @adityabindal . But we still hope the common code of `MMS` and `pytorch/serve` could be reusable meanwhile these code are copying under different licenses.
