### ISSUE TITLE
not found models

### ISSUE THREAD

**Issue by laohur** [pytorch/serve#272]
ENV： ubuntu18, cuda10.2 
modify Dockerfile from Dockerfile.gpu

> RUN pip install ../serve/
RUN pip install torch-model-archiver
RUN mkdir /workspace
WORKDIR /workspace
COPY  config.properties /workspace
ENV TEMP=/workspace/tmp

and mount volumes as model-store
" torchserve --start --ts-config config.properties" or "torchserve --start --model-store model-store --models model-store/densenet161.mar"
can not load or register "densenet161.mar"

>  torchserve --start --model-store model-store --models model-store/densenet161.mar
 2020-04-27 05:42:37,474 [INFO ] main org.pytorch.serve.ModelServer -
TS Home: /usr/local/lib/python3.6/dist-packages
Current directory: /workspace
Temp directory: /workspace/tmp
Number of GPUs: 10
Number of CPUs: 56
Max heap size: 27305 M
Python executable: /usr/bin/python3
Config file: logs/config/20200427053832866-shutdown.cfg
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Model Store: /workspace/model-store
Initial Models: model-store/densenet161.mar
Log dir: /workspace/logs
Metrics dir: /workspace/logs
Netty threads: 32
Netty client threads: 0
Default workers per model: 10
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
2020-04-27 05:42:37,479 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Started restoring models from snapshot {
  "name": "20200427053832866-shutdown.cfg",
  "modelCount": 0,
  "created": 1587965912867,
  "models": {}
}

**Comment by harshbafna** [comment]
@laohur, You only need to supply the mar name with `--models` flag for the models already present in the model-store.

E.g.
```
torchserve --start --model-store model-store --models densenet161.mar
```

> 2020-04-27 05:42:37,479 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Started restoring models from snapshot {
> "name": "20200427053832866-shutdown.cfg",
> "modelCount": 0,
> "created": 1587965912867,
> "models": {}
> }

From the above logs, TorchServe is starting from old snapshot available in `<log_path>/config` direcotry, in which case the models passed through `--models` param will be ignored.

To overcome this problem you can use one of the following options :

1) Use a specific config.properties file to start TorchServe using `--ts-config` flag
2) Start TorchServe with snapshot feature disabled. You can use `--ncs` flag for this.

**Comment by laohur** [comment]
> 
> 
> @laohur, You only need to supply the mar name with `--models` flag for the models already present in the model-store.
> 
> E.g.
> 
> ```
> torchserve --start --model-store model-store --models densenet161.mar
> ```
> 
> > 2020-04-27 05:42:37,479 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Started restoring models from snapshot {
> > "name": "20200427053832866-shutdown.cfg",
> > "modelCount": 0,
> > "created": 1587965912867,
> > "models": {}
> > }
> 
> From the above logs, TorchServe is starting from old snapshot available in `<log_path>/config` direcotry, in which case the models passed through `--models` param will be ignored.
> 
> To overcome this problem you can use one of the following options :
> 
>     1. Use a specific config.properties file to start TorchServe using `--ts-config` flag
> 
>     2. Start TorchServe with snapshot feature disabled. You can use `--ncs` flag for this.

yes, only successed via "config.properties" 
and failed via cmd which likes "torchserve --start --model-store ~/model_store --models ~/model_store/densenet161.mar"

**Comment by harshbafna** [comment]
> yes, only successed via "config.properties"
> and failed via cmd which likes "torchserve --start --model-store ~/model_store --models ~/model_store/densenet161.mar"

If no config file is supplied with --ts-config flag while starting TorchServe, last snapshot in ./logs/configs is used for startup and any models passed through `--models` flag is ignored.

The snapshot feature is by default enabled.

Refer following documentation for more details : https://github.com/pytorch/serve/blob/master/docs/snapshot.md

**Comment by laohur** [comment]
> 
> 
> > yes, only successed via "config.properties"
> > and failed via cmd which likes "torchserve --start --model-store ~/model_store --models ~/model_store/densenet161.mar"
> 
> If no config file is supplied with --ts-config flag while starting TorchServe, last snapshot in ./logs/configs is used for startup and any models passed through `--models` flag is ignored.
> 
> The snapshot feature is by default enabled.
> 
> Refer following documentation for more details : https://github.com/pytorch/serve/blob/master/docs/snapshot.md

Many thanks!
Is ther any benchmark for bert models?  how fast compairing to TensorRT... ?

**Comment by harshbafna** [comment]
@laohur : We currently don't have any benchmark reports related to bert models.

**Comment by laohur** [comment]
> 
> 
> @laohur : We currently don't have any benchmark reports related to bert models.

OR other models。  And how fast compairing to TensorRT... ?

**Comment by DSLituiev** [comment]
I had a similar problem. Cleared the `logs` and it worked. 
It's a very confusing error message. Is there a way to do something about the message or clean the logs automatically?
