### ISSUE TITLE
Neuronx Benchmark runs are failing

### ISSUE THREAD

**Issue by agunapal** [pytorch/serve#2749]
### 🐛 Describe the bug

Benchmark runs for neuronx are failing for the last few days.

### Error logs

N/A

### Installation instructions

N/A

### Model Packaing

N/A

### Versions

Nightly

### Repro instructions

Benchmark runs

**Comment by namannandan** [comment]
Inf2 benchmark has been fixed in these PRs:
- https://github.com/pytorch/serve/pull/2887
- https://github.com/pytorch/serve/pull/2893
- https://github.com/pytorch/serve/pull/2900
Successful benchmark run: https://github.com/pytorch/serve/actions/runs/7649045673
