### ISSUE TITLE
Why TorchServe Don't Supply Authentication?

### ISSUE THREAD

**Issue by BeomseoChoi** [pytorch/serve#2754]
### 🚀 The feature

Should support authentication features.

### Motivation, pitch

I'm using TorchServe to serve my deep learning model.
The initial purpose that I use this framework was just to inference from local server which is in bound.
Now, I would like to open my TorchServe server to public.
For this, I need to grant something for authentication such as token to others who use my server.
But from https://pytorch.org/serve/configuration.html, they say that TorchServe doesn't support authentication.

### Additional context

Does TorchServe have a plan to support authentication features? if so, when it will be at?

**Comment by lxning** [comment]
There is a [ticket](https://github.com/pytorch/serve/issues/2612) to address this request. It is on our roadmap.

**Comment by namannandan** [comment]
Token authorization is now supported in TorchServe `0.10.0`: https://github.com/pytorch/serve/blob/v0.10.0/docs/token_authorization_api.md
