### ISSUE TITLE
How to auto-scale model replicas in a single GPU based EC2 instance based on number-of-requests-in-queue ?

### ISSUE THREAD

**Issue by yogendra-yatnalkar** [pytorch/serve#2766]
Hi team, I mainly had 1 question and 1 observation:
---

### **Question:**

- **I was not able to locate any resource explaining ways to auto-scale ML model in torch-serve on single GPU instance.** 
- I did had a look at the model configuration documentation which explained the 2 parameters: min-workers and max-worker where each worker will have 1 model loaded.  I also had a look at this issue: https://github.com/pytorch/serve/issues/714  where **ts_queue_latency_microseconds** flag was explained to auto-scale in a Kubernetes cluster. 

#### **_But what I need is:_** 

> A way to load more replicas of the model in the same instance based on certain conditions like: number-of-requests-in-queue or something similar.

> **Assumption**: There is sufficient amount of GPU memory remaining and GPU utilization is not 100%

---

### **Observation:** The Problem I faced: 

- I hosted the simple **MNIST classifier example** provided in torch-serve tutorials on a **T4 GPU (G4dn EC2 Instance**) and load tested it using the **Locust Application**
- I had set the max-workers to 2 and min-workers to 1. The batch-size was set to 1. 
- With the help of Locust Application, I gradually sent 1000 requests per sec to the model server. 
- I observed the GPU and CPU memory and compute utilization:
          - GPU memory utilization was less than 3% because the ML model is very small. The compute utilization was also less than 5%. 
          - Even CPU memory and compute was not utilized at max (was higher than GPU but less than 20% of total availability) 
- **Problem**: 
          - **The model server did not process all the requests. At any given point, it only responded to ~700-750 requests and the remaining requests were discarded/dropped** 
          - I dont think the model got replicated as 2nd worker because the GPU memory and compute utilization was very small. 
---

Please let me know if there are any good resources to refer and how to auto-scale based on **ts_queue_latency_microseconds** flag in a single GPU instance.

**Comment by agunapal** [comment]
Hi @yogendra-yatnalkar You can monitor the pending requests in queue and based on a threshold scale the workers up/down

https://github.com/pytorch/serve/blob/master/examples/LLM/llama2/chat_app/torchserve_server_app.py#L51

In the code shared above, I am just displaying the status, but you can use this to define your threshold.

**Comment by yogendra-yatnalkar** [comment]
Hi @agunapal, thanks a lot for the response. I am a beginner in torch-serve hence I believe I was searching the wrong thing. 

I had one question on this: 
- The example seem to use streamlit, which can act as a server itself to continuously monitor the model status and then increase the workers with management API based on the need 
- But how can I replicate it without streamlit ? Is it something possible directly with torch-serve or will I have to place a small server like Flask which will periodically check model status and replicate the above steps ?

**Comment by agunapal** [comment]
Hi @yogendra-yatnalkar In your use-case, I would make use of dynamic batching to solve the issue. Ex: if you set this to 128, the front end would batch 128 requests before sending this to the backend worker.

The example I shared above also shows how to increase the batch size. 

Having multiple workers on a single GPU wouldn't solve the issue as the workers wont be able to execute on CUDA in parallel

**Comment by yogendra-yatnalkar** [comment]
@agunapal understood, thanks. I agree that I should increase the dynamic batch size. If I understand it correctly, if the dynamic batch size is 512, and at a single time-stamp, if 200 requests gets registered --> Then model will form a dynamic batch  of 200 samples for the time stamp and perform the inference. 

Last 2 question before closing this thread: 
- For CUDA parallel problem, if I add more workers on a single GPU, wont it use separate cores for inference ? 

- For working on AWS Neuron, I am of the knowledge that since the model needs to be compiled, it cannot accept dynamic batch size at inference (i.e the model needs to be compiled with the required batch size). During such cases, what will you suggest ? 

---

Thanks a lot in advance.

**Comment by agunapal** [comment]
@yogendra-yatnalkar yes there is also a max_batch_delay parameter you can configure.  The requests which come by then will be batched.

Yes, you are right. It will be excuted in parallel. Sorry, i was thinking of a different usecase where it wont work if we are using shared memory.

For aws neuron, i believe that is the current behavior

**Comment by yogendra-yatnalkar** [comment]
Thanks again for all the support since many weeks. 

---
**On a side note:** 
For AWS Neuron, I dont have much experience, but I believe there can be a way where I can add random vectors to fill the required batch-size. Eg. If I set the batch size to "N" during compilation, but during runtime, at time-stamp "T", only N/2 samples are incoming. Then I can fill the remaining N/2 samples with random vector and remove those later. 

***I am not sure how I can do that at this point, but thanks, I am clear for now.**
