### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by sunanlin13174** [pytorch/serve#277]
i used pip install the torchserve on windows.The environment is 
windows10
python 3.7.3
jdk-11.0.7
torch 1.4
torchvision 0.5
I succeeded in getting a mar file by tutorials,but an error occurs when i run this command:
torchserve --start --model-store ~/model_store --models ~/model_store/densenet161.mar

Error: Could not find or load main class org.pytorch.serve.ModelServer
Caused by: java.lang.ClassNotFoundException: org.pytorch.serve.ModelServer

i dont know how to solve it,please give me some advice..

**Comment by harshbafna** [comment]
@sunanlin13174 : Currently `TorchServe` is supported only on Ubuntu and MacOS and not on windows.

**Comment by sunanlin13174** [comment]
> @sunanlin13174 : Currently `TorchServe` is supported only on Ubuntu and MacOS and not on windows.

oh,thank you, i will try it on linux,Thanks to the developers for their hard work
