### ISSUE TITLE
Object Detection worker dies 

### ISSUE THREAD

**Issue by Guillem96** [pytorch/serve#281]
I am deploying a FasterRCNN model with 2 workers, and when I POST an image to the inference API as follows:

```curl -X POST http://localhost:8080/predictions/faster-rcnn -T image.png```

The server responds with this error:

```json
{
  "code": 507,
  "type": "InternalServerException",
  "message": "Worker died."
}
```

I first thought that this issue was related to memory usage, but I am increasing the Java VM memory by setting this options to the ts config file: `vmargs=-Xmx12g` and I am still getting this 507 error.

The server logs are:

```
2020-04-29 06:57:02,007 [INFO ] epollEventLoopGroup-4-2 org.pytorch.serve.wlm.WorkerThread - 9001 Worker disconnected. WORKER_MODEL_LOADED
2020-04-29 06:57:02,057 [DEBUG] W-9001-faster-rcnn_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:128)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Can someone help me?

Also I want to thank Pytorch team for this awesome work.

Environment details:

- Windows using docker image [pytorch/torchserve:0.1-cpu](https://hub.docker.com/layers/pytorch/torchserve/0.1-cpu/images/sha256-ef95375236b55e3d0e90b3da71ebe7d32d5d7f3b33c34aa70cedf1936ad1cead?context=explore)

Log file: [ts_log.log](https://github.com/pytorch/serve/files/4550172/ts_log.log)

**Comment by harshbafna** [comment]
@Guillem96 : Could you please share the following environment details :

 - OS
 - Python version
 - PyTorch and TorchVision version
 - JDK version

Please also attach the ts_log.log file from the logs directory.

**Comment by harshbafna** [comment]
@Guillem96 : Thanks for the update, I will validate this on the docker image shared. I assume, you registered the model through some public URL. Could you please share the model url and the commands you used for registration and inference.

**Comment by Guillem96** [comment]
It is my own model, It is working perfectly with a si gle worker, but when increasing the workers to 2, then the error raises

**Comment by harshbafna** [comment]
@Guillem96 : Could you please provide the model and the command used for creating the model-archive?

**Comment by Guillem96** [comment]
@harshbafna 

 *Upload as txt because GitHub is not allowing .py*

Model handler: [handler.txt](https://github.com/pytorch/serve/files/4550596/handler.txt)
Model file: [model.txt](https://github.com/pytorch/serve/files/4550595/model.txt)

Model archive command: 

```
$ torch-model-archiver \
    --model-name faster_rcnn \
    --serialized-file faster_rcnn.pt \
    --handler handler.py \
    --model-file model.py
```

TS config file:

```
# Server properties
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
job_queue_size=100

# Model archives location
load_models=all
default_workers_per_model=1
model_store=/image-asset-server/model-store

# Java VM arguments
vmargs=-Xmx12g
```

**Comment by harshbafna** [comment]
@Guillem96 : I modified the you load function in the model.py as follows as I didn't had the checkpoint file you used while creating the mar file :

```
@classmethod
    def load(cls, checkpoint_path, map_location):
        checkpoint = torch.load(checkpoint_path, map_location=map_location)

        model = build_model().to(map_location)

        model.load_state_dict(checkpoint['model_state'])
        model.eval()

        return cls(model, False)
```

And saved the checkpoint as follows :

```
import torch
from model import ObjectDetector

from model import build_model

model = build_model()

torch.save(
    dict(
        model_state=model.state_dict(),
    ),
    'faster_rcnn.pt'
)
```

With the above changes, I created the mar file and was successfully able to register it on TorchServe with 4 workers and run multiple inferences on the same.

Environment :
Ubuntu 18.04 with docker image :[pytorch/torchserve:0.1-cpu](https://hub.docker.com/layers/pytorch/torchserve/0.1-cpu/images/sha256-ef95375236b55e3d0e90b3da71ebe7d32d5d7f3b33c34aa70cedf1936ad1cead?context=explore)


> $ torch-model-archiver \
>     --model-name faster_rcnn \
>     --serialized-file faster_rcnn.pt \
>     --handler handler.py \
>     --model-file model.py

You have version flag missing in your torch-model-archiver command, which is mandatory. I am assuming this is just a typo here.

Could you share the checkpoint file you used for reproducing the issue?

**Comment by Guillem96** [comment]
@harshbafna I attach my checkpoint. 

https://drive.google.com/file/d/1Eil_1-BlJRmOa8q1XRkV6NR7rF_1hy83/view?usp=sharing

**Comment by harshbafna** [comment]
@Guillem96 : The model works just with the provided checkpoint as well. 

I am able to run prediction on the model as well. Following metrics is also getting logged:

```
2020-04-29 16:14:16,118 - InferenceTime.Seconds:1.9499194622039795|#ModelName:faster_rcnn,Level:Model|#hostname:7c6ab4c539d6,requestID:2409d2a2-607b-4feb-87f1-54ac5b42cb1b,timestamp:1588176856
2020-04-29 16:14:16,119 - PostProcessingTime.Seconds:0.00012969970703125|#ModelName:faster_rcnn,Level:Model|#hostname:7c6ab4c539d6,requestID:2409d2a2-607b-4feb-87f1-54ac5b42cb1b,timestamp:1588176856
2020-04-29 16:14:16,119 - PredictionTime.Milliseconds:1966.95|#ModelName:faster_rcnn,Level:Model|#hostname:7c6ab4c539d6,requestID:2409d2a2-607b-4feb-87f1-54ac5b42cb1b,timestamp:1588176856
```

**Comment by Guillem96** [comment]
Have you tried to run predicions in paralel?

**Comment by harshbafna** [comment]
I am running on ubuntu 18:04, c4.4xlarge EC2 instance with the docker image : [pytorch/torchserve:0.1-cpu](https://hub.docker.com/layers/pytorch/torchserve/0.1-cpu/images/sha256-ef95375236b55e3d0e90b3da71ebe7d32d5d7f3b33c34aa70cedf1936ad1cead?context=explore)

**Comment by Guillem96** [comment]
It Is not trained with coco I am using a custom dataset. Maybe the issue is related to Windows an Docker for windows.

I will try to run the code on a GCP compute engine with ubuntu and see what happens

**Comment by Guillem96** [comment]
@harshbafna Works when running the docker image on a Ubuntu. The issue must be related with Docker for windows and how it manage the memory.

Thanks for helping.

**Comment by ucb-pb** [comment]
Mac also has this problem for me, but wanted to note here that switching to ubuntu also fixed it

**Comment by harshbafna** [comment]
@ucb-pb: Could you please create a fresh ticket with setup details and logs. Please also share the docker's memory and CPU configuration.
