### ISSUE TITLE
Read .mar archive file into a readable format

### ISSUE THREAD

**Issue by uzaymacar** [pytorch/serve#284]
Is there a way I can read the `.mar` archive file as a dictionary, JSON, etc.? Any resources or suggestions will be helpful!

**Comment by dhaniram-kshirsagar** [comment]
Why do you want to read mar file? In general, it is zip archive.

**Comment by uzaymacar** [comment]
Thank you, this was helpful. When unzipped, I saw that the only file I didn't specify in the `torch-model-archiver` command was the self-generated `MAR-INF/MANIFEST.json` file. We have a `.mar` the file that is working on one setup and not working on another setup so we wanted to see what might be causing this issue.
