### ISSUE TITLE
When registering a model, initial_workers not working.

### ISSUE THREAD

**Issue by Git-TengSun** [pytorch/serve#2851]
When specifying minWorkers and maxWorkers in the model-config.yaml file, the initial_workers parameter no longer takes effect when registering the model using curl.

torchserve 0.9.0

**Comment by lxning** [comment]
@Git-TengSun could you provide the details in your configuration?
- minWorkers and maxWorkers in the model-config.yaml file
- register curl cmd

**Comment by Git-TengSun** [comment]
@lxning 
model-config.yaml 
```
# TS frontend parameters
# See all supported parameters: https://github.com/pytorch/serve/blob/master/frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelConfig.java#L14 
minWorkers: 1 # default: #CPU or #GPU
maxWorkers: 1 # default: #CPU or #GPU
batchSize: 1 # default: 1
maxBatchDelay: 100 # default: 100 msec
responseTimeout: 120 # default: 120 sec
#deviceType: cpu # cpu, gpu, neuron
#deviceIds: [0,1,2,3] # gpu device ids allocated to this model. 
#parallelType: pp # pp: pipeline parallel; pptp: tensor+pipeline parallel. Default: empty

# See torchrun parameters: https://pytorch.org/docs/stable/elastic/run.html
#torchrun:
#  nproc-per-node: 2

# TS backend parameters
#pippy:
#  rpc_timeout: 1800
#  pp_group_size: 4 # pipeline parallel size, tp_group_size = world size / pp_group_size
```
curl cmd
```
curl -X POST "localhost:8081/models?model_name=efficientnet_b7&url=efficientnet-b7.mar&batch_size=4&max_batch_delay=100&initial_workers=2&synchronous=false"
```
batch_size also doesn't work. When I comment out minWorkers, maxWorkers and batchSize, the curl command line becomes normal.

**Comment by lxning** [comment]
@Git-TengSun the number of workers should be [#minWorkers, #maxWorkers]. The initialWorker is set as 2 which is larger than #maxWorkers. TorchServe will automatically adjust the number of workers.

Regarding to batchSize, TorchServer uses Dynamic batching. It means the real batch size is set based on traffic volume. It is not a fixed value. In your case, backend should receive 4 requests in high traffic volume (ie, frontend queue is saturated). could you let me know how you detected batchSize didn't work? Thanks!

**Comment by Git-TengSun** [comment]
@lxning 
According to https://github.com/pytorch/serve/blob/master/docs/configuration.md，the REST or gRPC model management API has the highest priority.I think the curl command line will override the parameters in the model configuration file.  
Regarding batch, logs and the information of the model viewed by the curl command,both show that batchsize is still 1.

**Comment by lxning** [comment]
@Git-TengSun 
- You are right the curl command has the highest priority. Could you add minWorkers and maxWorkers in the curl command? For example:
curl -X POST "localhost:8081/models?model_name=efficientnet_b7&url=efficientnet-b7.mar&batch_size=4&max_batch_delay=100&maxWorkers=2&initial_workers=2&synchronous=false"

Let me know if the above command still does not work.

- For batch size, could you provide the logs and the information of the model viewed by the curl command and the reproduce steps so that i can take a look? Thanks.

**Comment by Git-TengSun** [comment]
@lxning 
Based on https://github.com/pytorch/serve/tree/master/examples/image_classifier/resnet_152_batch, I deployed two models, resnet152_0 and resnet152_1, with different model configuration files. The same problem will occur.
## resnet152_0  
model-config-0.yaml：
```
# TS frontend parameters
# See all supported parameters: https://github.com/pytorch/serve/blob/master/frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelConfig.java#L14 
minWorkers: 1 # default: #CPU or #GPU
maxWorkers: 1 # default: #CPU or #GPU
batchSize: 1 # default: 1
maxBatchDelay: 50 # default: 100 msec
responseTimeout: 120 # default: 120 sec
```
deploy model
```
#pack
torch-model-archiver --model-name resnet-152-batch-0 --version 1.0 --model-file examples/image_classifier/resnet_152_batch/model.py --serialized-file resnet152-394f9c45.pth --handler image_classifier --extra-files examples/image_classifier/index_to_name.json -c model-config-0.yaml
#register
curl -X POST "localhost:8081/models?model_name=resnet152_0&url=resnet-152-batch-0.mar&batch_size=2&max_batch_delay=5000&maxWorkers=2&initial_workers=2&synchronous=true"
```
result
![企业微信截图_17026071703291](https://github.com/pytorch/serve/assets/53203204/6328c800-df5b-4aba-87d8-56f98c7c1a26)

![企业微信截图_17026075312641](https://github.com/pytorch/serve/assets/53203204/2e6fea4d-80ff-4073-b056-bba68c33776b)
It can be seen that batch_size=2&maxWorkers=2&initial_workers=2 does not work.
## resnet152_1  
model-config-1.yaml：
```
# TS frontend parameters
# See all supported parameters: https://github.com/pytorch/serve/blob/master/frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelConfig.java#L14 
#minWorkers: 1 # default: #CPU or #GPU
#maxWorkers: 1 # default: #CPU or #GPU
#batchSize: 1 # default: 1
maxBatchDelay: 50 # default: 100 msec
responseTimeout: 120 # default: 120 sec
```
deploy model
```
#pack
torch-model-archiver --model-name resnet-152-batch-1 --version 1.0 --model-file examples/image_classifier/resnet_152_batch/model.py --serialized-file resnet152-394f9c45.pth --handler image_classifier --extra-files examples/image_classifier/index_to_name.json -c model-config-1.yaml
#register
curl -X POST "localhost:8081/models?model_name=resnet152_1&url=resnet-152-batch-1.mar&batch_size=2&max_batch_delay=5000&initial_workers=2&synchronous=true"
```
result
![企业微信截图_17026072393170](https://github.com/pytorch/serve/assets/53203204/06022140-f292-4040-be67-ebf85c93ff33)

![企业微信截图_170260655522](https://github.com/pytorch/serve/assets/53203204/24a966de-3d60-4d0c-8c48-a6ba11ee08d3)
It can be seen that curl can register normally.

**Comment by agunapal** [comment]
closing as this has been fixed.
