### ISSUE TITLE
Torchserve Error: number of batch response mismatched

### ISSUE THREAD

**Issue by rajeshmore1** [pytorch/serve#2853]
### 🐛 Describe the bug

We deployed NER Model with n1-standard-8 machine without GPU with below config properties. when we kept batch size as 1, it is taking more time to process the simultaneous requests. when we try to increase the batch size, we are getting below error. (we tried with different batch size like 16,32,64,8 etc and max workers as 1 and 8). I want to process multiple threads simultaneously. Please suggest solution. Do I need to change handler script, if yes, how? How to increase throughput?

### Error logs

Response: response_data: {'code': 503, 'type': 'InternalServerException', 'message': 'number of batch response mismatched'}

### Installation instructions

Yes, we are using docker container to deploy the model on vertex ai

### Model Packaing

Using docker and creating a custom prediction container and packaging all the serving scripts like handler.py, config properties etc

### config.properties

inference_address=http://0.0.0.0:8090
management_address=http://0.0.0.0:8091
metrics_address=http://0.0.0.0:8092
install_py_dep_per_model=true
prefer_direct_buffer=true
job_queue_size=10000
async_logging=true
number_of_netty_threads=8
netty_client_threads=8
default_workers_per_model=1
models={\
  "description": {\
    "1.0": {\
        "defaultVersion": true,\
        "marName": "description.mar",\
        "minWorkers": 1,\
        "maxWorkers": 8,\
        "batchSize": 16,\
        "maxBatchDelay": 65,\
        "responseTimeout": 100\
    }\
  }\
}

### Versions

we are using this base image

pytorch/torchserve:latest-gpu

### Repro instructions

we carried out performance testing using 5/10/20 simultaneous users hitting vertex ai endpoint but avg time is around 20 seconds which is very high for 20 simultaneous users.

### Possible Solution

How to optimize the config parameters? Do I need to update handler script? Please suggest a way

**Comment by agunapal** [comment]
@rajeshmore1 Could you please share the logs and if possible, the handler you are using?

**Comment by agunapal** [comment]
If you are running on intel cpu, please refer to this link to improve performance

https://github.com/pytorch/serve/tree/master/examples/intel_extension_for_pytorch

**Comment by rajeshmore1** [comment]
@agunapal Fyi The handler script


from abc import ABC
import json
import logging
import os
from collections import defaultdict

import torch
import spacy
import pickle
import re

from ts.torch_handler.base_handler import BaseHandler

logger = logging.getLogger(__name__)


class SpacyNERHandler(BaseHandler, ABC):
    """
    Transformers text classifier handler class. This handler takes a text (string) and
    as input and returns the classification text based on the serialized transformers checkpoint.
    """
    def __init__(self):
        super(SpacyNERHandler, self).__init__()
        self.initialized = False

    def initialize(self, ctx):
        self.manifest = ctx.manifest

        properties = ctx.system_properties
        model_dir = properties.get("model_dir")


        # model_dir = properties.get("model_dir")
        # serialized_file = self.manifest["model"]["serializedFile"]
        apn_model_pt_path = os.path.join(model_dir, "apn_model.pkl")
        condo_model_pt_path = os.path.join(model_dir, "condo_model.pkl")
        address_unit_model_pt_path = os.path.join(model_dir, "address_unit_model.pkl")
        condo_lot_model_pt_path = os.path.join(model_dir, "condo_lot_model.pkl")
        non_condo_lot_model_pt_path = os.path.join(model_dir, "non_condo_lot_model.pkl")
        lot_range_model_pt_path = os.path.join(model_dir, "lot_range_model.pkl")
        condo_unit_model_pt_path = os.path.join(model_dir, "condo_unit_model.pkl")

        # self.model = pickle.load(open(model_pt_path,"rb"))


        self.apn_model = pickle.load(open(apn_model_pt_path, 'rb'))
        self.condo_model = pickle.load(open(condo_model_pt_path , 'rb'))
        self.address_unit_model = pickle.load(open(address_unit_model_pt_path, 'rb'))
        self.condo_lot_model = pickle.load(open(condo_lot_model_pt_path, 'rb'))
        self.non_condo_lot_model = pickle.load(open(non_condo_lot_model_pt_path, 'rb'))
        self.lot_range_model = pickle.load(open(lot_range_model_pt_path, 'rb'))
        self.condo_unit_model = pickle.load(open(condo_unit_model_pt_path, 'rb'))
        

        logger.debug('Spacy model from path {0} loaded successfully'.format(model_dir))


        self.initialized = True

    def nlp_model(self, _id,text_id_input):
        # self.apn_model = pickle.load(open('./model_archive/apn_model.pkl', 'rb'))
        # self.condo_model = pickle.load(open('./model_archive/condo_model.pkl', 'rb'))
        # self.address_unit_model = pickle.load(open('./model_archive/address_unit_model.pkl', 'rb'))
        # self.condo_lot_model = pickle.load(open('./model_archive/condo_lot_model.pkl', 'rb'))
        # self.non_condo_lot_model = pickle.load(open('./model_archive/non_condo_lot_model.pkl', 'rb'))
        # self.lot_range_model = pickle.load(open('./model_archive/lot_range_model.pkl', 'rb'))
        # self.condo_unit_model = pickle.load(open('./model_archive/condo_unit_model.pkl', 'rb'))
        _id = f"{_id}"
        text = f"{text_id_input}"
        text = text.upper()
    #     text = text.replace('&APOS;','').replace('?','').replace('&QUOT','').replace('?','')
        text = text.replace('&APOS;','').replace('?','').replace('&QUOT','').replace('?','').replace(';',' ').replace('(','').replace(')','')

        text_check = re.sub('[^a-zA-Z0-9 \n\.]', '', text)

        apn_list = []
        condo_list = []
        condo_unit_list = []
        address_unit_list = []
        non_condo_lot_list = []
        condo_lot_list = []
        non_condo_lot_range_list = []
        condo_lot_range_list = []
        output_non_condo_lot_ranges = []
        output_condo_lot_ranges = []         
            
        output = []

        # check if legal description is valid

        if (text_check.isdigit()==True) or (text_check.isalpha()==True):
            output.append({ 'document_id': _id, 'apn':[], 'condo_flag': [],
                        'condo_unit': [], 'address_unit':[]
                        ,
                        'non_condo_lot': []
                        , 'condo_lot': []
                        })

        else:
            apn_doc = self.apn_model(text)
            condo_doc = self.condo_model(text)
            condo_unit_doc = self.condo_unit_model(text.replace(',', ', ').replace('.', ' '))
            address_unit_doc = self.address_unit_model(text)
            non_condo_lot_doc = self.non_condo_lot_model(text.replace(',', ', ').replace(' LO T ', ' LOT ').replace(' LO TS ', ' LOTS '))
            condo_lot_doc = self.condo_lot_model(text)
            lot_range_doc = self.lot_range_model(text)
            
            # lot_ranges
            if len(lot_range_doc.ents)>0:
                try:
                    for ent in lot_range_doc.ents:
                        range_list = []
                        start = int(ent.text.replace('-',' ').split()[0])
                        try:
                            end = int(ent.text.replace('-',' ').split()[len(ent.text.replace('-',' ').split())-1])
                        except:
                            end = start+1
                        for r in range(start,end+1 ):
                            range_list.append(r)
                            for n in range_list:
                                if ent.label_=='FullySubjectLotRanges':
                                    non_condo_lot_range_list.append(('Fully Subject Lot',n))
                                elif ent.label_=='PartialSubjectLotRanges':
                                    non_condo_lot_range_list.append(('Partial Subject Lot',n))
                                elif ent.label_=='NonSubjectLotRanges':
                                    non_condo_lot_range_list.append(('Non-Subject Lot',n))   
                                elif ent.label_=='CondoLotRanges':
                                    condo_lot_range_list.append(('Condo Lot',n.astype(string)))
                    output_non_condo_lot_ranges = list(set(non_condo_lot_range_list))
                    output_condo_lot_ranges = list(set(condo_lot_range_list))
                except:
                    output_condo_lot_ranges = []
                    output_non_condo_lot_ranges = []

            # APN
            if len(apn_doc.ents)>0:
                try:
                    for ent in apn_doc.ents:
                        apn_list.append(ent.text)
                    output_apn = list(set(apn_list))
                except:
                    output_apn = []
            else:
                output_apn = []
                

            # CONDO UNITS    
            if len(condo_unit_doc.ents)>0:
                try:
                    for ent in condo_unit_doc.ents:
                        range_list = []
                        if 'TH' in ent.text:
                            condo_unit_doc = self.condo_unit_model(text.replace('THROUGH ','THROUGH'))
                            for ent in condo_unit_doc.ents:
                                start = int(ent.text.replace('THROUGH', ' ').split()[0])
                                try:
                                    end = int(ent.text.replace('THROUGH', ' ').split()[len(ent.text.replace('THROUGH', ' ').split())-1])
                                except:
                                    end = start+1
                                for r in range(start, end+1):
                                    # print('r', r)
                                    range_list.append(r)
                                    for n in range_list:
                                        condo_unit_list.append((n))
                    

                        else:
                            condo_unit_list.append(ent.text)
                    output_condo_unit = list(set(condo_unit_list))
                except:
                    output_condo_unit = []  
            else:
                output_condo_unit = [] 
            
            # ADDRESS UNIT
            if len(address_unit_doc.ents)>0:
                try:
                    for ent in address_unit_doc.ents:
                        address_unit_list.append(ent.text)
                    output_address_unit = list(set(address_unit_list))
                except:
                    output_address_unit = []  
            else:
                output_address_unit = []  
                
            # CONDO LOT
            if len(condo_doc.ents)>0 and len(condo_unit_doc.ents)>0 :
                try:
                    if len(condo_lot_doc.ents)>0:
                        for ent in condo_lot_doc.ents:
                            condo_lot_list.append((ent.label_, ent.text))
                        output_condo_lot = list(set(condo_lot_list))
                        output_non_condo_lot = []
                    else:
                        output_condo_lot = [] 
                        output_non_condo_lot = [] 
                except:
                    output_condo_lot = [] 
                    output_non_condo_lot = []                 

            else: 
            # NON-CONDO LOT    
                try:
                    if len(non_condo_lot_doc.ents)>0:

                            for ent in non_condo_lot_doc.ents:
                                non_condo_lot_list.append((ent.label_, ent.text))

                            output_non_condo_lot = list(set(non_condo_lot_list))
                            output_condo_lot = []
                            # print(output_non_condo_lot)
                    else:
                        output_non_condo_lot = [] 
                        output_condo_lot = []
                except:
                    output_non_condo_lot = [] 
                    output_condo_lot = []                   



            # print('lot output',output_non_condo_lot)
            # COMBINE LOT
            try:
                if len(condo_doc.ents)>0 and len(condo_unit_doc.ents)>0 :
                    if output_condo_lot_ranges!=[] and output_condo_lot!=[]:
                        # print('4')
                        output_condo_lot_final = list(set(output_condo_lot_ranges+ output_condo_lot))
                        output_non_condo_lot_final=[]
                    elif output_condo_lot_ranges!=[] and output_condo_lot==[]:
                        # print('5')
                        output_condo_lot_final = list(set(output_condo_lot_ranges)) 
                        output_non_condo_lot_final=[]
                    elif  output_condo_lot_ranges==[] and output_condo_lot!=[]:
                        # print('6')
                        output_condo_lot_final = list(set(output_condo_lot))
                        output_non_condo_lot_final=[]
                    else:
                        # print('7')
                        output_condo_lot_final=[]              
                        output_non_condo_lot_final=[]  
                    # print(output_non_condo_lot_final)
                    # print(output_condo_lot_final)
                else:
                    if output_non_condo_lot_ranges!=[] and output_non_condo_lot!=[]:
                        # print('1')
                        output_non_condo_lot_final = list(set(output_non_condo_lot_ranges+ output_non_condo_lot))
                        output_condo_lot_final=[]  
                    elif output_non_condo_lot_ranges!=[] and output_non_condo_lot==[]:
                        # print('2')
                        output_non_condo_lot_final = list(set(output_non_condo_lot_ranges)) 
                        output_condo_lot_final=[]  
                    elif  output_non_condo_lot_ranges==[] and output_non_condo_lot!=[]:
                        # print('3')
                        output_non_condo_lot_final = list(set(output_non_condo_lot))
                        output_condo_lot_final=[]                 
                    else:
                        output_non_condo_lot_final=[]
                        output_condo_lot_final=[] 
                    # print(output_non_condo_lot_final)
                    # print(output_condo_lot_final)

            except:
                output_non_condo_lot_final=[]
                output_condo_lot_final =[]



            # CONDO FLAG
            if len(condo_doc.ents)>0 and len(condo_unit_doc.ents)>0 :
                for ent in condo_doc.ents:
                    condo_list.append(ent.text)
                    output_condo = [True]
        
            else:
                output_condo = [False]  

            # ADD RULES TO ALIGN CONDO FLAG AND CONDO UNIT

            # NOT A CONDO, YET A CONDO UNIT: REMOVE CONDO UNIT
            if output_condo == [False] and output_condo_unit!=[]:
                output.append({ 'document_id': _id, 'apn':output_apn, 'condo_flag': output_condo,
                        'condo_unit': [], 'address_unit':output_address_unit
                        ,
                        'non_condo_lot': output_non_condo_lot_final
                        , 'condo_lot': output_condo_lot_final
                        })
            # A CONDO, YET NO CONDO UNIT: REMOVE CONDO FLAG
            elif output_condo == [True] and output_condo_unit==[]:
                output.append({ 'document_id': _id, 'apn':output_apn, 'condo_flag': [False],
                        'condo_unit': [], 'address_unit':output_address_unit
                        ,
                        'non_condo_lot': output_non_condo_lot_final
                        , 'condo_lot': output_condo_lot_final
                        })
            # OTHERS:
            else:
                output.append({ 'document_id': _id, 'apn':output_apn, 'condo_flag': output_condo,
                        'condo_unit': output_condo_unit, 'address_unit':output_address_unit
                        ,
                        'non_condo_lot': output_non_condo_lot_final
                        , 'condo_lot': output_condo_lot_final
                        })

        return output
   


    def inference(self, inputs):

        
        """
        Predict the class of a text using a trained transformer model.
        """
        # NOTE: This makes the assumption that your model expects text to be tokenized
        # with "input_ids" and "token_type_ids" - which is true for some popular transformer models, e.g. bert.
        # If your transformer model expects different tokenization, adapt this code to suit
        # its expected input format.

        try:
            text1 = inputs[0]['body']['instances'][0]['data']['content']
            id1 = inputs[0]['body']['instances'][0]['data']['id']
            # text = inputs.get_json()['content']
            # id = inputs.get_json()['id']
        except:
            text1 = 'BEGINNING AT A STAKE ON THE EDGE'
            id1 = 'invalid-id'
        
    
        # text = inputs.get('content')
        # id = inputs.get('id')
        logger.info(f"predicting for {inputs} and type {type(inputs)}")
        logger.info(f"text is {text1} and id is {id1}")
        # anotate = self.nlp_model(_id = id, text_id_input = text)
        #anotate = self.nlp_model(_id = id1, text_id_input = text1)
        
        try:
            anotate = self.nlp_model(_id = id1, text_id_input = text1)
            # anotate = response
            
        except:
            anotate = {'predictions':{'invalid-request': id}, 'id':id1}
     
        # predictions = []
        # for i, doc in enumerate(self.model.pipe(inputs, n_threads = -1)):
        #     meta_dict = defaultdict(list)
        #     for ent in doc.ents:
        #         meta_dict[ent.label_].append(ent.text)
        #     predictions.append(meta_dict)
        logger.info("Model predicted: '%s'", anotate)

        return anotate

    def postprocess(self, inference_output):
        # TODO: Add any needed post-processing of the model predictions here
        #inference_output = inference_output[0]
        #inference_output = str(inference_output)
        return [{ "predictions": inference_output}]
        #return {"predictions": inference_output}
        # return inference_output
        # return json.dumps(inference_output)


_service = SpacyNERHandler()


def handle(data, context):
    try:
        if not _service.initialized:
            _service.initialize(context)

        if data is None:
            return None

        data = _service.inference(data)
        data = _service.postprocess(data)

        return data
    except Exception as e:
        raise e

**Comment by rajeshmore1** [comment]
We used pytorch/torchserve:latest-gpu this base image because if we want to go for gpu in future, we don't need to update this. Is this base image causing a problem for getting good throughput (without gpu)? Please guide.

**Comment by agunapal** [comment]
@rajeshmore1 No, that should be fine. Can you please check the ipex example that I shared.

**Comment by agunapal** [comment]
The error happens here https://github.com/pytorch/serve/blob/master/ts/service.py#L161

I notice that you have many try/except statements . If a batch of 4 is being processed, the result must have 4 elements. Please make sure you are handling this

To benchmark torchserve and see the effect of num_workers , you can use this example to benchmark with different batch_sizes. concurrent requests, workers 
https://github.com/pytorch/serve/tree/master/examples/benchmarking/resnet50

**Comment by rajeshmore1** [comment]
What I understood is I need to update the handler script that will process the multiple requests let's say 4? Could you please provide sample scrip for that? Do I need to update the inference function? Could you please elaborate this solution?

Also I will try to implement the ipex example that you have provided and let you know.

**Comment by agunapal** [comment]
@rajeshmore1 You can refer to this https://github.com/pytorch/serve/blob/master/examples/image_classifier/near_real_time_video/near_real_time_video_handler.py

Basically, you need to make sure that if `n` requests are being batched, the output has a list of `n` elements

If this is not happening, problem is usually in the pre-process or post-process function. You can print the number of elements or use a debugger.

You can also follow this example to debug your handler with a debugger 

https://github.com/pytorch/serve/tree/master/examples/image_classifier/resnet_18#debug-torchserve-backend

**Comment by rajeshmore1** [comment]
Thank you. We are working on it.

**Comment by agunapal** [comment]
please re-open if you need more assistance
