### ISSUE TITLE
The workers works in parallelism? 

### ISSUE THREAD

**Issue by IonBoleac** [pytorch/serve#2866]
### 📚 The doc issue

This is not an issue. How the workers works in parallelism and if they works in parallelism?

**Comment by agunapal** [comment]
@IonBoleac Yes, these are python processes. If you have a multi-GPU instance, you can choose to assign each GPU to a worker. In an intel CPU based instance, you can use core pinning to distribute the physical cores evenly between all the workers

**Comment by IonBoleac** [comment]
@agunapal thanks for your answer... In this case the workers of a model works in parallel? If the serving receive a request for a inference., then this request can be divided in all workers assigned to this model? Thus the request is elaborated in parallel form all workers or one worker for only one request?

**Comment by IonBoleac** [comment]
@agunapal thangs very much for your eventually help

**Comment by agunapal** [comment]
@IonBoleac No, each worker will handle a single request sent from the frontend at a time. This request can be either dynamically batched or not depending on the config. 
If multiple clients are sending requests at the same time, then having multiple workers can process these in parallel instead of being sequential

**Comment by IonBoleac** [comment]
@agunapal thnaks very much... I've an another question. What is the sense to use minWorker and maxWorker if there isn't autoscaling of the workers? The single way to increase or decrease the workers is form management API

**Comment by lxning** [comment]
@IonBoleac It is expensive for worker process to auto scale. Currently TorchServe only supports increase or decrease the worker via management API

**Comment by IonBoleac** [comment]
@lxning thanks for your help...
