### ISSUE TITLE
Difference between `Custom handler with module level entry point` and `Custom handler with class level entry point`

### ISSUE THREAD

**Issue by IonBoleac** [pytorch/serve#2890]
### 📚 The doc issue

# Not an issue
What is the difference between `Custom handler with module level entry point` and `Custom handler with class level entry point`?
Can you give me any examples? 
Thanks for help

**Comment by mreso** [comment]
Hi @IonBoleac,

the difference is that for [module level entry point](https://github.com/pytorch/serve/blob/4a110235b334f46564d0c3d1ba8946806368b075/ts/model_loader.py#L170C19-L170C19) you provide a single function that is called for model initialization and prediction (handle). It is supposed to take two arguments: data and ctx. If data is None the function should initialize the model. When data is not None do inference on it. In the [class level entry point](https://github.com/pytorch/serve/blob/4a110235b334f46564d0c3d1ba8946806368b075/ts/model_loader.py#L175) case this corresponds to the two methods that need to be provided by the class: initialize and handle. The recommended way (and the one most if not all our examples use) is the class level entry point where you start by deriving from [BaseHandler ](https://github.com/pytorch/serve/blob/4a110235b334f46564d0c3d1ba8946806368b075/ts/torch_handler/base_handler.py#L111) and implement initialize. The handle method is already implemented by BaseHandler and you only need to overwrite pre-/postprocessing and inference depending on your use case. 

Hope that helps. Let me know if you still have questions. Happy to dive deeper into this.

Matthias

**Comment by mreso** [comment]
Closing this issue for now. Feel free to re-open if you have further questions.
