### ISSUE TITLE
Setting log level of handler

### ISSUE THREAD

**Issue by hariom-qure** [pytorch/serve#2892]
### 📚 The doc issue

I need to set the logging level of handler to debug, i wanna see all the logs (of torch also). The docs dont mention much other than setting the log level for torch serve itself (log4j ones).  
I tried setting the config inside the handler, but it didnt work

```python
logging.basicConfig(level=logging.DEBUG)
```

**Comment by mreso** [comment]
Hi @hariom-qure,

the logging level for the model worker and thus the handler is defined [here](https://github.com/pytorch/serve/blob/4a110235b334f46564d0c3d1ba8946806368b075/ts/model_service_worker.py#L245C25-L245C25). Any additional configuration should be ignored as this one will take precedence over them.
Thinking about it, it might make sense to make this configurable. Will discuss this with the team.

Let me know if this helped you or if you need further assistance.

Matthias

**Comment by mreso** [comment]
Closing this as resolved, feel free to reopen if further questions occur.

**Comment by GenghisChen** [comment]
@mreso if I understand correctly, there's no way to configure this to a value other than INFO?

**Comment by mreso** [comment]
Sorry @GenghisChen did not see the notification.

This only means you can not reconfigure the logging system with basicConfig in the handler. You can still set the logging level by doing:

```
logger = logging.getLogger(__file__)
logger.setLevel(logging.DEBUG)
```

@CandiedCode
