### ISSUE TITLE
How can I implement batch inference in my model?

### ISSUE THREAD

**Issue by steelONIONknight** [pytorch/serve#2894]
### 📚 The doc issue

I read the docs, and I see this sentence:

> The frontend then tries to aggregate the batch-size number of requests and send it to the backend.

How does it work?

In my case, my batch_size is 4 and max_batch_delay is 5000. I sent 2 request simultaneously to torchserve, but in my handler log, which showed torchserve ran 2 preprocess, inference and postprocess. This situation is not as expected?  How I can achieve batch inference in my model? 

My model have 3 input tensors, shapes are [12568, 20, 4], [12568], [12568, 4]. When batch size is 2, shapes are [12568 x 2, 20, 4], [12568 x 2], [12568 x 2, 4].

**Comment by agunapal** [comment]
Hi @steelONIONknight Please refer to this example which shows how batching works

https://github.com/pytorch/serve/tree/master/examples/image_classifier/resnet_152_batch

**Comment by steelONIONknight** [comment]
sorry for photos, here is my handler code snippet
![DCIM(2)](https://github.com/pytorch/serve/assets/32484081/40d721f8-cbaf-4397-8d32-d092a806c49f)
![DCIM(3)](https://github.com/pytorch/serve/assets/32484081/c77a710a-2f19-41d9-b9b5-95da23db6465)
![DCIM(5)](https://github.com/pytorch/serve/assets/32484081/6d7609bd-4786-4776-97e5-631679670c42)
![DCIM(4)](https://github.com/pytorch/serve/assets/32484081/0dd23dfa-2c75-44db-894b-3e0fbc38492b)

**Comment by steelONIONknight** [comment]
> Hi @steelONIONknight Please refer to this example which shows how batching works
> 
> https://github.com/pytorch/serve/tree/master/examples/image_classifier/resnet_152_batch

Hi @agunapal, thanks your response, and I cannot see any special part here.

**Comment by agunapal** [comment]
Hi @steelONIONknight the front-end will just batch any requests that come within the batch delay time. You need to make sure the preprocess method of your handler resizes the tensors to a specific shape so the inference can work on the batched input

**Comment by steelONIONknight** [comment]
config isnot right, I closed the issue.
