### ISSUE TITLE
How torchserve uses grpc in java

### ISSUE THREAD

**Issue by pengxin233** [pytorch/serve#2899]
### 📚 The doc issue

I want to use grpc in the java service to call torchserve's model, but I don't seem to have found any relevant documentation.

**Comment by lxning** [comment]
@pengxin233 TorchServe grpc protocol is defined at [here](https://github.com/pytorch/serve/tree/master/frontend/server/src/main/resources/proto)

[GPRC doc](https://grpc.io/docs/languages/java/quickstart/#update-the-client) provides the step-by-step instruction about how to write a Java GRPC client.

**Comment by agunapal** [comment]
@pengxin233 You can also refer to this which has example https://github.com/pytorch/serve/blob/master/docs/grpc_api.md

**Comment by pengxin233** [comment]
alright, thank you very much
