### ISSUE TITLE
Update error message when attempting inference on model with 0 workers

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#29]
On adding a model via the management-api, the default min/max workers for the model is set to 0. As a result when running prediction against the model after registering gives a 503 error with details as 'No worker is available to serve request: densenet161'. This will be confusing for user's trying to add models from the inference api. 

**Register model using:**  
curl -X POST "http://<torchserve-host>:<mgmt-port>/models?url=https://<s3_path>/densenet161.mar"
{
  "status": "Model densenet161 registered"
}

**Inference using:** 
curl -X POST http://<torchserve-host>:<inf-port>/predictions/densenet161 -T cutekit.jpeg
{
  "code": 503,
  "type": "ServiceUnavailableException",
  "message": "No worker is available to serve request: densenet161"
}

**Model details:** 
curl -X GET http://<torchserve-host>:<mgmt-port>/models/densenet161
[
  {
    "modelName": "densenet161",
    "modelVersion": "1.0",
    "modelUrl": "https://<s3-bucket-url>/densenet161.mar",
    "runtime": "python",
    "minWorkers": 0,
    "maxWorkers": 0,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": false,
    "workers": []
  }
]

**Comment by DSLituiev** [comment]
I ran into a similar issue when following an example [here](https://github.com/pytorch/serve/tree/master/examples/image_classifier/resnet_152_batch):


```
curl -X POST "localhost:8081/models?model_name=resnet152&url=resnet-152-batch.mar&batch_size=4&max_batch_delay=5000&initial_workers=3&synchronous=true"
```

I plugged in my own model. Is it an outdated piece?
