### ISSUE TITLE
How to use torchserve metrics

### ISSUE THREAD

**Issue by pengxin233** [pytorch/serve#2907]
### 📚 The doc issue

When I call curl http://127.0.0.1:8082/metrics, it always returns empty results, even if it is called after model inference. But there is clearly a corresponding log in model_metrics.log. I saw that the previous Issue said that prometheus is currently supported as a plug-in? I would like to ask if there is any corresponding documentation.

**Comment by lxning** [comment]
@pengxin233 [here](https://github.com/pytorch/serve/blob/master/docs/metrics.md#introduction) is the instruction link.

set `metrics_mode= prometheus` in config.properties or export TS_METRICS_MODE=prometheus
