### ISSUE TITLE
https://github.com/pytorch/serve/issues/2870 - New Release Required for this Fix

### ISSUE THREAD

**Issue by DeepakkumarArumugam** [pytorch/serve#2933]
### 🐛 Describe the bug

Team,

seems like worker auto recovery fix in this PR. Can we create patch release so that we can proceed with production update?

Thanks

Regards,
Deepak Kumar A

### Error logs

NA

### Installation instructions

NA

### Model Packaing

NA

### Versions

0.8.1

### Repro instructions

0.8.1

**Comment by agunapal** [comment]
Hi @DeepakkumarArumugam We will be making a new release in the next week or so.

**Comment by namannandan** [comment]
TorchServe `0.10.0` has been released which includes [worker auto recovery fix](https://github.com/pytorch/serve/pull/2746): https://github.com/pytorch/serve/releases/tag/v0.10.0
