### ISSUE TITLE
enable test_install_dependencies_to_venv_with_requirements in docker regression

### ISSUE THREAD

**Issue by agunapal** [pytorch/serve#2942]
### 🐛 Describe the bug

test_install_dependencies_to_venv_with_requirements fails in docker regession

### Error logs

```
=================================== FAILURES ===================================
_____________ test_install_dependencies_to_venv_with_requirements ______________

    def test_install_dependencies_to_venv_with_requirements():
        # Torchserve cleanup
        test_utils.stop_torchserve()
        test_utils.delete_all_snapshots()
    
        try:
            generate_model_archive(use_requirements=True, use_venv=True)
            test_utils.start_torchserve(
                model_store=test_utils.MODEL_STORE,
                snapshot_file=os.path.join(
                    test_utils.REPO_ROOT,
                    "test",
                    "pytest",
                    "test_data",
                    "custom_dependencies",
                    "config.properties",
                ),
                no_config_snapshots=True,
                gen_mar=False,
            )
>           register_model_and_make_inference_request(expect_model_load_failure=False)

test_model_custom_dependencies.py:253: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_model_custom_dependencies.py:122: in register_model_and_make_inference_request
    raise e
test_model_custom_dependencies.py:117: in register_model_and_make_inference_request
    resp.raise_for_status()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Response [500]>

    def raise_for_status(self):
        """Raises :class:`HTTPError`, if one occurred."""
    
        http_error_msg = ""
        if isinstance(self.reason, bytes):
            # We attempt to decode utf-8 first because some servers
            # choose to localize their reason strings. If the string
            # isn't utf-8, we fall back to iso-8859-1 for all other
            # encodings. (See PR #3538)
            try:
                reason = self.reason.decode("utf-8")
            except UnicodeDecodeError:
                reason = self.reason.decode("iso-8859-1")
        else:
            reason = self.reason
    
        if 400 <= self.status_code < 500:
            http_error_msg = (
                f"{self.status_code} Client Error: {reason} for url: {self.url}"
            )
    
        elif 500 <= self.status_code < 600:
            http_error_msg = (
                f"{self.status_code} Server Error: {reason} for url: {self.url}"
            )
    
        if http_error_msg:
>           raise HTTPError(http_error_msg, response=self)
E           requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8081/models?model_name=mnist_custom_dependencies&url=mnist_custom_dependencies&initial_workers=1&synchronous=true

```

### Installation instructions

Nightly

### Model Packaing

N/A

### Versions

Nightly

### Repro instructions

Run  this test in a docker container

**Comment by namannandan** [comment]
Currently, in our docker container, we create a virtual environment and install torchserve inside it as follows:
https://github.com/pytorch/serve/blob/33d87e3797c3298a5c8c1cbfd09fdd8804df8e92/docker/Dockerfile#L54-L58

The feature to use virtual environment to install custom model dependencies creates a separate virtual environment and attempts to start the model worker and load the model in the new virtual environment. This fails with at the following point:
```
2024-02-12T21:54:23,630 [INFO ] epollEventLoopGroup-3-1 org.pytorch.serve.wlm.ModelManager - Model mnist_custom_dependencies loaded.
2024-02-12T21:54:23,631 [DEBUG] epollEventLoopGroup-3-1 org.pytorch.serve.wlm.ModelManager - updateModel: mnist_custom_dependencies, count: 1
2024-02-12T21:54:23,638 [DEBUG] W-9000-mnist_custom_dependencies_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/home/model-server/tmp/models/0f78acce5ed84427a9e427e3ea7d9394/venv/bin/python, /home/venv/lib/python3.9/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /home/model-server/tmp/.ts.sock.9000, --metrics-config, /home/venv/lib/python3.9/site-packages/ts/configs/metrics.yaml]
2024-02-12T21:54:23,690 [WARN ] W-9000-mnist_custom_dependencies_1.0-stderr MODEL_LOG - Traceback (most recent call last):
2024-02-12T21:54:23,691 [WARN ] W-9000-mnist_custom_dependencies_1.0-stderr MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 15, in <module>
2024-02-12T21:54:23,692 [WARN ] W-9000-mnist_custom_dependencies_1.0-stderr MODEL_LOG -     from ts.arg_parser import ArgParser
2024-02-12T21:54:23,693 [WARN ] W-9000-mnist_custom_dependencies_1.0-stderr MODEL_LOG - ModuleNotFoundError: No module named 'ts'
```

Root cause of the issue is that venv created during the container build contains `torchserve` installed to its site-packages. The new venv that is created to load the model inherits the system site packages but not site-packages of the existing venv in which torchserve is installed, hence `from ts.arg_parser import ArgParser` fails.

Potential options to fix this:
1) Document that the `useVenv` option is not supported when `torchserve` is installed and already started from a virtual environment and disable the `useVenv` related tests for Docker.
2) Find a way to inherit site-packages from one venv in another.

**Comment by agunapal** [comment]
> Currently, in our docker container, we create a virtual environment and install torchserve inside it as follows:
> 
> https://github.com/pytorch/serve/blob/33d87e3797c3298a5c8c1cbfd09fdd8804df8e92/docker/Dockerfile#L54-L58
> 
> The feature to use virtual environment to install custom model dependencies creates a separate virtual environment and attempts to start the model worker and load the model in the new virtual environment. This fails at the following point:
> 
> ```
> 2024-02-12T21:54:23,630 [INFO ] epollEventLoopGroup-3-1 org.pytorch.serve.wlm.ModelManager - Model mnist_custom_dependencies loaded.
> 2024-02-12T21:54:23,631 [DEBUG] epollEventLoopGroup-3-1 org.pytorch.serve.wlm.ModelManager - updateModel: mnist_custom_dependencies, count: 1
> 2024-02-12T21:54:23,638 [DEBUG] W-9000-mnist_custom_dependencies_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/home/model-server/tmp/models/0f78acce5ed84427a9e427e3ea7d9394/venv/bin/python, /home/venv/lib/python3.9/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /home/model-server/tmp/.ts.sock.9000, --metrics-config, /home/venv/lib/python3.9/site-packages/ts/configs/metrics.yaml]
> 2024-02-12T21:54:23,690 [WARN ] W-9000-mnist_custom_dependencies_1.0-stderr MODEL_LOG - Traceback (most recent call last):
> 2024-02-12T21:54:23,691 [WARN ] W-9000-mnist_custom_dependencies_1.0-stderr MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 15, in <module>
> 2024-02-12T21:54:23,692 [WARN ] W-9000-mnist_custom_dependencies_1.0-stderr MODEL_LOG -     from ts.arg_parser import ArgParser
> 2024-02-12T21:54:23,693 [WARN ] W-9000-mnist_custom_dependencies_1.0-stderr MODEL_LOG - ModuleNotFoundError: No module named 'ts'
> ```
> 
> Root cause of the issue is that venv created during the container build contains `torchserve` installed to its site-packages. The new venv that is created to load the model inherits the system site packages but not site-packages of the existing venv in which torchserve is installed, hence `from ts.arg_parser import ArgParser` fails.
> 
> Potential options to fix this:
> 
> 1. Document that the `useVenv` option is not supported when `torchserve` is installed and already started from a virtual environment and disable the `useVenv` related tests for Docker.
> 2. Find a way to inherit site-packages from one venv in another.

How this is different compared to creating a venv, installing TorchServe standalone and then using `useVenv`
