### ISSUE TITLE
Incomplete example about emitting metrics

### ISSUE THREAD

**Issue by feeeper** [pytorch/serve#2977]
### 📚 The doc issue

The example code in the section [Emitting custom metrics](https://pytorch.org/serve/metrics.html#emitting-custom-metrics) doesn't contains `emit_metrics` function call

### Suggest a potential alternative/fix

```
from ts.service import emit_metrics

class ExampleCustomHandler(BaseHandler, ABC):
   def initialize(self, ctx):

context.metrics.add_counter(...)
emit_metrics(context.metrics.store)
```

**Comment by namannandan** [comment]
Please use this example as reference to emit custom metrics: https://github.com/pytorch/serve/tree/master/examples/custom_metrics

**Comment by feeeper** [comment]
@namannandan, yes, you've already [shown me this example](https://github.com/pytorch/serve/issues/2979). The issue is that the documentation I found on the PyTorch site is incomplete, and this is a problem not just for me, but likely for others as well. The author of the article mentioned the function but never used it. It really drove me crazy; I wondered if I was doing something wrong or if there was a problem with the example.

**Comment by namannandan** [comment]
Metrics documentation will be fixed as a part of this tracking issue: https://github.com/pytorch/serve/issues/3001
