### ISSUE TITLE
Does TorchServe support CUDA 10.0

### ISSUE THREAD

**Issue by monkeyDemon** [pytorch/serve#306]
I want to know is TorchServer support CUDA 10.0 or whether there is Dockerfile supporting CUDA 10.0 ?
If so, how to use it in CUDA 10.0 environment ?
Some experiential guidance will be very helpful to me, thank you.

**Comment by dhaniram-kshirsagar** [comment]
Not sure if you have seen this https://github.com/pytorch/serve/blob/master/docker/Dockerfile.gpu

**Comment by harshbafna** [comment]
@monkeyDemon : TorchServe works fine with CUDA 9.2 and 10.x . However, it is recommended to use the latest version supported by PyTorch.

Also as indicated by @dhaniram-kshirsagar : We have dockerfile with CUDA 10.1

**Comment by chauhang** [comment]
@monkeyDemon You should be to create own Dockerfile for 10.0 using the https://github.com/pytorch/serve/blob/master/docker/Dockerfile.gpu as a reference
