### ISSUE TITLE
How to modify torchserve’s Python runtime from 3.8.0 to 3.10

### ISSUE THREAD

**Issue by pengxin233** [pytorch/serve#3086]
### 📚 The doc issue

My handle uses the syntax of Python 3.10, but the log shows Python runtime: 3.8.0. causing the model to fail to run. I would like to ask how to convert its environment to Python 3.10. I have introduced the dependencies of the Python 3.10 version into the corresponding dockerfile.

**Comment by agunapal** [comment]
TorchServe publishes binaries for versions 3.8 to 3.11 . When you create a conda environment, are you specifying the python version to be 3.10? The correct version will be picked when you do this.
