### ISSUE TITLE
Unable to use build_image.sh to build the cu102 version of the image

### ISSUE THREAD

**Issue by pengxin233** [pytorch/serve#3089]
### 📚 The doc issue

When using -cv cu102 in build_image.sh, the corresponding base image does not exist.
elif [ "${CUDA_VERSION}" == "cu102" ];
           then
             BASE_IMAGE="nvidia/cuda:10.2-cudnn8-runtime-ubuntu18.04"
             
  Error response from daemon: manifest for nvidia/cuda:10.2-cudnn8-runtime-ubuntu18.04 not found: manifest unknown: manifest unknown

**Comment by agunapal** [comment]
Hi @pengxin233 Please check Nvidia's docker hub to see if CUDA 10.2 images are still available. We follow PyTorch's CUDA compatibility matrix. In the latest release, CUDA 11.8 and CUDA 12.1 are supported.

**Comment by pengxin233** [comment]
> Hi @pengxin233 Please check Nvidia's docker hub to see if CUDA 10.2 images are still available. We follow PyTorch's CUDA compatibility matrix. In the latest release, CUDA 11.8 and CUDA 12.1 are supported.

Okay, currently the CUDA 10.2 image on docker hub is no longer available.
