### ISSUE TITLE
Install from source not working

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#312]
The install from source is not working on the staging branch, giving ClassNotFoundException

```
(serve) ubuntu@ip-172-31-15-18:~/stage/serve$ pip install -U -e .
Obtaining file:///home/ubuntu/stage/serve
Requirement already satisfied, skipping upgrade: Pillow in /home/ubuntu/anaconda3/lib/python3.6/site-packages (from torchserve==0.0.1b20200507) (5.4.1)
Requirement already satisfied, skipping upgrade: psutil in /home/ubuntu/anaconda3/lib/python3.6/site-packages (from torchserve==0.0.1b20200507) (5.4.5)
Requirement already satisfied, skipping upgrade: future in /home/ubuntu/anaconda3/lib/python3.6/site-packages (from torchserve==0.0.1b20200507) (0.18.2)
Installing collected packages: torchserve
 Found existing installation: torchserve 0.0.1b20200507
  Uninstalling torchserve-0.0.1b20200507:
   Successfully uninstalled torchserve-0.0.1b20200507
 Running setup.py develop for torchserve
Successfully installed torchserve
(serve) ubuntu@ip-172-31-15-18:~/stage/serve$ cd ~/work
(serve) ubuntu@ip-172-31-15-18:~/work$ torchserve --ts-config config.properties
Removing orphan pid file.
(serve) ubuntu@ip-172-31-15-18:~/work$ Error: Could not find or load main class org.pytorch.serve.ModelServer
Caused by: java.lang.ClassNotFoundException: org.pytorch.serve.ModelServer
```

**Comment by harshbafna** [comment]
@chauhang  : Please use `pip install .` instead of `pip install -e .`

Because of -e flag pip skips out the build process which generated the frontend jar for `TorchServe`. I will put a PR with the doc fix.

**Comment by chauhang** [comment]
@harshbafna Similar issue was reported 10 days back on master as well. Can you please clarify why https://github.com/pytorch/serve/issues/269 was closed?

**Comment by harshbafna** [comment]
@chauhang : This got missed out there because the OP of the issue had mixed up multiple environment and tried installed from conda repo as well as from source and created a confusion. And later the user was successfully able to install from conda repo on a fresh environment.

**Comment by mycpuorg** [comment]
Both changes for Linux and MacOS are in staging. Removing Launch Blocker tag. @chauhang @dhanainme @lokeshgupta1975 Time for a merge from `staging_0_1_1` to `master` to pull this in??

**Comment by chauhang** [comment]
Please go ahead with merge to master

**Comment by maaquib** [comment]
I created an issue for install from source #375 
Please fix this before merging to master
