### ISSUE TITLE
Cannot import module while using custom handler 

### ISSUE THREAD

**Issue by mohammedayub44** [pytorch/serve#314]
🐛 Bug report

I'm trying to use a custom crowd counting model and while serving it gives me an error while importing custom model libraries.
  
Python Import code is like below: 

```python3
module_path = os.path.abspath(os.path.join('../../../../'))  # Parent Dir on local machine
if module_path not in sys.path:
    sys.path.append(module_path+"/SSDCNet")

...
from Network.SSDCNet import SSDCNet_classify
``` 

Error:

```python

   File "/tmp/models/58eb8da6a1c8563374304a9fc66b2788a9c9c440/crdcnt_handler.py", line 9, in <module>
   from crowdmodel import CrowdCounter
   File "/tmp/models/58eb8da6a1c8563374304a9fc66b2788a9c9c440/crowdmodel.py", line 8, in <module>
    from Network.SSDCNet import SSDCNet_classify
ModuleNotFoundError: No module named 'Network'
```

Here is the log file:  
[server_log3.txt](https://github.com/pytorch/serve/files/4596700/server_log3.txt)

**Environment Details:**

Operating System and version: Ubuntu 16.04

![image](https://user-images.githubusercontent.com/7122670/81383380-f0c78080-90dd-11ea-98e6-e0c3816c9207.png)

**Possible Fix: ** 
Instead of adding to `sys.path`. Adding the parent folder to `PYTHONPATH`  before you run the `torchserve` command temporarily fixes the issue.

```bash
> export PYTHONPATH=/home/ubuntu/mayub/Github/SSDCNet:$PYTHONPATH 
> echo $PYTHONPATH
> torchserve --ts-config ./config.properties --start --ncs --model-store ./torchserve_model_store --models all
```
Since this is temporary and session based maybe a better solution is required.

Thanks !

**Comment by harshbafna** [comment]
@mohammedayub44 All the dependency files need to be packaged inside the mar file using the `torch-model-archiver` utility. `TorchServe` extracts the mar file in a temporary location and that is already added in the path for importing the modules.

Could you share your mar file.

**Comment by mohammedayub44** [comment]
Yes correct, I'm using the modules which are outside the mar file. However the `torch-model-archiver` does not throw any errors while generating the mar file, which made me guess that everything is fine. Only while running the `torchserve`, it checks imports and throws an error.

I also tried, including all the dependency files in the same location as model.py and handler.py. That works fine without explicitly adding external locations to `PYTHONPATH`. The only reason I avoided this is because if there are many dependency files for a custom model and you only need an instance of a Model class for model.py, you would want to keep them separate.

Here is my [mar file](https://www.dropbox.com/s/mq0bhcec0p7cdkf/ssdc_mar.zip?dl=0) for reference. 

Thanks !

**Comment by harshbafna** [comment]
@mohammedayub44 : `torch-model-archiver` is just a utility tool for packaging your model and does not validates you model. It is expected that the user will supply all the other dependency files using the `--extra-files` flag. You can always create an egg/zip file to upload your custom python package if the number of files are more.

**Comment by mohammedayub44** [comment]
Sure. Thanks for confirming 👍

**Comment by vinayaksable2399** [comment]
> @mohammedayub44 : `torch-model-archiver` is just a utility tool for packaging your model and does not validates you model. It is expected that the user will supply all the other dependency files using the `--extra-files` flag. You can always create an egg/zip file to upload your custom python package if the number of files are more.

how to create egg/zip :
or it's zip file 
in extract-file

**Comment by DhyeyPatel1416** [comment]
> @mohammedayub44 All the dependency files need to be packaged inside the mar file using the `torch-model-archiver` utility. `TorchServe` extracts the mar file in a temporary location and that is already added in the path for importing the modules.
> 
> From your code snippet it looks like you are trying to access modules which are outside the mar file.
> 
> Could you share your mar file.

how to add a folder as extra files
?

**Comment by gioipv** [comment]
> > @mohammedayub44 : `torch-model-archiver` is just a utility tool for packaging your model and does not validates you model. It is expected that the user will supply all the other dependency files using the `--extra-files` flag. You can always create an egg/zip file to upload your custom python package if the number of files are more.
> 
> how to create egg/zip :
> or it's zip file
> in extract-file

Hello vinayaksable2399 
u can zip folder (custom module) as normal
When use `torch-model-archiver`  , set extra-file is path the zip file .and in you'r custom handler, u have to unzip file before import you'r custom module (using zipfile).

**Comment by borijang** [comment]
Hi @harshbafna,

Supplying the python file in the `--extra-files` flag still doesn't work for me. When I'm trying to import the module in the custom handler I get the ModuleNotFoundError. Is there something I'm missing?

**Comment by borijang** [comment]
It turns out that the extra files are all saved in the first level of the output directory, i.e. I'd have to change the imports in the handler from: `from src.models.foo import model` to: `from foo import model`. Other than the IDE complaining, it works!
