### ISSUE TITLE
Wrong repeated argument flag in README.md

### ISSUE THREAD

**Issue by kovarsky** [pytorch/serve#317]
In `examples/image_classifier/resnet_152_batch/README.md` `--handler` is wrongly repeated twice.
>  `torch-model-archiver --model-name resnet-152-batch --version 1.0  --serialized-file resnet-152-batch.pt --extra-files serve/examples/image_classifier/index_to_name.json --handler --handler serve/examples/image_classifier/resnet_152_batch/resnet152_handler.py`

**Comment by maaquib** [comment]
Fixed in release v0.1.1 on branch `staging_0_1_1` as part of #354 . Pending merge to master
