### ISSUE TITLE
Follow up on token authentication PR comments

### ISSUE THREAD

**Issue by mreso** [pytorch/serve#3185]
### 🚀 The feature

Follow up on refactor comments in https://github.com/pytorch/serve/pull/3163

### Motivation, pitch

Follow up on refactor comments in https://github.com/pytorch/serve/pull/3163

**Comment by mreso** [comment]
We also need to go through all examples and add the right options.

**Comment by mreso** [comment]
Benchmark tool is also affected.

**Comment by mreso** [comment]
This needs to be described in api docs as well.

**Comment by udaij12** [comment]
> Benchmark tool is also affected.

Benchmark tool should be fixed in this PR https://github.com/pytorch/serve/pull/3188

**Comment by udaij12** [comment]
Doc changes in this PR #3183

**Comment by udaij12** [comment]
Think we have address all token related PRs. Closing this issue.
