### ISSUE TITLE
How to send a torch array via request

### ISSUE THREAD

**Issue by lschaupp** [pytorch/serve#3195]
I want to send a torch (cuda) array via python request to the inference API. Is that possible?

**Comment by agunapal** [comment]
AFAIK you can't send it as is. It needs to be serialized.

**Comment by lschaupp** [comment]
@agunapal Would it be possible to have some kind of pinned memory where the torch arrays are loaded, and then simply sharing the memory pointer via the request? I have larger image files to handle - and trying to find the most efficient way on systems with low CPU performance.

**Comment by agunapal** [comment]
If you are doing this locally,  should be possible using shared memory. However,  if you have a cuda tensor, I don't think it works. Atleast,  it didn't work previously

**Comment by lschaupp** [comment]
> If you are doing this locally, should be possible using shared memory. However, if you have a cuda tensor, I don't think it works. Atleast, it didn't work previously

Thanks for the info. It could work with tensors on shared memory ("cpu") based on your response.  That would be massively better than sending the file across imho.
