### ISSUE TITLE
Model archive manifest file version mismatch

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#325]
The Model archive MANIFEST.json file should include correct version numbers for all components and have an additional timestamp field for the time when it was created.

Current manifest file for the vgg11.mar 

```
{
  "runtime": "python",
  "model": {
    "modelName": "vgg11",
    "serializedFile": "vgg11-bbd30ac9.pth",
    "handler": "image_classifier",
    "modelFile": "model.py",
    "modelVersion": "1.0"
  },
  "modelServerVersion": "1.0",
  "implementationVersion": "1.0",
  "specificationVersion": "1.0"
}
```

**Comment by lokeshgupta1975** [comment]
@chauhang Can you be more specific please? Which version numbers should be corrected here?
@harshbafna Does the field "modelServerVersion" represent the version of TS, for e.g. should it be set to "0.1.0" here?

**Comment by chauhang** [comment]
@mycpuorg Can you please comment on this? The versions are from the Manifest file created inside the .mar model packages. The modelserverversion should match the TorchServe version. Please comment for the others.
