### ISSUE TITLE
GPU memory not released after inference

### ISSUE THREAD

**Issue by Di-Gu** [pytorch/serve#3253]
I built the .mar file by using torch-model-archiver, and wrote a custom handler that processes batched inputs, to be more specific
I'm doing the following steps:

sending one single request with N images as a list of base64 str
converting these images into tensors in my handler's preprocess
create a batch from the above tensors and pass it to the model for inference
return the inference response

and through testing, I found if I send 4 images it will occupy around 14G memories of GPU, and then after sending 4 images, the next request if I only send 1 image, the GPU memory is not released and kept at 14G

Is this normal, and is there any way I can release some GPU memories after no inference request like after a while?

**Comment by mreso** [comment]
Hi @Di-Gu 
this is the usual behavior of PyTorch to avoid reallocating memory over and over again by holding it in a memory pool which can be reused. Please see https://pytorch.org/docs/stable/notes/cuda.html#memory-management for more information. There you can also find the calls to influence the memory management and release unused memory.

Feel free to re-open if this does not answer your question.
