### ISSUE TITLE
Allow .tar.gz models to be loaded using load_models=all

### ISSUE THREAD

**Issue by m10an** [pytorch/serve#3320]
### 🚀 The feature

Allow to load on server startup `.tar.gz` model archives using property `load_models=all`, besides `.mar` and `.model` files

### Motivation, pitch

I am currently using TorchServe to serve models archived with the `--archive-format=tgz` flag. The model storage folder contains multiple versions of the same model, but currently, it is impossible to load all of them on server startup because it only works with `.mar` and `.model` files.

### Additional context

I already tested simple [change in code](https://github.com/pytorch/serve/compare/master...m10an:TrochServe:load_all_fix), works as expected

**Comment by mreso** [comment]
Hi @m10an thanks for reporting this issue. That change would be very valuable for our users I think. I am also not sure if no_archive models i.e. folder are currently included in load_models=all. Would you be interested to contribute a PR for this change? I would be happy to review it!

**Comment by m10an** [comment]
Hi @mreso, thank you for quick response. I will gladly contribute
