### ISSUE TITLE
Install from src additional tests and cleanup

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#334]
Following changes need to be done to the CI/CD to ensure install from src does not break again, and we cleanup errors from the logs. 

1. Use the install from src script in the CI/CD sanity test for install / resinstall check 
1. Cleanup extra build artifacts - `torchserve.egg-info` folder and any others temp files / folders created as part of the build
1.  Fix following erorrs for the gradle tests during the build:

```
> Task :modelarchive:pmdMain
Removed misconfigured rule: LoosePackageCoupling cause: No packages or classes specified
> Task :server:pmdMain
Removed misconfigured rule: LoosePackageCoupling cause: No packages or classes specified
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.2/userguide/command_line_interface.html#sec:command_line_warnings
```

**Comment by mycpuorg** [comment]
@vdantu any idea about specific gradle features which are deprecated?

**Comment by mycpuorg** [comment]
@harshbafna Can you please use this ticket to make changes that ensure only one script is used to install from source within sanity script? That way our one source of truth is tested and used for CI/CD tests as well?

**Comment by mycpuorg** [comment]
@dhaniram-kshirsagar Could you help?

**Comment by dhaniram-kshirsagar** [comment]
> @dhaniram-kshirsagar Could you help?

Yes, we are working on it.
