### ISSUE TITLE
Respond status 429 Too Many Requests instead of broad Internal Server Error

### ISSUE THREAD

**Issue by tysg** [pytorch/serve#3342]
TorchServe returns 500 Internal Server Error when the job queue is full. Would it make sense to return a more specific 429 Too Many Requests error instead?

https://github.com/pytorch/serve/blob/e8879c10c1400a45aca4f36b9d9f8f7e7be3f5fe/frontend/server/src/main/java/org/pytorch/serve/grpcimpl/InferenceImpl.java#L267-L278

**Comment by mreso** [comment]
Hi @tysg when I read this description https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429 my interpretation is that the error gets returned when a specific user issues too many requests in a short amount of time. On the other hand, an input queue which runs full is more of a configuration/scaling issue on the server side. Do you have a different description of 429 that would underpin this change?

**Comment by tysg** [comment]
You're right, 429 is a client error. I overlooked it
