### ISSUE TITLE
Will serve support gRPC inference call?

### ISSUE THREAD

**Issue by mpjlu** [pytorch/serve#342]
The performance of gRPC is better than REST API. Will serve support gRPC inference call?

**Comment by dhaniram-kshirsagar** [comment]
It will be available in future releases. Here is the RFC torchserve. https://github.com/pytorch/pytorch/issues/27610

**Comment by mpjlu** [comment]
Thanks. Is there a plan time about gRPC release.

**Comment by dhaniram-kshirsagar** [comment]
> Thanks. Is there a plan time about gRPC release.

@lokeshgupta1975 - Could you please comment here.

**Comment by lokeshgupta1975** [comment]
@mpjlu We do not have a concrete plan yet but roughly it would be by end of Q3'2020. I have created another tracking issue for this feature #378
