### ISSUE TITLE
Docker: How to add your .mar files?

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [pytorch/serve#343]
Dear all,

Could you please update the doc showing how to use your `.mar` files and `model-store` dir with docker? Assuming I have a stored `.mar` and `model-store` dir locally on my pc and I want to run `torchserve` on docker with them, what should I do? Is there an option to add the `mar` file? The docker page of `torchserve` doesn't contain information.

Thank you.

Be safe and best regards,

Francesco Saverio

**Comment by mycpuorg** [comment]
Hi @FrancescoSaverioZuppichini is the idea to keep a persistent model store dir? If so, then you could use `-v` option in docker to map your host's local directory to docker's mounted filesystem and provide the path.

Be sure to provide the Docker's view of the path as model store. It points to `/home/model-server/model-store` inside the docker if you used the sample config.
Refer: [this config file](https://github.com/pytorch/serve/blob/85dbef426688c5d0fe2a47fc56cad6a79b179718/docker/config.properties#L5)

Let's consider the following instructions [page](https://github.com/pytorch/serve/tree/master/docker)
```
docker run --rm -it -p 8080:8080 -p 8081:8081 pytorch/torchserve:0.1-cpu
```

You would change the above to
```
docker run --rm -it -p 8080:8080 -p 8081:8081 -v <LOCAL HOST DIR>:/home/model-server/model-store pytorch/torchserve:0.1-cpu
```

If this makes sense, feel free to make a PR I will be happy to review :)
Thanks.

**Comment by dhaniram-kshirsagar** [comment]
@mycpuorg @FrancescoSaverioZuppichini  Discussion is in progress to add such a support #195 should address this.

**Comment by FrancescoSaverioZuppichini** [comment]
@dhaniram-kshirsagar Thank you :)
