### ISSUE TITLE
streaming inference like speech recognition

### ISSUE THREAD

**Issue by jeon30c** [pytorch/serve#353]
Can I do streaming service with pytorch-serve like streaming speech recognition?

I cannot find the way for it. So if not, do you have any plan for it?

**Comment by dhanainme** [comment]
Torchserve currently supports only inference though HTTP 1.0 - Request / Response style. 
We dont have anything particular in out roadmap - https://github.com/pytorch/pytorch/issues/27610

Feel free to open a Issue / Feature ask with specific details of your need.

**Comment by prajwaljpj** [comment]
@jeon30c For now you can just stream it externally and send it as a batch as your input.

**Comment by jeon30c** [comment]
@prajwaljpj Oh. Glad to hear that. Can you give me examples/documentations link for that?

**Comment by prajwaljpj** [comment]
You can use [torch.split](https://pytorch.org/docs/stable/generated/torch.split.html) to split your input tensor to pieces. Then feed these pieces to your server. Outside the server you can write a function to join these into one.

**Comment by msaroufim** [comment]
@prajwaljpj's suggestion is correct - if there's a need for something more sophisticated feel free to open up this issue again
