### ISSUE TITLE
Best practice question - how to chain multiple models together for pipeline process?

### ISSUE THREAD

**Issue by lessw2020** [pytorch/serve#363]
Hi all - I couldn't find anything in the documentation so wondering if there is a recommendation for how to chain multiple models together in an internal pipeline?
Example - we need to take an incoming image, do obj detection , then do a seperate mdoel classification from items cropped and zoomed, return the result...i.e.:

1 - Model A -  Run obj detector on incoming image
1a - post process to determine cropped subset of image where object is  (inside model handler)

2 - Model B - run inference on subset image from step 1a to classify the detected item
3 - return final result

Is our only option to force the client to do two calls to the /serve and effectively remote control this pipeline?  
Ideally we want to pass in the large image, and just return the final result all from one client http POST call since its  expensive in our setup to pass/ do multiple remote calls  (i.e. post to model 1, post to model 2). 
But where would one control this two step process from within torch server or is there any built in 'controller' concept?  
It seems the current design model is based around hosting independent models each doing their own work without any reference to how to internally bind them together into a pipeline. 
Could you provide any recommendations for how to best structure a pipeline like the above or is it not supported/possible/recommended?
Thanks very much!

**Comment by harshbafna** [comment]
@lessw2020 : You can create a custom handler to invoke multiple models in your flow and host it as a single model. You can pass the model/checkpoint/statedict file for the second model using `--extra-files` flag and use it in your custom handler.

You can refer the recently added example for [text-to-speech-translation](https://github.com/pytorch/serve/tree/staging_0_1_1/examples/text_to_speech_synthesizer) using `waveglow` and `tacotron2` model. 

**torch-model-archiver command :** https://github.com/pytorch/serve/blob/staging_0_1_1/examples/text_to_speech_synthesizer/create_mar.sh#L17

**custom handler :** https://github.com/pytorch/serve/blob/staging_0_1_1/examples/text_to_speech_synthesizer/waveglow_handler.py

**Comment by lessw2020** [comment]
@harshbafna - thanks a bunch, that is great to hear we can design a flow with multiple models!
I'll use the --extra-files flag and setup our custom handler, the code links were very informative on how to do this. 
Much appreciated!
