### ISSUE TITLE
torch-model-archiver - support inference code with external python dependencies

### ISSUE THREAD

**Issue by assapin** [pytorch/serve#370]
Inference code may depend on arbitrary packages outside of torch projects.

currently I didn't see a way to include these in the .mar file.
I had to do a hack which is to pip install --target to a temp folder, open the .mar and inject these in.

Sagemaker has an elegant solution which is to just include a requiremetns.txt in the zip and it will inject them into the environment (conda? pip install inside the model continer as entry point? I have no idea how they implement it in mms)

would be good to have a simliar support in torchserve

**Comment by vdantu** [comment]
The dependency management is a tricky feature to have, especially when you host multiple models on the server which have dependency on different versions of the same python package :) . But, I agree with the ask. This is a very good feature to have,.
