### ISSUE TITLE
best practice - preferred model saving mechanism for performance/scaling?

### ISSUE THREAD

**Issue by lessw2020** [pytorch/serve#373]
For production, is there a preferred method of saving out a given model depending on it's use case of testing vs production?

Right now mar supports:
1 - eager model save
2 - script save
3 - traced save

Just wondering if there is a preferred way to save the model(s) depending on final destination -  production vs test?  I'm wondering if traced might be closer to c++ style/jit compilation and thus perf better vs a an eager saved model?
(i.e. is eager mode better for prototyping, vs for final model production perf gain if traced? )

**Comment by chauhang** [comment]
@lessw2020 For better inference performance it is recommended to use TorchScripted models. There are two options for TorchScripting:

- **Trace** mode - is generally used for rapid testing to convert your model to TorchScript before deploying into production. It requires example input for doing the tracing, and traces for the parts of the model code exercised by the example input provided. Tracing can have some limitations in edge cases as described [here](https://pytorch.org/docs/stable/jit.html#tracer). 
- **Script** mode - is used for deploying final models into production and the recommended approach to get best performance.

Check out the TorchScript [tutorial](https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html) for more insights.

**Comment by lessw2020** [comment]
Extremely helpful info - thanks very much @chauhang

**Comment by harshbafna** [comment]
Closing as the query has already been answered.
