### ISSUE TITLE
code for the default image_classifier / object detection handlers and/or base class to build on for custom?

### ISSUE THREAD

**Issue by lessw2020** [pytorch/serve#374]
I must be missing it but I can't find the .py code for the default image_classifier handler (i.e. custom_service.py)? 
 
In the examples I see some variations of handlers, but was hoping to use the default handler to then build our own handler up from depending on what it already does or does not do.
Is this code available or is it in java and thus deeper in the torchserve code base?

It would be ideal to have a base class available in the https://github.com/pytorch/serve/tree/master/examples/image_classifier and similar,
 that users can then take and build up from on for their own. 

Right now most of the model examples don't show a handler (b/c they use the base, but where is the base code?) or show one that might have to have a lot of code removed to break it back down to a base starting point.

**Comment by maaquib** [comment]
@lessw2020 Not sure if you are looking for this [ImageClassifier](https://github.com/pytorch/serve/blob/376110010a2fe3f8341d6299ec60795eaead7bf6/examples/image_classifier/squeezenet/model.py#L4). It uses [SqueezeNet](https://github.com/pytorch/vision/blob/12b551e7a7232d829df0f01ae9f6c56305571dfc/torchvision/models/squeezenet.py#L37) as the base class.

**Comment by lessw2020** [comment]
Hi @maaquib  - thanks for the reply.
What I meant was code like this, but for the generic implementation provide for each category:
https://github.com/pytorch/serve/blob/master/examples/image_classifier/resnet_152_batch/resnet152_handler.py

I'm unclear for example how the base Image_classifier handler know what the desired image size is (reads the input channels for the model?), does it resize incoming images preserving aspect ratio, how does it impl padding (zeroes or mean), etc. so hard to know if we can use the base image_classifier handler or not for custom production models without seeing the code.

In addition and more importantly, I am writing a chained series of handlers so having good default classes to build on (i.e. obj detection -> classifier) would be helpful to start. 

Note - Inow see the documentation has a clean base class for custom service handlers - could that be added here as a "base_handler_class.py" b/c the earlier doc pages link to the example dir, but there's no base class there...this what's in the docs it's better than what is there currently for people who want to implement their own I think.
https://pytorch.org/serve/custom_service.html

Thanks very much!

**Comment by lessw2020** [comment]
also just to clarify a bit more - the handler shown resnet152 handler does a center crop as part of the pre-processing which is fine for base classification, but complete failure for medical diagnostics work.
Thus without seeing the code for the included "image_classifier" impossible to tell how the image is being prepped, hence the interest in knowing what is or is not being done in the base would help inform users if they should write their own handler or not.
Thanks again!

**Comment by harshbafna** [comment]
@lessw2020 : Here are the code for all the default handlers provided by `TorchServe`

[Image Classifier](https://github.com/pytorch/serve/blob/master/ts/torch_handler/image_classifier.py)
[Text Classifier](https://github.com/pytorch/serve/blob/master/ts/torch_handler/text_classifier.py)
[Object Detector](https://github.com/pytorch/serve/blob/master/ts/torch_handler/object_detector.py)
[Image Segmenter](https://github.com/pytorch/serve/blob/master/ts/torch_handler/image_segmenter.py)

**Comment by lessw2020** [comment]
Thanks a bunch @harshbafna - that's exactly what I was looking for.  Would it be worth linking those on the readme or docs to make easier to find?  I imagine a lot of people will want to see and build on those as base classes. 
Regardless, thanks again as that was exactly what I was looking for.

**Comment by maaquib** [comment]
@lessw2020 Already added to [staging](https://github.com/pytorch/serve/tree/staging_0_1_1/docs#default-handlers). This will be updated in the next release

**Comment by lessw2020** [comment]
suggestion - expose the image size and resize method as an argument somewhere and whether to centercrop or not?  
With a bit of tweaking could make it so most people wont' need to build their own b/c they mostly would just need to adjust:
1 - image size and resize method
2 - center crop or not

**Comment by lessw2020** [comment]
@maaquib - excellent, that should be very useful.  Thanks for the fast updates!

**Comment by maaquib** [comment]
@lessw2020 Created #381 to track your request for enhancing the base image classifier

**Comment by chauhang** [comment]
@lessw2020 For now you can create a custom service and put logic for all the transformations in the preprocess function. Please take a look at the mnist image classifier example for details: https://github.com/pytorch/serve/blob/master/examples/image_classifier/mnist/mnist_handler.py#L49
