### ISSUE TITLE
Support gRPC based inference call in TorchServe

### ISSUE THREAD

**Issue by lokeshgupta1975** [pytorch/serve#378]
Linked to Issue #342 
This is an enhancement request, we will put this on our roadmap. Rough timeline for this feature as of now is by end of Q3'2020 (Sep'2020).

**Comment by qiaoning** [comment]
expect

**Comment by zhoudayang** [comment]
expect

**Comment by harshbafna** [comment]
This is being tracked through #656, targetted for 0.3.0 release. Closing this ticket.
