### ISSUE TITLE
packaging eager mode and .py file - do we need to move all dependencies to have a single model.py file?

### ISSUE THREAD

**Issue by lessw2020** [pytorch/serve#380]
I'm currently blocked from scripting a model, so planning to run for now with eager mode.  
However, this model has multiple sub file dependencies.
Thus, do I need to move all dependencies into the single model.py file equivalent (meaning it's just model.py and then system imports) or is there a way to package model.py + dependency1.py + dependency2.py?
Not really sure how the model.py is packaged relative to dependencies once it's in the .mar file, so appreciate any clarification.

Thanks much!

**Comment by mycpuorg** [comment]
@lessw2020 You can use `--extra-files` and pass comma separated dep files. Refer to the documentation for the model archiver [here](https://github.com/pytorch/serve/tree/master/model-archiver#creating-a-model-archive). Also, the MAR file is simply a zipped archive of all the files including serialize, json, handlers etc. So you can play around with the structure for all your files.

**Comment by lessw2020** [comment]
@mycpuorg  - thanks that helps a ton.  I didnt' realize the .mar was just a zip, that makes things a lot easier for packaging knowing that!

**Comment by chauhang** [comment]
@lessw2020  Model specific custom requirements.txt is also supported now, see PR https://github.com/pytorch/serve/pull/462 for details.
