### ISSUE TITLE
Enhancement for the base image classifier

### ISSUE THREAD

**Issue by maaquib** [pytorch/serve#381]
suggestion - expose the image size and resize method for the base image classifier as an argument somewhere and whether to centercrop or not?  
With a bit of tweaking could make it so most people wont' need to build their own b/c they mostly would just need to adjust:
1 - image size and resize method
2 - center crop or not

_Originally posted by @lessw2020 in https://github.com/pytorch/serve/issues/374#issuecomment-632416015_

**Comment by chauhang** [comment]
@maaquib Better way of handling this by exposing the preprocess and postprocess functions for the default handlers. The mnist image classifier custom handler example already describes how to do this. Similar examples needs to be added for the default handlers.

https://github.com/pytorch/serve/blob/master/examples/image_classifier/mnist/mnist_handler.py#L49
