### ISSUE TITLE
Point Cloud Custom Handler

### ISSUE THREAD

**Issue by StephanieRogers-ML** [pytorch/serve#392]
Has anyone had any luck implementing a point cloud custom handler to run inference with MinkowskiEngine (MinkUNet34C) or PointNet++ for point cloud segmentation and object detection?  I understand both would need their own handler.  Would we Pip the additional package requirements into the .mar file during archive?  Can open3d be used in the post process part of the handler to write the point cloud results to a point cloud?  Thank you for any insight!

**Comment by maaquib** [comment]
@StephanieRogers-ML You are correct about writing a [custom handler](https://github.com/pytorch/serve/blob/master/docs/custom_service.md) and packaging it into a .mar file. You'd pip install additional packages separately. You might find these two examples useful for writing a custom handler which require additional dependencies [1](https://github.com/pytorch/serve/tree/staging_0_1_1/examples/Huggingface_Transformers) [2](https://github.com/pytorch/serve/tree/staging_0_1_1/examples/text_to_speech_synthesizer). Let me know if this was helpful

**Comment by harshbafna** [comment]
Closing this as the query has been answered.
