### ISSUE TITLE
Issues running regression_tests.sh in docker for staging_0_1_1 branch

### ISSUE THREAD

**Issue by balachandrafb** [pytorch/serve#395]
Consolidating all issues in a single thread

1. Sysconfig was missing in docker image and this crashed the test execution. After pulling, worked fine. 
2. Once above was fixed When executing regression_tests.sh, got the following two errors
2a. 
```
Building wheels for collected packages: torch-model-archiver
  Running setup.py bdist_wheel for torch-model-archiver ... error
  Complete output from command /home/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/home/model-server/tmp/pip-0j51y9qq-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /home/model-server/tmp/tmpud7xqkixpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for torch-model-archiver
```
 
2b. 
```
+ start_torchserve /workspace//model_store /tmp/ts.log
+ torchserve --start --model-store /workspace//model_store --models /workspace//model_store/densenet161_v1.mar
+ sleep 10
+ curl http://127.0.0.1:8081/models
./test/regression_tests.sh: line 58: curl: command not found
+ newman run -e postman/environment.json --bail --verbose postman/management_api_test_collection.json -r cli,html --reporter-html-export /workspace//report/management_report.html
 
```
 
Neither seemed to cause any actual issues running the tests which worked fine in docker with just a single error below
 
3. Only test that failed in docker
```

→ Model Zoo - Register Model
  POST http://localhost:8081/models?url=https://torchserve.s3.amazonaws.com/mar_files/vgg11.mar&model_name=vgg11&initial_workers=1&synchronous=true [507 Insufficient Storage, 374B, 2m 38s]
```

**Comment by dhaniram-kshirsagar** [comment]
@balachandrafb Could you share detailed steps for this. Unable to repro on staging branch.

**Comment by balachandrafb** [comment]
1. Create docker image from source using  ./build_image.sh -b staging_0_1_1 -t staging:0_1_1
2. Start docker container 
docker run -it --user root staging:0_1_1 /bin/bash
3. In the Docker CLI execute the following cmds.

apt-get update 
apt-get install -y git wget sudo 
git clone https://github.com/pytorch/serve
cd serve 
git checkout staging_0_1_1
4. ./test/regression_tests.sh staging_0_1_1

In this version, I didn't see the errors 1, 2a and 2b above. But 3 still happened.

**Comment by dhaniram-kshirsagar** [comment]
@balachandrafb Enhancements in #398 will fix 3.

**Comment by maaquib** [comment]
@dhaniram-kshirsagar I am seeing exception 2a running inside venv as well. Additional `pip install wheel` fixes this

**Comment by dhaniram-kshirsagar** [comment]
> @dhaniram-kshirsagar I am seeing exception 2a running inside venv as well. Additional `pip install wheel` fixes this
