### ISSUE TITLE
Benchmark profiling for backend not working on staging_0_1_1  

### ISSUE THREAD

**Issue by balachandrafb** [pytorch/serve#400]
Followed instructions in https://github.com/pytorch/serve/blob/staging_0_1_1/benchmarks/README.md

In the profiling-> backend section, it talks about setting constant BENCHMARK to true. But this doesn’t seem to exist in the file ts/model_service_worker.py
 
Just adding this const on top of DEBUG into the file and running torchserve and benchmark.py didn’t generate /tmp/tsPythonProfile. Frontend profiling works fine via JProfiler

**Comment by chauhang** [comment]
Verified this has been fixed by PR #402
