### ISSUE TITLE
debugging tips?  code 503, InternalServerException, Prediction failed... 

### ISSUE THREAD

**Issue by lessw2020** [pytorch/serve#410]
(update - I found the issue is the assumption is topK = 5, in my case only 2 classes - https://github.com/pytorch/serve/issues/411 to track and resolve
However, still would be good to know recommended debugging options....) 

Using default image_classifier handler I loaded my model with no issue but when doing a first prediction get this error:

curl -X POST http://127.0.0.1:2000/predictions/nest101 -T pos2.jp
g
{
  "code": 503,
  "type": "InternalServerException",
  "message": "Prediction failed"
}

I don't see anything aberrant in the logs - is there a way to get more info on what the exception is in a scenario like this or any other tips on how to isolate the issue?

**Comment by dhaniram-kshirsagar** [comment]
I am not sure but if you are talking about debugging backend [i.e. model loading/inferencing] then the same will be addressed via #215. More precisely via Developer guide.

**Comment by lessw2020** [comment]
Hi @dhaniram-kshirsagar  - yes that's exactly what I'm after.  Some details on interacting with the logger for debugging, and common issues related to prediction errors, etc would be great as per that issue.
I'll close this one out since it's basically encompassed in #215
