### ISSUE TITLE
Error building GPU image on an Ubuntu 18.04 EC2 Instance m4.xlarge

### ISSUE THREAD

**Issue by josiahdavis** [pytorch/serve#416]
## Context

I am trying to build the docker image for a GPU instance but would like to build the image on a non-GPU instance. I am just trying to build using the [provided docker example](https://github.com/pytorch/serve/tree/master/docker) as is with no modifications.

* torchserve version: I am running a git clone on the current version (master branch)
* torch version: I am running on an m4.xlarge instance outside of any virtual environments with torch installed.
* torchvision version [if any]: N/A
* torchtext version [if any]: N/A
* torchaudio version [if any]: N/A
* java version: 
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
* Operating System and version: Ubuntu 18.04.4 LTS

## Your Environment

* Installed using source? [yes/no]: no (not installed on instance being used to build container)
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]:
* What kind of model is it e.g. vision, text, audio?: Just using the docker 
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.? public url for now using one of the public examples.
  [If public url then provide link.]: https://torchserve.s3.amazonaws.com/mar_files/resnet-18.mar
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: 

config.properties (again, just a copy and paste from the provided example).
```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
number_of_netty_threads=32
job_queue_size=1000
```

logs (see attached)

* Link to your project [if any]: N/A

## Expected Behavior
I am expecting the image to build without errors.

## Current Behavior
Getting `ERROR: Failed building wheel for torchserve`: `subprocess.CalledProcessError: Command 'frontend/gradlew -p frontend clean build' returned non-zero exit status 1.`

See attached for full output.

## Steps to Reproduce

1. Clone the repository
git clone https://github.com/pytorch/serve.git

2. CD into the repo
cd serve/docker/

3. Clone the repo again
git clone https://github.com/pytorch/serve.git

4. Build the docker file
docker build --file Dockerfile.gpu -t torchserve:latest .

## Failure Logs

_Originally posted by @josiahdavis in https://github.com/pytorch/serve/issues/30#issuecomment-631975789_

**Comment by josiahdavis** [comment]
[output.txt](https://github.com/pytorch/serve/files/4710522/output.txt)

Here is full output.

**Comment by harshbafna** [comment]
@josiahdavis : This is a known issue related to intermittent gradle build failure (refer #349) and has been fixed in `staging_0_1_1` branch and will be available in `master` branch with the next release.
