### ISSUE TITLE
Memory footprint optimizations

### ISSUE THREAD

**Issue by mycpuorg** [pytorch/serve#419]
In case of multiple models, we will experience higher memory footprint. We had a patch proposed internally a while back (needs a ton of testing) that uses fork's COW semantics to prevent redundant copies of models from being loaded into memory. 

Linux's fork system call's Copy-On-Write semantics that performs a lazy copy of virtual address spaces from parent to child. Performing a pre-load of the model prior to spawning worker allows for this optimization as long as the worker doesn't update the pages. This should have an impact with memory footprint for multiple models. The increase in footprint is when the model is loaded into memory.

PS: This is from internal discussions with several developers from a while back but relevant here.

**Comment by harshbafna** [comment]
Closing this ticket as Linux fork semantics does not work well with PyTorch models. Instead, we should look for sharing the models across multiple workers through multithreading and/or PyTorch's enhanced multiprocessing.

This will be tracked through #733
