### ISSUE TITLE
How to use management API in Sagemaker? e.g how to change batch size

### ISSUE THREAD

**Issue by bananemure** [pytorch/serve#456]
Hi,

Is it possible to use management api to a sagemaker deployed model?

I am trying to increase the batch size but I don't know if it is doable in sagemaker.

Can we just customise it (batch size) through config.properties so it will apply when sagemaker deploy the model ?

Thanks

**Comment by vdantu** [comment]
@bananemure : I don't there is a way to do this currently. But once https://github.com/pytorch/serve/pull/287 is pulled in, there will be a way to configure batch on your endpoint through `config.properties` file or by giving batch related environment variables when you `create model` on Amazon Sagemaker.

**Comment by bananemure** [comment]
@vdantu Thanks for the reply.
