### ISSUE TITLE
How to avoid contention between models, workers and runtime parallelism?

### ISSUE THREAD

**Issue by la-cruche** [pytorch/serve#459]
Hi! this is a question, not an issue

I see that TorchServe can serve multiple models or multiple workers per model. For example the [AWS blog](https://aws.amazon.com/blogs/machine-learning/deploying-pytorch-models-for-inference-at-scale-using-torchserve/) says "If your model is hosted on a CPU with many cores such as the c5.24xlarge EC2 instance with 96 vCPUs, you can easily scale the number of threads by using the method described previously"

So I see possibly up to 3 things competing for cores:

- multiple models
- multiple workers per model
- multiple threads of the inference runtime running in each worker

Is that understanding correct? How is TorchServe handling that triple level of parallelism? Is there any best practice or settings to tune?

**Comment by harshbafna** [comment]
@la-cruche 

There are two levels of parallelism in TorchServe :
 - ** Frontend model workers**: Whenever a new worker is added to a model, a corresponding new java thread is created.
 - ** Backend model workers**: Each frontend model worker(java thread) creates a backend python process that is responsible for loading the model and running the inference.

The frontend and backend workers work in tandem for every inference request.

For more details refer [TorchServe architecture](https://github.com/pytorch/serve#torchserve-architecture) documentation.

Refer [this](https://github.com/pytorch/serve#concurrency-and-number-of-workers) documentation for best practices to tune the number of workers.

**Comment by sermakarevich** [comment]
@harshbafna Hi, I got a bit different question but ask here as it is related to parallelism as well. 

We have torchserve deployed with 5 different models, 1 worker for every model, instance has 12 threads . The goal is to query all models at the same time. 

When we do this with python multiprocessing.Pool - it takes multiple times longer than querying  every model sequentially one by one. Same thing when we send queries from bash - if requests are sent sequentially, they are processed x4 faster. 

Any hints or links to docs?

**Comment by maaquib** [comment]
Closing. @la-cruche please reopen if you need any further infromation regarding this

**Comment by la-cruche** [comment]
Hi, I have a follow-up question: I see in TorchServe only the ability to configure a number of model workers. But how about the ability to configure the number of CPU allocated to a single model worker? 
Let's take this fictional example: I have a model deployed in TorchServe over an 8-CPU machine. I want to create 2 model workers, using 4 CPU each. How can I configure than in TorchServe?

(that refers to the third level of parallelism mentioned in my initial question, "multiple threads of the inference runtime running in each worker")

**Comment by dhaniram-kshirsagar** [comment]
@la-cruche There is no direct config to do this.
