### ISSUE TITLE
Custom handler template with context error handling

### ISSUE THREAD

**Issue by SlimFrkh** [pytorch/serve#461]
## Is your feature request related to a problem? Please describe.
Custom handler documentation lacks context error handling and context object manipulation. Plus, custom handler can be created as a template with preprocess, predict and postprocess functions or transform function.

## Describe the solution
Port These code snippets from Sagemaker inference toolkit repo:
https://github.com/aws/sagemaker-inference-toolkit/blob/ac1b164aed3c466876452202e5858b620a87c3cc/src/sagemaker_inference/default_handler_service.py#L23
https://github.com/aws/sagemaker-inference-toolkit/blob/ac1b164aed3c466876452202e5858b620a87c3cc/src/sagemaker_inference/transformer.py#L93

**Comment by htappen** [comment]
Incidentally, I think SlimFrikh and I are asking for similar changes: https://github.com/pytorch/serve/issues/434
