### ISSUE TITLE
Pass folder/zipfile to torch-model-archiver

### ISSUE THREAD

**Issue by Varun-Epi** [pytorch/serve#464]
I have been working on deploying deep learning models using serve and been able to deploy BERT models without any issues.

Currently, I have been trying to deploy an allennlp model stored in a folder structure/zipfile (both possible). To load model inside torch_serve_handler:
```
from allennlp.models import load_archive
from allennlp.predictors.predictor import Predictor

archive = load_archive(MODEL_PATH, cuda_device=device)
predictor = Predictor.from_archive(archive, predictor_name="text-classification")
``` 
Tried couple of things,
1. Passed folder to serialized-file argument but it returns error as it expects file.
2. Passed tarfile to serialized-file argument like mentioned below,

```
torch-model-archiver --model-name "text_classifier" --version 1.0 --serialized-file ./model.tar.gz --handler torch_serve_handler.py
mv text_classifier.mar model_store/
torchserve --start --model-store model_store --models text_classifier.mar
```
**Output:**  It generates multiple temp files to save model from tarfile apparently for each worker & keeps on doing that until it empties out total space of the server.

Is there anyway to deploy model saved in a folder or zipfile?

**Comment by harshbafna** [comment]
@Varun-Epi : `TorchServe` extracts the contents of a `mar` file in a temporary location only once at the time of model registration and each worker refers to the same model directory. 

However, the `Predicator.from_archive` function in your code snippet will get executed per worker and it looks like this function is generating temp files in different path every time. 

You could write custom code for model loading aspect in place of `Predicator.from_archive` in your custom handler

**Comment by Varun-Epi** [comment]
Hey @harshbafna, thank you for the quick response.

I found the issue on `load_archive` func which was deliberately creating tempdir for each worker, so took your advice to customize the script & it worked!

Thanks!!

**Comment by nickliu86** [comment]
@Varun-Epi Can you share your script torch_serve_handler.py? I'm trying to use an allennlp model in torchserve but have a hard time to make it work. Thanks a lot!
