### ISSUE TITLE
Add GPU tests to the Automation test framework

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#480]
To catch the regression issues on GPU side, please add support for running the Automation test suite on GPU machines in addition to the current tests on CPUs.  GPU tests can run daily or few times a week.

## Is your feature request related to a problem? Please describe.
The issue with BERT example not running on GPU would have been caught sooner, if the tests were in place. 

## Describe the solution
Spin up GPU instance and run all the tests on GPU. In case the frequency on GPU tests is not the same as the CPU tests, in the Tests/readme page add another status tag for GPU tests success/failure and link to last run tests with the timestamp.

## Describe alternatives solution
None

**Comment by harshbafna** [comment]
Reopened this issue as the bert scripted models are still broken on GPU. This got accidentally merged because code build succeeded due to #564 .

We have reverted back the changes from master and the bert models should be added back in sanity-suite once #479 is fixed.

**Comment by maaquib** [comment]
Latest mar file working with GPU https://torchserve.s3.amazonaws.com/mar_files/BERTSeqClassification_Torchscript_gpu.mar
