### ISSUE TITLE
Is the model-archiver's documentation supposed to look like a page written in basic html?

### ISSUE THREAD

**Issue by TheRochVoices** [pytorch/serve#490]
![Screenshot from 2020-07-02 17-16-52](https://user-images.githubusercontent.com/35432742/86355204-f1b50280-bc87-11ea-84a8-6e4f39bca4cb.png)

From the content it looks like we did not intended the page to look like what it looks in the above screenshot.

**Comment by jlin27** [comment]
I added a fix in this PR: https://github.com/pytorch/serve/pull/497
Could someone from the aws team help review and merge? Thanks!

**Comment by chauhang** [comment]
This has been fixed on pytorcg.org
