### ISSUE TITLE
Inference / prediction does not work, after serving the mnist model from the examples, with change in directory structure

### ISSUE THREAD

**Issue by jesudasvf** [pytorch/serve#495]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.
** Sorry could not locate an issue similar to this

## Context

Trying to serve the mnist classifier example on a Linux Ububtu 18.04 VM on Azure
After serving the model the torchserve keep repeating a message that a worker thread has stopped. 
 

* torchserve version: 0.1.1
* torch-model-archiver: 0.1.1
* torch version: 1.5.1
* torchvision version [if any]:  0.6.1
* torchtext version [if any]: 0.6.0
* torchaudio version [if any]: not installed
* java version: jdk 11
* Operating System and version: Ubuntu 18.04 Bionic (Azure VM)
* python : 3.8.3
* installer : Conda

## Your Environment

* Installed using source? [yes/no]: No
* Are you planning to deploy it using docker container? [yes/no]: No
* Is it a CPU or GPU environment?: GPU - NVIDIA Tesla K80
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom handler as given mnist digit classifier example
https://github.com/pytorch/serve/tree/stage_release/examples/image_classifier/mnist --> handler.py
* What kind of model is it e.g. vision, text, audio?: vision
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.? trained models locally in a folder on /fdrive/model_store
[ts_log.log](https://github.com/pytorch/serve/files/4869241/ts_log.log)

  [If public url then provide link.]:examples from torchserve github
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
  1. Attached the ts_log.log file
  2. command for model archival : torch-model-archiver --model-name mnist --version 1.0 --model-file /fdrive/t_serve_eg/src/model.py --serialized-file /fdrive/t_serve_eg/saved_model/mnist_cnn.pt --export-path /fdrive/model_store --handler /fdrive/t_serve_eg/src/handler.py
 3. command for serving :  torchserve --start --ts_config /fdrive/t_serve_eg/config.properties --model-store /fdrive/model_store --models mnist=mnist.mar
 4. attached the config.properties file
* JAVA_HOME = /usr/lib/jvm/java-11-openjdk-amd64

* Link to your project [if any]:
using the example on a Azure Linux VM
https://github.com/pytorch/serve/tree/stage_release/examples/image_classifier/mnist

## Expected Behavior

After serving the model, a REST API request to predictions should have returned the predicted value. But the rest API hangs 
Also when trying from the web browser http://localhost:8098/predictions/mnist, there is no response received, the web keeps trying continuously. 

## Current Behavior

After serving the model, a REST API request to predictions should have returned the predicted value. But the rest API hangs 
Also when trying from the web browser http://localhost:8098/predictions/mnist, there is no response received, the web keeps trying continuously. 

## Possible Solution

Based on what I see in the logs on the console. Once the model is loaded the first time, one of the worker thread dies, which then causes a series of errors. 

## Steps to Reproduce

1. Build and train the mnist model 
2. Save the trained model in /fdrive/t_serve_p38/saved_model/
3. Create the model archive file using the torch-model-archiver and store the model.mar file in /fdrive/model_store
torch-model-archiver --model-name mnist --version 1.0 --model-file /fdrive/t_serve_eg/src/model.py --serialized-file /fdrive/t_serve_eg/saved_model/mnist_cnn.pt --export-path /fdrive/model_store --handler /fdrive/t_serve_eg/src/handler.py
4. serve the model using torchserve
torchserve --start --ts_config /fdrive/t_serve_eg/config.properties --model-store /fdrive/model_store --models mnist=mnist.mar

## Failure Logs [if any]

[ts_log.log](https://github.com/pytorch/serve/files/4869457/ts_log.log)

**Comment by harshbafna** [comment]
@jesudasvf :

From the provided logs, I observed following error while loading the model :

```
2020-07-03 08:20:47,007 [INFO ] W-9000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     from src.model import Net
2020-07-03 08:20:47,007 [WARN ] W-9000-mnist_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-mnist_1.0-stdout
2020-07-03 08:20:47,007 [INFO ] W-9000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'src'
```

Looks like you have modified the custom handler supplied with the `mnist` example and replaced 

```
from model import Net
```

to 

```
from src.model import Net
```

**Comment by jesudasvf** [comment]
> @jesudasvf :
> 
> From the provided logs, I observed following error while loading the model :
> 
> ```
> 2020-07-03 08:20:47,007 [INFO ] W-9000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     from src.model import Net
> 2020-07-03 08:20:47,007 [WARN ] W-9000-mnist_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-mnist_1.0-stdout
> 2020-07-03 08:20:47,007 [INFO ] W-9000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'src'
> ```
> 
> Looks like you have modified the custom handler supplied with the `mnist` example and replaced
> 
> ```
> from model import Net
> ```
> 
> to
> 
> ```
> from src.model import Net
> ```

Thanks @harshbafna 
I had created a folder called src and moved the model.py, and all the code under the src folder. 
I will try by maintaining the original folder structure and revert with the results.

**Comment by jesudasvf** [comment]
Added the following lines in the handler code to make it work with a different dir structure

import sys
sys.path.insert(1, '/fdrive/t_serve_eg/src/')

Rebuilt the model archive with this change and torchserve is working well and predictions are successful. 

thanks @harshbafna for pointing out the issue.

**Comment by harshbafna** [comment]
@jesudasvf : I would not recommend setting a local drive to the system path. Instead, you could zip/tar your dir structure and supply it with the `--extra-files` param while creating the model-archive. Then later you can unzip this in the model directory while initializing your model.

You can refer the following mar creation step and handler from [waveglow example](https://github.com/pytorch/serve/tree/master/examples/text_to_speech_synthesizer)

 - [mar creation](https://github.com/pytorch/serve/blob/master/examples/text_to_speech_synthesizer/create_mar.sh#L17)
 - [Waveglow handler](https://github.com/pytorch/serve/blob/master/examples/text_to_speech_synthesizer/waveglow_handler.py#L57) for example.

**Comment by jesudasvf** [comment]
thanks @harshbafna for suggesting how to handle the change in directory structure. I will try the recommended method and revert. 

I had a couple of questions
1. why does the TS-METRICS not include GPU utilization?
2. When I add debug log messages in the handler, I do not see them in the console output neither in the TS_LOG file? where can I see the debug log messages added in the handler code?
3. How can I confirm that the torchserve is serving the models on the GPU?

**Comment by harshbafna** [comment]
> thanks @harshbafna for suggesting how to handle the change in directory structure. I will try the recommended method and revert.
> 
> I had a couple of questions
> 
> 1. why does the TS-METRICS not include GPU utilization?
> 2. When I add debug log messages in the handler, I do not see them in the console output neither in the TS_LOG file? where can I see the debug log messages added in the handler code?
> 3. How can I confirm that the torchserve is serving the models on the GPU?

 - TS metric currently just captures the CPU usage. This can be taken up as a future enhancement.
 - It should get logged into the `ts_log.log` file. Make sure you are using the root logger from `logging` module provided by python.
 - You can use the [describe api](https://github.com/pytorch/serve/blob/master/docs/management_api.md#describe-model) to check if the worker is running on CPU or GPU. You could also use `nvidia-smi` to check the workers created on GPU.

**Comment by jesudasvf** [comment]
thanks a lot ! @harshbafna for the response. Will check out the details as pointed out by you.
