### ISSUE TITLE
Model's memoryUsage double its size after a inference request

### ISSUE THREAD

**Issue by dhaniram-kshirsagar** [pytorch/serve#499]
Model's memoryUsage double its size after a request. 
model archive size: 106MB
memoryUsage after load: 175-220 MB
after an inference request (or a couple of) memoryUsage spike to ~400MB

in a pure python I can control the process size to be less than 200 MB always. 

![image](https://user-images.githubusercontent.com/9593371/85769150-04748800-b71a-11ea-8d12-090a8a5fadfe.png)
![image](https://user-images.githubusercontent.com/9593371/85769365-34239000-b71a-11ea-896f-27d0a9025627.png)

_Originally posted by @sermakarevich in https://github.com/pytorch/serve/issues/481#issuecomment-649718275_

**Comment by dhaniram-kshirsagar** [comment]
Please comment in #481 - This requires fix to default handlers where `with no_grade: `context manager is not used.

**Comment by dhaniram-kshirsagar** [comment]
Updates - 
The increase in size [without no_grad] is model dependent per our observations .e.g in case of vgg11 or resnet-18 based cnn models memory increases by 20-30% however for densenet-161, it doubles! Tried running gc explicitly however no memory is released.

NOTE even after deactivating autograd engine, we saw a 10-15% increase in memory footprint based on model type as explained above. Example models provided with torchserve have been taken from torch hub.

Raised ticket with pytorch forum -  [#89035](https://discuss.pytorch.org/t/is-increase-in-model-memory-post-prediction-forward-call-expected/89035)

**Comment by sermakarevich** [comment]
Hey @dhaniram-kshirsagar. I have made the fix with no-grad on my end and did additional profiling, this is what I got: 
```
MB
- jit traced model size on disk 150
- torch-model-archive on disk  140
- inside python process (import torch; torch.jit.load) 163 + (50 torch lib), smem PSS
- inside torchserve process 465, smem PSS
```
