### ISSUE TITLE
Setting batch inference.

### ISSUE THREAD

**Issue by baopanda** [pytorch/serve#500]
Hi all, 
I am running my model using torch serve but when I configure TorchServe to use the batching feature, it get an error.
 

> curl -X POST "localhost:8081/models?url=segment.mar&batch_size=8&max_batch_delay=50"

and the error: 

> {
  "code": 409,
  "type": "ConflictStatusException",
  "message": "Model version 1.0 is already registered for model segment"
}

Thank you in advance for helping me.

**Comment by harshbafna** [comment]
@baopanda : As the error message clearly indicates, a model named `segment` is already registered in `TorchServe`.

To handle this you could do one of the following :

 - Register the model with a different name. You could use `model_name` parameter while registering the model. Sample :

```
curl -X POST "localhost:8081/models?url=segment.mar&batch_size=8&max_batch_delay=50&model_name=segment_batch"
```

This will register the model with the name `segment_batch`

 - Change the model version while creation the mar, to value other than `1.0`. This will allow registering the model with same name but a different version. 

 - Change the model name while creating the mar file. In this case, you will not need to supply the `model_name` parameter while registering the model.

 - If not required, unregister the existing `segment` model and then re-register the model.

**Comment by baopanda** [comment]
@harshbafna Thank for your reply, I have setup some basic config with min_workers and max_workers = 6, batch_size =8.
but when I testing with apache benchmark, i got an error: 
`ab -k -l -n 1000 -c 10 -p test1.json -T 'application/json' http://127.0.0.1:8080/predictions/segment_batch`
and the error: 

> apr_socket_recv: Connection reset by peer (104)

Another question I want to ask you is "How can I decode the response that TS will give to me? becase of some non-English character will not decode, for ex "sáng suốt" --> "s\u1eedng s\u1ed1t". "

Thank you for helping me, I am very appreciate.

**Comment by baopanda** [comment]
@harshbafna Do you have any ideas?

**Comment by harshbafna** [comment]
@baopanda : 

> 2020-07-07 11:15:54,969 [INFO ] W-9004-segment_batch_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - model: segment_batch, number of batch response mismatched, expect: 8, got: 1.

`TorchServe` creates a batch of requests (list) based on the configured batch size (8 in your case) in the frontend and forwards it on to the model's handler and expects a response of similar size. In your case, the custom handler is returning back a list with a single item and hence the above error is observed.

You could refer the following example custom handler with batch inferencing support : [resnet-152 batch handler](https://github.com/pytorch/serve/blob/master/examples/image_classifier/resnet_152_batch/resnet152_handler.py)

> Another question I want to ask you is "How can I decode the response that TS will give to me? because of some non-English character will not decode, for ex "sáng suốt" --> "s\u1eedng s\u1ed1t". "

Could you please share a sample request command and response received?

**Comment by baopanda** [comment]
Thank for your help mr @harshbafna 
This is my json file that i will sent to the api:

> {
	"sentence":"Hà Đức Chinh tỏa sáng với hat-trick vào lưới Brunei và khiến HLV Park Hang Seo 2 lần trong phòng họp báo sửng sốt."
}

and the response I have printed after preprocessing phrase:

```
def postprocess(self, outputs):
        tagset_size = len(self.l_map)
        start_tag = self.l_map['<start>']
        end_tag = self.l_map['<pad>']

        res = []

        for output in outputs:
            scores = output[0]
            mask = output[1]
            features = output[2]
            indexes = output[3]

            decoded = decode_torch.decode(scores, mask, start_tag, tagset_size, end_tag)

            result = decode_torch.decode_seg(features[0][0], decoded, indexes[0][0], self.l_map)

            res.append(result)

            print(res)

        return res`

> [[{'word': 'Hà Đức Chinh', 'start_index': 0, 'end_index': 12}, {'word': 'tỏa', 'start_index': 13, 'end_index': 16}, {'word': 'sáng', 'start_index': 17, 'end_index': 21}, {'word': 'với', 'start_index': 22, 'end_index': 25}, {'word': 'hat-trick', 'start_index': 26, 'end_index': 35}, {'word': 'vào', 'start_index': 36, 'end_index': 39}, {'word': 'lưới', 'start_index': 40, 'end_index': 44}, {'word': 'Brunei', 'start_index': 45, 'end_index': 51}, {'word': 'và', 'start_index': 52, 'end_index': 54}, {'word': 'khiến', 'start_index': 55, 'end_index': 60}, {'word': 'HLV', 'start_index': 61, 'end_index': 64}, {'word': 'Park Hang Seo', 'start_index': 65, 'end_index': 78}, {'word': '2', 'start_index': 79, 'end_index': 80}, {'word': 'lần', 'start_index': 81, 'end_index': 84}, {'word': 'trong', 'start_index': 85, 'end_index': 90}, {'word': 'phòng họp', 'start_index': 91, 'end_index': 100}, {'word': 'báo', 'start_index': 101, 'end_index': 104}, {'word': 'sửng sốt', 'start_index': 105, 'end_index': 113}, {'word': '.', 'start_index': 113, 'end_index': 114}]]

but when I am using postman to get response, i will give me the unexcepted output:

> [
  {
    "word": "H\u00e0 \u0110\u1ee9c Chinh",
    "start_index": 0,
    "end_index": 12
  },
  {
    "word": "t\u1ecfa",
    "start_index": 13,
    "end_index": 16
  },
  {
    "word": "s\u00e1ng",
    "start_index": 17,
    "end_index": 21
  },
  {
    "word": "v\u1edbi",
    "start_index": 22,
    "end_index": 25
  },
  {
    "word": "hat-trick",
    "start_index": 26,
    "end_index": 35
  },
  {
    "word": "v\u00e0o",
    "start_index": 36,
    "end_index": 39
  },
  {
    "word": "l\u01b0\u1edbi",
    "start_index": 40,
    "end_index": 44
  },
  {
    "word": "Brunei",
    "start_index": 45,
    "end_index": 51
  },
  {
    "word": "v\u00e0",
    "start_index": 52,
    "end_index": 54
  },
  {
    "word": "khi\u1ebfn",
    "start_index": 55,
    "end_index": 60
  },
  {
    "word": "HLV",
    "start_index": 61,
    "end_index": 64
  },
  {
    "word": "Park Hang Seo",
    "start_index": 65,
    "end_index": 78
  },
  {
    "word": "2",
    "start_index": 79,
    "end_index": 80
  },
  {
    "word": "l\u1ea7n",
    "start_index": 81,
    "end_index": 84
  },
  {
    "word": "trong",
    "start_index": 85,
    "end_index": 90
  },
  {
    "word": "ph\u00f2ng h\u1ecdp",
    "start_index": 91,
    "end_index": 100
  },
  {
    "word": "b\u00e1o",
    "start_index": 101,
    "end_index": 104
  },
  {
    "word": "s\u1eedng s\u1ed1t",
    "start_index": 105,
    "end_index": 113
  },
  {
    "word": ".",
    "start_index": 113,
    "end_index": 114
  }
]

**Comment by harshbafna** [comment]
@baopanda 

I created a dummy handler that returns an unicode string in response.

```
class MyUnicodeHandler(object):

    def initialize(self, ctx):
        pass

    def handle(self, data, context):
        return [u'Hà Đức Chinh']
```

and executed a simple inference request on this model using `curl` as well as `postman app` but couldn't reproduce the issue :

```
$ curl -X POST "http://localhost:8081/models?url=unicode-test.mar&initial_workers=1"
{
  "status": "Model \"unicode-test\" Version: 1.0 registered with 1 initial workers"
}
$ curl -X POST "http://localhost:8080/predictions/unicode-test" -T ~/test_images/kitten.jpg 
Hà Đức Chinh
```

<img width="970" alt="Screen Shot 2020-07-07 at 3 32 31 PM" src="https://user-images.githubusercontent.com/26594595/86765995-8abc9280-c067-11ea-9cb2-022e4a0ad1be.png">

**Comment by ndvbd** [comment]
> @baopanda :
> 
> > 2020-07-07 11:15:54,969 [INFO ] W-9004-segment_batch_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - model: segment_batch, number of batch response mismatched, expect: 8, got: 1.
> 
> `TorchServe` creates a batch of requests (list) based on the configured batch size (8 in your case) in the frontend and forwards it on to the model's handler and expects a response of similar size. In your case, the custom handler is returning back a list with a single item and hence the above error is observed.
> 
> You could refer the following example custom handler with batch inferencing support : [resnet-152 batch handler](https://github.com/pytorch/serve/blob/master/examples/image_classifier/resnet_152_batch/resnet152_handler.py)
> 
> > Another question I want to ask you is "How can I decode the response that TS will give to me? because of some non-English character will not decode, for ex "sáng suốt" --> "s\u1eedng s\u1ed1t". "
> 
> Could you please share a sample request command and response received?

Why do we need to "configure batch size"? Every query/inference can have a different size of batch, so what's the point in configuring it beforehand? Where's the relevant documentation for this process?
