### ISSUE TITLE
CircleCI Enchancements

### ISSUE THREAD

**Issue by prashantsail** [pytorch/serve#505]
## Is your feature request related to a problem? Please describe.
- Enhance CircleCI configuration for independent build and test jobs.
- Support for workflows like smoke \ regression \ performance along with scheduling on specific branches
- Better error reporting \ feedback on test failures
- Optimize build time by eliminating creation of a new docker image on every build trigger
- Support for executing CircleCI jobs on developer's local machine

## Describe the solution
1. Create a docker image tailored for torchserve builds, make it available in public dockerhub registry
2. In CircleCI's config.yaml
    - Separate torchseve\modelarchiver build and tests as independent jobs
        - Use the docker image(from Step1) as an executor for all the jobs
        - Add new jobs like - torchserve build, python tests, newman tests, benchmark, modelarchiver build and tests
    - Each job to store respective build\test artifacts for better reporting
    - Create and use workflows along with triggers\schedule\branches to orchestrate jobs
3. Create a script using "circleci cli" to help developers execute a specific job \ all jobs from a workflow on their local machine

## Describe alternatives solution
\-

**Comment by dhaniram-kshirsagar** [comment]
@prashantsail Please add following to nightly build task
- It should build binary using available scripts
- Binary should be either placed on Github or linked to S3

Also, need to incorporate benchmark-ab script in nightly.
