### ISSUE TITLE
models "all" option only starts first mode found in model store

### ISSUE THREAD

**Issue by bigswede74** [pytorch/serve#512]
## Issue
Torchserve start with models "all" option only starts the first model found in the model store unless snapshots are disabled. All models are started if the --ncs option is added.

**Only first model is started**
```bash
torchserve --start --model-store model_store --models all
```

**All models are started**
```bash
torchserve --start --ncs --model-store model_store --models all
```

* torchserve version: 0.1.1
* Operating System and version: ubuntu 18.04

## Environment

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: no
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: Using Custom Handlers
* What kind of model is it e.g. vision, text, audio?: Image Segmentation
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: Local model store
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Expected Behavior
The "all" option should start all the models found in the model store

## Current Behavior
Only the first model found is started unless the --ncs option is supplied

## Steps to Reproduce
1. Create two .mar files
2. Add both .mar files to a model store
3. Start torchserve using the below command
```bash
torchserve --start --model-store model_store --models all
```
4. Run the below command to query for running models and observe only a single model is running
```bash
curl "http://localhost:8081/models
```
```json
{
  "models": [
    {
      "modelName": "model_1",
      "modelUrl": "model_1.mar"
    }
  ]
}
```
5. Stop torchserve
```bash
torchserve --stop
```
6. Start torchserve using the below command disabling the snapshots feature
```bash
torchserve --start --ncs --model-store model_store --models all
```
7. Run the below command to query for running models and observe both models are running
```bash
curl "http://localhost:8081/models
```
```json
{
  "models": [
    {
      "modelName": "model_1",
      "modelUrl": "model_1.mar"
    },
   {
      "modelName": "model_2",
      "modelUrl": "model_2.mar"
    }
  ]
}
```

**Comment by harshbafna** [comment]
@bigswede74 : I could not reproduce this issue on the latest master.

Following is my model store :

```
ubuntu@ip-172-31-54-27:~$ ls model-store/
densenet161.mar  resnet-18.mar
```

I used the following command to start `TorchServe` :

```
torchserve --start --model-store model-store --models all
```

And following is the output of list models API :

```
ubuntu@ip-172-31-54-27:~$ curl "http://localhost:8081/models"
{
  "models": [
    {
      "modelName": "densenet161",
      "modelUrl": "densenet161.mar"
    },
    {
      "modelName": "resnet-18",
      "modelUrl": "resnet-18.mar"
    }
  ]
}

```

Detailed logs : 
[load_all_models_on_startup.log](https://github.com/pytorch/serve/files/4898522/load_all_models_on_startup.log)


Could you please check if there is no old snapshot config available in `logs/config`. `TorchServe` by default loads the most recent snapshot file available. Supplying the `--ncs` flag disables the snapshot feature and `TorchServe` starts normally.

**Comment by bigswede74** [comment]
@harshbafna  What am I looking for? I have eight .cfg files in that directory, 4 startup and 4 shutdown.

**Comment by harshbafna** [comment]
@bigswede74 :  The snapshot files get generated on startup, shutdown, and every management API call. These snapshot files have timestamp in the filename in `yyyyMMddHHmmssSSS` format and based on this timestamp `TorchServe` will select the latest one while starting and load the models present in the`model_snapshot` parameter in the snapshot file. 

Note that the `--models` parameter is ignored if `TorchServe` is restoring from a snapshot.

**Comment by harshbafna** [comment]
@bigswede74: You can refer to the [snapshot documentation](https://github.com/pytorch/serve/blob/master/docs/snapshot.md) for more details on the snapshot feature.

**Comment by bigswede74** [comment]
@harshbafna  So I can just clear out this folder to get back to a good state?

**Comment by harshbafna** [comment]
> @harshbafna So I can just clear out this folder to get back to a good state?

Yes. Or if you don't want to use snapshot feature, just use `--ncs` to disable it while starting `TorchServe` :-)

**Comment by bigswede74** [comment]
@harshbafna Thanks for the help.
