### ISSUE TITLE
 Invalid return type: <class 'numpy.ndarray'>.

### ISSUE THREAD

**Issue by buqing2009** [pytorch/serve#526]
When I post process the inference output in handler, it seems that it only support return list object. But some model of other tasks like depth estimation, sceneflow, 3D reconstruction..., the output is just a image. It's necessary for torch serve to response the client request, and return an image url.

**Comment by harshbafna** [comment]
@buqing2009: You could return the binary data for the image generated by your model and write it to a file at the client end.

You can refer the following examples :
 - [Waveglow speech to text synthesizer](https://github.com/pytorch/serve/tree/master/examples/text_to_speech_synthesizer)
 - [Image segmentation example using fcn_resnet_101_coco model](https://github.com/pytorch/serve/tree/issue_355/examples/image_segmenter)

**Comment by buqing2009** [comment]
thanks， it's helpful

**Comment by sevenold** [comment]
for example， the text detection(CTPN, CRAFT, EAST...) model output a lot of images.  How should I use other default return methods in my custom handler.  [{},{}],[[[]]] not only []  Thanks.
@harshbafna
