### ISSUE TITLE
Newbie Questions about pytorch version compatibility 

### ISSUE THREAD

**Issue by philipskokoh** [pytorch/serve#539]
I have one quick question. Based on the guideline, we need to archive all model artifacts into `.mar` file before we can register the model to TorchServe.
https://github.com/pytorch/serve/blob/master/model-archiver/README.md

Does the `torch-model-archiver` have assumptions/requirements on pytorch models that can be archived? Is it compatible with all pytorch versions. Let say we have few models written in different pytorch version such as v1.0.0, v1.1.0, v1.2.0. Can we use `torch-model-archiver` to archive them?

Thank you very much.

**Comment by harshbafna** [comment]
@philipskokoh : `torch-model-archiver` has no dependency on `PyTorch` version. It is just a utility to package all the model's dependency files in one single archive file `.mar`. What you need need to ensure is that the model artifacts like `model-file`, `state-dict`, `checkpoint`, handler(used for model loading and inferencing), etc. are compatible with the version of `PyTorch` and other torch packages like `torchvision`, `torchtext` etc. which are installed along with `TorchServe`.

**Comment by philipskokoh** [comment]
I see. So I just need to ensure that no conflicts among the pytorch and my model dependencies in one `TorchServe` instance. Thanks for the clarification.

Sorry, one more quick question: 
If the model size is not too big, do you suggest we share one GPU to run multiple installed pytorch models inference in `TorchServe`? Any considerations about pros and cons? 

Thank you.

**Comment by harshbafna** [comment]
> I see. So I just need to ensure that no conflicts among the pytorch and my model dependencies in one `TorchServe` instance. Thanks for the clarification.
> 
> Sorry, one more quick question:
> If the model size is not too big, do you suggest we share one GPU to run multiple installed pytorch models inference in `TorchServe`? Any considerations about pros and cons?
> 
> Thank you.

It will depend on the number of models and workers per model. `TorchServe` creates one java thread per and one python process per worker. You could refer the following documentation for deciding on the number of workers :

[Concurrency And Number of Workers](https://github.com/pytorch/serve#concurrency-and-number-of-workers)

**Comment by philipskokoh** [comment]
Understand. Thank you very much for the clarification! :)
