### ISSUE TITLE
Can development environment transfer to Serving environment?

### ISSUE THREAD

**Issue by wangxiang2713** [pytorch/serve#545]
Hi, when i develop my model, i used some third party libraries, which serving environment doesn't contain, how can TorchServer supports models developed in different environment?

**Comment by harshbafna** [comment]
@wangxiang2713: Please have a look at this PR https://github.com/pytorch/serve/pull/462, which adds support for supplying model specific packages with the mar file.

**Comment by wangxiang2713** [comment]
Hi, thank you for your response, i have read official documents about mar file, i wonder if my model need third party libraries such as some python libraries, is mar file recommended solution?

**Comment by harshbafna** [comment]
> @harshbafna: Hi, thank you for your response, i have read official documents about mar file, i wonder if my model need third party libraries such as some python libraries, is mar file recommended solution?

@wangxiang2713: This PR (#462) is a new feature in progress and will be available as a part of the upcoming release. Have you looked into the details of this PR?

**Comment by wangxiang2713** [comment]
> > @harshbafna: Hi, thank you for your response, i have read official documents about mar file, i wonder if my model need third party libraries such as some python libraries, is mar file recommended solution?
> 
> @wangxiang2713: This PR (#462) is a new feature in progress and will be available as a part of the upcoming release. Have you looked into the details of this PR?

@harshbafna Oh, i'm very sorry, it looks amazing! Thankyou very much.

**Comment by damosuzuki** [comment]
Looks like https://github.com/pytorch/serve/pull/462 will solve my problem. However, is there a known workaround for supplying packages in 0.1.1?
