### ISSUE TITLE
OpenCV in Docker by default?

### ISSUE THREAD

**Issue by ptschandl** [pytorch/serve#546]
Given its prominent use in other libraries (e.g. albumentations) and probable enhancements in custom handlers, would it make sense to install opencv by default in the official pytorch docker container(s)?  
`RUN pip install --no-cache-dir torch torchvision torchtext torchserve torch-model-archiver opencv-python`
https://github.com/pytorch/serve/blob/ebe55b0d099aa0e7c32af6a284d11b992c86078b/docker/Dockerfile#L50

**Comment by harshbafna** [comment]
@ptschandl: Please have a look at this PR #462, which adds support for supplying model specific packages with the mar file. This feature will be available in the upcoming release.
