### ISSUE TITLE
the link to the Resnet-152 handler py code on the "https://pytorch.org/serve/batch_inference_with_ts.html#" web page needs to be updated

### ISSUE THREAD

**Issue by jesudasvf** [pytorch/serve#548]
## 📚 Documentation

On the web page
https://pytorch.org/serve/batch_inference_with_ts.html#

When you click on the hyperlink  resnet152_handler.py,  in section https://pytorch.org/serve/batch_inference_with_ts.html#id4
it redirects you to 
https://pytorch.org/examples/image_classifier/resnet_152_batch/resnet152_handler.py
![torchserve_batchHandler_example_incorrect_link](https://user-images.githubusercontent.com/40178708/88185719-e6834000-cc51-11ea-8eb3-19f8cec76693.png)

Whereas it should redirect you to 
https://github.com/pytorch/serve/blob/master/examples/image_classifier/resnet_152_batch/resnet152_handler.py
where the referred sample script is available
![torchserve_batchHandler_example_correct_link](https://user-images.githubusercontent.com/40178708/88185874-12062a80-cc52-11ea-9c3a-7e81042597aa.png)

Similarly please check all the hyperlinks on this page, most of them are redirecting to pages which do not exist. 
1. Hyperlink to custom service code in the Prerequisites
2. * POST/models** API under TorchServe Model configuration section
3.  Under the section "Demo to configure TorchServe with batch-supported model" two hyperlinks "Readme" under the prerequisites and 
resnet152 image classification example hyperlink, under the "Loading Resnet-152 which handles batch inferences"

**Comment by Jrokisky** [comment]
Linking to a similar issue reported on the pytoch.github.io repo: https://github.com/pytorch/pytorch.github.io/issues/425
