### ISSUE TITLE
Dump system metrics in a database

### ISSUE THREAD

**Issue by vishal-wiai** [pytorch/serve#553]
How should I access system metrics to dump it in a SQL database?

Also, what are the best practices for logging inference predictions in a database?

**Comment by dhaniram-kshirsagar** [comment]
@vishal-wiai At present, there is no api interface to dump system metrics to SQL database however the torchserve metrics are generated in ts_model.log and ts_metrics.log. These are pip '|' separated files which can be easily parsed and serialized to any DB.

Can you please elaborate/use case, why you want to log inference data in DB?

**Comment by vishal-wiai** [comment]
I want to track and monitor the prediction generated by my model when an inference request was served. Later, I would use the predictions for analysis and fine-tune.

**Comment by dhaniram-kshirsagar** [comment]
@vishal-wiai You can use a solution similar to the one given here - [Adding predictions to DB](https://github.com/pytorch/serve/issues/581#issuecomment-667464975)
