### ISSUE TITLE
Is there a way to test my handle file before serving my model?

### ISSUE THREAD

**Issue by wangxiang2713** [pytorch/serve#558]
Hi, i recently use TorchServer to serving my model. For each model i write a handle file, but i don't know how to test it. Is there a way to test my handle file before serving my model?

**Comment by harshbafna** [comment]
@wangxiang2713: 

You could simply write python code to test model loading (initialize) and inferencing (pre-process, inference and post-process) outside TorchServe where you can hard-code the device and paths for model definition file and/or model's serialized file.

Once you are satisfied with the results then convert the same code into a handler file and replace the hard-coded values with the dynamic values for `gpuid`, `model_dir` etc from the `context` object which is made available to the handler by TorchServe.

You could also write a mock class with dummy context while writing the test handler which will make it look more or less similar to the final handler which you will bundle in the `model-archive`

**Comment by harshbafna** [comment]
Closing due to no response from OP.
