### ISSUE TITLE
Diffcult to continuously rollout and serve multiple models at scale with Kubernetes

### ISSUE THREAD

**Issue by misrasaurabh1** [pytorch/serve#560]
Assume an architecture where in a Kubernetes environment a gateway service generates API requests for models which are then handled by TorchServe. We deploy models where torchserve is serving multiple models that are for the same use case but maybe have different architectures or trained on different data for AB testing.
In such a case it is very difficult for the gateway service to know what models are being served by Torchserve service.

The requirement is that with a new model being released, the gateway should know what models are being served by Torchserve. 
One way would be to `GET  /models ` to figure out what models are being served by torchserve but that would mean that the gateway gets lists of models and setting each models' traffic allotment becomes difficult to set up. This is because an AB-testing config would say "model-1" gets 40% traffic and "model-2" gets 60% traffic. Now what does it do for "model-3"? Even if I set this separately for model-3, how do I ensure that those settings get activated when model-3 has started being served by torchserve? Possibility for a lot of dropped requests when a new model is released.

Another way is that I just say torch serve just serves 2 models "red" and "blue" and I set which models gets assigned to "red" and "blue" but then I am only restricted to two models and not really using the torchserve APIs properly. This is the simplest to orchestrate.

Another problem is ensuring gateway and torchserve is in sync while deploying new models. How do I make sure both the gateway and torchserve at the same time start using the same model? It is possible that torchserve loads new model and the gateway still hits and misses the older model.

Trying to highlight a problem with the way Torchserve does things.

These problems could be solved if torchserve itself had an AB testing mechanism where if I hit `/predictions` a custom code would help me decide which model would serve this request. I could set it up using a service like Optimizely. This would hide all this model selection problem from the gatway as it can always request predictions from torchserve and it would provide it the selected model. Deploying new models now just means updating the image of torchserve and kubernetes and torchserve handles everything else.

Registering a new model through the management API is complicated and not possible because our models are private and not available on the public internet

**Comment by dhaniram-kshirsagar** [comment]
@misrasaurabh1 Thanks for listing out deployment issues that you are facing. We will get back to you on this.

 For the last part, there is an open enhancement request #476  for having customizable downloader

**Comment by chauhang** [comment]
@misrasaurabh1 Please check the TorchServe KFServing integration with the [canary rollout ](https://github.com/kubeflow/kfserving/blob/master/docs/samples/v1beta1/torchserve/canary/README.md)feature for this.
