### ISSUE TITLE
Doc reviews + enhancements

### ISSUE THREAD

**Issue by dhaniram-kshirsagar** [pytorch/serve#561]
## 📚 Documentation

This has been created to review overall doc changes and figure out if there are any technical or doc flow shortcomings-
Findings - 
1. Add a link to custom handler doc in MAR doc
2. Provide more details around requirements.txt which is a parameter to torch-model-archive when you someone wants to install model-specific python packages

....more to be added and fixed

**Comment by deepakbabel** [comment]
Some documentations sections appear to be broken in examples section. Here are the steps that I tried:
1) Navigate to https://github.com/pytorch/serve/tree/master/examples[#85].
The following URL's are not updated properly:
- Serving torchvision image classification models in TorchServe
- Serving custom model with custom service handler
- Serving text classification model
- Serving object detection model
- Serving image segmentation model

Also subsection for Hugging Face Transformers is missing from the above list.

**Comment by deepakbabel** [comment]
In examples section for batch inference, there is some typos. Details below:
Navigate to https://github.com/pytorch/serve/blob/master/docs/batch_inference_with_ts.md#batch-inference-with-torchserve-using-resnet-152-model

In the "Run inference to test the model" section, the port number is missing while infering:
curl localhost/predictions/resnet-152-batch -T kitten.jpg
As the port number is not specified, it will normally default to port 80 and hence throw error while trying to run inference.
