### ISSUE TITLE
How to use model archiver utility for complex projects?

### ISSUE THREAD

**Issue by sagjounkani** [pytorch/serve#566]
I am trying to serve the model from the [NCRFpp](https://github.com/jiesutd/NCRFpp) project using torchserve. The files that are required by my custom _handler.py_ file are in multiple folders and have import statements which refer to this folder hierarchy. The model archiver zips all these files and extracts into a temporary folder at the same level without this folder hierarchy, leading to runtime errors because the import statements fail. How do I ensure that the import statements work, with same folder hierarchy as used during development, while using torchserve?

**Comment by harshbafna** [comment]
@sagjounkani: You could create a zip file of the dependency python files in the required folder hierarchy and supply this zip file using the `--extra-files` parameter while creating the mar. Later while initializing the handler you could extract this zip file, in the model's temporary directory which is already added in the `PYTHONPATH`

You can refer to the [waveglow text-to-speech-synthesizer](https://github.com/pytorch/serve/tree/master/examples/text_to_speech_synthesizer) example

 - [waveglow mar creation script](https://github.com/pytorch/serve/blob/master/examples/text_to_speech_synthesizer/create_mar.sh)
 - [waveglow handler](https://github.com/pytorch/serve/blob/master/examples/text_to_speech_synthesizer/waveglow_handler.py#L57)

**Comment by misrasaurabh1** [comment]
Yep, I encountered this problem as well. Even though the files specified by `--extra-files` even though may belong to a directory structure, torchserve copies them all to a single top level directory while serving. This complicates things for applications. Also there is a big possibility of filename collisions. I would like the directory structure of the files within the `--extra-files` to be preserved.
Also, if the current behavior is what is expected it should be made clear in the documentation.

**Comment by sagjounkani** [comment]
@harshbafna Thank you for the resolution, I was able to deploy the model. I found it easier to append the path for dependencies in my custom handler file compared to the process followed in the waveglow text-to-speech-synthesizer example. Not sure of a standard way to approach this. Agree with @misrasaurabh1 that if somehow the directory structure is preserved within the --extra-files it will make things easier.

**Comment by harshbafna** [comment]
@sagjounkani: Your solution may work when TorchServe is deployed on your localhost, however, it will fail in case you need to register the model on a remote host where the extra files will not be available on the server's file system.

There are multiple ways you can add you dependency python files in the model-archive :

 - zip your directory structure as required and unzip in the handler (as explained earlier)
 - You could also create an egg file for all the dependency python packages and add that in the model-archive(.mar).
 - if your model is dependent on a third-party python package, you could also supply a requirements.txt file to include a list of all the python modules required in the mar file. Refer [documentataion](https://github.com/pytorch/serve/blob/master/docs/configuration.md#allow-model-specific-custom-python-packages) for more details. Note that, this feature is not available in the current GA release but is available in the latest master. It will be a part of the upcoming release.
 - In case the project is not available on PyPi repo, you can manually create the build for that project and supply the generated `.tar.gz` or `.zip` file in the and include it in the requirements.txt.

@misrasaurabh1: 

> Also, if the current behavior is what is expected it should be made clear in the documentation.

We will take this up as a part of #568 . Also, if you think the above-provided options are too complicated please feel free to raise a feature request.

**Comment by hatzel** [comment]
While I think this is certainly an area where torchserve should support a simpler approach, let me share my work around with you.

The implementation [here](https://github.com/pytorch/serve/blob/72761c050b4c05616a02c917844e1492c9dc8611/model-archiver/model_archiver/model_packaging_utils.py#L148-L159) just recursively copies any sub directories (of the included directories) over. You can actually trick this into doing what you want by creating a temporary directory into which you symlink the directories you originally wanted to include. 
```bash
TEMP_DIR=$(mktemp -d)
ln -s "$(pwd)/dir_a" $TEMP_DIR
ln -s "$(pwd)/dir_b" $TEMP_DIR

# call torch-model-archiver with `--extra-files $TEMP_DIR` here

rm -rf $TEMP_DIR
```

The resulting archive will include the top level directories named `dir_a` and `dir_b`.

**Comment by mhashas** [comment]
Yes, and a drawback of your approach is that all imports need to be done locally in functions, after the unzipping was done: https://github.com/pytorch/serve/blob/master/examples/text_to_speech_synthesizer/waveglow_handler.py#L40. If you move this import at the top-level, it would fail, because the source files don't exist yet. For my use-case, I cannot add the shared handler as a base class to the handler, because it only exists after the handler was initialized and the zip unzipped.

I think in the end @hatzel's response is the easiest one to implement and does solve my problem.

**Comment by harshbafna** [comment]
> @harshbafna Yes, and a drawback of your approach is that all imports need to be done locally in functions, after the unzipping was done: https://github.com/pytorch/serve/blob/master/examples/text_to_speech_synthesizer/waveglow_handler.py#L40. If you move this import at the top-level, it would fail, because the source files don't exist yet. For my use-case, I cannot add the shared handler as a base class to the handler, because it only exists after the handler was initialized and the zip unzipped.
> 
> I think in the end @hatzel's response is the easiest one to implement and does solve my problem.

Yes, that is one way to workaround the problem.

Other workaround can be to package the wheel file and a custom [requirements.txt](https://github.com/pytorch/serve/tree/master/model-archiver#model-specific-custom-python-requirements) file in your model archive. TorchServe will automatically install the package.
