### ISSUE TITLE
Can I use get method for http request, currently seems only post is supported

### ISSUE THREAD

**Issue by SeaOfOcean** [pytorch/serve#569]
## Is your feature request related to a problem? Please describe.
Can I use get method for http request, currently seems only post is supported

**Comment by harshbafna** [comment]
@SeaOfOcean: Could you please elaborate, for which API you are trying out the GET method request?

You can use the API descriptions to view a full list of inference/management APIs and their respective details
 - [Inference API description](https://github.com/pytorch/serve/blob/master/docs/inference_api.md#api-description)
 - [Management API description](https://github.com/pytorch/serve/blob/master/docs/management_api.md#api-description)

**Comment by SeaOfOcean** [comment]
> @SeaOfOcean: Could you please elaborate, for which API you are trying out the GET method request?
> 
> You can use the API descriptions to view a full list of inference/management APIs and their respective details
> 
> * [Inference API description](https://github.com/pytorch/serve/blob/master/docs/inference_api.md#api-description)
> * [Management API description](https://github.com/pytorch/serve/blob/master/docs/management_api.md#api-description)

Inference API, for example call by

```
curl http://localhost:8080/predictions/pipeline?arg1=1&arg2=2
```
pass argument arg1 and arg2 by get method, and handle it in user defined processor

**Comment by harshbafna** [comment]
> > @SeaOfOcean: Could you please elaborate, for which API you are trying out the GET method request?
> > You can use the API descriptions to view a full list of inference/management APIs and their respective details
> > 
> > * [Inference API description](https://github.com/pytorch/serve/blob/master/docs/inference_api.md#api-description)
> > * [Management API description](https://github.com/pytorch/serve/blob/master/docs/management_api.md#api-description)
> 
> Inference API, for example call by
> 
> ```
> curl http://localhost:8080/predictions/pipeline?arg1=1&arg2=2
> ```
> 
> pass argument arg1 and arg2 by get method, and handle it in user defined processor

Unfortunately prediction/inference API currently only supports the POST method.

**Comment by SeaOfOcean** [comment]
> > > @SeaOfOcean: Could you please elaborate, for which API you are trying out the GET method request?
> > > You can use the API descriptions to view a full list of inference/management APIs and their respective details
> > > 
> > > * [Inference API description](https://github.com/pytorch/serve/blob/master/docs/inference_api.md#api-description)
> > > * [Management API description](https://github.com/pytorch/serve/blob/master/docs/management_api.md#api-description)
> > 
> > 
> > Inference API, for example call by
> > ```
> > curl http://localhost:8080/predictions/pipeline?arg1=1&arg2=2
> > ```
> > 
> > 
> > pass argument arg1 and arg2 by get method, and handle it in user defined processor
> 
> Unfortunately prediction/inference API currently only supports the POST method.

Do you have any plan for supporting GET method? Most serving framework like flask/tornado support GET

**Comment by harshbafna** [comment]
> > > > @SeaOfOcean: Could you please elaborate, for which API you are trying out the GET method request?
> > > > You can use the API descriptions to view a full list of inference/management APIs and their respective details
> > > > 
> > > > * [Inference API description](https://github.com/pytorch/serve/blob/master/docs/inference_api.md#api-description)
> > > > * [Management API description](https://github.com/pytorch/serve/blob/master/docs/management_api.md#api-description)
> > > 
> > > 
> > > Inference API, for example call by
> > > ```
> > > curl http://localhost:8080/predictions/pipeline?arg1=1&arg2=2
> > > ```
> > > 
> > > 
> > > pass argument arg1 and arg2 by get method, and handle it in user defined processor
> > 
> > 
> > Unfortunately prediction/inference API currently only supports the POST method.
> 
> Do you have any plan for supporting GET method? Most serving framework like flask/tornado support GET

There is no immediate plan for this. The serving framework (netty) supports all HTTP methods. It's the inference API which only supports the POST method.

**Comment by dhaniram-kshirsagar** [comment]
There is no direct relation between flask and torchserve except the fact that both support handling http request however using different engines [netty or python apis]. Hence naturally, they can support all HTTP methods. 
In torchserve context, we need input for inference hence POST method is needed and hence GET cannot be supported unless you have some model that doesn't need any input!!

**Comment by SeaOfOcean** [comment]
> There is no direct relation between flask and torchserve except the fact that both support handling http request however using different engines [netty or python apis]. Hence naturally, they can support all HTTP methods.
> In torchserve context, we need input for inference hence POST method is needed and hence GET cannot be supported unless you have some model that doesn't need any input!!
we can also get input from arguments of Get method. e.g. curl http://localhost:8080/predictions/pipeline?arg1=1&arg2=2

**Comment by SeaOfOcean** [comment]
> There is no direct relation between flask and torchserve except the fact that both support handling http request however using different engines [netty or python apis]. Hence naturally, they can support all HTTP methods.
> In torchserve context, we need input for inference hence POST method is needed and hence GET cannot be supported unless you have some model that doesn't need any input!!

we can also get input from arguments of Get method. e.g. curl http://localhost:8080/predictions/pipeline?arg1=1&arg2=2

**Comment by MichaelMMeskhi** [comment]
@SeaOfOcean One method I am working on is doing the following:

`curl http://localhost:8080/predictions/model -F "imgid=555" -F "image=@file" -F "task=classify" -F "result=prob"`

This way I can handle specific conditions that I need inside `handler.py`.

**Comment by SeaOfOcean** [comment]
> @SeaOfOcean One method I am working on is doing the following:
> 
> `curl http://localhost:8080/predictions/model -F "imgid=555" -F "image=@file" -F "task=classify" -F "result=prob"`
> 
> This way I can handle specific conditions that I need inside `handler.py`. I don't know if this is the "correct" way, but it works for my needs.

thanks, it is a great workaround
