### ISSUE TITLE
Regression suite fails for scripted densenet161 model due to timeout issue on PyTorch 1.6

### ISSUE THREAD

**Issue by harshbafna** [pytorch/serve#570]
Regression suite fails for scripted densenet161 model due to a timeout issue on PyTorch 1.6 due to the following issue on PyTorch :

https://github.com/pytorch/pytorch/issues/33354

## Context
* torchserve version: latest master
* torch version: 1.6
* torchvision version [if any]: 0.7.0
* torchtext version [if any]: 0.7.0
* torchaudio version [if any]: 0.6.0
* java version: 11
* Operating System and version: Ubuntu 18.0.4

## Your Environment

* Installed using source? [yes/no]:Yes
* Are you planning to deploy it using docker container? [yes/no]:Yes
* Is it a CPU or GPU environment?: Both
* Using a default/custom handler? [If possible upload/share custom handler/model]:image_classifier
* What kind of model is it e.g. vision, text, audio?: vision
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: https://torchserve.s3.amazonaws.com/mar_files/densenet161_scripted.mar
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: NA
* Link to your project [if any]: NA

## Expected Behavior
Regression suite should succeed

## Current Behavior
Regression suite fails with timeout error for densenet161_scripted model

## Possible Solution
Move the densenet161_model suite to an independent newman collection in the regression suite and increase the timeout in torchserve for the this collection.

## Steps to Reproduce
Run the regression suite as per the documentation

**Comment by chauhang** [comment]
@harshbafna Can you please recreate the .mar files files for densenet161 model with PyTorch 1.6 release and test again. Things should speed up with the new zip serialization mechanism. For details check out:

https://github.com/pytorch/pytorch/pull/38379
https://pytorch.org/docs/master/generated/torch.save.html#torch.save. (_use_new_zipfile_serialization now defaults to True, use this mode for saving your model)

**Comment by harshbafna** [comment]
> @harshbafna Can you please recreate the .mar files files for densenet161 model with PyTorch 1.6 release and test again. Things should speed up with the new zip serialization mechanism. For details check out:
> 
> [pytorch/pytorch#38379](https://github.com/pytorch/pytorch/pull/38379)
> https://pytorch.org/docs/master/generated/torch.save.html#torch.save. (_use_new_zipfile_serialization now defaults to True, use this mode for saving your model)

@chauhang  

This current issue is observed with the densenet161 TorchScripted model saved using `torch.jit.save()`. This is a known problem with TorchScripted models and the performance seems to have worsened with PT 1.6. 

Refer to https://github.com/pytorch/pytorch/issues/33354#issuecomment-665656904 for more details. 

The explanation given below doesn't resolve this problem.

IIUC, the above URLs are related to `torch.save()` and not to `torch.jit.save()`. With this new feature, `torch.save()`  saves the model in a format the same as the TorchScript serialization format. I tried saving and loading the densenet161 model outside TorchServe and the speed is good. 

As per the current implementation of default handlers, we have the following mechanism to load models :

 - If the user has supplied the model file representing the model-architecture, it is assumed that it is an eager mode model and the user will a state-dict in serialized format and we use `torch.load()` to load the model and the state-dict

 - If user has only supplied the model's serialized file, it is assumed that it is a scripted/traced model saved using `torch.jit.trace()` or `torch.jit.script()` and the model is loaded using the `torch.jit.load()`.

TorchServe's default handlers currently have no mechanism to figure out if the TorchScripted model was saved using `torch.save()` with new zip file serialization or `torch.jit.save()` and if the model should be loaded with `torch.jit.load()` or `torch.load()`. **This will require some minor code changes in the default handlers.** 

This can obviously be handled through custom handlers where the user knows how exactly the model was saved.
