### ISSUE TITLE
handler(.py)  return type

### ISSUE THREAD

**Issue by sevenold** [pytorch/serve#576]
for example， the text detection(CTPN, CRAFT, EAST...) model output a lot of images. How should I use other default return methods in my custom handler. [{},{}],[[[]]] not only [] Thanks.

**Comment by dhaniram-kshirsagar** [comment]
@sevenold You can create an array of image object. Look at following examples - [text_to_speech_synthesizer](https://github.com/pytorch/serve/blob/master/examples/text_to_speech_synthesizer/waveglow_handler.py) and [image segmenter](https://github.com/pytorch/serve/tree/issue_411/examples/image_segmenter)
Also, look at this which returns an image [can be easily extended] - [sending image data](https://github.com/pytorch/serve/pull/385/files#diff-adc7c0bfb23303230c7a57a0f285f712R66)

**Comment by harshbafna** [comment]
Closing due to no response from OP.
