### ISSUE TITLE
Update Kubernetes version to 1.17 / Use EKS Managed nodes

### ISSUE THREAD

**Issue by dhanainme** [pytorch/serve#580]
The Kubernetes scripts are installing older v1.14 version. The latest EKS supported version is 1.17. 
Update to one of the new version as 1.14 shows red warning when seen from EKS dashboard. 

EKS will soon default to all managed nodes. Change the Kubernetes installation to reflect the same.

**Comment by jagadeeshi2i** [comment]
@dhanainme The version is chosen by ekctl, try upgrading ekctl tool. Check for default kubernetes version used by running `eksctl create cluster --help`
