### ISSUE TITLE
Transfer model between gpu and cpu

### ISSUE THREAD

**Issue by LinDong123a** [pytorch/serve#583]
I am trying to serve multiple models on a server. Considering the resource limit,  I wanted to transfer model between gpu to cpu when the model hasn't been used for some time, so no time-consuming disk reading has to be done when I want to reload the model to model. However, the `delete` inference would just wrap out the model from gpu or memory. I want to know if there is such a API for controling targe device(gpu/cpu) a registered model will be load.

**Comment by harshbafna** [comment]
@LinDong123a: `TorchServe` currently does not have an API to move models between CPU and GPU. This will be an interesting feature to add. Could you add a feature request for this with a detailed use-case?

For now, you could add a hack in custom handler based on the input parameter(s) in the inference request: 
 - either run the inference
 - or move the model to the specific device (CPU/GPU).

Note that this will be a bit tricky as each model worker loads the model in memory and each inference request is picked by a model-worker in round-robin fashion.

**Comment by harshbafna** [comment]
Closing due to no response from OP.
