### ISSUE TITLE
Backends & performance comparison

### ISSUE THREAD

**Issue by yaysummeriscoming** [pytorch/serve#590]
## 📚 Documentation

This seems like a really useful deployment solution. However I can't find in the documentation anywhere what this is running under the hood: FBGEMM, tensor-rt, MKL?

I'm also trying to get an idea of performance vs OpenVINO and tensor-rt, are there any benchmarks?

**Comment by dhaniram-kshirsagar** [comment]
@yaysummeriscoming torchserve is not using or supporting any of these at present. torchserve requires you to create MAR file using pytorch model file i.e. .pt/pth file however the accelerators you have listed need models in ONNX format. At present, torchserve doesn't support ONNX models and models are loaded to cpu/gpu using pytorch.

**Comment by yaysummeriscoming** [comment]
I'm not following sorry, FBGEMM & MKL are CPU backends for pytorch. So presumably, torchserve is using these?

Benchmarks would be great, as that would easily allow devs to compare performance to OpenVINO & other packages and make the process of choosing a deployment solution much easier.

I'd love to use torchserve, but unfortunately until I get an idea of its performance that's hard to do.

**Comment by dhaniram-kshirsagar** [comment]
@yaysummeriscoming  Looks like misinterpreted it. Similar query was answered earlier here - https://github.com/pytorch/serve/issues/361
