### ISSUE TITLE
Add environment information header in regression and sanity suite scripts

### ISSUE THREAD

**Issue by harshbafna** [pytorch/serve#598]
## Is your feature request related to a problem? Please describe.

Enhance regression suite and sanity suite logging to add headers which include following environment information :

 - torchserve branch
 - torch module versions: torch, torchvision, torchaudio, torchtext
 - OS name and version
 - python version
 - java version
 - CPU/GPU environment
 - NVCC version / NVIDIA driver version (when running on GPU instance)

**Comment by dhaniram-kshirsagar** [comment]
This should be implemented in #505 as well.
