### ISSUE TITLE
Add handler for audio models with an example

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#60]
Add new handler for audio models along with an example for pre / post processing of audio data.

**Comment by adityabindal** [comment]
Reopening and adding v0.11 milestone

**Comment by fbbradheintz** [comment]
As noted in a comment on #258, there is one other item: At the team status meeting today, it was raised that this is not really a complete example, as it stashes the output in a file in /tmp - which does the requester no good if they're on another machine. To make the example truly valuable, it should package the file for download with the HTTP response.
