### ISSUE TITLE
Does torchserve manages memory when different models are called at the same time? 

### ISSUE THREAD

**Issue by TheRochVoices** [pytorch/serve#601]
Suppose there are 2 models. Calling both parallely will cause a machine to go Out of Memory. Is there a way to queue (or something else) when different models are getting hit parallely?

**Comment by harshbafna** [comment]
@TheRochVoices: The model is loaded in memory at the model registration itself and not at the time of inference. TorchServe creates a copy of the model per-worker. You can tune the number of workers per model based on the inference load and memory availability.

TorchServe doesn't provide any memory management feature as of now.

We have recently added support for [TorchServe on Kubernetes](https://github.com/pytorch/serve/tree/master/kubernetes). However, adding support for multi-node deployment and autoscaling is a work in progress.

**Comment by TheRochVoices** [comment]
Ok thanks. I feel like this will be a bottleneck when a server is hosting multiple models (which is a valid case in real-life projects). Multiple models will get hits parallely and some kind of memory management will be needed.

Do you have any recommendations for hosting multiple models on a same machine in a way that it doesn't go out of memory?

**Comment by harshbafna** [comment]
@TheRochVoices:  You should consider each model's memory consumption, inference load on each model, resources available on the machine (memory and GPU/CPU cores). Based on these parameters, you can decide on the number of workers that should be allocated to each model.

You can use the [scale workers API](https://github.com/pytorch/serve/blob/master/docs/management_api.md#scale-workers) to control the number of workers per model.
