### ISSUE TITLE
Automate benchmarking activity for release.

### ISSUE THREAD

**Issue by harshbafna** [pytorch/serve#608]
## Is your feature request related to a problem? Please describe.
Benchmarking `TorchServe` with different models and environment combination for release is a time consuming manual task and needs to be automated.

## Describe the solution
 - Add pre-configured `json` files which can be supplied to [benchmark-ab.py](https://github.com/pytorch/serve/blob/master/benchmarks/benchmark-ab.py) script

 - Automate the task through Circle CI

**Comment by msaroufim** [comment]
Dupe of work by @nskool
