### ISSUE TITLE
Update doc/scripts with s3 url based model archive/mar files

### ISSUE THREAD

**Issue by dhaniram-kshirsagar** [pytorch/serve#61]
Docs and few scripts are still pointing to local mar files i.e. at present, the user has to build mar files themselves. Need to update the docs/scripts with required S3 mar file urls for readymade mar files.

**Comment by fbbradheintz** [comment]
Circling back to this: It's not clear to me what the problem is with users creating their own .mar files. The model archiver is part of the package, and the instructions are clear.
