### ISSUE TITLE
GPU loading config for multiple-gpu machine

### ISSUE THREAD

**Issue by LinDong123a** [pytorch/serve#613]
I find that worker thread will be allocated based on the number of gpu in the deployed machine, without external config for controlling, after reading the source. This is quite awkward when I want to perform custom loading balance on gpu. So I wonder if there is a way to specify target gpu device for each model's worker.

**Comment by harshbafna** [comment]
@LinDong123a: `TorchServe` selects the GPU devices in a round-robin fashion and passes the selected GPU-ID to the backend worker. The base/default handlers use this GPU id to load the model in memory.

Refer: https://github.com/pytorch/serve/blob/master/ts/torch_handler/base_handler.py#L34

> So I wonder if there is a way to specify target gpu device for each model's worker.

You can always write a custom handler to control on which device you want to load the model.

**Comment by LinDong123a** [comment]
> You can always write a custom handler to control on which device you want to load the model.
I'm afraied this solution may cause risk when `torchserve` want to gather gpu-relation infomation. If I just wirte a custom handler to control device, the actual gpu the model loaded will differ from what a worker thread expects,  which makes disorder between thread and behavior. If such behaivor is allowed, unreliable gpu-related infomation will be gathered if wanted.

**Comment by LinDong123a** [comment]
> You can always write a custom handler to control on which device you want to load the model.

I'm afraied this solution may cause risk when torchserve want to gather gpu-relation infomation. If I just wirte a custom handler to control device, the actual gpu the model loaded will differ from what a worker thread expects, which makes disorder between thread and behavior. If such behaivor is allowed, unreliable gpu-related infomation will be gathered if wanted.

**Comment by harshbafna** [comment]
> > You can always write a custom handler to control on which device you want to load the model.
> 
> I'm afraied this solution may cause risk when torchserve want to gather gpu-relation infomation. If I just wirte a custom handler to control device, the actual gpu the model loaded will differ from what a worker thread expects, which makes disorder between thread and behavior. If such behaivor is allowed, unreliable gpu-related infomation will be gathered if wanted.

Currently, no GPU information is collected by TorchServe and a worker is just a python process that uses the handler's initialize function to load the model in CPU/GPU memory. 

To keep the memory usage balanced across multiple GPU devices, TorchServe passes on a GPU id selected in round-robin fashion that can be used/ignored at the worker level.

**Comment by harshbafna** [comment]
Closing due to no response from OP.
