### ISSUE TITLE
Add example use case guide

### ISSUE THREAD

**Issue by dhaniram-kshirsagar** [pytorch/serve#616]
## 📚 Documentation

This guide will provide the reference use cases i.e. different ways in which torchserve can be deployed for serving different types of pytorch models.

This will be separate guide apart from faq and troubleshooting guide being addressed via #384 #215

**Comment by dhanainme** [comment]
@dhaniram-kshirsagar can you please point me to the specific ask for which we created this documentation. 

Took a look #616. Just trying to get the context.
