### ISSUE TITLE
Benchmark CPU optimized Docker.ipex

### ISSUE THREAD

**Issue by maaquib** [pytorch/serve#619]
Run benchmark against [Docker.ipex](https://github.com/ashokei/serve/blob/ipex_docker/docker/Dockerfile.ipex) for CPU optimized deployment

Note from Intel: By default the container is configured with OMP=1 thread, for BERT i notice it gives better performance with atleast 4 cores per container instance, which you can invoke follows.
`docker run -e OMP_NUM_THREADS=4 --rm --name ts -p 8080:8080 -p 8081:8081 torchserve:ipex`

**Comment by maheshambule** [comment]
@maaquib, Below are the benchmark results BERT model:

Torch Serve version = 66216ce945d99a32fb281707eb88791215a44dd5 + [intel_torch_extension changes](https://github.com/maheshambule/serve/blob/6e8a88a9c007da5821360dab4d97039184532e09/ts/torch_handler/base_handler.py#L37-L48) 
EC2 Instance : c5.4xlarge

Benchmark|Model|Concurrency|Requests|TS failed requests|TS throughput|TS latency P50|TS latency P90|TS latency P99|TS latency mean|TS error rate|Model_p50|Model_p90|Model_p99
---|---|---|---|---|---|---|---|---|---|---|---|---|---
AB|[url](https://torchserve.s3.amazonaws.com/mar_files/BERTSeqClassification_Torchscript_batch.mar)|100|10000|0|16.56|5942|6307|7674|6040.142|0.0|133.92|123.58|129.85|

**Comment by maheshambule** [comment]
@maaquib, Please take a look at the Benchmark results. They are are updated now.

**Comment by maaquib** [comment]
@maheshambule Thanks for this benchmakr. I'll take a closer look at these numbers. Can you also create a PR with your changes?
