### ISSUE TITLE
About Arguments

### ISSUE THREAD

**Issue by Sandeep418** [pytorch/serve#621]
I'm trying to serve the human action recognition model in my case the model need a list of images. Can you give any suggestion about how to pass a list of images or an image folder to the model.

**Comment by harshbafna** [comment]
@Sandeep418: Please refer the following comment: https://github.com/pytorch/serve/issues/529#issuecomment-658012913

**Comment by Sandeep418** [comment]
> @Sandeep418: Please refer the following comment: [#529 (comment)](https://github.com/pytorch/serve/issues/529#issuecomment-658012913)

Presently I am doing the same thing, but we need to pass a large number of images 30 or more for which it would be better to pass the set of images in a folder for inference.

**Comment by harshbafna** [comment]
> Presently I am doing the same thing, but we need to pass a large number of images 30 or more for which it would be better to pass the set of images in a folder for inference.

@Sandeep418: It will be better to write a custom python/shell script to do this task at the client end.

**Comment by Sandeep418** [comment]
> > Presently I am doing the same thing, but we need to pass a large number of images 30 or more for which it would be better to pass the set of images in a folder for inference.
> 
> @Sandeep418: It will be better to write a custom python/shell script to do this task at the client end.

okay, Thanks.

**Comment by Sandeep418** [comment]
> > Presently I am doing the same thing, but we need to pass a large number of images 30 or more for which it would be better to pass the set of images in a folder for inference.
> 
> @Sandeep418: It will be better to write a custom python/shell script to do this task at the client end.

okay,Thanks

**Comment by harshbafna** [comment]
Closing as the query has been answered.
