### ISSUE TITLE
Limited to batches of 100 during inference, even if model deployed with batch_size = 128

### ISSUE THREAD

**Issue by Leoduv** [pytorch/serve#623]
## Context

- Using torchserve gpu docker container, built locally from source.
- Running on a VM with a gpu
- torch==1.5 
- torchvision==0.6 
- torchtext==0.6 
- torchserve==0.1.1
- in config.properties : job_queue_size=1000
- custom image classification model, custom handler

## Issue
I am sending batches of 128 images to my torchserve container, but when I check the logs that my handler is giving me, I can see that the preprocessing is getting one batch of 100 and one of 28, even if the batch_size of my deployed model is 128. 
Same problem if I try with a bigger batch (256 becomes 100, 100, 56). I first thought it was coming from the default job_queue_size that is set to 100 I think, but I tried setting it to 1000 in my config file but it didn't resolve anything.

## Question
Is there something else limiting the maximum batch size sent to the handler ?

**Comment by dhaniram-kshirsagar** [comment]
@Leoduv Can you please check if torchserve initialization log [in ts.log/on console] is correctly printing the new job queue size as 1000. Also, please attach the log file.

**Comment by Leoduv** [comment]
Hi, here are the contents the ts_log.log file :

> 2020-08-18 08:20:29,103 [INFO ] main org.pytorch.serve.ModelServer -
Torchserve version: 0.1.1
TS Home: /home/venv/lib/python3.6/site-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 1
Number of CPUs: 2
Max heap size: 1866 M
Python executable: /home/venv/bin/python3
Config file: /home/model-server/config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Model Store: /home/model-server/model-store
Initial Models: N/A
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 32
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Prefer direct buffer: false
2020-08-18 08:20:29,173 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2020-08-18 08:20:29,303 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:8080
2020-08-18 08:20:29,303 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2020-08-18 08:20:29,309 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://0.0.0.0:8081


I maybe missed I step when modifying the job queue size in order for it to take effect.

**Comment by Leoduv** [comment]
I upgraded to torchserve 0.2.0, and checked that the config is used in the docker entrypoint (torchserve --start --ts-config /home/model-server/config.properties), the contents of the config.properties are : 

> inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store

But the problem persists, I'm still limited to batches of 100.

**Comment by harshbafna** [comment]
> I upgraded to torchserve 0.2.0, and checked that the config is used in the docker entrypoint (torchserve --start --ts-config /home/model-server/config.properties), the contents of the config.properties are :
> 
> > inference_address=http://0.0.0.0:8080
> > management_address=http://0.0.0.0:8081
> > number_of_netty_threads=32
> > job_queue_size=1000
> > model_store=/home/model-server/model-store
> 
> But the problem persists, I'm still limited to batches of 100.

@Leoduv: Could you please share the following details so that we can reproduce the error at our end :

 - Curl command used for registering the model
 - How you are sending the requests? Using some tool like apache-bench or jmeter?
 - What is the concurrency used at the client end for inference requests.

**Comment by Leoduv** [comment]
> ### Curl command used for registering the model

I'm doing it in a python using the requests library `r = requests.post(url=f"http://localhost:8081/models?url={model_name}.mar&batch_size={batch_size}"
                          f"&initial_workers=1&max_batch_delay=100")`

> ### How you are sending the requests? Using some tool like apache-bench or jmeter?
> ### What is the concurrency used at the client end for inference requests.

For the predictions requests I am sending then using the `asyncio` and `aiohttp` python libraries

```
async def make_predictions(datastack, model_url):
    async with aiohttp.ClientSession() as session:
        post_tasks = []
        # prepare the coroutines that post
        for img in datastack:
            post_tasks.append(do_post(session, model_url, img))
        # now execute them all at once
        responses = await asyncio.gather(*post_tasks)
        return responses


async def do_post(session, url, image):
    async with session.post(url, data=image) as response:
        return await response.text()


def get_predictions(databatch, model_url):
    loop = asyncio.get_event_loop()
    predictions = None
    try:
        predictions = loop.run_until_complete(make_predictions(databatch, model_url))
    finally:
        return predictions
```

I have also joined the Dockerfile I'm using for building the torchserve image

**Comment by harshbafna** [comment]
@Leoduv: From the initial analysis, the value `100ms` for `max_batch_delay` is too low. Could you try increasing the value to some higher value say 5000 (5 seconds)?

I will try and reproduce this scenario at my end with your shared script.

**Comment by Leoduv** [comment]
@harshbafna  Just finished testing it and it didn't change anything. I have a handler that logs the size of the tensor after the preprocessing and when I was making batches of 64 : 

> 2020-08-19 13:11:08,718 [INFO ] W-9000-roof_material_type_bigger_bs_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - PREPROCESS IMAGE TENSOR SIZE : torch.Size([64, 4, 256, 256])

But when I redeployed the model with a batch size of 128 : 

> PREPROCESS IMAGE TENSOR SIZE : torch.Size([100, 4, 256, 256])

and after the predictions of this batch were returned : 

> PREPROCESS IMAGE TENSOR SIZE : torch.Size([28, 4, 256, 256])

ect ect

**Comment by maaquib** [comment]
@Leoduv were you able to resolve this issue?

**Comment by Leoduv** [comment]
No we are still having this issue for now

**Comment by Leoduv** [comment]
It seems that aiohttp has a default limit I didn't notice of 100 simultaneous requests :/ This was the cause of all my problems. Closing the issue.

**Comment by harshbafna** [comment]
Thanks, @Leoduv for the update.
