### ISSUE TITLE
Reason for implementing HTTP request server via Java

### ISSUE THREAD

**Issue by crameth** [pytorch/serve#641]
## Is your feature request related to a problem? Please describe.
Not applicable.

## Describe the solution
Not applicable.

## Describe alternatives solution
FastAPI - https://fastapi.tiangolo.com/
uvicorn - https://www.uvicorn.org/

This is more of a question directed at the decision behind using Java. What are the reasons why Java is chosen to implement the HTTP request server?

There are a myriad of HTTP request servers available for us to use in Python, or other effective solutions written in Go or Node.js which would better serve the requirement for a HTTP request server in this day and age.

Is there a particular reason why Java was specifically chosen to implement TorchServe in this case?

Edit: My bad, accidentally closed issue.

**Comment by akarazniewicz** [comment]
Just a my view. Unfortunatelly python solutions are quite challenging in terms of tuning for every-day user. Java on the other hand is rock solid in this area. After all it's supposed to be kind of black box, usually inside of the container and, well not that important from user perspective. 

If You are looking for alternatives - ray-serve is excellent, pure python solution, which can be integrated with FastAPI.

**Comment by msaroufim** [comment]
Java/JVM is still a powerful combo, Spark was built on top of it and so was Hadoop. There are always tradeoffs when it comes to picking a language for a project so unless those alternatives in other languages are actually built it's hard to make a prediction as to what would actually be the best solution.

That said we are also working on a C++ backend which will bring improved multithreaded performance so stay tuned!
