### ISSUE TITLE
`torch.jit.load(...)` fails silently

### ISSUE THREAD

**Issue by alexdmiller** [pytorch/serve#645]
## Context

* torchserve version: `0.0.1`
* Operating System and version: ubuntu:18.04

## Your Environment

* Installed using source? [yes/no]: No
* Are you planning to deploy it using docker container? [yes/no]: Yes
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: Yes: [custom-handler.py.txt](https://github.com/pytorch/serve/files/5121141/custom-handler.py.txt)

* What kind of model is it e.g. vision, text, audio?: Vision
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: Local model
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:

```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
load_models=nhs-rdt.mar
```

* Link to your project [if any]:

## Expected Behavior

I'm using the [TorchServe docker container](https://hub.docker.com/r/pytorch/torchserve). When I run inference in the container on my Macbook (MacOS 10.15), everything works. However, when I deploy the container to an AWS EC2 instance, inference fails.

## Current Behavior

In my custom handler, the worker stops after the line

```
    model = torch.jit.load(model_pt_path, map_location=map_location)
```

No feedback or error — the worker just stops. (I had to insert `print(...)` calls to figure out where the code was stopping.) Then, when inference is run, the model doesn't exist and I get an error.

## Possible Solution

1. Any way of getting more feedback from `torch.jit.load(...)` would be great. Error messages, logs, return values, whatever. With zero feedback, I'm not sure how to debug.
2. I notice that there is a newer version of torchserve than 0.0.1. It would be helpful if the docker container were updated.

Please let me know if any other specific information would be helpful. Thanks.

**Comment by harshbafna** [comment]
@alexdmiller: 

 - There have been lots of structural changes with TorchServe 0.2.0 release. Please use the latest docker container.

 - To use the latest docker image for TorchServe on your EC2 instance use the following command

```
docker pull pytorch/torchserve
```

If the problem still persists please share `logs/ts_log.log` file.

**Comment by alexdmiller** [comment]
My apologies. I thought I had run `docker pull pytorch/torchserve`, but clearly had not. Updating to the latest docker image fixed it. Thanks!
