### ISSUE TITLE
Please Clarify How Data are Organized in Outermost JSON Array on Handler Side in the Document

### ISSUE THREAD

**Issue by BorisPolonsky** [pytorch/serve#647]
## 📚 Documentation

I tried to implement custom handlers by subclassing `ts.BaseHanlder` as suggested in the document. By adding `sys.stdout.write(str(data))` for data inspection on server side, it turns out that no matter what kind of data I've included in my request body (e.g. array of string or single string), I always receive a single element list on the server size. e.g:
By sending `curl  http://localhost:8080/predictions/whatevermodel -H 'Content-Type: application/json' -d '["text1", "text2"]'`, I got `[{'body': ['text1', 'text2']}]`
The purpose of the single element outermost array for wrapping up the request body is a bit confusing for me. It would be helpful if the document clarifies some of the points: 
- is length of the array guaranteed to be 1 normally (i.e. should I always try to get the first element of the array only for parsing input data), if not, in which index lies the data posted from a specific client
- If multiple elements exist in the outermost array
  - what determines the length of the array (e.g. How to form request that results in array of multiple elements on handler's side)
  - if it's related to batch inference, what should we expect in each entry of the outermost array, a single sample or a batch of sample to be aggregated to a greater batch? Do elements all entries come from the same client?

The code of my customer handler:
```
from abc import ABC
import torch
import os
import sys
from ts.torch_handler.base_handler import BaseHandler

class NamedEntityRecognitionHandler(BaseHandler, ABC):
    """
    A custom model handler implementation.
    """

    def __init__(self):
        self._context = None
        self.initialized = False
        self.model = None
        self.device = None

    def initialize(self, context):
        """
        Invoke by torchserve for loading a model
        :param context: context contains model server system properties
        :return:
        """

        #  load the model
        self.manifest = context.manifest

        properties = context.system_properties
        model_dir = properties.get("model_dir")
        self.device = torch.device("cuda:" + str(properties.get("gpu_id")) if torch.cuda.is_available() else "cpu")
        # self.device = torch.device("cuda:0")
        # Read model serialize/pt file
        serialized_file = self.manifest['model']['serializedFile']
        model_pt_path = os.path.join(model_dir, serialized_file)
        if not os.path.isfile(model_pt_path):
            raise RuntimeError("Missing the model.pt file")

        self.model = torch.jit.load(model_pt_path)

        self.initialized = True

    def preprocess(self, data):
        """
        Transform raw input into model input data.
        :param batch: list of raw requests, should match batch size
        :return: list of preprocessed model input data
        """
        # Take the input data and make it inference ready
        sys.stdout.write(str(data))  # This is how I inspect data
        data = data[0]["body"] # when will data be a list of size 0/greater than 1? 
        inputs = data.get("inputs", None)
        instances = data.get("instances", None)
        if inputs is not None and instances is not None:
            raise ValueError
        elif inputs:
            if isinstance(inputs, list):
                text_list = inputs
            elif isinstance(inputs, dict):
                text_list = inputs["text"]
            else:
                raise ValueError
        elif instances:
            raise NotImplementedError
        else:
            raise ValueError
        sys.stdout.write("=========Preprocessed:"+str(text_list))
        return data
```

**Comment by dhaniram-kshirsagar** [comment]
> * if it's related to batch inference, what should we expect in each entry of the outermost array, a single sample or a batch of sample to be aggregated to a greater batch? Do elements all entries come from the same client?

@BorisPolonsky Yes, it is related to batch however at present there is no separation for different clients. Our batch aggregator accumlates requests [irrespective of clients] for same model/version for a time equal to batch delay and forwards it to its handler in a format indicated by you.

**Comment by BorisPolonsky** [comment]
So what response will each client receive respectively after the server accumulates data from each client and finshes prediction on the whole accumulated batch.? Does this means that a client will receive prediction that should be delivered to another client?

**Comment by BorisPolonsky** [comment]
> > * if it's related to batch inference, what should we expect in each entry of the outermost array, a single sample or a batch of sample to be aggregated to a greater batch? Do elements all entries come from the same client?
> 
> @BorisPolonsky Yes, it is related to batch however at present there is no separation for different clients. Our batch aggregator accumlates requests [irrespective of clients] for same model/version for a time equal to batch delay and forwards it to its handler in a format indicated by you.


So what response will each client receive respectively after the server accumulates data from each client and finshes prediction on the whole accumulated batch.? Does this means that a client will receive prediction that should be delivered to another client?

**Comment by dhaniram-kshirsagar** [comment]
> > > * if it's related to batch inference, what should we expect in each entry of the outermost array, a single sample or a batch of sample to be aggregated to a greater batch? Do elements all entries come from the same client?
> > 
> > 
> > @BorisPolonsky Yes, it is related to batch however at present there is no separation for different clients. Our batch aggregator accumlates requests [irrespective of clients] for same model/version for a time equal to batch delay and forwards it to its handler in a format indicated by you.
> 
> So what response will each client receive respectively after the server accumulates data from each client and finshes prediction on the whole accumulated batch.? Does this means that a client will receive prediction that should be delivered to another client?

Even though its an old comment, replying it for reference. The requests are tracked using request-id associated with clients request hence corresponding correct response will be sent back to clients.
