### ISSUE TITLE
Add more torchserve examples using popular PyTorch models

### ISSUE THREAD

**Issue by prashantsail** [pytorch/serve#649]
## Description
To enrich and diversify the torchserve examples, we would like to add a few more by using some of the popular PyTorch models.

I have segregated a small list - 

| Model | Github Stars | PR | Overview |
| ----- | ------------ | -- | -------- |
| [RoBERTa (fairseq)](https://github.com/pytorch/fairseq)| 8.9k | #592 | Models for translation, summarization, language modeling and other text generation tasks |
| [SSD](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Detection/SSD) | 4.5k |  | Object Detection (Image size 300 x 300) [[performance](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Detection/SSD#performance)] |
| [Tacotron 2](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/Tacotron2) | 4.5k | - | Text to speech [[performance](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/Tacotron2#performance)] <br> `Example already exists` |
| [3D-ResNets](https://github.com/kenshohara/3D-ResNets-PyTorch) | 2.4k |  | Human action recognition in videos  |
| [ResNeSt](https://github.com/zhanghang1989/ResNeSt) | 2.2k |  | Split-Attention Network, A New ResNet Variant [[performance](https://github.com/zhanghang1989/ResNeSt#pretrained-models)] |
| [CRAFT](https://github.com/clovaai/CRAFT-pytorch) | 1.5k |  | Effectively detect text area in an image |
| [DCGAN on FashionGen](https://github.com/facebookresearch/pytorch_GAN_zoo/blob/master/models/DCGAN.py) | 1.1k | #659 | Create Images from input |
| [Progressive Growing of GANs](https://pytorch.org/hub/facebookresearch_pytorch-gan-zoo_pgan/) | 1.1k | - | Create Images from input <br> `Similar to DCGAN example` |
| [ProxylessNAS](https://github.com/mit-han-lab/ProxylessNAS) | 1.1k |  | Specialize CNN architectures for different hardware platforms (CPU \ GPU \ Mobile) [[performance](https://github.com/mit-han-lab/ProxylessNAS#performance)] |  |
| [GhostNet](https://github.com/huawei-noah/ghostnet) | 1.0k |  | More Features from Cheap Operations [[performance](https://github.com/huawei-noah/ghostnet#ghostnet)] |

Most of it is sourced from [PyTorch Hub](https://pytorch.org/hub/)

@dhaniram-kshirsagar @chauhang @maaquib @MengMeng96 @HamidShojanazeri @htappen 
Please provide your inputs on this ticket.

**We are also open to any other suggestions**

**Comment by msaroufim** [comment]
Closing because we already have many examples - I think it makes more sense to refactor our existing docs to make it trivial for people to add their own handlers
