### ISSUE TITLE
How to change Temp Directory?

### ISSUE THREAD

**Issue by CSLujunyu** [pytorch/serve#654]
## 📚 Documentation

My computer has little space to mount '/tmp'. And I can't find any helps. 
Are there any way to change Temp Directory?

**Comment by harshbafna** [comment]
@CSLujunyu: You can export `TEMP` environment variable to the desired path. This path will be used by `TorchServe` to extract the model-archives content.

**Comment by CSLujunyu** [comment]
> @CSLujunyu: You can export `TEMP` environment variable to the desired path. This path will be used by `TorchServe` to extract the model-archives content.

I see. Thanks.
