### ISSUE TITLE
Torchserve can not stop, and restarts again.

### ISSUE THREAD

**Issue by CSLujunyu** [pytorch/serve#655]
## Expected Behavior

Run `torchserve --stop`  to stop the server

## Current Behavior

When changing the environment variable of `TEMP`, I run `torchserve --stop` and get message "TorchServe is not currently running." But the server is still alive.

**Comment by harshbafna** [comment]
@CSLujunyu: Please also add the environment details and steps followed for reproducing the issue.

**Comment by CSLujunyu** [comment]
> @CSLujunyu: Please also add the environment details and steps followed for reproducing the issue.
1. Add `TEMP` in order to change default temp directory
export TEMP=~/torch_server/examples/Huggingface_Transformers/tmp

2. Follow Huggingface example, and create a torch model archive
torch-model-archiver --model-name BERTEmbedding --version 1.0 --serialized-file ~/pretrained_checkpoints/model_V1.pt --handler ./Transformer_handler_generalized.py --extra-files "setup_config.json,models.py"

3. Registering the Model on TorchServe and Running Inference
mv BERTEmbedding.mar model_store/
torchserve --start --model-store model_store --models my_tc=BERT.mar --ts-config config.properties

4. Then can not stop server via `torchserve --stop`

**Comment by harshbafna** [comment]
@CSLujunyu:

I could not reproduce this using the latest binaries from PyPI :

 - Install torchserve
```
(base) USL07109:~ harsh_bafna$ pip install torchserve
Collecting torchserve
  Downloading torchserve-0.2.0-py2.py3-none-any.whl (5.0 MB)
     |████████████████████████████████| 5.0 MB 144 kB/s 
Requirement already satisfied: Pillow in /opt/anaconda3/lib/python3.7/site-packages (from torchserve) (7.1.2)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.7/site-packages (from torchserve) (20.3)
Requirement already satisfied: psutil in /opt/anaconda3/lib/python3.7/site-packages (from torchserve) (5.7.2)
Requirement already satisfied: future in /opt/anaconda3/lib/python3.7/site-packages (from torchserve) (0.18.2)
Requirement already satisfied: pyparsing>=2.0.2 in /opt/anaconda3/lib/python3.7/site-packages (from packaging->torchserve) (2.4.7)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.7/site-packages (from packaging->torchserve) (1.14.0)
Installing collected packages: torchserve
Successfully installed torchserve-0.2.0
```

 - Export `TEMP` variable

```
export TEMP=/Users/harsh_bafna/model_tmp
```

 - Start `TorchServe`
```
(base) USL07109:~ harsh_bafna$ torchserve --start --model-store model_store
(base) USL07109:~ harsh_bafna$ 2020-08-27 17:54:43,841 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.2.0
TS Home: /opt/anaconda3/lib/python3.7/site-packages
Current directory: /Users/harsh_bafna
Temp directory: /Users/harsh_bafna/model_tmp
Number of GPUs: 0
Number of CPUs: 8
Max heap size: 4096 M
Python executable: /opt/anaconda3/bin/python
Config file: N/A
Inference address: http://127.0.0.1:8080
Management address: http://127.0.0.1:8081
Metrics address: http://127.0.0.1:8082
Model Store: /Users/harsh_bafna/model_store
Initial Models: N/A
Log dir: /Users/harsh_bafna/logs
Metrics dir: /Users/harsh_bafna/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 8
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Prefer direct buffer: false
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
2020-08-27 17:54:43,890 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: KQueueServerSocketChannel.
2020-08-27 17:54:43,981 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://127.0.0.1:8080
2020-08-27 17:54:43,981 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: KQueueServerSocketChannel.
2020-08-27 17:54:43,982 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://127.0.0.1:8081
2020-08-27 17:54:43,982 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: KQueueServerSocketChannel.
2020-08-27 17:54:43,983 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://127.0.0.1:8082
Model server started.
2020-08-27 17:54:44,080 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:USL07109,timestamp:1598531084
2020-08-27 17:54:44,081 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:314.0293655395508|#Level:Host|#hostname:USL07109,timestamp:1598531084
2020-08-27 17:54:44,081 [INFO ] pool-2-thread-1 TS_METRICS - DiskUsage.Gigabytes:10.312271118164062|#Level:Host|#hostname:USL07109,timestamp:1598531084
2020-08-27 17:54:44,081 [INFO ] pool-2-thread-1 TS_METRICS - DiskUtilization.Percent:3.2|#Level:Host|#hostname:USL07109,timestamp:1598531084
2020-08-27 17:54:44,082 [INFO ] pool-2-thread-1 TS_METRICS - MemoryAvailable.Megabytes:6615.44140625|#Level:Host|#hostname:USL07109,timestamp:1598531084
2020-08-27 17:54:44,082 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUsed.Megabytes:8840.2578125|#Level:Host|#hostname:USL07109,timestamp:1598531084
2020-08-27 17:54:44,082 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUtilization.Percent:59.6|#Level:Host|#hostname:USL07109,timestamp:1598531084
```

 - Stop `TorchServe`

```
torchserve --stop
TorchServe has stopped.
2020-08-27 18:04:46,415 [INFO ] KQueueEventLoopGroup-2-1 org.pytorch.serve.ModelServer - Inference model server stopped.
2020-08-27 18:04:46,415 [INFO ] KQueueEventLoopGroup-2-2 org.pytorch.serve.ModelServer - Management model server stopped.
2020-08-27 18:04:46,417 [INFO ] KQueueEventLoopGroup-2-1 org.pytorch.serve.ModelServer - Metrics model server stopped.
2020-08-27 18:04:48,499 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
111
```

**Comment by harshbafna** [comment]
> > @CSLujunyu: Please also add the environment details and steps followed for reproducing the issue.
> 
> 1. Add `TEMP` in order to change default temp directory
>    export TEMP=~/torch_server/examples/Huggingface_Transformers/tmp
> 2. Follow Huggingface example, and create a torch model archive
>    torch-model-archiver --model-name BERT --version 1.0 --serialized-file ~/pretrained_checkpoints/model_V1.pt --handler ./Transformer_handler_generalized.py --extra-files "setup_config.json,models.py"
> 3. Registering the Model on TorchServe and Running Inference
>    mv BERT.mar model_store/
>    torchserve --start --model-store model_store --models my_tc=BERT.mar --ts-config config.properties
> 4. Then can not stop server via `torchserve --stop`
> 
> the config.properties shows as follows:
> 
> number_of_gpu=1
> inference_address=https://127.0.0.1:8443
> management_address=https://127.0.0.1:8444
> keystore=keystore.p12
> keystore_pass=changeit
> keystore_type=PKCS12

It would be great if you could share the details using the bug report template.

**Comment by CSLujunyu** [comment]
## Context


* torchserve version: 0.2.0
* torch version: 1.4.0
* torchvision version : 0.5.0
* java version: 11.0.8
* Operating System and version: CentOS Linux release 7.5.1804 (Core)

## Your Environment

* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom handler
* What kind of model is it e.g. vision, text, audio?: text
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: use local models from model-store
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
```
number_of_gpu=1
inference_address=https://127.0.0.1:8443
management_address=https://127.0.0.1:8444
keystore=keystore.p12
keystore_pass=changeit
keystore_type=PKCS12
```

## Expected Behavior


## Current Behavior


## Possible Solution

Notice I also export Java Environment path, because orignal Java version is 8. Maybe there are something wrong causes by Java Version?

## Steps to Reproduce


1. Add TEMP in order to change default temp directory
```
export JAVA_HOME=~/java/jdk-11.0.8
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib:$CLASSPATH
export JAVA_PATH=${JAVA_HOME}/bin:${JRE_HOME}/bin
export TEMP=~/torch_server/examples/Huggingface_Transformers/tmp

```
2. Follow Huggingface example, and create a torch model archive
`torch-model-archiver --model-name BERT --version 1.0 --serialized-file ~/pretrained_checkpoints/model_V1.pt --handler ./Transformer_handler_generalized.py --extra-files "setup_config.json,models.py"`

3. Registering the Model on TorchServe and Running Inference
```
mv BERT.mar model_store/
torchserve --start --model-store model_store --models my_tc=BERT.mar --ts-config config.properties

```
4. Then can not stop server via torchserve --stop

5. When I don't export TEMP as follows, everything is running well.
```
export JAVA_HOME=~/java/jdk-11.0.8
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib:$CLASSPATH
export JAVA_PATH=${JAVA_HOME}/bin:${JRE_HOME}/bin
```

**Comment by harshbafna** [comment]
> * Are you planning to deploy it using docker container? [yes/no]: yes

Are you executing all the above commands inside the docker container?

**Comment by CSLujunyu** [comment]
> > * Are you planning to deploy it using docker container? [yes/no]: yes
> 
> Are you executing all the above commands inside the docker container?
> 
> > Notice I also export Java Environment path, because orignal Java version is 8. Maybe there are something wrong causes by Java Version?
> 
> Why would you have multiple java versions inside the docker container? Are you using a custom docker file to create the image?

Sorry, I make a mistake. I am not using docker container currently. I will deploy it in the future.

- Are you planning to deploy it using docker container? [yes/no]: no

**Comment by harshbafna** [comment]
@CSLujunyu: We were not able to reproduce this issue at our end. Could you share the `ts_log.log` file and the error message that you get on executing `torchserve --stop` command. It would be great if you could share the complete dump of commands executed on your terminal to reproduce this issue.

**Comment by harshbafna** [comment]
Closing due to no response from OP.
