### ISSUE TITLE
Add support for gRPC

### ISSUE THREAD

**Issue by harshbafna** [pytorch/serve#656]
Add support for gRPC in `TorchServe`

**Comment by cbasavaraj** [comment]
Hi, I see gRPC has been added in v0.3.0. By when will this version be released? When I pip install torchserve, I get 0.2.2.  Right now, is there a way of testing v0.3.0?

**Comment by harshbafna** [comment]
@cbasavaraj: You can [install TorchServe from the source](https://github.com/pytorch/serve#install-torchserve-for-development) for now. TorchServe 0.3.0 will be very soon available on PyPi. :-)

**Comment by cbasavaraj** [comment]
Ah yes, I'd seen that section yesterday, forgot about it. Thanks!

**Comment by cbasavaraj** [comment]
I tried from master, and it works great! I think on the [readme](https://github.com/pytorch/serve/blob/master/docs/grpc_api.md), the entire paths need not be included for the proto files, as that's already present in `proto_path`.

One question: `inference.proto` seems to be quite generic, as it takes `map<string, bytes> input = 3` as input into the model and returns ` bytes prediction = 1;` as output. So for my own model, there's not much to change here or in `torchserve_grpc_client.py` right?

**Comment by harshbafna** [comment]
> One question: `inference.proto` seems to be quite generic, as it takes `map<string, bytes> input = 3` as input into the model and returns ` bytes prediction = 1;` as output. So for my own model, there's not much to change here or in `torchserve_grpc_client.py` right?

Yes, that's correct.
