### ISSUE TITLE
High CPU utilization when serving GPU and CPU models on one container.

### ISSUE THREAD

**Issue by yuanshaochen** [pytorch/serve#661]
## Context

* torchserve version: pytorch/torchserve:0.1-cuda10.1-cudnn7-runtime
* torch version: N/A
* torchvision version [if any]: N/A
* torchtext version [if any]: N/A
* torchaudio version [if any]: N/A
* java version: N/A
* Operating System and version: N/A

## Your Environment

* Installed using source? [yes/no]: yes.
* Are you planning to deploy it using docker container? [yes/no]: yes.
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom handler.
* What kind of model is it e.g. vision, text, audio?: text. (DistilBert)
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: using model-store in EFS
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: 
```
[TorchServe]
inference_address = http://0.0.0.0:8080
management_address = http://0.0.0.0:8081
num_workers = 1
number_of_gpu = 1
number_of_netty_threads = 32
job_queue_size = 1000
async_logging = true
model_store = /home/model-server/shared/model-store/en
model_snapshot = {"name": "startup.cfg", "modelCount": 9, "models": {"dummy_cpu_model_1": {"0.0.2": {"defaultVersion": true, "marName": "dummy_cpu_model_1_0.0.2.mar", "minWorkers": 1, "maxWorkers": 1, "batchSize": 1, "maxBatchDelay": 100, "responseTimeout": 300}}, "dummy_cpu_model_2": {"0.0.2": {"defaultVersion": true, "marName": "dummy_cpu_model_2_0.0.2.mar", "minWorkers": 1, "maxWorkers": 1, "batchSize": 1, "maxBatchDelay": 100, "responseTimeout": 300}}, "dummy_cpu_model_3": {"0.0.2": {"defaultVersion": true, "marName": "dummy_cpu_model_3_0.0.2.mar", "minWorkers": 1, "maxWorkers": 1, "batchSize": 1, "maxBatchDelay": 100, "responseTimeout": 300}}, "dummy_cpu_model_4": {"0.0.2": {"defaultVersion": true, "marName": "dummy_cpu_model_4_0.0.2.mar", "minWorkers": 1, "maxWorkers": 1, "batchSize": 1, "maxBatchDelay": 100, "responseTimeout": 300}}, "dummy_gpu_model_1": {"0.0.4": {"defaultVersion": true, "marName": "dummy_gpu_model_1_0.0.4.mar", "minWorkers": 1, "maxWorkers": 2, "batchSize": 1, "maxBatchDelay": 100, "responseTimeout": 300}}, "dummy_cpu_model_5": {"0.0.2": {"defaultVersion": true, "marName": "dummy_cpu_model_5_0.0.2.mar", "minWorkers": 1, "maxWorkers": 1, "batchSize": 1, "maxBatchDelay": 100, "responseTimeout": 300}}, "dummy_cpu_model_6": {"0.0.2": {"defaultVersion": true, "marName": "dummy_cpu_model_6_0.0.2.mar", "minWorkers": 1, "maxWorkers": 1, "batchSize": 1, "maxBatchDelay": 100, "responseTimeout": 300}}, "dummy_cpu_model_7": {"0.0.2": {"defaultVersion": true, "marName": "dummy_cpu_model_7_0.0.2.mar", "minWorkers": 1, "maxWorkers": 1, "batchSize": 1, "maxBatchDelay": 100, "responseTimeout": 300}}, "dummy_gpu_model_2": {"0.0.3": {"defaultVersion": true, "marName": "dummy_gpu_model_2_0.0.3.mar", "minWorkers": 1, "maxWorkers": 2, "batchSize": 1, "maxBatchDelay": 100, "responseTimeout": 300}}}}
```
* Link to your project [if any]: N/A. Company confidential project.

## Expected Behavior

TorchServe could serve both CPU models and GPU models on one container. 

## Current Behavior

When incoming prediction traffic increased (from 1 to ~5 TPS for all models), the CPU utilization spike to 100% from 10% suddenly without any error/exception. Prediction time for GPU models increased a little bit. (from 30ms to 100ms), but prediction time for GPU models increased from 200ms to >10000ms. The 100% CPU utilization could last for more than 6 hours. After stop receiving new requests, the queued CPU model requests finally got executed and cleaned the queue. Checked the threads using `top` command during the event and found there were ~8 threads which used 100% cpu respectively (8 vCPU) and last for X hours from event starts. When those threads got killed manually, the new thread still stuck there and never complete.

## Possible Solution

Could it due to the wrong value in configuration? Or the bugs from custom handler? 

## Steps to Reproduce

N/A

## Failure Logs [if any]

There is no failure logs. Everything looks normal from logs except the prediction time.
Logs before event:
```
2020-08-31 20:08:24,793 [INFO ] W-9008-dummy_gpu_model_1_0.0.3-stdout MODEL_METRICS - PredictionTime.Milliseconds:33.51|#ModelName:dummy_gpu_model,Level:Model|#hostname:64a172094409,requestID:fc18854d-ef55-40ce-a97d-aad68b63fcd4,timestamp:1598904504
2020-08-31 20:08:24,831 [INFO ] W-9004-dummy_gpu_model_2_0.0.4-stdout MODEL_METRICS - PredictionTime.Milliseconds:33.53|#ModelName:dummy_gpu_model,Level:Model|#hostname:64a172094409,requestID:de2a9d9e-88c8-4f94-ae0e-3181348dbb69,timestamp:1598904504
2020-08-31 20:08:25,981 [INFO ] W-9005-dummy_cpu_model_1_0.0.2-stdout MODEL_METRICS - PredictionTime.Milliseconds:146.0|#ModelName:dummy_cpu_model_1,Level:Model|#hostname:64a172094409,requestID:45541030-5fd3-4609-824f-becfe35c36c6,timestamp:1598904505
2020-08-31 20:08:26,747 [INFO ] W-9002-dummy_cpu_model_2_0.0.2-stdout MODEL_METRICS - PredictionTime.Milliseconds:212.72|#ModelName:dummy_cpu_model_2,Level:Model|#hostname:64a172094409,requestID:d5fd9ac5-6dbe-4de5-b191-dee180ce18a7,timestamp:1598904506
2020-08-31 20:08:26,800 [INFO ] W-9001-dummy_cpu_model_3_0.0.2-stdout MODEL_METRICS - PredictionTime.Milliseconds:208.62|#ModelName:dummy_cpu_model_3,Level:Model|#hostname:64a172094409,requestID:2492c2ba-bd9d-46ae-89dc-e9c0241ad5ae,timestamp:1598904506
```

Logs after event:
```
2020-08-31 20:09:51,942 [INFO ] W-9004-dummy_gpu_model_0.0.4-stdout MODEL_METRICS - PredictionTime.Milliseconds:129.28|#ModelName:dummy_gpu_model,Level:Model|#hostname:64a172094409,requestID:d3843a37-388c-4df2-a9c0-b87c2dcd5b71,timestamp:1598904591
2020-08-31 20:09:52,059 [INFO ] W-9004-dummy_gpu_model_0.0.4-stdout MODEL_METRICS - PredictionTime.Milliseconds:93.54|#ModelName:dummy_gpu_model,Level:Model|#hostname:64a172094409,requestID:96ad3e34-c053-410d-bf06-3ff845438117,timestamp:1598904592
2020-08-31 20:09:52,428 [INFO ] W-9003-dummy_cpu_model_1_0.0.2-stdout MODEL_METRICS - PredictionTime.Milliseconds:13412.81|#ModelName:dummy_cpu_model_1,Level:Model|#hostname:64a172094409,requestID:f860a7d5-7533-4f36-9233-89d9102c19db,timestamp:1598904592
2020-08-31 20:09:52,548 [INFO ] W-9000-dummy_cpu_model_2_0.0.2-stdout MODEL_METRICS - PredictionTime.Milliseconds:13555.96|#ModelName:dummy_cpu_model_2,Level:Model|#hostname:64a172094409,requestID:2df4c897-1f0d-4850-bd73-3bfe9d360115,timestamp:1598904592
2020-08-31 20:09:53,164 [INFO ] W-9001-dummy_cpu_model_3_0.0.2-stdout MODEL_METRICS - PredictionTime.Milliseconds:10503.18|#ModelName:dummy_cpu_model_3,Level:Model|#hostname:64a172094409,requestID:09e553db-c204-4146-9d28-3040d6eadb9f,timestamp:1598904593
```

**Comment by dhaniram-kshirsagar** [comment]
@yuanshaochen To better understand the situation, could you please let me know the following
1. Are you saying that CPU models are not performing well on the CUDA based torchserve image you are running?
2. Are you saying that CPU model inference request is blocked or getting processed at a slow pace compared to GPU based models?

FYI - The eight threads that you saw are worker thread which process the inference request queue. They process inference request from internal queue irrespective of gpu or cpu model.

**Comment by yuanshaochen** [comment]
Thank you for the response. Here are the answers for your question:
1. Are you saying that CPU models are not performing well on the CUDA based torchserve image you are running?
Not that case from my recent tests. I have tried to use cpu torchserve image for serving those 7 cpu models and observed the same high CPU utilization when traffic increased. I thinks this is not related to GPU or GPU models. 

2. Are you saying that CPU model inference request is blocked or getting processed at a slow pace compared to GPU based models?
Yes. CPU model inference requests were getting processed at a slow pace due to 100% CPU util. GPU based models did not get impact so much.

I think my questions are: 
1. Why the CPU model inference request become so slow when CPU util spike to 100%?
2. Is there any method to prevent CPU util to 100% when multiple worker running?
2. After CPU util went to 100%, why it could not auto-recover to ~10% util soon, since the request TPS was remain the same,

**Comment by dhanainme** [comment]
Hi @yuanshaochen ,

TorchServe runs each inference in a separate Process. You may be able to isolate if this is a TorchServe specific issue by running N inference workers as processes with python multiprocess.

You might want to look @ the [knobs that are exposed by TS for performance tuning](https://github.com/pytorch/serve/blob/master/docs/configuration.md#other-properties) - job_queue_size / number_of_netty_threads / netty_client_threads

You can also increase the JVM memory consumed by tweaking the [JVM params](https://github.com/pytorch/serve/blob/master/docs/configuration.md#customize-jvm-options)

**Comment by yuanshaochen** [comment]
@dhanainme Thank you for the information. I have tried to tune the `job_queue_size` to zero and `netty_client_threads` to a small number, but the issue still happened. I think the problem is causing by requests for different models come in at the same moment, since we have >9 models and each request could use up to 30% CPU utils for model inference, the CPU utils would spike to 100% and could not come back to normal.

Is there a way to restrict the worker CPU utilization? We want to find a way to prevent the CPU utils reach 100%.

**Comment by dhaniram-kshirsagar** [comment]
@yuanshaochen 
As you have mentioned, there are 9 models each having 1 worker. This means, you will be having 10  processes running on your machine. 10 process => 9 worker processes [which load and serve your specific model] + 1 main process with 9 worker threads. Assuming your request load is fairly distributed among 9 workers, what you can try is following
1. Increase the number of workers for each model
2. Use batching so that multiple requests for a model can be processed at the same time
3. To start with, I would not recommend you to change default configs like job_queue_size and netty_client_threads
4. As torchserve uses multiprocessing, I would recommend you to use a higher config machine if possible.

**Comment by dhaniram-kshirsagar** [comment]
> * Why the CPU model inference request become so slow when CPU util spike to 100%?
Seems like a model inference request taking more time and hence overall spike when all the models are busy inferencing.
> * Is there any method to prevent CPU util to 100% when multiple worker running?
No
> * After CPU util went to 100%, why it could not auto-recover to ~10% util soon, since the request TPS was remain the same,
As you said, the same TPS is still going on hence CPU load is not going down i.e. Model worker processes are still busy with inferencing

**Comment by yuanshaochen** [comment]
Thank you for the suggestions! I have a naive question about the first suggestion: Why increasing the number of works could help with this issue, does it make it worse? As worker number increased, the chance to reach 100% CPU gets higher?

**Comment by dhaniram-kshirsagar** [comment]
> Thank you for the suggestions! I have a naive question about the first suggestion: Why increasing the number of works could help with this issue, does it make it worse? As worker number increased, the chance to reach 100% CPU gets higher?

Replying to the old thread for reference

@yuanshaochen  Number of workers should be tuned per machine configuration used in your deployment. So accordingly CPU usage should be taken care of.
