### ISSUE TITLE
Enhancing API regression suite to test batch support for models

### ISSUE THREAD

**Issue by shivamshriwas** [pytorch/serve#679]
## Is your feature request related to a problem? Please describe.
The API Regression suite is used to test the models available in model zoo & examples such as HF - BERT.
However, this is yet incomplete as it does not test batching of inference request for the models.
As almost all models support batch inference there should some check for testing models with batch.

The current postman collection based implementation seems to  have a limitation to run multiple requests simultaneously.  

## Describe the solution

A python-based framework can be added with a goal testing these models &/or the other APIs as well.
This will be a robust solution to test model inference to test and validate various scenarios.
- to validate various output types of a model (text/json/image/tensor..etc)
- to test the models without batch(ie batch size=1)
- to test models with batch (if supported)

**Comment by msaroufim** [comment]
This is now available in torchserve
