### ISSUE TITLE
S3 Model Store SSE support

### ISSUE THREAD

**Issue by MFreidank** [pytorch/serve#691]
## Is your feature request related to a problem? Please describe.
Yes. The [management API](https://pytorch.org/serve/management_api.html#id1) has support for MAR files stored on S3, using syntax `/models?url=https://<s3_path>/${MODEL_NAME}.mar`.
 
However, when the MAR file is stored on a S3 bucket encrypted with server-side encryption (e.g. AWS KMS) the syntax above is insufficient because it does not allow us to specify a KMS key. 

In addition, access to S3 is currently handled exclusively through REST interface. 
For an enterprise-friendly interface, it would be preferable to allow specification of URI's on S3 via the syntax: `s3://${MODEL_S3_KEY}.mar`. This could be implemented in a straightforward way using the `boto3` library.

## Describe the solution
Add support to specify an optional (custom) SSE key for S3 related operations and honour this key on the server side.
Possible ways to implement support could include:
* server-side (e.g. through as [configuration](https://pytorch.org/serve/configuration.html))
* client-side (e.g. by exposing an optional REST argument.

**Comment by dhaniram-kshirsagar** [comment]
This can be very well covered via #476

**Comment by MFreidank** [comment]
@dhaniram-kshirsagar agree - but what would it take for that to get more traction? Looks like it's been open for a while.

**Comment by dhaniram-kshirsagar** [comment]
@MFreidank Sure will get back to you on this. This shouldn't take much effort. The idea here is to provide a pluggable or extendable interface. One way of achieving this could be to ask the user to configure the custom downloader **python** file which will be invoked by torchserve. Obviously, torchserve will have to supply the target download path to this custom downloader. This way download will be generic and different types of downloaders can be configured.

**Comment by vivekpd15** [comment]
Any updates on this? Or a prospective timeline?

**Comment by msaroufim** [comment]
Hi @vivekpd15 thank you for your patience, this feature is now available https://github.com/pytorch/serve/pull/1027
