### ISSUE TITLE
Change batch_size of registered model through management API

### ISSUE THREAD

**Issue by cceyda** [pytorch/serve#693]
## Is your feature request related to a problem? Please describe.
This is more of a convenience issue.
It would be nice to have an endpoint for modifying `batch_size`, `max_batch_delay` and `response_timeout` for a registered model rather than deleting an re-registering a model.

## Describe the solution
It could be similar to modifying [number of workers](https://pytorch.org/serve/management_api.html#scale-workers)
Like:
`PUT /models/{model_name}?batch_size=12&max_batch_delay=1000`

## Describe alternatives solution
alternatives welcome

**Comment by harshbafna** [comment]
This is really good to have feature. A similar ticket is already there and targetted for future release.

https://github.com/pytorch/serve/issues/64

**Comment by lxning** [comment]
fixed in v0.4.1
