### ISSUE TITLE
model inference by java or pytorch ?

### ISSUE THREAD

**Issue by tranquangchung** [pytorch/serve#701]
Dear Author

We have a question about TorchServe.

Is TorchServe convert pytorch model to inference by java ?
Or Java only wraps outside pytorch model with the purpose is only easy to use ?

Thanks

**Comment by dhaniram-kshirsagar** [comment]
@tranquangchung Java is not used for inferencing. We use PyTorch in the backend for inferencing.
Java is used in frontend component of torchserve whose main purpose is to provide rest APIs and model mgmt.

**Comment by harshbafna** [comment]
Closing as the query has been answered.
