### ISSUE TITLE
[Question] K8s multi-model set-up for large models

### ISSUE THREAD

**Issue by gromoglasov** [pytorch/serve#710]
##  Question

The k8s integration with helm from 0.2.0 has helped a lot with the set up, but working with larger models is still a problem due to the memory requirements. 

With the size of the models I am working with, I can only launch one/two models per machine. I can realistically only have 2 models registered per one TorchServe pod. 

I was thinking to only deploy 1 model per 1 TorchServe pod, within a separate node-group. With this set-up I can scale models independetly of each other. The problem with this set-up is that I can not make use of the managemet API, as I will not be registering new models to the TorchServe pods, but rather creating a separate node group.

Any suggestions on how to go about it?

**Comment by chauhang** [comment]
@gromoglasov This should be fine for managing models on your own in K8s deployments.  You can inherit from the based TorchServe docker image and create a new image per model with the model config and mar files as part of that docker container and set the scaling rules for it on K8s side. Let us know if you run into any problems.

**Comment by gromoglasov** [comment]
Thanks, @chauhang :)
