### ISSUE TITLE
how to register model present in local file system

### ISSUE THREAD

**Issue by paniabhisek** [pytorch/serve#712]
I have `my-model`, present in `/path/to/models`; the path is local file system path.

**command to start `torchserve`**: `docker run -p 8080:8080 -p 8081:8081 --name my-serve pytorch/torchserve:0.2.0-cpu`

Then when I try to register `my-model` -> `curl -X POST "http://localhost:8081/models?url=/path/to/models/my-model.mar"`, I get:

	{
	  "code": 404,
	  "type": "ModelNotFoundException",
	  "message": "Model not found in model store: /path/to/models/my-model.mar"
	}

The _register api call_ link is broken on the [docs](https://pytorch.org/serve/server.html#arguments) and I couldn't find anywhere for local file system.

**Comment by harshbafna** [comment]
@paniabhisek: TorchServe 2.0 expects the URL to be either an HTTP(s) URI which can be downloaded from the internet or just the name of the mar file which is already present in the model-store.

In your case, you can map the model-store directory in the docker container to your local model directory which starting the container as follows:

```
docker run -p 8080:8080 -p 8081:8081 --name my-serve -v $(pwd)/model-store:<path_to_models> pytorch/torchserve:0.2.0-cpu
```

Then change your curl command to the following:
```
curl -X POST "http://localhost:8081/models?url=my-model.mar"
```

Please refer the following documentation from the TorchServe GH repo for more details

 - [TorchServe quickstart with docker](https://github.com/pytorch/serve/tree/master/docker)
 - [Register a model](https://github.com/pytorch/serve/blob/master/docs/management_api.md#register-a-model)

The latest master also has support for `file://` protocol in model url and will available in TorchServe 3.0 release.

**Comment by paniabhisek** [comment]
$ pwd
	/path/to/model-store
	$ ls
	model-store
	$ ls model-store
	my-model.mar

**command to start torchserve**: `docker run -p 8080:8080 -p 8081:8081 --name my-serve -v /path/to/model-store/model-store:/home/model-server/model-store pytorch/torchserve:0.2.0-cpu`

	$ curl -X POST "http://localhost:8081/models?url=my-model.mar"
	{
	  "code": 404,
	  "type": "ModelNotFoundException",
	  "message": "Model not found in model store: my-model.mar"
	}

**Comment by harshbafna** [comment]
> docker run -p 8080:8080 -p 8081:8081 --name my-serve -v /path/to/model-store/model-store:/home/model-server/model-store pytorch/torchserve:0.2.0-cpu

Do not replace the `($pwd)/model-store` in the command, this represents the default model-store path used in the TorchServe docker image.

**Comment by paniabhisek** [comment]
Same issue. Besides `$(pwd)/model-store` and it's equivalent absolute path shouldn't make any difference, as after creation of container they will point to same path

**Comment by harshbafna** [comment]
> Same issue. Besides `$(pwd)/model-store` and it's equivalent absolute path shouldn't make any difference, as after creation of container they will point to same path
> 
> Also when I do curl, where does it look for `my-model.mar`?

@paniabhisek: My bad, I by-mistake swapped the `-v` arguments. It should be <local-path>:<container-path>

Here is what I tried,

My local model-store
```
(base) ubuntu@ip-172-31-54-27:~/model-store$ pwd
/home/ubuntu/model-store
(base) ubuntu@ip-172-31-54-27:~/model-store$ ls
densenet161.mar 
```

Docker container start command:

```
docker run -p 8080:8080 -p 8081:8081 -v /home/ubuntu/model-store:/home/model-server/model-store pytorch/torchserve:0.2.0-cpu
```

Model registration command:

```
(base) ubuntu@ip-172-31-54-27:~$ curl -X POST "http://localhost:8081/models?url=densenet161.mar"
{
  "status": "Model \"densenet161\" Version: 1.0 registered with 0 initial workers. Use scale workers API to add workers for the model."
}

```

**Comment by paniabhisek** [comment]
My bad it has to do with file permission: the folder permission was `drwx------.` and file permission was `-rw-------`.

Also you can be anywhere in the local file system while registering as long as the file name is correct.

Thanks @harshbafna
