### ISSUE TITLE
Autoscaling TorchServe Questions and feature request

### ISSUE THREAD

**Issue by misrasaurabh1** [pytorch/serve#714]
I am trying to deploy TorchServe in a kubernetes cluster and it seems hard to figure out how to autoscale this server to handle a variety of traffic load while not deploying maximum possible number of replicas to save money as well.

It seems like there is a Prometheus metrics framework with the v0.2 release and it has metrics like `ts_inference_latency_microseconds` , `ts_inference_requests_total` and `ts_queue_latency_microseconds`. These could be useful for autoscaling but the documentation does not explain how these metrics are measured, making it hard to use them. For example these do not say are these instantaneous measurements, measurements of the last request served, averaged measurements and if so then at what averaging interval. I would appreciate better documentation for the metrics.

For workloads that don't have a constant inference time (language-generation models), it is again hard to understand which one of these metrics would help the most with autoscaling. In our experience deploying models with TF-serve, we learnt that the best metric to autoscale is the queue depth, that is how many requests are waiting to be processed and are waiting in a queue. It seems like there is a similar metric `ts_queue_latency_microseconds` but that seems ill defined and seems to measure time rather than depth. Could you clarify what queue is this measuring the latency for? Is it the time waiting before handled by the Handler? If this is not the queue-wait-time, then could you please implement the queue wait time and queue depth as metrics so that we can use them for reliable autoscaling?

**Comment by maaquib** [comment]
@misrasaurabh1 We do plan to use these metrics for autoscaling. The work for this is being tracked under #88
