### ISSUE TITLE
is there a method to add additional endpoints to the API?

### ISSUE THREAD

**Issue by reachtarunhere** [pytorch/serve#716]
## 📚 Documentation

Say I want to POST some JSON which changes model's behaviour for inference of future requests?

**Comment by dhaniram-kshirsagar** [comment]
@reachtarunhere Please provide an example.

**Comment by dhaniram-kshirsagar** [comment]
> @reachtarunhere Please provide an example.

I did notice the issue description. Yes, you can add additional endpoints, have a look at https://github.com/pytorch/serve/plugins. Documentation for this is in progress. Let us know if you need any other details on this.

**Comment by reachtarunhere** [comment]
@dhaniram-kshirsagar thanks for the prompt reply. Say along with text labelling I want to provide a captialization API (for reasons I can't explain in detail this has can't be  PyTorch model). So I would like to add an endpoint like /captalize/ instead of /predict/

Technically I can wrap torchserve behind another WebAPI and get this functionality. I am curious tho if I can avoid doing that.

Further are names for endpoints like /predict/ fixed or can they be renamed to say /classify/

**Comment by dhaniram-kshirsagar** [comment]
Yes, you can add as many endpoints as you want. You don't have to wrap torchserve behind WebAPI. Plugins are simply jars which are loaded in the same container as torchserve.

**Comment by harshbafna** [comment]
Closing as the query has been answered.
