### ISSUE TITLE
batch_size is hard coded as 1 if model is loaded during server initialization.

### ISSUE THREAD

**Issue by lxning** [pytorch/serve#720]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

* torchserve version: master
* torch version: master
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version: 
* Operating System and version:

## Your Environment

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: both
* Using a default/custom handler? [If possible upload/share custom handler/model]:
* What kind of model is it e.g. vision, text, audio?: any model
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Expected Behavior

A model's batch size should be as same as the "batch_size" defined in configuration.

## Current Behavior

A model's batch size always is 1 even though the "batch_size" defined in configuration is larger than 1.

## Steps to Reproduce

Here is [source code](https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/ModelServer.java#L218) which shows batch size is hard coded as 1 during model registration.

**Comment by spate141** [comment]
Any update on this one?

**Comment by lxning** [comment]
@spate141 it was added into our working list. The code review will be sent out soon.

**Comment by spate141** [comment]
@harshbafna @lxning: Any update on this one? 

One specific use case for this could be when deploying models on commodity hardwares. For example, when the system recycles and models loads up again, it's using default parameters like `batch_size, max_batch_delay, initial_workers, response_timeout`. My temporary hack is to run another service script to set these variables according to my hardware every time model server restarts which is kind feels hacky. 

If this implementation is taking too long then any better suggestion on how to handle this?

**Comment by lxning** [comment]
[Here](https://github.com/pytorch/serve/pull/759) is the pr.
