### ISSUE TITLE
Torchserve Management Dashboard 

### ISSUE THREAD

**Issue by cceyda** [pytorch/serve#726]
I have created a dashboard for the management API using streamlit 🔥 
https://github.com/cceyda/torchserve-dashboard

![Demo](https://cceyda.github.io/blog/images/copied_from_nb/torchserve/dashboard_demo.gif)

`pip3 install torchserve-dashboard --user`
`torchserve-dashboard`

Along with a TorchServe tutorial type [blog post](https://cceyda.github.io/blog/torchserve/streamlit/dashboard/2020/10/15/torchserve.html)

Hope this is useful! 🥳 [Share](https://twitter.com/ceyda_cinarel/status/1315996417345814529)

**Comment by mycpuorg** [comment]
Looks good, Thank you!

**Comment by HamidShojanazeri** [comment]
Nice work, thanks!

**Comment by MartinEliasQ** [comment]
This looks really good, Thank you.
