### ISSUE TITLE
Conda installation errors

### ISSUE THREAD

**Issue by Licini** [pytorch/serve#736]
## 📚 Documentation
Hi,

There are few parts might need to small adjustments in installation instruction using conda:
1. `pip install -U -r requirements_gpu.txt` under conda would throw an error:
```
ERROR: Could not find a version that satisfies the requirement torch==1.6.0+cu101 (from -r requirements/gpu.txt (line 1)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.5.0, 1.5.1, 1.6.0)
ERROR: No matching distribution found for torch==1.6.0+cu101 (from -r requirements/gpu.txt (line 1))
```
I needed to remove `+cu101` from requirements and install torch and torch version with `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch` first.

2.  Suggesting replace `conda install torchserve torch-model-archiver` with `conda install -c pytorch torchserve torch-model-archiver` , since pytorch channel is not included in conda by default

**Comment by harshbafna** [comment]
@Licini: This is a documentation issue.

Please use the following command to run requirements_gpu.txt 

```
pip install -U -r requirements_gpu.txt -f https://download.pytorch.org/whl/torch_stable.html
```
