### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by Licini** [pytorch/serve#737]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

* torchserve version: 0.2.1
* torch version: 1.6.0
* Operating System and version: Ubuntu 20.04 with Conda python3.8
## Your Environment

* Installed using source? [yes/no]: No
* Are you planning to deploy it using docker container? [yes/no]: Yes
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: Object_Detector
* What kind of model is it e.g. vision, text, audio?: Vision, MaskRCNN/FastRCNN

## Current Behavior

Models using Object_Detector not able to load. Error log suggesting `ModuleNotFoundError: No module named 'packaging'`

## Possible Solution

`pip install packaging` solved the issue. Please consider adding it to dependencies 

## Failure Logs [if any]

[ts_log copy.log](https://github.com/pytorch/serve/files/5397539/ts_log.copy.log)

**Comment by harshbafna** [comment]
@Licini:  The TorchServe version reported by you is `0.2.1` and the same can be seen in the provided logs as well. However, the official latest version of TorchServe is 0.2.0 only. Is this some custom implementation of TorchServe that you are using?

The `packaging` module used in `object_detector` default handler is already a part of TorchServe dependency defined in [setup.py](https://github.com/pytorch/serve/blob/master/setup.py#L132)

**Comment by Licini** [comment]
> @Licini: The TorchServe version reported by you is `0.2.1` and the same can be seen in the provided logs as well. However, the official latest version of TorchServe is [0.2.0](https://pypi.org/project/torchserve/) only. Is this some custom implementation of TorchServe that you are using?
> 
> The `packaging` module used in `object_detector` default handler is already a part of TorchServe dependency defined in [setup.py](https://github.com/pytorch/serve/blob/master/setup.py#L132)

@harshbafna Thanks for the quick reply, I used `conda install torchserve`. It is mysteriously one version ahead ...
 https://anaconda.org/pytorch/torchserve

**Comment by harshbafna** [comment]
@Licini: Thanks for the update on the steps used for installation. I will try and reproduce this at my end and revert.

**Comment by harshbafna** [comment]
@Licini: Thanks for reporting this. I can confirm this is a bug with the conda binary and the `packaging` module does not get installed as part of TorchServe dependency. We will fix this in the next release.
