### ISSUE TITLE
Replace JUnit tests with TestNG and unify testing framework 

### ISSUE THREAD

**Issue by jeremiahschung** [pytorch/serve#743]
## Is your feature request related to a problem? Please describe.

No. Currently the [serving-sdk](serving-sdk/src/test/java/org/pytorch/serve/servingsdk/ModelServerEndpointTest.java) uses the JUnit framework for unit testing. This is the only place JUnit is used compared to TestNG being used in the main frontend code. 

## Describe the solution

Replace the use of JUnit in the serving-sdk with TestNG and remove dependencies on JUnit.

**Comment by dhaniram-kshirsagar** [comment]
@jeremiahschung This should be taken care of by PR #536

**Comment by jeremiahschung** [comment]
> @jeremiahschung This should be taken care of by PR #536

@dhaniram-kshirsagar Thanks for the response! It looks like PR #536 still has references to JUnit (https://github.com/pytorch/serve/pull/536/files#diff-ef66cdab4bf76628f5e70f719f2c16ad0952fe5a0ba8ac5dace57bed9c5bab46R7). IS this intended?
