### ISSUE TITLE
Question: Is it possible to secure .mar files?

### ISSUE THREAD

**Issue by stefempath** [pytorch/serve#745]
I hope it's okay to ask questions here. I couldn't find a community channel for Serve.

We would like to deploy trained TorchScript models on-premise. For this we need to at least secure the trained weights. If the .mar files can somehow be secured, it would allow us to use Serve on the client's server. Any thoughts?

**Comment by dhaniram-kshirsagar** [comment]
@saifrahmed Do you want to protect mar in transit e.g. have pass protected zip OR Are you looking at protecting extracted content on the server?

**Comment by saifrahmed** [comment]
I think that comment was meant for @stefempath

**Comment by stefempath** [comment]
@dhaniram-kshirsagar 
1. Stored securely in the model store, so that when not in use, the .mar contents cannot be accessed. I guess this would require some sort of key that can expire that can safely be stored somewhere?
2. Prevent/complicate the extraction of weights when the model is being loaded for inference.

**Comment by dhaniram-kshirsagar** [comment]
@stefempath 
Both these requirements cannot be supported in torchserve at present however you can raise an enhancement request.
Suggestion-
For 1, Yes, you will have to secure a mar file using a password etc.. and in your custom torchserve handler you will have to extract it however there is a risk as python files can be read.
NOTE mar file is nothing but a zip file

**Comment by harshbafna** [comment]
Closing as the query has been answered.
