### ISSUE TITLE
Support AWS Elastic Inference (EI)?

### ISSUE THREAD

**Issue by shnoru1** [pytorch/serve#746]
I've been trying to deploy `TorchServe` API via AWS Elastic Inference (EI), referring to the document written by AWS https://docs.aws.amazon.com/elastic-inference/latest/developerguide/ei-pytorch-using.html#ei-pytorch-inference.

I've read that `TorchServe` selects the GPU devices in a round-robin fashion, and would this be same to Elastic Inference? It would be very helpful if there is a best practice using `TorchServe` with Elastic Inference. Thank you.

**Comment by dhaniram-kshirsagar** [comment]
@shnoru1 Yes, torchserve selects the  GPU in a round-robin fashion. 
I am assuming for using aws EI, you have written a custom torchserve handler as it doesn't support EI in default handlers. If yes, then look at [this](https://github.com/pytorch/serve/blob/master/examples/text_to_speech_synthesizer/waveglow_handler.py#L56) which demonstrates how given gpu id can be used while loading model. 

For best practice, you can raise a doc enhancement request.

**Comment by shnoru1** [comment]
@dhaniram-kshirsagar Yes, I've written a custom torchserve just as waveglow examples. I've figured out `torch.jit` is required to save a trained model, as described [here](https://docs.aws.amazon.com/elastic-inference/latest/developerguide/ei-pytorch.html). But I'm still little bit confused applying it to torchserve, like how to deal with the gpu devices, etc.. I think I can raise a doc enhancement request as you suggested while I'm working on it.

**Comment by dhaniram-kshirsagar** [comment]
@shnoru1 As such you don't have to manage the GPU aspect, the only thing required from you is to load your model and later during inference input with supplied GPU id to your [custom handler](https://github.com/pytorch/serve/blob/master/docs/custom_service.md#handling-model-execution-on-multiple-gpus) as shown [here](https://github.com/pytorch/serve/blob/master/examples/text_to_speech_synthesizer/waveglow_handler.py#L56)

**Comment by harshbafna** [comment]
Closing as the query has been answered and doc enhancement related to best practices for AWS Elastic Inference will be tracked through #748
