### ISSUE TITLE
Doc enhancement request for the best practice using TorchServe with AWS Elastic Inference

### ISSUE THREAD

**Issue by shnoru1** [pytorch/serve#748]
## 📚 Documentation

I'm trying to write a custom handler that handles AWS EI model. [This document](https://github.com/awslabs/multi-model-server/blob/master/docs/elastic_inference.md) from AWS multi model server repo gives an example showing custom service using MXNet, but I couldn't find a document explaining best practice for PyTorch. It would be helpful if the document is enhanced by adding information on the use of EI.

**Comment by msaroufim** [comment]
Hi @shnoru1 what kinds of best practices do you think we're missing? This doc feels very similar to our existing README.md

**Comment by lxning** [comment]
@shnoru1 Feel free to reopen if you think there still have some issues.
