### ISSUE TITLE
Torchserve latest-gpu remote docker image does not support Metrics API

### ISSUE THREAD

**Issue by jeremiahschung** [pytorch/serve#752]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

The remote docker image pytorch/torchserve:latest-gpu fails to receive metrics API calls on port 8082.
Please see the logs below where I tested:
- Deploying torchserve on EKS with the "latest-gpu" image, metrics API fails.
- Deploying torchserve on EKS with the "latest" image, metrics API succeeds.
- Running torchserve locally with the docker image "latest-gpu", metrics API fails.

## Expected Behavior
Making a request to <torchserve>:8082/metrics should work.

## Current Behavior
Making the request results in an error.

## Steps to Reproduce

1. Run a docker container using command `docker run --rm -it --gpus all -p 8080:8080 -p 8081:8081 -p 8082:8082  pytorch/torchserve:latest-gpu`
2. Make an inference at least once `curl -X POST http://localhost:8080/predictions/squeezenet1_1 -T kitten.jpg`
3. Query the metrics API endpoint `curl http://localhost:8082/metrics` and this will fail

## Failure Logs [if any]

[failure_log.txt](https://github.com/pytorch/serve/files/5441737/failure_log.txt)

**Comment by maaquib** [comment]
@jeremiahschung I don't think the latest gpu image was tagged to `pytorch/torchserve:latest-gpu`. You should try with `pytorch/torchserve:0.2.0-cuda10.1-cudnn7-runtime`

https://hub.docker.com/r/pytorch/torchserve/tags?page=1

**Comment by jeremiahschung** [comment]
Image `pytorch/torchserve:0.2.0-cuda10.1-cudnn7-runtime` is failing with the same error. 

Regardless of this issue, since the "latest-gpu" tag is widely used across our documentation, we should update the image when we release a new build. Thoughts?

```
(base) jc@jc:~/dev$ docker container list
CONTAINER ID        IMAGE                                              COMMAND                  CREATED              STATUS              PORTS                              NAMES
886fd10ceb90        pytorch/torchserve:0.2.0-cuda10.1-cudnn7-runtime   "/usr/local/bin/dock…"   About a minute ago   Up About a minute   0.0.0.0:8080-8082->8080-8082/tcp   funny_wilson
(base) jc@jc:~/dev$ curl -X POST http://localhost:8080/predictions/squeezenet1_1 -T kitten.jpg 
{
  "tabby": 0.2752005457878113,
  "lynx": 0.2546869218349457,
  "tiger_cat": 0.24254141747951508,
  "Egyptian_cat": 0.22137463092803955,
  "cougar": 0.0022544844541698694
(base) jc@jc:~/dev$ curl http://localhost:8082/metrics
curl: (56) Recv failure: Connection reset by peer
```

**Comment by maaquib** [comment]
@jeremiahschung I see. I tried with `0.2.0-cuda10.1-cudnn7-runtime` and it seems like the port is open only to the loopback address. Hence the failure.
```
2020-10-26 22:13:14,797 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2020-10-26 22:13:14,852 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:8080
2020-10-26 22:13:14,852 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2020-10-26 22:13:14,853 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://0.0.0.0:8081
2020-10-26 22:13:14,853 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2020-10-26 22:13:14,854 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://127.0.0.1:8082
```

@seemethere Just want to confirm if the gpu image was not tagged to `latest-gpu` intentionally

**Comment by jeremiahschung** [comment]
Good catch. I believe that is part of the config.properties configuration. Perhaps the gpu image was built with the wrong config settings?

**Comment by Hammamwa47** [comment]
Hi, I think the config.properties  should be modified to include the metrics address e.g like this: 

`metrics_address=https://0.0.0.0:8082`

**Comment by harshbafna** [comment]
Validated this on latest `torchserve:latest-gpu` image

```
ubuntu@ip-172-31-69-243:~$ docker run --rm -it --gpus all -p 8080:8080 -p 8081:8081 -p 8082:8082 pytorch/torchserve:latest-gpu


ubuntu@ip-172-31-69-243:~$ curl -X POST "http://localhost:8081/models?url=https://torchserve.pytorch.org/mar_files/squeezenet1_1.mar&initial_workers=1"
{
  "status": "Model \"squeezenet1_1\" Version: 1.0 registered with 1 initial workers"
}


ubuntu@ip-172-31-69-243:~$ curl -X POST "http://localhost:8080/predictions/squeezenet1_1" -T serve/examples/image_classifier/kitten.jpg 
{
  "tabby": 0.2752005457878113,
  "lynx": 0.2546869218349457,
  "tiger_cat": 0.24254141747951508,
  "Egyptian_cat": 0.22137463092803955,
  "cougar": 0.0022544844541698694
}


ubuntu@ip-172-31-69-243:~$ curl http://localhost:8082/metrics
# HELP ts_inference_latency_microseconds Cumulative inference duration in microseconds
# TYPE ts_inference_latency_microseconds counter
ts_inference_latency_microseconds{uuid="912a19f8-44e3-4752-be02-f5ac428abaf2",model_name="squeezenet1_1",model_version="default",} 37233.815
# HELP ts_queue_latency_microseconds Cumulative queue duration in microseconds
# TYPE ts_queue_latency_microseconds counter
ts_queue_latency_microseconds{uuid="912a19f8-44e3-4752-be02-f5ac428abaf2",model_name="squeezenet1_1",model_version="default",} 246.001
# HELP ts_inference_requests_total Total number of inference requests.
# TYPE ts_inference_requests_total counter
ts_inference_requests_total{uuid="912a19f8-44e3-4752-be02-f5ac428abaf2",model_name="squeezenet1_1",model_version="default",} 1.0
ubuntu@ip-172-31-69-243:~$ 
```


Closing.
