### ISSUE TITLE
Regression suite fails to install newman with latest nodejs

### ISSUE THREAD

**Issue by harshbafna** [pytorch/serve#755]
## Context
* torchserve version: latest master
* torch version: 1.6.0
* torchvision version [if any]: 0.7.0
* torchtext version [if any]: 0.7.0
* torchaudio version [if any]: 0.6.0
* java version: OpenJDK 11
* Operating System and version:Ubuntu 18.04

## Your Environment

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: No
* Is it a CPU or GPU environment?: Both
* Using a default/custom handler? [If possible upload/share custom handler/model]: NA
* What kind of model is it e.g. vision, text, audio?: NA
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: NA
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: NA
* Link to your project [if any]: NA

## Expected Behavior
Regression suite should successfully install newman and successfully execute the postman collections.

## Current Behavior
`newman` fails to install with latest nodejs and postman collections doesn't execute.

## Possible Solution
Freeze the `node` version to `14.13.1` as per the workaround provided here.
https://github.com/npm/cli/issues/2000

## Steps to Reproduce
Run torchserve rergression suite.

## Failure Logs [if any]

`npm` installation failure log.

```
+ sudo npm install -g newman newman-reporter-html
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: newman@5.2.0
npm ERR! node_modules/newman
npm ERR!   newman@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer newman@"4" from newman-reporter-html@1.0.5
npm ERR! node_modules/newman-reporter-html
npm ERR!   newman-reporter-html@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/ubuntu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-10-27T15_09_25_222Z-debug.log
```

**Comment by tigercosmos** [comment]
this also failed at `mac_npm_deps`

**Comment by harshbafna** [comment]
@tigercosmos: Please use the `ts_scripts/install_dependencies.py` instead of directly executing the `mac_npm_deps` script. It should take care of installing and setting the node version to `14.x`.

**Note**: It will only unlink any existing version of the node and not uninstall it.
