### ISSUE TITLE
python requests examples desired

### ISSUE THREAD

**Issue by opconty** [pytorch/serve#760]
There are only curl examples in Predictions API document, it would be better if providing some python requests examples .

**Comment by alvarobartt** [comment]
Hi @opconty! I found the same issue while I was starting with TorchServe, here I leave you an example using Python once the TorchServe server is deployed. Note that it really depends on the model you are using, the example below applies to any image related problem (for text would be different as you don't need to transform the data to bytes), so I'll show you how to proceed for images as it may seem more complex.

As an example, before proceeding lets assume you deployed the TorchServe server so as to serve [FCN ResNet 101]() model, following the deployment steps detailed under [examples/image_segmenter](https://github.com/pytorch/serve/tree/master/examples/image_segmenter) as it follows:

```bash
pip install torch torchvision torchserve torch-model-archiver -f https://download.pytorch.org/whl/torch_stable.html
git clone https://github.com/pytorch/serve.git
cd serve/
wget https://download.pytorch.org/models/fcn_resnet101_coco-7ecb50ca.pth
torch-model-archiver --model-name fcn_resnet_101 --version 1.0 --model-file examples/image_segmenter/fcn/model.py --serialized-file fcn_resnet101_coco-7ecb50ca.pth --handler image_segmenter --extra-files examples/image_segmenter/fcn/fcn.py,examples/image_segmenter/fcn/intermediate_layer_getter.py
mkdir model_store
mv fcn_resnet_101.mar model_store/
torchserve --start --ncs --model-store model_store --models fcn=fcn_resnet_101.mar
```

_Note that using the handler is optional as well as generating the MAR file yourself, for more details please feel free to ask me._

---

### Preprocessing

First of all, regarding the preprocessing it depends if you deployed the model using `image_segmenter` or `image_classifier` handlers or, on the other hand, you did not used any handler at all. Here you have a piece of code for preprocessing any input image either from path or from buffer, for both approaches, with/without TorchServe handlers.

```python
import cv2
import numpy as np
from PIL import Image
from io import BytesIO


def preprocess(img_path_or_buf):
    # Check whether image is a path or a buffer
    raw_image = (
        Image.fromarray(cv2.imread(img_path_or_buf))
        if isinstance(img_path_or_buf, str)
        else img_path_or_buf
    )

    # If buffer was np.array instead of PIL.Image, transform it
    if type(raw_image) == np.ndarray:
        raw_image = Image.fromarray(raw_image)

    # Converts the image to RGB
    raw_image = raw_image.convert("RGB")

    # Here you should uncomment the T.Compose if you are not using 
    # TorchServe `image_classifier` or `image_segmenter` handlers.
    # from torchvision import transforms as T
    # image_processing = T.Compose([
    #     T.Resize(256),
    #     T.CenterCrop(224),
    #     T.ToTensor(),
    #     T.Normalize(
    #         mean=[0.485, 0.456, 0.406],
    #         std=[0.229, 0.224, 0.225]
    #     )])
    # raw_image = image_processing(raw_image)

    # Transform the PIL.Image into a bytes string (required for the inference)
    raw_image_bytes = BytesIO()
    raw_image.save(raw_image_bytes, format="PNG")
    raw_image_bytes.seek(0)

    return raw_image_bytes.read()
```

### Inference

Then you will need to proceed with the request to the deployed TorchServe Inference API which by default it's deployed at `localhost:8080` (more information regarding the TorchServe REST APIs available at: https://pytorch.org/serve/rest_api.html)

```python
import requests
import torch

def predict(preprocessed_image_bytes):
    # Send HTTP Post request to TorchServe Inference API
    url ="localhost:8080/predictions/fcn"
    req = requests.post(url, data=preprocessed_image_bytes)
    if req.status_code == 200:
        # Convert the output list into a torch.Tensor
        output = req.json()
        return torch.FloatTensor(output)
    return None
```

### Postprocessing

Then it's up to you how to handle the output of the model, but you can check the default postprocessing behaviors of the `image_segmenter` handler at https://github.com/pytorch/serve/blob/master/ts/torch_handler/image_segmenter.py and the `image_classifier` ones at https://github.com/pytorch/serve/blob/master/ts/torch_handler/image_classifier.py.

---

Hope you found this useful!

BTW @harshbafna I'd love to create a proper documentation for this, just let me know! 🤗

**Comment by opconty** [comment]
HI,alvarobartt,
Thanks a lot, I found pycurl works nice for me, but I'll try your method,

by using pycurl:
   ```
 import pycurl
    url = 'http://localhost:8080/predictions/model_name'
    buffer = io.BytesIO()
    crl = pycurl.Curl()
    crl.setopt(crl.URL, url)
    crl.setopt(crl.HTTPPOST, [
        ('body', (crl.FORM_FILE, img_paths[0])),
        # ('data', (crl.FORM_FILE, img_paths[1]))
    ])
    crl.setopt(crl.WRITEDATA, buffer)
    crl.perform()
    crl.close()
    body = literal_eval(buffer.getvalue().decode('utf-8'))
```

**Comment by alvarobartt** [comment]
You're welcome @opconty if you have any other doubt just let me know! 🤗

**Comment by harshbafna** [comment]
@alvarobartt: Thanks for the elaborate example. It would be good to have a simple python based code snippet for inference for every example we have.

**Comment by alvarobartt** [comment]
@harshbafna ok then! I'll probably start off with `image_segmenter` and `image_classifier` Python examples as those are the ones I'm more familiar with. Anyway I'll try to develop a simple Python snippet plus a minimal explanation for every example!

Then should I get this issue assigned? Thanks!

**Comment by harshbafna** [comment]
@alvarobartt: Any updates on this?

**Comment by alvarobartt** [comment]
Sure @harshbafna I'm working on it, I'll prepare the README with a fully working Python example for Image Segmentation and Image Classification too! I'll do it before the year ends! 🔥

**Comment by alvarobartt** [comment]
@harshbafna Here I attach the first example, just let me know if you like the content and the formatting of the example and I'll create one example per different model (starting with the image models).

https://github.com/alvarobartt/serve/tree/python_examples/examples/image_segmenter/README.md

**Comment by harshbafna** [comment]
@alvarobartt: We don't really need the documentation to be so elaborate and generic. We should simply have another example of through python's request module to send an HTTP request to the model as an alternative to the curl request example we already have.

**Comment by harshbafna** [comment]
Something similar to what we have here:

https://github.com/pytorch/serve/tree/master/examples/text_to_speech_synthesizer#serve-the-waveglow-speech-synthesis-model-on-torchserve

**Comment by alvarobartt** [comment]
Oh cool I see! Then I'll do it later today 👍🏻 Thanks for the info

**Comment by cbasavaraj** [comment]
Hi, I have a use case where I need to send an image + a python dict (which is the output of another network). Here is what it looks like using `requests`:
```
        files = {'image': data['frame'].tobytes()}
        response = requests.post(TS_URL, files=files, data=data['text'])
```
Would it be possible to treat this case in the handler on the server side? And how? Thanks

**Comment by alvarobartt** [comment]
Sorry for taking too long @harshbafna! I've just updated the example at https://github.com/alvarobartt/serve/blob/python_examples/examples/image_segmenter/README.md following the pattern you requested, let me know if that looks OK to you and I'll apply it to the other examples so as to finally document the Python usage 👍🏻

**Comment by alvarobartt** [comment]
Hi @cbasavaraj, which handler are you using while generating the MAR? You can handle the format of the input data of the inference request on the handler, but you need to provide more details. 👍🏻

**Comment by msaroufim** [comment]
@opconty this is a nice example https://github.com/pytorch/serve/tree/master/examples/text_to_speech_synthesizer#serve-the-waveglow-speech-synthesis-model-on-torchserve

**Comment by opconty** [comment]
Thanks , and sorry for the late reply 
@msaroufim

**Comment by roomerjc** [comment]
Hi, below an example with `cv2.imencode`.

`import cv2
import requests

def im_encoder(path_to_image:str):
    """
    """
    im = cv2.imread(path_to_image)[:,:,::-1]
    _, x =cv2.imencode('.png', im,)
    
    return x.tobytes()
    

url_serve = 'http://localhost:8080/predictions/model_name'
header = {"content-type": "image/png"}
data  = im_encoder('image.png')


response = requests.put(url_serve, data=data, headers=header)
print(response.json())`
