### ISSUE TITLE
Ubuntu 20.04: Error: Could not find or load main class org.pytorch.serve.ModelServer

### ISSUE THREAD

**Issue by mightyroy** [pytorch/serve#766]
Installed torchserve with `pip install torchserve`

When I run the following example code:
```
torchserve --start --ncs --model-store model_store --models densenet161.mar
```
I got the following error:
```
Error: Could not find or load main class org.pytorch.serve.ModelServer
Caused by: java.lang.ClassNotFoundException: org.pytorch.serve.ModelServer
```

It seems like a recurring error reported several times in the past, with conda environment and in windows. I'm using Ubuntu 20.04. How can I fix the class path to solve the error?

**Comment by harshbafna** [comment]
@mightyroy: Please share the environment details as per the bug report template.

**Comment by mightyroy** [comment]
## Context
 Cannot start torchserve.

* torchserve version: TorchServe Version is 0.2.0
* torch version: 1.6.0
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version: openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9+11-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

* Operating System and version: Ubuntu 20.04

## Your Environment

* Installed using source? [yes/no]: installed from pip
* Are you planning to deploy it using docker container? [yes/no]: no
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: default handler
* What kind of model is it e.g. vision, text, audio?: Example densenet161 image classifier
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: local models from model-store
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: no log files generated in '/logs' folder.
The following lines in config.properties:
```
number_of_gpu=1
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
```

* Link to your project [if any]:

## Expected Behavior
Torchserve should start but didnt.


## Current Behavior
When I run the following example code:

`torchserve --start --ncs --model-store model_store --models densenet161.mar`

I got the following error:

```
Error: Could not find or load main class org.pytorch.serve.ModelServer
Caused by: java.lang.ClassNotFoundException: org.pytorch.serve.ModelServer
```



## Possible Solution
Set new class path so that ModelServer can be found, but I'd like to learn how to do it.


## Steps to Reproduce


1. On ubuntu 20.04 install torchserve with pip
2. run `torchserve --start --ncs --model-store model_store --models densenet161.mar`
...

## Failure Logs [if any]

**Comment by mightyroy** [comment]
I managed to fix it!!!
In the main torchserve folder, run the following to commands:
```
python setup.py build
python setup.py install
```
Then torchserve starts nicely with:
`torchserve --start --ncs --model-store model_store --models densenet161.mar`
