### ISSUE TITLE
Error running benchmark.py with the "--all" flag

### ISSUE THREAD

**Issue by jeremiahschung** [pytorch/serve#767]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

* torchserve version: 0.2.0
* torch version: 1.7.0
* torchvision version [if any]: 0.8.1
* Operating System and version: Ubuntu18.04

## Your Environment

* Installed using source? [yes/no]:no
* Are you planning to deploy it using docker container? [yes/no]:
* Is it a CPU or GPU environment?:GPU

## Expected Behavior
Running ` ./benchmark.py --all` should run all tests on all models. 

## Current Behavior

Option errors out due to the code compiling the list of tests incorrectly.
```
ubuntu@ip-172-31-26-87:~/serve/benchmarks$ ./benchmark.py --all --ts 127.0.0.1:8080 --management-port 8081

Running benchmark latency with model r
Traceback (most recent call last):
  File "./benchmark.py", line 491, in <module>
    run_benchmark()
  File "./benchmark.py", line 427, in run_benchmark
    res = getattr(Benchmarks, benchmark_name)()
  File "./benchmark.py", line 370, in latency
    plan, jmeter_args = parseModel()
  File "./benchmark.py", line 327, in parseModel
    'input_filepath': pargs.input[0]
TypeError: 'NoneType' object is not subscriptable
```
This is because the code is compiling the list of tests incorrectly due to the model name being used as a char list.

## Possible Solution

Fix the constant 
`ALL_BENCHMARKS = list(itertools.product(('latency', 'throughput'), (MODEL_RESNET_18)))`
-> 
`ALL_BENCHMARKS = list(itertools.product(('latency', 'throughput'), [MODEL_RESNET_18]))`

## Steps to Reproduce

1. Run `./benchmark.py --all`

## Failure Logs [if any]

Pasted above

**Comment by chauhang** [comment]
@jeremiahschung Please resolve the merge conflicts

**Comment by jeremiahschung** [comment]
Merge conflict resolved in [PR 768](https://github.com/pytorch/serve/pull/768)
