### ISSUE TITLE
JSON dumps slow

### ISSUE THREAD

**Issue by cbasavaraj** [pytorch/serve#769]
Hi, I'm trying to serve a detectron2 model. In fact, got it to work by more or less following the example posted here https://github.com/facebookresearch/detectron2/issues/1289
While it works fine for returning boxes + classes + scores, json.dumps is too slow for returning segmentation masks, which are per detection binary masks, each as big as the image resolution (720x1280 in my case). I could probably convert the masks into a different format (run-length encoding, for example).
But I also want to return detectron2 feature vectors (each of which is a 1x1024 float) for all the detections.
So my general question is, how to avoid using json dumps? Can we have some sort of a RPC, instead of having to use the REST API all the time?
Thanks.

**Comment by alvarobartt** [comment]
Just as a side note that may not answer your question but can be useful is that developers are already working on the gRPC support for TorchServe, you can find more details at https://github.com/pytorch/serve/pull/687

**Comment by cbasavaraj** [comment]
I've kinda fixed this using `orjson` instead of the standard `json` module. This alone reduced overall prediction time from 650 ms to 150 ms. I then used RLE instead of binary masks. This brought down pred time marginally to 120 ms.

**Comment by enjoykcc456** [comment]
Hi @cbasavaraj , do you mind sharing how you used RLE instead of binary masks? I am new to this, the model i tested was mask_rcnn_R_50_FPN_3x and it only returns pred_masks. Did you convert the masks to RLE? Thanks in advance.

**Comment by cbasavaraj** [comment]
Just need to use pycoco for RLE. Further need to convert the counts field to string datatype, else you get an error when you encode as json for returning from TorchServe.
```
from pycocotools import mask

def encode(masks):
    """RL Encode binary masks.

    Convert counts dtype from bytes to str.
    """
    rles = []
    for m in masks:
        rle = mask.encode(np.asfortranarray(m))
        rle['counts'] = rle['counts'].decode()
        rles.append(rle)
    return rles
```

**Comment by enjoykcc456** [comment]
Thanks @cbasavaraj , it is working now.
