### ISSUE TITLE
Hi, any suggestion on how to serve yolov5 on torchserve ?

### ISSUE THREAD

**Issue by yuanyuangoo** [pytorch/serve#779]
## Is your feature request related to a problem? Please describe.

I'd like to serve yolov5 model, but there is no template in the example.
## Describe the solution

serve model from https://github.com/ultralytics/yolov5/

**Comment by dhaniram-kshirsagar** [comment]
@yuanyuangoo You can use the following hints to deploy this model -

1. create torchscripted model using following from yolo repo. -
https://github.com/ultralytics/yolov5/issues/251

2. Create a custom handler -
https://github.com/ultralytics/yolov5/issues/36
https://github.com/pytorch/serve/blob/v0.2.0/docs/custom_service.md

3. Create torchscripted model MAR file -
https://github.com/pytorch/serve/tree/master/examples#creating-mar-file-for-torchscript-mode-model

4. Follow this guide to deploy the MAR file -
https://github.com/pytorch/serve/tree/v0.2.0#serve-a-model

**Comment by dhaniram-kshirsagar** [comment]
Closing as there is no response on this.

**Comment by abhinavanurag-garudaire** [comment]
HI . I have been facing the same error :500 worker died issue when deploying yolov8 using torchserve and sending requests using torchserve.Can anyone please help?the log files are just so large and showing too many error. It'd be better to have a full tutorial on yolo deployment using torchserve

**Comment by agunapal** [comment]
Hi @abhinavanurag-garudaire  @edworId  I tried running yolov8 in TorchServe,

The issue is happening here https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/__init__.py#L325
when trying to read settings.yaml

Its reading None . Not sure about the reason yet. Still looking into it.

It works fine with standalone yolov8

**Comment by agunapal** [comment]
@abhinavanurag-garudaire @edworId I have included the PR for YOLOv8. Please give it a try and let me know if this works.
