### ISSUE TITLE
ResNet-152 example code does suboptimal things with tensors and loops

### ISSUE THREAD

**Issue by fbbradheintz** [pytorch/serve#78]
In `examples/image_classifier/resnet_152_batch/resnet152_handler.py`, in the `preprocess()` and `postprocess()` methods, tensors are looped over and subtensors/elements are handled individually. This processing will probably be faster and take less code using tensor broadcasting semantics and a small amount of refactoring. I'll handle it when I have a little time.

**Comment by dhaniram-kshirsagar** [comment]
Being taken care by pr #432
