### ISSUE TITLE
Fix broken or dead links in docs

### ISSUE THREAD

**Issue by dhaniram-kshirsagar** [pytorch/serve#787]
The link checker for md files is showing the following problem -

ERROR: 1 dead links found!
[âœ–] tsutils.py.py â†’ Status: 400
##Broken links in file: scripts/Readme.md

ERROR: 1 dead links found!
[âœ–] https://torchserve-regression-test-gpu.s3.amazonaws.com/public/TS-NIGHTLY-REGRESSION-2020-07-10/tmp/test_exec.log â†’ Status: 403
##Broken links in file: test/README.md

ERROR: 6 dead links found!
[âœ–] ../ts/torch_handlers/image_classifier.py â†’ Status: 400
[âœ–] ../ts/torch_handlers/image_segmenter.py â†’ Status: 400
[âœ–] ../ts/torch_handlers/object_detector.py â†’ Status: 400
[âœ–] ../ts/torch_handlers/text_classifier.py â†’ Status: 400
[âœ–] ../ts/torch_handlers/base_handler.py â†’ Status: 400
[âœ–] ../examples/image_classifier/resnet_152_batch/resnet152_handler.py â†’ Status: 400
##Broken links in file: docs/custom_service.md

ERROR: 1 dead links found!
[âœ–] ../examples/image_classifier/resnet_152_batch/resnet152_handler.py â†’ Status: 400
##Broken links in file: docs/batch_inference_with_ts.md

ERROR: 1 dead links found!
[âœ–] https://github.com/pytorch/serve/tree/master/torchserve_sanity.py â†’ Status: 404
##Broken links in file: docs/default_handlers.md

ERROR: 2 dead links found!
[âœ–] http://localhost:9090/ â†’ Status: 0
[âœ–] http://localhost:3000/ â†’ Status: 0
##Broken links in file: docs/metrics_api.md

ERROR: 2 dead links found!
[âœ–] https://s3.amazonaws.com/&quot; â†’ Status: 400
[âœ–] https://torchserve.pytorch.org/&quot; â†’ Status: 403
##Broken links in file: docs/configuration.md

ERROR: 1 dead links found!
[âœ–] http://your.grafana.elb.us-west-2.elb.amazonaws.com:3000 â†’ Status: 0
##Broken links in file: kubernetes/README.md

ERROR: 2 dead links found!
[âœ–] NewTestPlan.md â†’ Status: 400
[âœ–] https://torchserve.pytorch.org/mar_files/squeezenet1_1.mar&quot; â†’ Status: 403
##Broken links in file: benchmarks/README.md

**Comment by harshbafna** [comment]
Changes covered in fix for #561

**Comment by lokeshgupta1975** [comment]
@harshbafna can we verify and close this issue?

**Comment by harshbafna** [comment]
@lokeshgupta1975: We are waiting for #561  to get merged.
