### ISSUE TITLE
Avoid reading GPU ID from properties for RR worker assignment

### ISSUE THREAD

**Issue by mycpuorg** [pytorch/serve#79]
https://github.com/pytorch/serve/issues/71
mentioned about assigning [GPU ID from properties](https://github.com/pytorch/serve/issues/71#issuecomment-594068814) explicitly which will work.
However, this will require end user to know the number of GPU devices present on an instance prior to assigning.

https://github.com/pytorch/serve/issues/71#issuecomment-591561184 should suffice IMO. Please look into this. Thanks.

**Comment by harshbafna** [comment]
The frontend layers selects the GPU device in a round robin fashion and passes the device ID on to the backend handler where user can use it to initialize the torch.device object with specified GPU ID.

The details for handling model execution is already documented [here](https://github.com/pytorch/serve/blob/master/docs/custom_service.md#handling-model-execution-on-multiple-gpus).

**Comment by ozancaglayan** [comment]
Hi there,

Lookin at this for some time and I think it is still super obscure where that `gpu_id` parameter should come from. Is that even possible that we deploy two models, one on `cpu` and the other one on `cuda:0`? Do we set this param from the `config.properties` file's `models=` section?
