### ISSUE TITLE
Pytorch website Docs link broken

### ISSUE THREAD

**Issue by misrasaurabh1** [pytorch/serve#792]
If you go to https://pytorch.org/ecosystem/ and then click on Docs on the topbar and select TorchServe it leads to a deadlink 
![image](https://user-images.githubusercontent.com/1271289/99758082-aa4bd900-2aa5-11eb-8c25-dab9eda87435.png)

The link it tries to take us to is https://pytorch.org/ecosystem/serve which is dead.

**Comment by msaroufim** [comment]
This seems to have been fixed so closing

![Screen Shot 2021-04-14 at 11 17 57 AM](https://user-images.githubusercontent.com/3282513/114759488-13611100-9d13-11eb-9e77-268ce7456b95.png)
