### ISSUE TITLE
Documentaion and sanity testing issues

### ISSUE THREAD

**Issue by maaquib** [pytorch/serve#801]
* Running `python ./ts_scripts/install_from_src.py && python ./torchserve_sanity.py` on a fresh EC2 instance (Ubuntu 18.04) throws exception due to missing dependencies not installed in `install_from_src.py`

```
## In directory: /home/ubuntu/serve | Executing command: pylint -rn --rcfile=./ts/tests/pylintrc ts/.
sh: 1: pylint: not found
...
## TorchServe Linting Failed !
```

* We should verify that the versions of Java, Python and Pip are correct before running `ts_scripts/install_from_src.py`

* Looking at the [readme](https://github.com/pytorch/serve/#install-torchserve) it is not clear right now whether `Install Java 11` and `Install python pre-requisite packages` are also prerequisites for `Install TorchServe for development`

* Verify that re-running `ts_scripts/install_from_src.py` and other scripts multiple times doesn't break the tests

**Comment by chauhang** [comment]
Additionally please see: https://github.com/pytorch/serve/issues/797#issuecomment-733920793

**Comment by dhaniram-kshirsagar** [comment]
@maaquib Could you please share logs for this. Assuming these are not EC2 DLAMI instances. 
NOTE Our observation, on **non**-DLAMI nodes, the python site-packages are not accessible and hence our dependencies gets installed under `~/.local/...`.

**Comment by dhaniram-kshirsagar** [comment]
> Additionally please see: [#797 (comment)](https://github.com/pytorch/serve/issues/797#issuecomment-733920793)

Commented on #797

**Comment by maaquib** [comment]
> @maaquib Could you please share logs for this. Assuming these are not EC2 DLAMI instances.
> NOTE Our observation, on **non**-DLAMI nodes, the python site-packages are not accessible and hence our dependencies gets installed under `~/.local/...`.

This was a barebones EC2 instance, not DL AMI

**Comment by harshbafna** [comment]
Documentation has been updated as part of #836. Closing.
