### ISSUE TITLE
Proper dev/test environment instructions

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#802]
Please add proper documented steps for Contributors for setting up development environment and how to run the tests for the different components:

1. Steps for development environment setup including all the dev/test environment dependencies for running the tests (eg pytest)
2. Steps for install from source, that work properly on reinstalling from source as well
3. Steps for running the tests for: Frontend, TorchServe, ModelArchiver, Sanity tests, E2E regression tests

**Comment by lokeshgupta1975** [comment]
@dhaniram-kshirsagar Can you go through the latest documentation and make sure that following the documented steps, contributors will be able to do what @chauhang has mentioned in her note above?

**Comment by harshbafna** [comment]
The instructions have been streamlined and now merged to master as part of #836 . Closing
