### ISSUE TITLE
Pip install support for windows

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#804]
Publish the wheel files for pip install for native windows. Current [Native windows install steps](https://github.com/pytorch/serve/blob/master/docs/torchserve_on_win_native.md#install-from-binaries) ask user's to create the files and install

**Comment by lokeshgupta1975** [comment]
Binaries for Windows to be published for this release, Eli should do this once we are done with the release branch being stable. @chauhang Can you give a heads up to @seemethere

**Comment by lokeshgupta1975** [comment]
@harshbafna  will check whether the windows binaries and all other binaries are getting generated and will do some basic sanity testing with the binaries.

**Comment by lokeshgupta1975** [comment]
@harshbafna Can you confirm whether you are able to generate all the required binaries for publishing as well as basic testing with these binaries has been done?

**Comment by harshbafna** [comment]
@lokeshgupta1975: We have validated the scripts are in good shape and were able to generate the required binaries for `pip` and `conda`.

We did some basic testing on Ubuntu DLAMI, Local Mac, and Windows 10 Pro on Azure.

There were minor doc updates required which have been done in #869

**Comment by harshbafna** [comment]
Closing as the wheels have been published.
