### ISSUE TITLE
Passing multiple(variable) input images to the handler via curl

### ISSUE THREAD

**Issue by anustupc** [pytorch/serve#805]
Hello,

I am trying to pass multiple images using a custom handler that I build. I understand that in order to pass a single image during inference I have to give the command as follows: curl localhost:8080/predictions/<model> -F "data=@image1.jpg"

On looking online, I found that in order to give multiple images, I need to give it as an array as follows: curl localhost:8080/predictions/<model> -F "data[]=@image1.jpg" -F "data[]=@image2.jpg"
However, that doesn't seem to work. The dictionary containing the data just has a single key with the name as data[] (containing information of image2.jpg) instead of it being an array containing information about both image1.jpg and image2.jpg.

Any thoughts regarding how I can pass a variable number of images to the handler using an array? 

Thanks

**Comment by harshbafna** [comment]
@anustupc: Please refer to the following comment :

https://github.com/pytorch/serve/issues/529#issuecomment-658012913

**Comment by anustupc** [comment]
Hi @harshbafna ,
Thanks for your reply. I understand that it can be done by giving a different key value for each image. I was wondering if it is possible to pass everything as elements of one list. If not, the solution as stated right now should work for me (for now).

**Comment by harshbafna** [comment]
@anustupc 

you could use the -d flag of curl command as follows:
```
-d '["data1", "data2", "data3"]'
```

**Comment by anustupc** [comment]
Thanks for your suggestion @harshbafna . I haven't really tested the -d option but I can make do with using multiple names with -F. I think we can close this for now and if need be reopen it later.
