### ISSUE TITLE
SageMaker support for gpu and cpu dockerfiles

### ISSUE THREAD

**Issue by adityabindal** [pytorch/serve#81]
Update cpu and gpu dockerfiles so that Docker Images work on SageMaker (eg add SageMaker inference toolkit)

**Comment by harshitmalik03** [comment]
Hey can u help me with this one ?

**Comment by msaroufim** [comment]
Did this work for you? https://aws.amazon.com/blogs/awsmarketplace/using-torchserve-to-list-pytorch-models-at-scale-in-aws-marketplace/

And if not please let me know what the issue was and I can help
