### ISSUE TITLE
Serve installation fails on SageMaker Notebook and Cloud9

### ISSUE THREAD

**Issue by C24IO** [pytorch/serve#83]
Following steps in Readme and the following errors occur - environment is Cloud9 and Amazon SageMaker Notebooks.
`
(venv) chzar:~/environment/serve/serve-setup/serve (master) $ pip install .
Processing /home/ec2-user/environment/serve/serve-setup/serve
Requirement already satisfied: Pillow in /home/ec2-user/environment/serve/serve-setup/venv/lib/python3.6/dist-packages (from torchserve==0.0.1b20200308) (7.0.0)
Collecting psutil (from torchserve==0.0.1b20200308)
  Downloading https://files.pythonhosted.org/packages/c4/b8/3512f0e93e0db23a71d82485ba256071ebef99b227351f0f5540f744af41/psutil-5.7.0.tar.gz (449kB)
    100% |████████████████████████████████| 450kB 20.8MB/s 
Collecting future (from torchserve==0.0.1b20200308)
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 21.7MB/s 
Requirement already satisfied: torch in /home/ec2-user/environment/serve/serve-setup/venv/lib/python3.6/dist-packages (from torchserve==0.0.1b20200308) (1.4.0)
Requirement already satisfied: torchvision in /home/ec2-user/environment/serve/serve-setup/venv/lib/python3.6/dist-packages (from torchserve==0.0.1b20200308) (0.5.0)
Collecting torchtext (from torchserve==0.0.1b20200308)
  Downloading https://files.pythonhosted.org/packages/79/ef/54b8da26f37787f5c670ae2199329e7dccf195c060b25628d99e587dac51/torchtext-0.5.0-py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 23.4MB/s 
Requirement already satisfied: six in /home/ec2-user/environment/serve/serve-setup/venv/lib/python3.6/dist-packages (from torchvision->torchserve==0.0.1b20200308) (1.14.0)
Requirement already satisfied: numpy in /home/ec2-user/environment/serve/serve-setup/venv/lib/python3.6/dist-packages (from torchvision->torchserve==0.0.1b20200308) (1.18.1)
Collecting sentencepiece (from torchtext->torchserve==0.0.1b20200308)
  Downloading https://files.pythonhosted.org/packages/74/f4/2d5214cbf13d06e7cb2c20d84115ca25b53ea76fa1f0ade0e3c9749de214/sentencepiece-0.1.85-cp36-cp36m-manylinux1_x86_64.whl (1.0MB)
    100% |████████████████████████████████| 1.0MB 21.5MB/s 
Collecting requests (from torchtext->torchserve==0.0.1b20200308)
  Downloading https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 23.7MB/s 
Collecting tqdm (from torchtext->torchserve==0.0.1b20200308)
  Downloading https://files.pythonhosted.org/packages/47/55/fd9170ba08a1a64a18a7f8a18f088037316f2a41be04d2fe6ece5a653e8f/tqdm-4.43.0-py2.py3-none-any.whl (59kB)
    100% |████████████████████████████████| 61kB 24.2MB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->torchtext->torchserve==0.0.1b20200308)
  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 32.5MB/s 
Collecting certifi>=2017.4.17 (from requests->torchtext->torchserve==0.0.1b20200308)
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 31.7MB/s 
Collecting chardet<4,>=3.0.2 (from requests->torchtext->torchserve==0.0.1b20200308)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 32.0MB/s 
Collecting idna<3,>=2.5 (from requests->torchtext->torchserve==0.0.1b20200308)
  Downloading https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 26.6MB/s 
Installing collected packages: psutil, future, sentencepiece, urllib3, certifi, chardet, idna, requests, tqdm, torchtext, torchserve
  Running setup.py install for psutil ... done
  Running setup.py install for future ... done
  Running setup.py install for torchserve ... error
    Complete output from command /home/ec2-user/environment/serve/serve-setup/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-lpcdwxb3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3aonh65v/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/environment/serve/serve-setup/venv/include/site/python3.6/torchserve:
    running install
    running build
    running build_py
    running build_frontend
    Downloading https://services.gradle.org/distributions/gradle-4.9-bin.zip
    ........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
    Unzipping /home/ec2-user/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t/gradle-4.9-bin.zip to /home/ec2-user/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t
    Set executable permissions for: /home/ec2-user/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t/gradle-4.9/bin/gradle
    
    Welcome to Gradle 4.9!
    
    Here are the highlights of this release:
     - Experimental APIs for creating and configuring tasks lazily
     - Pass arguments to JavaExec via CLI
     - Auxiliary publication dependency support for multi-project builds
     - Improved dependency insight report
    
    For more details see https://docs.gradle.org/4.9/release-notes.html
    
    Starting a Gradle Daemon (subsequent builds will be faster)
    Download https://plugins.gradle.org/m2/com/google/googlejavaformat/google-java-format/1.6/google-java-format-1.6.pom
    Download https://plugins.gradle.org/m2/com/google/googlejavaformat/google-java-format-parent/1.6/google-java-format-parent-1.6.pom
    Download https://plugins.gradle.org/m2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
    Download https://plugins.gradle.org/m2/com/google/guava/guava/22.0/guava-22.0.pom
    Download https://plugins.gradle.org/m2/com/google/guava/guava-parent/22.0/guava-parent-22.0.pom
    Download https://plugins.gradle.org/m2/com/google/errorprone/javac-shaded/9+181-r4173-1/javac-shaded-9+181-r4173-1.pom
    Download https://plugins.gradle.org/m2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.pom
    Download https://plugins.gradle.org/m2/com/google/errorprone/error_prone_annotations/2.0.18/error_prone_annotations-2.0.18.pom
    Download https://plugins.gradle.org/m2/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.pom
    Download https://plugins.gradle.org/m2/com/google/errorprone/error_prone_parent/2.0.18/error_prone_parent-2.0.18.pom
    Download https://plugins.gradle.org/m2/org/codehaus/mojo/animal-sniffer-parent/1.14/animal-sniffer-parent-1.14.pom
    Download https://plugins.gradle.org/m2/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.pom
    Download https://plugins.gradle.org/m2/org/codehaus/mojo/mojo-parent/34/mojo-parent-34.pom
    Download https://plugins.gradle.org/m2/org/codehaus/codehaus-parent/4/codehaus-parent-4.pom
    Download https://plugins.gradle.org/m2/com/google/guava/guava/22.0/guava-22.0.jar
    Download https://plugins.gradle.org/m2/com/google/googlejavaformat/google-java-format/1.6/google-java-format-1.6.jar
    Download https://plugins.gradle.org/m2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
    Download https://plugins.gradle.org/m2/com/google/errorprone/error_prone_annotations/2.0.18/error_prone_annotations-2.0.18.jar
    Download https://plugins.gradle.org/m2/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
    Download https://plugins.gradle.org/m2/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
    Download https://plugins.gradle.org/m2/com/google/errorprone/javac-shaded/9+181-r4173-1/javac-shaded-9+181-r4173-1.jar
    
    FAILURE: Build failed with an exception.
    
    * Where:
    Build file '/tmp/pip-req-build-lpcdwxb3/frontend/build.gradle' line: 28
    
    * What went wrong:
    A problem occurred evaluating root project 'frontend'.
    > Could not open dsl remapped class cache for 4116txk5uyl7fsx1ml41gcwgu (/home/ec2-user/.gradle/caches/4.9/scripts-remapped/formatter_8g1qvyqrv7q4wxxey9do0wgaw/4116txk5uyl7fsx1ml41gcwgu/dsl1724d65be2ee623103b4c593e57fc0c5).
       > Could not open dsl generic class cache for script '/tmp/pip-req-build-lpcdwxb3/frontend/tools/gradle/formatter.gradle' (/home/ec2-user/.gradle/caches/4.9/scripts/4116txk5uyl7fsx1ml41gcwgu/dsl/dsl1724d65be2ee623103b4c593e57fc0c5).
          > com/google/googlejavaformat/java/Main : Unsupported major.minor version 52.0
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
    Use '--warning-mode all' to show the individual deprecation warnings.
    See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings
    
    BUILD FAILED in 13s
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-lpcdwxb3/setup.py", line 160, in <module>
        license='Apache License Version 2.0'
      File "/home/ec2-user/environment/serve/serve-setup/venv/lib64/python3.6/dist-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/ec2-user/environment/serve/serve-setup/venv/lib64/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 593, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-lpcdwxb3/setup.py", line 98, in run
        self.run_command('build_frontend')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-lpcdwxb3/setup.py", line 85, in run
        subprocess.check_call('frontend/gradlew -p frontend clean build', shell=True)
      File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'frontend/gradlew -p frontend clean build' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/home/ec2-user/environment/serve/serve-setup/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-lpcdwxb3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3aonh65v/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/environment/serve/serve-setup/venv/include/site/python3.6/torchserve" failed with error code 1 in /tmp/pip-req-build-lpcdwxb3/
You are using pip version 18.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`

**Comment by lokeshgupta1975** [comment]
@C24IO Can this be closed now?

**Comment by maaquib** [comment]
@C24IO Closing this. Please re-open if you are still running into this issue on the latest release
