### ISSUE TITLE
Failing to install the Nvidia plugin  on EKS 

### ISSUE THREAD

**Issue by HamidShojanazeri** [pytorch/serve#831]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

* torchserve version: 0.2.1
* torch version:1.6.0
* torchvision version [if any]:0.7.0
* Operating System and version:ubuntu 18.04 

## Your Environment
* Installed using source? [yes/no]:no
* Are you planning to deploy it using docker container? [yes/no]:
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]:
* What kind of model is it e.g. vision, text, audio?:
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Current Behavior 
Following the EKS doc, the command for installing the nvidia plugin to run GPU enabled containers fails. However, when checking the resource using kubectl get service,po,daemonset,pv,pvc --all-namespaces,  it seems is existing there but helm list return nothing.

Also, the 
the url in `helm repo add stable https://kubernetes-charts.storage.googleapis.com 
` seem needs to be changed to "https://charts.helm.sh/stable"
## Steps to Reproduce
Following EKS doc, on EC2 instance, Ubuntu 18.04 DLAMI.

## Failure Logs [if any]
[error.logs.txt](https://github.com/pytorch/serve/files/5640933/error.logs.txt)

**Comment by jagadeeshi2i** [comment]
Please use nvidia plugin version `0.7.1`.
