### ISSUE TITLE
Add version check for python for install with source

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#834]
Install with source scripts fail on machines with python 2.x with a cryptic error message: 

```
python ./ts_scripts/install_from_src.py
  File "./ts_scripts/install_from_src.py", line 20
    print(f"## In directory: {os.getcwd()} | Executing command: {cmd}")
```

Add a version check in the install script and print helpful for the users to upgrade to python3 for running the scripts

**Comment by harshbafna** [comment]
This has been added as part of #836. Closing.
