### ISSUE TITLE
Log date and environment info in the regression test logs

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#847]
The regression tests in the "tests" folder should log the date on which test was run, along with full environment details to verify when and on which configuration the tests were run. You can start by simply adding output of `python -m torch.utils.collect_env` for the environment logging till we have proper sol implemented by #833

**Comment by lokeshgupta1975** [comment]
@lxning Can you update the issue and link your fix PR to it?

**Comment by lxning** [comment]
https://github.com/pytorch/serve/pull/865
