### ISSUE TITLE
Regression tests "Latest logs" and "Test Logs by date" showing old logs

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#848]
The "Test Logs by date" on the [tests](https://github.com/pytorch/serve/tree/master/test) page are showing logs of very old date. 

Same issue started coming for the main logs as well from the "Latest Test Logs : CPU / GPU / Windows" (all these logs are of Dec 3rd  with errors as below using the old .sh version of the scripts: 

> TS Branch :  master
> TS Branch Commit Id :  78eeaa74fe460fd5adb09462d26c29fba6b1b63f
> Build date :  Thu Dec  3 15:50:22 UTC 2020
> ./test/regression_tests.sh: line 131: newman: command not found
> ./test/regression_tests.sh: line 139: newman: command not found
> ./test/regression_tests.sh: line 146: newman: command not found
> ./test/regression_tests.sh: line 154: newman: command not found

Please fix:

1. Verify the latest scripts (.py) version are being used for the tests
2. Link logs of latest run date for each item for both the "latest" logs and "test logs by date"
3. For Windows add links for both CPU and GPU logs

**Comment by lokeshgupta1975** [comment]
@dhanainme Can you update this issue, link your PR to it and close it if this has been verified?

**Comment by maaquib** [comment]
Fixed as part of https://github.com/pytorch/serve/pull/852
