### ISSUE TITLE
ModuleNotFoundError: No module named 'pygit2' on running install_from_src.py

### ISSUE THREAD

**Issue by abishekchiffon** [pytorch/serve#850]
## Context
On running install_from_src,  I get the following error.
Traceback (most recent call last):
  File "ts_scripts/install_from_src.py", line 62, in <module>
    from pygit2 import Repository
ModuleNotFoundError: No module named 'pygit2'

* java version: openjdk 11.0.9.1
* Operating System and version: ubuntu  20.04
* This is run on ec2 t3xlarge instace with intel x64

## Your Environment

* Installed using source? [yes/no]: yes
* Is it a CPU or GPU environment?: CPU 

## Expected Behavior
Install_from_src should install the torchserve after running python3 ts_scripts/install_dependencies.py

## Steps to Reproduce
1. python ts_scripts/install_dependencies.py
2.python3 ts_scripts/install_from_src.py

## Log
[log of install_dependency](https://github.com/pytorch/serve/files/5666262/ec2_install_from_src_fail.log)

**Comment by harshbafna** [comment]
@abishekchiffon : As per the updated instructions you need to run following command for installing dependencies in dev environment

```
python ./ts_scripts/install_dependencies.py --environment=dev
```

Documentaion : https://github.com/pytorch/serve#install-torchserve-for-development

By default `install_dependencies.py` installs only production specific dependencies.

**Comment by harshbafna** [comment]
Closing as per feedback from OP over slack.
