### ISSUE TITLE
Difference in docker image size

### ISSUE THREAD

**Issue by ladanisavan** [pytorch/serve#870]
Why there is huge difference in docker image size between official dockerhub (https://hub.docker.com/r/pytorch/torchserve) and build using ./build_image.sh? 
from dockerhub: pytorch/torchserve:latest-gpu =  3.42GB
build by build_image.sh: pytorch/torchserve:latest-gpu =  5.68GB

**Comment by maaquib** [comment]
@ladanisavan Are you building from master? We have added stuff since the last release v0.2.0 on dockerhub

**Comment by ladanisavan** [comment]
> @ladanisavan Are you building from master? We have added stuff since the last release v0.2.0 on dockerhub

Yes I have built image from master for Production and GPU (./build_image.sh -g)
