### ISSUE TITLE
Frontent sanity test failures on lower memory instances

### ISSUE THREAD

**Issue by jeremiahschung** [pytorch/serve#878]
## Context

* torchserve version: installed from source
* torch-model-archiver version: installed from source
* torch version: 1.6.0
* torchvision version [if any]: 0.7.0
* torchtext version [if any]:
* torchaudio version [if any]:
* java version: openjdk11
* Operating System and version: Ubuntu 18.04

## Your Environment

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: no
* Is it a CPU or GPU environment?: CPU

## Expected Behavior

The torchserve_sanity.py script succeeds.

## Current Behavior

On smaller EC2 instances, the sanity test is failing with the following error:
```
BUILD FAILED in 9m 20s
28 actionable tasks: 26 executed, 2 up-to-date
## Stopping TorchServe
## In directory: /home/ubuntu/serve | Executing command: torchserve --stop
TorchServe is not currently running.
## Successfully stopped TorchServe
## Frontend Gradle Tests Failed !
```

The tests failed on t2.medium (4G RAM) and t2.large (8G RAM) instances whereas it succeeded on a t2.xlarge (16G RAM) and t2.2xlarge (32G RAM) instance. The issue may to be related to the RAM available on the instance running the script.
[1211_master_ubuntu_sanity_t2m_fail.txt](https://github.com/pytorch/serve/files/5682138/1211_master_ubuntu_sanity_t2m_fail.txt)
[1211_master_ubuntu_sanity_t2m_fail.txt](https://github.com/pytorch/serve/files/5682139/1211_master_ubuntu_sanity_t2m_fail.txt)
[1211_master_ubuntu_sanity_t2xl_success.txt](https://github.com/pytorch/serve/files/5682140/1211_master_ubuntu_sanity_t2xl_success.txt)

## Steps to Reproduce

1. Start a new EC2 instance with less than 8G of RAM. (e.g. t2.medium)
2. Install the dev dependencies `python ts_scripts/install_dependencies.py environment=dev`
3. Install code from source `python ts_scripts/install_from_src.py`
4. Run the sanity check script and observe some tests fail `python torchserve_sanity.py`

## Failure Logs [if any]

See above.

**Comment by harshbafna** [comment]
This is more to do with a lower number of cores on the machine, a similar error is observed randomly while running the frontend Gradle build on a g4dn.xl instance which has 4 cores and 16G RAM

**Comment by msaroufim** [comment]
Tagging as won't fix for now - recommendation is to use a machine with at least 8 cores
