### ISSUE TITLE
Create Production deployment AWS Cloudformation template for TorchServe

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#88]
For Production deployment of TorchServe, provide AWS Cloudformation templates that support following configurations:

- [x] Simple EC2 deployment
- [ ] Sagemaker deployment with autoscaling
- [ ] K8s/EKS deployment with autoscaling 

Each of the production deployment templates should include configuration with:

- TorchServe inference node(s)
- TorchServe Model management node
- NGINX loadbalancer
- Metrics collection node - Statsd/Prometheus/CloudWatch
- Visualization Dashboard for metrics - Cloudwatch dashboard / Grafana
- Log aggregation on CloudWatch/Fluentd (or similar) 
- Secure deployment option using HTTPS 
- Option to select CPU or GPU deployment for the Inference nodes (this could be a parameter to select AWS instance type for the Inference nodes).

**Comment by lokeshgupta1975** [comment]
@maaquib Can you please provide updates here on this one?

**Comment by maaquib** [comment]
Adding additional items that need to be incorporated in next release v0.2.0
* Use optimal AMI for production deployment
* Use a standard install scripts for cloudwatch agent, cfn-init and torchserve
