### ISSUE TITLE
Unable to run install_dependencies.py in ec2 instance

### ISSUE THREAD

**Issue by abishekchiffon** [pytorch/serve#883]
## Context

Facing Install dependencies issues - gcc error(present in the logs). 

* java version: openjdk 11.0.9.1 2020-11-04
* Operating System and version: Ubuntu 18.04.5 LTS

## Your Environment
Ubuntu Server 18.04 LTS (HVM), SSD Volume Type - ami-0ac73f33a1888c64a (64-bit x86)

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: no
* Is it a CPU or GPU environment?: cpu

## Steps to Reproduce

I created a new C5.4xlarge ec2 instance and performed the below sequence of steps 

1) Created a new conda environment with Python Version 3.8
2) Ran the install dependencies script without sudo command : gave a  GCC error(available in the logs)
3) Ran the install dependencies script with sudo command : no error
4) Ran the install from source script without sudo command - after Step 3, unable to import pygit2 module.
5) Installed the pygit module
6) Ran the install from source script with sudo command: Didn't work. 

...

## Failure Logs [if any]
[ec2_master_installation_issues.log](https://github.com/pytorch/serve/files/5682640/ec2_master_installation_issues.log)

**Comment by harshbafna** [comment]
@abishekchiffon : It looks like gcc is outdated on your instance. I couldn't find the ami id provided above.

<img width="1427" alt="Screen Shot 2020-12-12 at 1 37 15 PM" src="https://user-images.githubusercontent.com/26594595/101979194-f2af7e80-3c80-11eb-95da-90400335930b.png">

<img width="1440" alt="Screen Shot 2020-12-12 at 1 55 08 PM" src="https://user-images.githubusercontent.com/26594595/101979273-bd576080-3c81-11eb-91bc-7b35431c4f86.png">

**Comment by abishekchiffon** [comment]
[ec2_torch_env.log](https://github.com/pytorch/serve/files/5682769/ec2_torch_env.log)

Hi @harshbafna , please find attached the env details of the ec2 instance.

**Comment by maaquib** [comment]
Looks like this was resolved. @abishekchiffon Please reopen if this is still an issue
