### ISSUE TITLE
Unable to start Torchserve

### ISSUE THREAD

**Issue by abishekchiffon** [pytorch/serve#884]
## Context
I installed the dependencies script and installed from source after which I started the Torchserve and encountered Native io exception java error.

* torchserve version: 0.3.0
* model archiver version: 0.2.1
* torch version:1.7.1
* torchvision version [if any]: 0.8.2
* torchtext version [if any]:0.8.1
* torchaudio version [if any]:0.7.2
* java version: openjdk 11.0.5 2019-10-15
* Operating System and version:
Ubuntu, 16.04

## Your Environment
[local_env_master_details.log](https://github.com/pytorch/serve/files/5682690/local_env_master_details.log)

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: No
* Is it a CPU or GPU environment?: CPU

## Steps to Reproduce

1. Ran Install Dependencies script
2. Ran the Install from source script
3. Started Torchserve by using the below command:
"torchserve --start --ncs --model-store model_store"

## Failure Logs [if any]

[local_master_torchserve.log](https://github.com/pytorch/serve/files/5682691/local_master_torchserve.log)

**Comment by harshbafna** [comment]
@abishekchiffon: From the shared logs it's clear that the ports required by TorchServe are already in use. It was able to bind to 8080/81/82 REST API default ports but failed while trying to bind the gRPC default ports 7070/71 with `Address already in use` error.

**Comment by abishekchiffon** [comment]
@harshbafna 
```
sudo netstat -ltnp | grep -w ':7071' 
sudo netstat -ltnp | grep -w ':7070' 
```
The above two command don't list anything.

**Comment by abishekchiffon** [comment]
[local_torch_env.log](https://github.com/pytorch/serve/files/5682768/local_torch_env.log)

Hi @harshbafna , please find the env details in this log attached for my local.

**Comment by maaquib** [comment]
Looks like this was resolved. @abishekchiffon Please reopen if this is still an issue
