### ISSUE TITLE
Dockerfile should not embed model/config file

### ISSUE THREAD

**Issue by dennybritz** [pytorch/serve#89]
The current Dockerfile requires the `resnet-18.mar` model and has a hard-coded configuration. Users could change this and build their own image with their own model.

But end-users probably don't want to build and push their own Docker images just to change the model. Instead, there should be a ready-to-use image that can be configured with a custom model and config file.

This is as easy as removing the `COPY` lines from the Dockerfile and asking the user to mount these instead. They shouldn't be copied into the image. This will make the image smaller too.

In addition, it would be nice if there was a way to configure the service via pure env vars. Dealing with and versioning config files in production is often a pain. It could be something like a `TS_CONFIG_STR` env var, or prefixes slike `TS_CONFIG_inference_address=http://0.0.0.0:8080` - I've seen both approaches being used in various other projects, like open source databases.

**Comment by harshbafna** [comment]
- The dependency for `resnet-18` mar file has been removed from the [docker files](https://github.com/pytorch/serve/tree/master/docker)
 - `TorchServe` already supports configurations through environment variables. However, user needs to set `enable_env_vars` parameter to true in config.properties. For more details on config parameters configurable through environment variables refer [configuration doc](https://github.com/pytorch/serve/blob/master/docs/configuration.md#other-properties)
 - Keeping the existing `config.properties` is good to have for `dev` docker images, where user can pre-configure the `TorchServe` as per their branch and/or test requirements.

**Comment by maaquib** [comment]
@dennybritz Based on the comments from @harshbafna , I am resolving this. Please reopen if necessary
