### ISSUE TITLE
Deploy TorchServe using Helm Charts fails for MNIST example in EKS

### ISSUE THREAD

**Issue by HamidShojanazeri** [pytorch/serve#895]
## Context
Following the EKS doc, deploying torchserve with hellm charts, checking the ts logs mnist example failed with the error: 'MNISTDigitClassifier' object has no attribute 'handle'. Removing mnist from config.properties, squeezenet worked fine, replacing mnist with densenet also worked fine. Logs are attached. 

* torchserve version: 0.3.0b20201214
* torch-model-archiver version: 0.2.1b20201214
* torch version:1.7
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
* Operating System and version:ubuntu 18.04

## Your Environment

* Installed using source? [yes/no]:
* Are you planning to deploy it using docker container? [yes/no]:
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]:
* What kind of model is it e.g. vision, text, audio?: vision 
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Expected Behavior
register the model

## Current Behavior
model registration fails with error:
'MNISTDigitClassifier' object has no attribute 'handle'

## Steps to Reproduce

Following EKS doc on ubuntu 18.04, EC2 gpu instance (cluster , p2.xlarge)

## Failure Logs [if any]

Logs include the error of mnist, removing the mnist and running squeezenet fine. Logs of replacing the mnist with densent.
[EKS_logs_gpu_mnist_failed_squeezenet_worked.logs.txt](https://github.com/pytorch/serve/files/5686859/EKS_logs_gpu_mnist_failed_squeezenet_worked.logs.txt)
[Rpelacing_mnist_with_densent_working.logs.txt](https://github.com/pytorch/serve/files/5686860/Rpelacing_mnist_with_densent_working.logs.txt)

**Comment by harshbafna** [comment]
@HamidShojanazeri : Could you please try with https://torchserve.s3.amazonaws.com/mar_files/mnist_v2.mar. This is the referenced mar for mnist model in our model zoo as well.

**Comment by chauhang** [comment]
@harshbafna Please update the readme in the EKS install steps which is still pointing to the old paths. Also please verify the links of all the Model Zoo mar files

**Comment by HamidShojanazeri** [comment]
@harshbafna sure, I will try and update.

**Comment by harshbafna** [comment]
@chauhang : Created #897

**Comment by HamidShojanazeri** [comment]
@harshbafna Still getting the same error, please check the logs.

[Mnist_fails_new_url.logs.txt](https://github.com/pytorch/serve/files/5687251/Mnist_fails_new_url.logs.txt)

**Comment by harshbafna** [comment]
@HamidShojanazeri: I looked at the logs, the TorchServe version is `0.1.1`. You might want to use the Torchserve docker image built from source.

Also, the `torchserve:latest-gpu` image looks outdated on the docker hub (6 months old).

**Comment by HamidShojanazeri** [comment]
@harshbafna my understanding is the issue should be from the image. I will give it a try.

**Comment by HamidShojanazeri** [comment]
@harshbafna I built the image from src and worked. Please modify the doc accordingly.  Thanks.
[Mnist_working.logs.txt](https://github.com/pytorch/serve/files/5687521/Mnist_working.logs.txt)

**Comment by chauhang** [comment]
@harshbafna The TorchServe Helm chart in EKS setup is pointing to the published docker image `torchserve_image: pytorch/torchserve:latest-gpu` which is still on older version of PyTorch and the old code for the base handlers from 0.2 release. Things will work with matching versions

**Comment by harshbafna** [comment]
@chauhang @HamidShojanazeri: I think we should fix the image names in docker hub with `pytorch/torchserve:latest-gpu` and `pytorch/torchserve:latest-cpu` always pointing to the latest TorchServe version. Thoughts?

Else we will always need to update this documentation with every release.

**Comment by chauhang** [comment]
@harshbafna We already have the "latest" and "latest-gpu" tags in dockerhub. The images are still 0.2 as the new release binaries are not yet published till we can cut the release. Please update the documentation steps accordingly. 

https://hub.docker.com/r/pytorch/torchserve/tags?page=1&ordering=last_updated

**Comment by maaquib** [comment]
@chauhang `latest-gpu` was built with TS v0.1.1
Last release (v0.2.0) we tagged the GPU image `0.2.0-cuda10.1-cudnn7-runtime` and not `latest-gpu`
Do you want the documentation to point to the above tag until v0.3.0 release?

**Comment by harshbafna** [comment]
Validated that the `torchserve:latest-gpu` docker image is now updated and built with TorchServe 0.3.0. 
Also validated both mnist.mar and mnist_v2.mar files.

```
docker run --rm -it --gpus all -p 8080:8080 -p 8081:8081 -p 8082:8082 pytorch/torchserve:latest-gpu
Unable to find image 'pytorch/torchserve:latest-gpu' locally
latest-gpu: Pulling from pytorch/torchserve
f22ccc0b8772: Pull complete 
3cf8fb62ba5f: Pull complete 
e80c964ece6a: Pull complete 
5d59c811e2af: Pull complete 
b4113a5e55be: Pull complete 
a192f484acd8: Pull complete 
863a93f3231a: Pull complete 
91078987f93f: Pull complete 
8d20d0c8951b: Pull complete 
0d49589435a9: Pull complete 
c065fa621038: Pull complete 
f942a1278fb5: Pull complete 
7d36ffd8b592: Pull complete 
bb9c20f809c7: Pull complete 
000bab050cb8: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:d3b29ce142ee81c280959a93b717e911edf875fb7f721f14036ce376316d410e
Status: Downloaded newer image for pytorch/torchserve:latest-gpu
2020-12-22 04:01:45,596 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.3.0
TS Home: /home/venv/lib/python3.6/site-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 4
Number of CPUs: 32
Max heap size: 30688 M
Python executable: /home/venv/bin/python3
Config file: /home/model-server/config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://0.0.0.0:8082
Model Store: /home/model-server/model-store
Initial Models: N/A
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 32
Netty client threads: 0
Default workers per model: 4
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
```

```
ubuntu@ip-172-31-69-243:~$ curl -X POST "http://localhost:8081/models?url=https://torchserve.pytorch.org/mar_files/mnist.mar&initial_workers=1"
{
  "status": "Model \"mnist\" Version: 1.0 registered with 1 initial workers"
}
ubuntu@ip-172-31-69-243:~$ 
ubuntu@ip-172-31-69-243:~$ curl -X POST "http://localhost:8080/predictions/mnist" -T serve/examples/image_classifier/mnist/test_data/0.png 
0
ubuntu@ip-172-31-69-243:~$ 
ubuntu@ip-172-31-69-243:~$ 
ubuntu@ip-172-31-69-243:~$ curl -X POST "http://localhost:8081/models?url=https://torchserve.pytorch.org/mar_files/mnist_v2.mar&initial_workers=1"
{
  "status": "Model \"mnist_v2\" Version: 2.0 registered with 1 initial workers"
}
ubuntu@ip-172-31-69-243:~$ 
ubuntu@ip-172-31-69-243:~$ curl -X POST "http://localhost:8080/predictions/mnist_v2" -T serve/examples/image_classifier/mnist/test_data/0.png 
0
```

Closing.
