### ISSUE TITLE
BERT model fails to run on k8s with docker image built from source

### ISSUE THREAD

**Issue by jeremiahschung** [pytorch/serve#898]
## Context

* torchserve version: source
* torch-model-archiver version: source
* torch version: 1.7.1 
* torchvision version [if any]: 0.8.2
* torchtext version [if any]:0.8.1
* torchaudio version [if any]:
* java version:openjdk11 
* Operating System and version: ubuntu18.04

## Your Environment

* Installed using source? [yes/no]:
* Are you planning to deploy it using docker container? [yes/no]:yes
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: Transformer_handler_generalized.py
* What kind of model is it e.g. vision, text, audio?: BERT Seq classification 

## Expected Behavior

Prediction succeeds.

## Current Behavior

Prediction fails with error "ModuleNotFoundError: No module named 'captum'"

## Possible Solution

In /serve/docker/Dockerfile, add "pip install captum"

## Steps to Reproduce

1. Build the a torchscripted default BERT model .mar file using the guide [here](https://github.com/pytorch/serve/tree/master/examples/Huggingface_Transformers)
2. Build a custom docker image from source with the guide [here](https://github.com/pytorch/serve/tree/master/docker), push it into the docker hub for remote access.
3. Create an EKS cluster per instructions [here](https://github.com/pytorch/serve/tree/master/kubernetes/EKS)
4. Before running `helm install ts .`, modify the config.properties file to use your torchserve docker image built in step #2, change the model setting to include the BERT model definition & file and copy the config file and the .mar file into the persistent volume k8s pod. 
5. Install torchserve with `helm install ts .` in /serve/kubernetes/Helm and make an inference to the BERT model
6. Run `kubectl exec <torchserve_pod_name> -- cat logs/ts_log.log and notice the error "ModuleNotFoundError: No module named 'captum'"

## Failure Logs [if any]

[1214_master_bert_k8s_failed.txt](https://github.com/pytorch/serve/files/5687494/1214_master_bert_k8s_failed.txt)

This was fixed after I rebuilt the Torchserve docker image with "pip install captum" in the Dockerfile and used that for the Helm chart install.

**Comment by jeremiahschung** [comment]
Initially reported the issue with Kubernetes, but this is due to the Transformer_handler_generalized.py being updated to have captum as a dependency. Newly archived BERT models with the updated handler will face the same issue. 

Addressed in PR https://github.com/pytorch/serve/pull/901

**Comment by maaquib** [comment]
The BERT model needs to be bundled with the required dependencies. @abishekchiffon Can you please address this

**Comment by HamidShojanazeri** [comment]
Captum has been added to the [dockerfile](https://github.com/pytorch/serve/blob/master/docker/Dockerfile#L66) and requirements which is being used by [dockerfile.dev](https://github.com/pytorch/serve/blob/master/docker/Dockerfile.dev#L56) in case of building image for dev env. I could successfully test it. 
[issue_898.logs.txt](https://github.com/pytorch/serve/files/5997869/issue_898.logs.txt)
