### ISSUE TITLE
Facing "CannotResolveClassException: kg.apc.jmeter.listener.GraphsGeneratorListener" on running benchmark

### ISSUE THREAD

**Issue by abishekchiffon** [pytorch/serve#899]
## Context

1. python benchmark.py latency -v -l 1 --ts http://127.0.0.1:8080.
Passes for all test but throws "CannotResolveClassException: kg.apc.jmeter.listener.GraphsGeneratorListener"
2. python benchmark.py throughput -v -l 1 --ts http://127.0.0.1:8080
Fails for 90% of the test and throws "CannotResolveClassException: kg.apc.jmeter.listener.GraphsGeneratorListener"
Ran the test on C5.4Xlarge instance.

* torchserve==0.3.0
* torch-model-archiver==0.2.1

* Python version: 3.6 (64-bit runtime)
* Python executable: /usr/bin/python

Versions of relevant python libraries:
* captum==0.3.0
* future==0.18.2
* numpy==1.19.4
* nvgpu==0.9.0
* psutil==5.7.3
* pygit2==1.4.0
* pylint==2.6.0
* pytest==6.2.0
* pytest-cov==2.10.1
* pytest-mock==3.3.1
* requests==2.25.0
* requests-unixsocket==0.1.5
* sentencepiece==0.1.94
* transformers==2.10.0
* wheel==0.36.2
* torch==1.7.1
* torchtext==0.8.1
* torchvision==0.8.2
* torchaudio==0.7.2
* java version: openjdk 11.0.9.1 2020-11-04
* Operating System and version: Ubuntu 18.04.5 LTS

## Your Environment

* Installed using source? [yes/no]:
* Are you planning to deploy it using docker container? [yes/no]: NO
* Is it a CPU or GPU environment?: CPU

## Steps to Reproduce

1. python ./ts_scripts/install_dependencies.py --environment=dev
2. python ./ts_scripts/install_from_src.py
3. ./install_dependencies.sh
4. torchserve --start --model-store model_store
5. cd serve/benchmarks
6. python benchmark.py throughput -l 1--ts http://127.0.0.1:8080
7. and python benchmark.py latency -l 1 --ts http://127.0.0.1:8080

## Failure Logs [if any]

[EC2_ENV.log](https://github.com/pytorch/serve/files/5690979/EC2_ENV.log)
[EC2_print_env.log](https://github.com/pytorch/serve/files/5690980/EC2_print_env.log)
[JMETER.zip](https://github.com/pytorch/serve/files/5690981/JMETER.zip)

**Comment by msaroufim** [comment]
With torchserve 0.4 and python 3.8 I am not seeing this issue so closing for now but can reopen if you feel we need to give this a second look
