### ISSUE TITLE
How many concurrent executions does Pytorch Serve dispatch? 

### ISSUE THREAD

**Issue by misrasaurabh1** [pytorch/serve#903]
## 📚 Documentation

Assume that a handler uses 30% of the time on CPU processing and 70% of time in GPU execution. Since we have two devices, if we run two different api requests sequentially, it would keep GPU unutilized for 30% of the time leading to potentially 30% slower throughput by the server compared to the case when GPU was in use 100%.

I am wondering how does pytorch serve handle execution dispatch for exploting such device level parallelism to improve throughput? Does it support multiple handler executions in flight for a single model? 

In case it only supports one execution in flight, would it mean that we should keep the cpu level code very small for highest throughput?

Also in general what is the scheduling and dispatch logic used by the server?

**Comment by misrasaurabh1** [comment]
Another comment. For large production use cases, as a customer and an engineer, I feel a bit uncomfortable using this server because it does not say much about how it optimizes for performance. It would be great if you could upload performance benchmarks wrt. other servers and recommend performance optimizations for getting best performance with this server. It would be great to know load tested, throughput and latency benchmarks on C++ serving/Torchscript serving/gRPC/eager pytorch serving etc.

The context is that companies spends a lot of money on model serving with GPUs so knowing that PyTorch Serve team has got my back in cost effective and efficient deployment would help a lot.

**Comment by dhaniram-kshirsagar** [comment]
> ## 📚 Documentation
> Assume that a handler uses 30% of the time on CPU processing and 70% of time in GPU execution. Since we have two devices, if we run two different api requests sequentially, it would keep GPU unutilized for 30% of the time leading to potentially 30% slower throughput by the server compared to the case when GPU was in use 100%.
> 
> I am wondering how does pytorch serve handle execution dispatch for exploting such device level parallelism to improve throughput? Does it support multiple handler executions in flight for a single model?

@misrasaurabh1  Yes, it supports multiple executions in flight for a single model on different GPUs [If available]. In general, for inference requests, minor time [say around 5% or lesser] goes in preprocessing image data [if needed] and inference is done on GPU using loaded/registered model. So its really not a 30% + 70% combination but much lower.

> 
> In case it only supports one execution in flight, would it mean that we should keep the cpu level code very small for highest throughput?

@misrasaurabh1  It is indeed a small code for CPU.

> 
> Also in general what is the scheduling and dispatch logic used by the server?

@misrasaurabh1 - torchserve supports request batching for a model and a round-robin approach is used for scheduling inference processing on available GPUs.

**Comment by dhaniram-kshirsagar** [comment]
> Another comment. For large production use cases, as a customer and an engineer, I feel a bit uncomfortable using this server because it does not say much about how it optimizes for performance. It would be great if you could upload performance benchmarks wrt. other servers and recommend performance optimizations for getting best performance with this server. It would be great to know load tested, throughput and latency benchmarks on C++ serving/Torchscript serving/gRPC/eager pytorch serving/batch inference etc.
> 
> The context is that companies spends a lot of money on model serving with GPUs so knowing that PyTorch Serve team has got my back in cost effective and efficient deployment would help a lot.

@misrasaurabh1 At present, we don't have such a report however it is a good idea to have it for reference. Can you please create a separate doc ticket for tracking this?

**Comment by msaroufim** [comment]
This question is very model dependent, for now we've started publishing our benchmarks nightly in github artifacts which may provide some signal if there's a specific model you think should be in our benchmarks please feel free to open a separate issue https://github.com/pytorch/serve/actions/workflows/benchmark_nightly_gpu.yml
