### ISSUE TITLE
Captum package not included as part of Dockerfile

### ISSUE THREAD

**Issue by harshbafna** [pytorch/serve#920]
Add `captum` package in Dockerfile.

**Comment by chauhang** [comment]
@harshbafna This is not needed. Captum is a prerequisite to use similar to PyTorch, TorchVision and these are handled via the install dependencies. We do not want to tag this as a pip dependency

**Comment by harshbafna** [comment]
@chauhang, This was based on the offline discussion, the production docker file neither had this package installed not uses install_dependency script to install the packages.

#924 will take care of this.

Updated the description.
