### ISSUE TITLE
Benchmark scripts are outdated

### ISSUE THREAD

**Issue by maaquib** [pytorch/serve#929]
On behalf of @HamidShojanazeri 

* [Benchmark](https://github.com/pytorch/serve/blob/master/benchmarks/install_dependencies.sh#L37) script is outdated. Installing an older version of PT and CUDA.
* Install dependencies installs brew in a different location on Ubuntu if I choose the non root install given I don't have a password for the default user on ec2 machine
```
==> Select the Homebrew installation directory
- Enter your password to install to /home/linuxbrew/.linuxbrew (recommended)
- Press Control-D to install to /home/ubuntu/.linuxbrew
- Press Control-C to cancel installation
```
* Benchamark [enable/disable](https://github.com/pytorch/serve/blob/master/ts/model_service_worker.py#L178) is also setup incorrectly causing empty files to be generated if I register a model, do an inference.

**Comment by lxning** [comment]
run cmd "python benchmark-ab.py -c 10 -r 10000 -bs 1 -ic 'application/text' -e docker -bp True \
                       -i ../examples/Huggingface_Transformers/QA_artifacts/sample_text0.txt \
                       -u https://torchserve.s3.amazonaws.com/mar_files/BERTSeqClassification_Torchscript_batch.mar"

profile file "tsPythonProfile.prof" is not generated.
