### ISSUE TITLE
Captum explanations fails with HF models other than BERT and Token classification explainations fails

### ISSUE THREAD

**Issue by HamidShojanazeri** [pytorch/serve#934]
## Context
The Captum explanations in  line 102 of Huggingface example handler is tied to bert embedding which stops the handler from serving for other HF models such as roberta, etc. Also, the target for the Captum explanations in line 246 of the handler, in case of token classification needs to be a tuple presenting the token and the class label for the token. The current target setting makes the handler to fail for explanation in case of token classification.

For question answering use-case, it may need some changes to output the importances for the start and end of the answers.

* torchserve version:0.3
* torch-model-archiver version:0.3
* torch version:1.7
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
* Operating System and version:ubuntu 18.04

## Your Environment

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: no
* Is it a CPU or GPU environment?: both
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom
* What kind of model is it e.g. vision, text, audio?: text

## Current Behavior
Changing the HF model from BERT to any other model, the handler fails to load the model. Also, in case of token classification using bert model, it fails due to missing the right target. 

## Steps to Reproduce
Following the doc using roberta instead of Bert in the setup_config.json

## Failure Logs [if any]

[Token_cls_eager.logs.txt](https://github.com/pytorch/serve/files/5767354/Token_cls_eager.logs.txt)
[Roberta_seq_cls_error.logs.txt](https://github.com/pytorch/serve/files/5767405/Roberta_seq_cls_error.logs.txt)

**Comment by lxning** [comment]
I installed TS from master branch. Run the following test. 
1. cd ~/serve/examples/Huggingface_Transformers
2. python Download_Transformer_models.py
3. torchserve --start --ncs --model-store model_store --models BERTSeqClassification.mar
4. curl  -X POST http://localhost:8080/predictions/BERTSeqClassification  -T ./Token_classification_artifacts/sample_text.txt
Accepted

**Comment by HamidShojanazeri** [comment]
> I installed TS from master branch. Run the following test.
> 
> 1. cd ~/serve/examples/Huggingface_Transformers
> 2. python Download_Transformer_models.py
> 3. torchserve --start --ncs --model-store model_store --models BERTSeqClassification.mar
> 4. curl  -X POST http://localhost:8080/predictions/BERTSeqClassification  -T ./Token_classification_artifacts/sample_text.txt
>    Accepted

@lxning Can you please share the error you got, also the version of the transformers you using.

**Comment by lxning** [comment]
@HamidShojanazeri There is no error in log.
 pip freeze|grep tran
transformers==4.0.0

**Comment by HamidShojanazeri** [comment]
@lxning The error will come up if you change the model_name in the setup cofing to anything other than bert models, e.g. Roberta, then it fails at this [line](https://github.com/pytorch/serve/blob/master/examples/Huggingface_Transformers/Transformer_handler_generalized.py#L102).
