### ISSUE TITLE
multiple image input (batched input) in single request through gRPC

### ISSUE THREAD

**Issue by ankita4AI** [pytorch/serve#938]
**Q&A**
As far as I could understand the simple torchserve grpc client given handles only single image in the input data.

Just like In tensorflow, shape is set this way
request.inputs['images'].CopyFrom(tf.contrib.util.make_tensor_proto(data, shape=[1]))

What is the correct way to set shape on the input entry to the prediction request here?

**Comment by maaquib** [comment]
@ankita4AI There is no specific schema for the request payload ([code](https://github.com/pytorch/serve/blob/5c03e711a401387a1d42fc01072fcc38b4995b66/frontend/server/src/main/resources/proto/inference.proto#L17)). You should be able to pass whatever payload you like and write a [custom handler](https://github.com/pytorch/serve/blob/master/docs/custom_service.md#custom-handler-with-class-level-entry-point) which handles single or multiple images.
