### ISSUE TITLE
Cloud agnostic K8s deployment script / instructions

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#94]
Provide a cloud agnostic K8s deployment script / instructions for production deployment of TorchServe for vanilla Kubernetes.  

It can be a helm chart deploy that includes: 

- TorchServe inference node(s)
- TorchServe Model management node
- NGINX loadbalancer
- Metrics collection node - Statsd/Prometheus
- Log aggregation using fluentd (or similar)

**Comment by dhaniram-kshirsagar** [comment]
As discussed offline. Assigning this to you.
