### ISSUE TITLE
Add possiblities of usage TensorFlow models

### ISSUE THREAD

**Issue by lessenko** [pytorch/serve#940]
## Is your feature request related to a problem? Please describe.

If it were possible, I think it would be useful to support other models, in particular TensorFlow models.
Currently I'm loading Universal Sentence Encoder https://tfhub.dev/google/universal-sentence-encoder/4. 
The model works, but the load is not optimal.

Thanks.

**Comment by maaquib** [comment]
@lessenko TorchServe was built specifically for serving PyTorch models. There is no plan to support TF or other frameworks.
