### ISSUE TITLE
Persistence/threading within handlers

### ISSUE THREAD

**Issue by ctlaltdefeat** [pytorch/serve#945]
My application requires me to routinely modify my handler variables (that are external to the pytorch model), in a way that is scheduled independently of incoming requests.
If I were to create a background thread that deals with it and initialize it in the initialization function of the handler, would that work or does the handler "wake up" only when requests are called?

**Comment by dhanainme** [comment]
> If I were to create a background thread that deals with it and initialize it in the initialization function of the handler, would that work or does the handler "wake up" only when requests are called?

This should work as long as the model workers registered / running. Essentially the code provided by the user is run as an independent python process. This would imply that this should work.

**Comment by ctlaltdefeat** [comment]
I can confirm that this does indeed work and conforms to my requirements, as far as I'm concerned the issue can be closed, although I'll leave it up to you decide what you want to do with it. Thanks!
