### ISSUE TITLE
serving with batch, wait only for inference possible ?

### ISSUE THREAD

**Issue by ShiroKL** [pytorch/serve#946]
Hello,

It is not really a bug, more a question as I don't know where to ask it. (maybe a feature request ? )

I am currently using batching with torchserve and it seems to work. However, I was wondering if it was possible to "configure" it a little. From my understanding, there is a queue which contains the different requests until it reach a time limit or a number of request. Instead, would it be possible to preprocess the request asap then put them in the queue which will be used for the inference ? Doing that should make the inference faster as we will  wait less for the preprocessing part. (such as text or audio for instance) I did not find any information in the documentation about that, is it possible ?

Thanks for your help,

**Comment by dhanainme** [comment]
> would it be possible to preprocess the request asap then put them in the queue which will be used for the inference ?

Right now both the preprocessing & the inference happens in the Python process while the queuing for Batching happens in the Java Process. Hence this may not be immediately possible with the current architecture. 

One way workaround this may be to do the pre processing on client side.
