### ISSUE TITLE
Model(s) loaded twice on same GPU

### ISSUE THREAD

**Issue by cbasavaraj** [pytorch/serve#947]
Hi, I have an inference workflow that requires three deep learning models. I am running this on an Ubuntu machine with two GPUs. As per TS documentation, I would expect one worker per GPU per model. But when I load all the models using `--models all`, two of my models get loaded on the same GPU twice. This is counter-intuitive, and may have implications on the inference time. Please see screenshot which shows what I'm saying. 

![Screenshot from 2021-01-26 18-28-16](https://user-images.githubusercontent.com/15706875/105882444-ef403e80-6005-11eb-95fe-b4e759ecb218.png)

When I load just one of the models, it loads once on each of the two GPUs. So I think when there are multiple models, `context.properties['gpu_id']` is not being set correctly. Can you please check?

**Comment by lxning** [comment]
I could not reproduce this bug. 

Teat case1: 3 models on 4gpus
- curl http://localhost:8081/models/
{
  "models": [
    {
      "modelName": "resnet-18",
      "modelUrl": "resnet-18.mar"
    },
    {
      "modelName": "squeezenet1_1",
      "modelUrl": "squeezenet1_1.mar"
    },
    {
      "modelName": "vgg11_v2",
      "modelUrl": "vgg11_v2.mar"
    }
  ]
}

- curl http://localhost:8081/models/resnet-18

[
  {
    "modelName": "resnet-18",
    "modelVersion": "1.0",
    "modelUrl": "resnet-18.mar",
    "runtime": "python",
    "minWorkers": 4,
    "maxWorkers": 4,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": true,
    "workers": [
      {
        "id": "9004",
        "startTime": "2021-02-23T02:38:16.230Z",
        "status": "READY",
        "memoryUsage": 163422208,
        "pid": 219,
        "gpu": true,
        "gpuUsage": "gpuId::1 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::4244 MiB"
      },
      {
        "id": "9005",
        "startTime": "2021-02-23T02:38:16.230Z",
        "status": "READY",
        "memoryUsage": 167059456,
        "pid": 220,
        "gpu": true,
        "gpuUsage": "gpuId::2 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::4244 MiB"
      },
      {
        "id": "9006",
        "startTime": "2021-02-23T02:38:16.230Z",
        "status": "READY",
        "memoryUsage": 164286464,
        "pid": 222,
        "gpu": true,
        "gpuUsage": "gpuId::3 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::4244 MiB"
      },
      {
        "id": "9007",
        "startTime": "2021-02-23T02:38:16.231Z",
        "status": "READY",
        "memoryUsage": 162648064,
        "pid": 221,
        "gpu": true,
        "gpuUsage": "gpuId::0 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::11788 MiB"
      }
    ]
  }
]

- ubuntu@ip-172-31-19-52:~$ 

curl http://localhost:8081/models/squeezenet1_1
[
  {
    "modelName": "squeezenet1_1",
    "modelVersion": "1.0",
    "modelUrl": "squeezenet1_1.mar",
    "runtime": "python",
    "minWorkers": 4,
    "maxWorkers": 4,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": true,
    "workers": [
      {
        "id": "9008",
        "startTime": "2021-02-23T02:38:16.332Z",
        "status": "READY",
        "memoryUsage": 147230720,
        "pid": 251,
        "gpu": true,
        "gpuUsage": "gpuId::1 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::4244 MiB"
      },
      {
        "id": "9009",
        "startTime": "2021-02-23T02:38:16.332Z",
        "status": "READY",
        "memoryUsage": 164442112,
        "pid": 252,
        "gpu": true,
        "gpuUsage": "gpuId::2 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::4244 MiB"
      },
      {
        "id": "9010",
        "startTime": "2021-02-23T02:38:16.332Z",
        "status": "READY",
        "memoryUsage": 152166400,
        "pid": 254,
        "gpu": true,
        "gpuUsage": "gpuId::3 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::4244 MiB"
      },
      {
        "id": "9011",
        "startTime": "2021-02-23T02:38:16.332Z",
        "status": "READY",
        "memoryUsage": 157167616,
        "pid": 253,
        "gpu": true,
        "gpuUsage": "gpuId::0 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::11788 MiB"
      }
    ]
  }
]

- ubuntu@ip-172-31-19-52:~$ 

curl http://localhost:8081/models/vgg11_v2
[
  {
    "modelName": "vgg11_v2",
    "modelVersion": "1.0",
    "modelUrl": "vgg11_v2.mar",
    "runtime": "python",
    "minWorkers": 4,
    "maxWorkers": 4,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": true,
    "workers": [
      {
        "id": "9000",
        "startTime": "2021-02-23T02:38:15.191Z",
        "status": "READY",
        "memoryUsage": 2710302720,
        "pid": 57,
        "gpu": true,
        "gpuUsage": "gpuId::1 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::4244 MiB"
      },
      {
        "id": "9001",
        "startTime": "2021-02-23T02:38:15.194Z",
        "status": "READY",
        "memoryUsage": 2723323904,
        "pid": 56,
        "gpu": true,
        "gpuUsage": "gpuId::2 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::4244 MiB"
      },
      {
        "id": "9002",
        "startTime": "2021-02-23T02:38:15.194Z",
        "status": "READY",
        "memoryUsage": 2719391744,
        "pid": 55,
        "gpu": true,
        "gpuUsage": "gpuId::3 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::4244 MiB"
      },
      {
        "id": "9003",
        "startTime": "2021-02-23T02:38:15.194Z",
        "status": "READY",
        "memoryUsage": 2712485888,
        "pid": 58,
        "gpu": true,
        "gpuUsage": "gpuId::0 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::11788 MiB"
      }
    ]
  }
]

- ubuntu@ip-172-31-19-52:~$

 nvidia-smi
Tue Feb 23 02:39:30 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   33C    P0    48W / 300W |  11788MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   35C    P0    49W / 300W |   4244MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   31C    P0    50W / 300W |   4244MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   32C    P0    54W / 300W |   4244MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    109647      C   /home/venv/bin/python3           1727MiB |
|    0   N/A  N/A    109808      C   /home/venv/bin/python3           1277MiB |
|    0   N/A  N/A    109809      C   /home/venv/bin/python3           1277MiB |
|    0   N/A  N/A    109810      C   /home/venv/bin/python3           1277MiB |
|    0   N/A  N/A    109811      C   /home/venv/bin/python3           1277MiB |
|    0   N/A  N/A    109840      C   /home/venv/bin/python3           1237MiB |
|    0   N/A  N/A    109841      C   /home/venv/bin/python3           1237MiB |
|    0   N/A  N/A    109842      C   /home/venv/bin/python3           1237MiB |
|    0   N/A  N/A    109843      C   /home/venv/bin/python3           1237MiB |
|    1   N/A  N/A    109646      C   /home/venv/bin/python3           1727MiB |
|    1   N/A  N/A    109808      C   /home/venv/bin/python3           1277MiB |
|    1   N/A  N/A    109840      C   /home/venv/bin/python3           1237MiB |
|    2   N/A  N/A    109645      C   /home/venv/bin/python3           1727MiB |
|    2   N/A  N/A    109809      C   /home/venv/bin/python3           1277MiB |
|    2   N/A  N/A    109841      C   /home/venv/bin/python3           1237MiB |
|    3   N/A  N/A    109644      C   /home/venv/bin/python3           1727MiB |
|    3   N/A  N/A    109811      C   /home/venv/bin/python3           1277MiB |
|    3   N/A  N/A    109843      C   /home/venv/bin/python3           1237MiB |
+-----------------------------------------------------------------------------+

Test case2: 3 models on 2 gpus
curl http://localhost:8081/models/
{
  "models": [
    {
      "modelName": "resnet-18",
      "modelUrl": "resnet-18.mar"
    },
    {
      "modelName": "squeezenet1_1",
      "modelUrl": "squeezenet1_1.mar"
    },
    {
      "modelName": "vgg11_v2",
      "modelUrl": "vgg11_v2.mar"
    }
  ]
}

- curl http://localhost:8081/models/resnet-18

[
  {
    "modelName": "resnet-18",
    "modelVersion": "1.0",
    "modelUrl": "resnet-18.mar",
    "runtime": "python",
    "minWorkers": 2,
    "maxWorkers": 2,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": true,
    "workers": [
      {
        "id": "9002",
        "startTime": "2021-02-23T02:46:16.910Z",
        "status": "READY",
        "memoryUsage": 161439744,
        "pid": 134,
        "gpu": true,
        "gpuUsage": "gpuId::1 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::4244 MiB"
      },
      {
        "id": "9003",
        "startTime": "2021-02-23T02:46:16.911Z",
        "status": "READY",
        "memoryUsage": 161595392,
        "pid": 135,
        "gpu": true,
        "gpuUsage": "gpuId::0 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::6758 MiB"
      }
    ]
  }
]

- curl http://localhost:8081/models/squeezenet1_1

[
  {
    "modelName": "squeezenet1_1",
    "modelVersion": "1.0",
    "modelUrl": "squeezenet1_1.mar",
    "runtime": "python",
    "minWorkers": 2,
    "maxWorkers": 2,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": true,
    "workers": [
      {
        "id": "9004",
        "startTime": "2021-02-23T02:46:17.011Z",
        "status": "READY",
        "memoryUsage": 158576640,
        "pid": 150,
        "gpu": true,
        "gpuUsage": "gpuId::1 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::4244 MiB"
      },
      {
        "id": "9005",
        "startTime": "2021-02-23T02:46:17.011Z",
        "status": "READY",
        "memoryUsage": 150724608,
        "pid": 151,
        "gpu": true,
        "gpuUsage": "gpuId::0 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::6758 MiB"
      }
    ]
  }
]

- curl http://localhost:8081/models/vgg11_v2
[
  {
    "modelName": "vgg11_v2",
    "modelVersion": "1.0",
    "modelUrl": "vgg11_v2.mar",
    "runtime": "python",
    "minWorkers": 2,
    "maxWorkers": 2,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": true,
    "workers": [
      {
        "id": "9000",
        "startTime": "2021-02-23T02:46:15.886Z",
        "status": "READY",
        "memoryUsage": 200531968,
        "pid": 50,
        "gpu": true,
        "gpuUsage": "gpuId::1 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::4244 MiB"
      },
      {
        "id": "9001",
        "startTime": "2021-02-23T02:46:15.888Z",
        "status": "READY",
        "memoryUsage": 200495104,
        "pid": 51,
        "gpu": true,
        "gpuUsage": "gpuId::0 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::6758 MiB"
      }
    ]
  }
]

- nvidia-smi
Tue Feb 23 02:47:16 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   33C    P0    48W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   34C    P0    49W / 300W |   6758MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   31C    P0    49W / 300W |   4244MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   32C    P0    53W / 300W |      0MiB / 16160MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    1   N/A  N/A    110725      C   /home/venv/bin/python3           1727MiB |
|    1   N/A  N/A    110808      C   /home/venv/bin/python3           1277MiB |
|    1   N/A  N/A    110809      C   /home/venv/bin/python3           1277MiB |
|    1   N/A  N/A    110824      C   /home/venv/bin/python3           1237MiB |
|    1   N/A  N/A    110825      C   /home/venv/bin/python3           1237MiB |
|    2   N/A  N/A    110724      C   /home/venv/bin/python3           1727MiB |
|    2   N/A  N/A    110808      C   /home/venv/bin/python3           1277MiB |
|    2   N/A  N/A    110824      C   /home/venv/bin/python3           1237MiB |
+-----------------------------------------------------------------------------+

**Comment by cbasavaraj** [comment]
Thanks for the response. I'll check again on my side and get back to you tomorrow or Friday.

**Comment by cbasavaraj** [comment]
Hello, I checked. Turns out I was not using the torch.device at all in two of my model handlers. Corrected now, and it works fine. Thanks.
