### ISSUE TITLE
Model hot load

### ISSUE THREAD

**Issue by khalid-davis** [pytorch/serve#949]
Does pytorch server supoort model hot load?
For example, I've run model 1.0 with torchserver, and I want to replace model 1.0 with model 2.0, and I don't want the service to be unavailable during the replacement.

**Comment by dhanainme** [comment]
You would be able to register multiple models & later set a default model with a set-default-version call. Would is this something similar to what you are expecting ?


https://github.com/pytorch/serve/blob/master/docs/management_api.md#set-default-version

**Comment by khalid-davis** [comment]
It seems that I need to register all models first. However, if the new model does not exist at the beginning but is trained later, I hope that the old model can be replaced with a new model without service interruption. The `set-default-version`  does not support this scenario. Of course, I can fulfill my needs by gray upgrade.

**Comment by khalid-davis** [comment]
In kfserving, maybe I can work with model_config_file_poll_wait_seconds and modify model config file to implement hot loading requirements.

**Comment by maaquib** [comment]
> It seems that I need to register all models first. However, if the new model does not exist at the beginning but is trained later, I hope that the old model can be replaced with a new model without service interruption. The `set-default-version` does not support this scenario. Of course, I can fulfill my needs by gray upgrade.

@khalid-davis You can register a new version of the model while TorchServe is still running by calling the [register model](https://github.com/pytorch/serve/blob/master/docs/management_api.md#register-a-model) API and then calling the [set-default](https://github.com/pytorch/serve/blob/master/docs/management_api.md#set-default-version) model API on the newly registered one.

**Comment by khalid-davis** [comment]
OK, thanks.
