### ISSUE TITLE
Pass model constructor parameters to TorchServe

### ISSUE THREAD

**Issue by aidan-fitz** [pytorch/serve#963]
## Is your feature request related to a problem? Please describe.

I am creating a PyTorch model with a variable number of `nn.Conv2d` layers that are stored in an `nn.ModuleList`. These layers are created during training, not initialization. Trying to load the `nn.Conv2d` parameters from the `state_dict` into an empty `nn.ModuleList` for inference throws the following error:
```python
RuntimeError: Error(s) in loading state_dict for EfficientNetSegmentation:
	Unexpected key(s) in state_dict: "conv2ds.0.weight", "conv2ds.0.bias", "conv2ds.1.weight", "conv2ds.1.bias", "conv2ds.2.weight", "conv2ds.2.bias". 
```

## Describe the solution

I want to pass a parameter specifying the number of layers to create to the constructor, which will create the desired number of layers so that the `state_dict` parameters can be loaded into them. Ideally, I would like to specify the parameters to pass to the model constructor when serving it in TorchServe.

**Comment by maaquib** [comment]
@aidan-fitz You can write a [custom handler](https://github.com/pytorch/serve/blob/master/docs/custom_service.md#custom-handlers) where you can define how your model is loaded. Please reopen if you need any further help. ([example](https://github.com/pytorch/serve/blob/master/examples/image_classifier/vgg_11/vgg_handler.py)).

**Comment by aidan-fitz** [comment]
Thanks, I'll try this.
