### ISSUE TITLE
How to change loadedAtStartup to be true while registering a model?

### ISSUE THREAD

**Issue by wangs0007** [pytorch/serve#965]
## 📚 Documentation

When a model is registered loadedAtStartup is false by default. Is this option related to model pre-load? Is the model supposed to be loaded all time if this is set to be true? And how exactly do we change it while registering a model? Thank you in advance.

**Comment by chauhang** [comment]
@wangs0007 Please use the [Scale Workers](https://github.com/pytorch/serve/blob/master/docs/management_api.md#scale-workers) after model registration for loading the model and starting actual worker threads.
