### ISSUE TITLE
Register multi-model error

### ISSUE THREAD

**Issue by zeyu-liu** [pytorch/serve#968]
When I serving two models simultaneously, I found that the prediction procedure was very very slow. I checked the log file and found models were re-started again and again. It seems that I cannot register two models at same time. And I tried to register one model and tested it multi times, everything is OK. So, what happened?

Parts of the log file:
[log](https://gist.github.com/zeyu-liu/d0acbfbb734cde1c15369df62ab4a799)

## Context
* torchserve version: 0.1.1
* torch-model-archiver version: 0.1.1
* torch version: 1.4.0
* torchvision version [if any]: 0.5.0
* java version: openjdk 11.0.5 2019-10-15 LTS

## Your Environment

* Installed using source? [yes/no]: no
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom handler
* What kind of model is it e.g. vision, text, audio?: vision

## Expected Behavior

register two models and perform well

## Current Behavior

when registered the second model, the first one crashed and registered again...

**Comment by dhanainme** [comment]
> Backend worker monitoring thread interrupted or backend worker process died.

Can you please confirm if you are able to perform inference in a simple python script without TorchServe. As its not clear why the backend python worker as died (no stack trace) this could be difficult to diagnose.

**Comment by zeyu-liu** [comment]
> > Backend worker monitoring thread interrupted or backend worker process died.
> 
> Can you please confirm if you are able to perform inference in a simple python script without TorchServe. As its not clear why the backend python worker as died (no stack trace) this could be difficult to diagnose.

Yes, and I also tried to serve these models separately. Everyone was worked well.

**Comment by zeyu-liu** [comment]
I put both models into a directory named 'model-store'. And I used the POST method "models" as it is said in DOC.

**Comment by zeyu-liu** [comment]
I tried to serve these models on a CPU machine, with same version of torch / torchvision / torchserve. No worker died event occurred.

**Comment by msaroufim** [comment]
Hi @zeyu-liu it'd be helpful to get more complete repro instructions using our issue template. Ideally something I can follow step by step to get the exact same issue you're getting.
