### ISSUE TITLE
Batch Mode Documentation: broken URLs

### ISSUE THREAD

**Issue by DSLituiev** [pytorch/serve#969]
in https://pytorch.org/serve/batch_inference_with_ts.html#batch-inference-with-torchserve-using-resnet-152-model

> see [Hugging face transformer generalised handler](https://pytorch.org/examples/Huggingface_Transformers/Transformer_handler_generalized.py)

in [TorchServe Model Configuration](https://pytorch.org/serve/batch_inference_with_ts.html#torchserve-model-configuration)

> [POST /models API](https://pytorch.org/serve/management_api.md#register-a-model)

**Comment by DSLituiev** [comment]
`Transformer_handler_generalized.py` is mentioned elsewhere in .md files on this repo, but doesn't seem  to be available any longer. 

Do you have any docs for batch inference on CNNs?

**Comment by dhanainme** [comment]
Are you referring to this ?


https://github.com/pytorch/serve/blob/eda7d586791a7192e7f664ff50dcedfbb5d5fef9/examples/Huggingface_Transformers/Transformer_handler_generalized.py

**Comment by DSLituiev** [comment]
@dhanainme yes. 

Another question / request: The [example](https://pytorch.org/serve/batch_inference_with_ts.html#batch-inference-with-torchserve-using-resnet-152-model) for CNN batch mode demonstrates how to send one image and get  back prediction. How can one make sure from just one image that it's running in batch mode? 

I tried sending several images, and I don't see any speed-up with batch mode. 

### setup
```
torchserve --start --model-store model_store

curl -X POST "localhost:8081/models?url=https://torchserve.pytorch.org/mar_files/resnet-152-batch_v2.mar&batch_size=8&max_batch_delay=10&initial_workers=1"

curl -LJO https://github.com/pytorch/serve/raw/master/examples/image_classifier/kitten.jpg

TILE=kitten.jpg
MODELNAME=resnet-152-batch_v2
```
### single run

```
start_time="$(date -u +%s%N)"
curl http://127.0.0.1:8080/predictions/$MODELNAME -T $TILE > /dev/null 2>&1
end_time="$(date -u +%s%N)"
elapsed="$((($end_time-$start_time)/1000000)) ms"
echo "Total of $elapsed elapsed for process"
```
 --> 301 m

### vs  batched run

```
start_time="$(date -u +%s%N)"
for x in `seq 1 128`
do
    curl http://127.0.0.1:8080/predictions/$MODELNAME -T $TILE > /dev/null 2>&1
    #2>&1  /dev/null
    #2>&1 | head -n4 | tail -n1
#   echo $(date)
done
end_time="$(date -u +%s%N)"
elapsed="$((($end_time-$start_time)/1000000)) ms"
echo "Total of $elapsed elapsed for process"
```
--> 303.203125 ms per image


How can I tell that it's really working?

**Comment by DSLituiev** [comment]
Another moment of confusion is regarding the handling. Do I need to modify `VisionHandler` or is it already compatible?

I don't see any special secret sauce in the `TransformersSeqClassifierHandler` that you've attached. The `preprocess()` has a very similar loop that collects data into a batch. 

in `ts.torch_handler.vision_handler.TransformersSeqClassifierHandler`: 
```
for idx, data in enumerate(requests):
            input_text = data.get("data")
            if input_text is None:
                input_text = data.get("body")
            if isinstance(input_text, (bytes, bytearray)):
                input_text = input_text.decode('utf-8')
```

in `VisionHandler`:

```
        for row in data:
            # Compat layer: normally the envelope should just return the data
            # directly, but older versions of Torchserve didn't have envelope.
            image = row.get("data") or row.get("body")
```

-- these two look the same to me. Can you please explain what needs to be modified to make it work with batching? Thank you

**Comment by aniketmaurya** [comment]
One more question, how do I send batch images from client side only. Say 4 images at a time?

**Comment by lxning** [comment]
@DSLituiev Usually batching is useful to improve performance in GPU host, but not guaranteed. You can use [benchmark-ab.py](https://github.com/pytorch/serve/tree/master/benchmarks#benchmark) to tune batch_size and check the latency difference.

**Comment by lxning** [comment]
@aniketmaurya Here batching means server processes multiple incoming requests together. In other words, it is not necessary for clients to batch.

**Comment by lxning** [comment]
@chauhang It seems that https://pytorch.org/serve/batch_inference_with_ts.html?highlight=batch is not sync up with TS doc. Could you pls help with this issue?

**Comment by aniketmaurya** [comment]
> @aniketmaurya Here batching means server processes multiple incoming requests together. In other words, it is not necessary for clients to batch.

@lxning I understand that client don't need to do any batching and it is handled by torchserve but in my use case I have multiple photos uploaded by a single client at the same time. So should I iterate the image list and hit torchserve one-by-one? Is there any workaround that I can send all the images at the same time?

**Comment by lxning** [comment]
@aniketmaurya yes, you need customized handler to preprocess the request if one request includes N(>1) images.
