### ISSUE TITLE
Custom model requirements in docker

### ISSUE THREAD

**Issue by toretak** [pytorch/serve#970]
First of all, I would like to thank for such a great tool! 
I have been searching for this issue, but nothing came up. Please forgive me if I missed it somewhere.

Let's have model with custom handler and custom requirement placed in requirements.txt attached to mar file.

in **config.properties** file is `install_py_dep_per_model` set to true
```bash
$ cat config.properties 
install_py_dep_per_model=true
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
number_of_netty_threads=32
```

But docker run on latest torchserve ... 
```bash
$ docker run --runtime nvidia --gpus all --rm -it -v $(pwd)/config.properties:/tmp/config.properties \
 -v $(pwd)/output:/home/model-server/model-store -p 8080:8080 -p 8081:8081 pytorch/torchserve:latest \
 torchserve --start --model-store model-store --models detection=classifier.mar  \
--ts-config /tmp/config.properties 
```

... fails to install dependencies
```bash
2021-02-16 13:54:42,812 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.3.0
TS Home: /home/venv/lib/python3.6/site-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 1
Number of CPUs: 12
Max heap size: 3964 M
Python executable: /home/venv/bin/python3
Config file: /tmp/config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://0.0.0.0:8082
Model Store: /home/model-server/model-store
Initial Models: detection=classifier.mar
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 32
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: true
Metrics report format: prometheus
Enable metrics API: true
2021-02-16 13:54:42,859 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: classifier.mar
2021-02-16 13:54:45,978 [INFO ] main org.pytorch.serve.archive.ModelArchive - eTag 56b4756d97974f8aa982c541cb1670b1
2021-02-16 13:54:45,986 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 0.2 for model detection
2021-02-16 13:54:45,986 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 0.2 for model detection
2021-02-16 13:54:45,986 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model detection loaded.
2021-02-16 13:55:50,254 [WARN ] main org.pytorch.serve.ModelServer - Failed to load model: classifier.mar
org.pytorch.serve.archive.ModelException: Custom pip package installation failed for detection
	at org.pytorch.serve.wlm.ModelManager.setupModelDependencies(ModelManager.java:191)
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:122)
	at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:227)
	at org.pytorch.serve.ModelServer.startRESTserver(ModelServer.java:327)
	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:114)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:95)

```

Is there any reason, why `setuptools` are not included in Dockerfile?

## Context
- Obviously, I would like to run model with custom dependencies in requirements file. 
- I would like to run it on production dockerfile (not dev)

## Your Environment
Production (not dev) docker related issue only.

## Expected Behavior
Install packages like in dev docker - [documentation]( https://pytorch.org/serve/configuration.html#allow-model-specific-custom-python-packages)

## Current Behavior
Model loading fails

## Possible Solution

Add `pip install setuptools` to production Dockerfile or write into documentation that this is not supported in docker

**Comment by dhanainme** [comment]
This is a bug as the intention is to allow users to provide req.txt file. This appears to be missing - https://github.com/pytorch/serve/blob/master/docker/Dockerfile.dev#L46

Have tagged this for the next release. Feel free to send a PR if you have made the change.

**Comment by lxning** [comment]
verified on master branch
steps:
1. cat requirements.txt
transformers==4.0.0
2. torch-model-archiver --model-name maskrcnn --version 1.0 --model-file model.py --serialized-file maskrcnn_resnet50_fpn_coco-bf2d0c1e.pth --handler object_detector --extra-files ../index_to_name.json --requirements-file requirements.txt
3. torchserve  --model-store /home/model-server/model-store --models maskrcnn.mar
4. ll tmp/models/61cd2d7c72c54eadb03996ac4db418f5/
drwxr-xr-x  8 model-server model-server      4096 Feb 27 06:24 transformers/
drwxr-xr-x  2 model-server model-server      4096 Feb 27 06:24 transformers-4.0.0.dist-info/

**Comment by toretak** [comment]
setuptools still missing, if installed package needs to install wheel dependecy
