### ISSUE TITLE
Add build support for Python 3.9

### ISSUE THREAD

**Issue by maaquib** [pytorch/serve#975]
Add Python 3.9 build support to TS0.4+PyTorch 1.8.0

**Comment by lxning** [comment]
Test the following cases in python3.9 environment. All the tests passed.
-  python ./ts_scripts/install_dependencies.py --environment=dev —coda cu110
        * sudo apt-get install python-apt
        * cd /usr/lib/python3/dist-packages
        * sudo ln -s apt_pkg.cpython-38-x86_64-linux-gnu.so apt_pkg.so
        * curl https://sh.rustup.rs -sSf | sh #install rust compiler
        
- python ./ts_scripts/install_from_src.py

- torch-model-archiver --model-name densenet161 --version 1.0 --model-file ./serve/examples/image_classifier/densenet_161/model.py --serialized-file densenet161-8d451a50.pth --export-path model_store --extra-files ./serve/examples/image_classifier/index_to_name.json --handler image_classifier

- python torchserve_sanity.py

- torchserve --start --ncs --model-store model_store --models 
        * BERTSeqClassification_Torchscript_gpu.mar
        * densenet161.mar
        * mnist_v2.mar
        * vgg11_v2.mar

- GRPC client 

- python test/regression_tests.py
