### ISSUE TITLE
Failing to trace Huggingface models on one device and inferencing on other device. 

### ISSUE THREAD

**Issue by HamidShojanazeri** [pytorch/serve#976]
## Context
 Using Trace API from Torchscript and tracing HF Models on one device (e.g. cpu) and running inference on another device (gpu) run into some issue with device inconsistency. Some of the inputs such as position_ids get hardcoded to the device that it's been traced on. This issue exist in multi-gpu setting as well, when tracing on one GPU (e.g. GPU:id0) and running inference on another GPU(e.g. GPU:id1) using the map_location setting. This [issue](https://github.com/huggingface/transformers/issues/6071) has been reported on HF repo as well. A merged [PR ](https://github.com/huggingface/transformers/pull/5773)tried to address the similar [issue](https://github.com/huggingface/transformers/issues/5664#issuecomment-658790379), although changes are not broadcasted to all models available in HF repo. The minimal code to reproduce the multi-gpu use case and traced model graph on the latest transformers version, is as follows:

* torchserve version:0.3
* torch-model-archiver version:0.3
* torch version:1.7.1
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
* Operating System and version:ubuntu 18.04

## Your Environment

* Installed using source? [yes/no]: Both
* Are you planning to deploy it using docker container? [yes/no]:No
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]:No
* What kind of model is it e.g. vision, text, audio?:text

## Expected Behavior
Run the inference on a multi-gpu machine using HF torchscripted model.

## Current Behavior
Failing with device inconsistency error. 

## Steps to Reproduce

This error occur, when following the [doc](https://github.com/pytorch/serve/tree/master/examples/Huggingface_Transformers#creating-a-torch-model-archive) for Huggingface example and made a torchscripted model and serve it on a multi-gpu machine, where workers can be assigned to different gpus (other than the one/gpu:id model was traced on) . This behavior can be  reproduced using the following minimal code as well. 

```
import transformers
from pathlib import Path
import os
import json
import torch
from transformers import (AutoModelForSequenceClassification, AutoTokenizer, AutoModelForQuestionAnswering,
 AutoModelForTokenClassification, AutoConfig)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device1 = torch.device('cuda:0')
device2 = torch.device('cuda:1')
config = AutoConfig.from_pretrained('roberta-base',num_labels=2,torchscript=True)
model = AutoModelForSequenceClassification.from_pretrained('roberta-base', config=config)
tokenizer = AutoTokenizer.from_pretrained('roberta-base',do_lower_case=True)
dummy_input = "This is a dummy input for torch jit trace"
max_length = 20
inputs = tokenizer.encode_plus(dummy_input,max_length = int(max_length),pad_to_max_length = True, add_special_tokens = True, return_tensors = 'pt')
input_ids = inputs["input_ids"]
attention_mask = inputs["attention_mask"]
print('device {}, device1 {}, device2 {}'.format(device,device1,device2))
outputs = model(**inputs)
model.to(device1).eval()
last_hidden_states = outputs[0]  
traced_model = torch.jit.trace(model,(input_ids.to(device1),attention_mask.to(device1)))
torch.jit.save(traced_model, "roberta.pt")
print(traced_model.graph)
print("\n")
loaded = torch.jit.load("roberta.pt", map_location=device2)
print("\n")
print(loaded.graph)
outputs = loaded(input_ids.to(device2),attention_mask.to(device2))
print(outputs)

```

## Failure Logs [if any]
[HF_roberta_error.logs.txt](https://github.com/pytorch/serve/files/6006606/HF_roberta_error.logs.txt)

**Comment by lxning** [comment]
Fixed in v0.4.2
