### ISSUE TITLE
I tried examples of nmt transformers, but I ran into error.

### ISSUE THREAD

**Issue by softmurata** [pytorch/serve#988]
Hello. I am a beginner of torchserve and I want to use translation model(nmt Transformer), but when I executed ./create_mar.sh and start torchserve, I ran into following error.
```
main org.pytorch.serve.ModelServer - Failed to load model: TransformerEn2Fr.mar
org.pytorch.serve.archive.ModelException: Custom pip package installation failed for TransformerEn2Fr
```
I searched issue on nmt Transformer and I found same errors which occured before. But I could not find solution against this problem. Please give me some advices or ideas in order to solve this problem.

**Comment by HamidShojanazeri** [comment]
cc @AshwinChafale

**Comment by toretak** [comment]
#970
