### ISSUE TITLE
Benchmarking run: Errors and results

### ISSUE THREAD

**Issue by fbbradheintz** [pytorch/serve#99]
Last night, I ran all the benchmarks on CPU and GPU. Some gave valid results, some did not. Please note that this run was for testing/debugging, not for actual profiling. (Too many bugs were encountered.)

Currently, latency, throughput, ping, and concurrent_inference tests are giving valid results; multiple_models, load, and repeated_scale_calls are buried in errors.

I'll be rerunning longer, more varied tests for those benchmarks that are giving valid results.

Test setup: I spun up one worker per processor (vCPU or GPU), and otherwise ran each benchmark with defaults.

**CPU config:** c4.4xlarge, DL AMI 27, Ubuntu 18, 16 vCPU, last night's `stage_release` branch (98d3f27)
**CPU command line:** `python ./benchmark.py $bmark --ts http://127.0.0.1:8080 -w 16`

**GPU config:** p3.8xlarge, DL AMI 27, Ubuntu 18, 4 GPU, last night's `stage_release` branch (98d3f27)
**GPU command line:** `python ./benchmark.py $bmark --ts http://127.0.0.1:8080 -g 4 -w 4`

Error reports and benchmark results (for those runs that gave valid data) are tabulated here: https://docs.google.com/spreadsheets/d/1OaCGwYBQIFGfNIFc2IwCDg1-Xf2IOsnw0q8_Nl7mlQI/edit?usp=sharing

Note that the error patterns were very consistent between CPU and GPU - the only substantive difference is an exception type on GPU that was not seen on CPU.

As part of automating my tests, I collected all logs and Jmeter reports separately for each run. I'm providing these to facilitate debugging.

CPU logs: https://www.dropbox.com/s/26pprkcxasakvei/cpu_benchmark_logs.tar.gz?dl=0
GPU logs: https://www.dropbox.com/s/w0yl3drt9wgitb1/gpu_benchmark_logs.tar.gz?dl=0

**Comment by maaquib** [comment]
@fbbradheintz Is this still relevant for the latest release?
