### ISSUE TITLE
Torchserve cannot run with MMS at the same time?

### ISSUE THREAD

**Issue by lynx97** [pytorch/serve#997]
when I start mxnet-model-server, torchserve detects that torchserve is running, so I cannot start torchserve?
Thanks

**Comment by dhanainme** [comment]
This may be due to same pid file name between the servers. This should be fixed

https://github.com/awslabs/multi-model-server/blob/master/mms/model_server.py#L33

https://github.com/pytorch/serve/blob/master/ts/model_server.py#L24

**Comment by dhanainme** [comment]
Similar to #1009

**Comment by dhanainme** [comment]
Similar to #1009

**Comment by maaquib** [comment]
Closing in favor of #1009
