### ISSUE TITLE
MaskRCNN Example Inferencing runs for long time with no error and no output

### ISSUE THREAD

**Issue by nagamanikandank** [pytorch/serve#998]
I was able to install PyTorch Serve on WSL and Register the MaslRCNN example model provided in Github.

To start the PyTorch server, I provided a `config.properties` with following configuration

```
inference_address=http://127.0.0.1:9090
management_address=http://127.0.0.1:9091
metrics_address=http://127.0.0.1:9092
```

When I hit this URL --> `curl -X GET http://127.0.0.1:9091/models`, I could see the model registered fine  with the following result

```
{
  "models": [
    {
      "modelName": "maskrcnn",
      "modelUrl": "maskrcnn.mar"
    }
  ]
}
```

The status of inference server also return healthy, when I access port 9090

```
curl http://localhost:9090/ping
{
  "status": "Healthy"
}
```

When I try to make a model prediction, there is no error shown in `ts_log.log` or `ts_metrics.log`, but the inference command keeps running forever (I let it run for 2 hours) with no result.

I use the `persons.jpg` file provided in the example to run an inference with the following command

`curl http://127.0.0.1:9090/predictions/maskrcnn -T C:\Users\persons.jpg`

**Comment by dhanainme** [comment]
Some debugging steps that might help 

* Can you try running inference w/o TS. Whats the typical time for an inference
* Look @ https://github.com/pytorch/serve/blob/c9ccaec192eecac70b62005938a53a12101cb0ad/docs/configuration.md#other-properties

default_response_timeout: Timeout, in seconds, used for model's backend workers before they are deemed unresponsive and rebooted. Default: 120 seconds.

**Comment by msaroufim** [comment]
Hi @nagamanikandank did the above solve your problem?
